name = "skyshop"
version = "0.1.0"
entry = "src/Main.sky"

[source]
root = "src"

[live]
port = 4000
input = "debounce"
poll_interval = 0

[live.session]
store = "memory"

[dependencies]
"github.com/anzellai/sky-tailwind" = "latest"

["go.dependencies"]
"cloud.google.com/go/firestore" = "latest"
"firebase.google.com/go/v4" = "latest"
"firebase.google.com/go/v4/auth" = "latest"
"google.golang.org/api/iterator" = "latest"
"google.golang.org/api/option" = "latest"
"encoding/base64" = "latest"
"encoding/json" = "latest"
"github.com/google/uuid" = "latest"
"net/http" = "latest"
"net/url" = "latest"
"io" = "latest"
"strings" = "latest"
"strconv" = "latest"
"os" = "latest"
"fmt" = "latest"
"context" = "latest"
