// hash:5-6
func Page_AuthPage_ViewAuthError(authErr any) any {
	return func() any { if sky_asBool(sky_equal(authErr, "")) { return sky_htmlText("") }; return sky_call(sky_call(sky_htmlEl("div"), []any{sky_call(sky_attrSimple("class"), "notification notification-error")}), []any{sky_htmlText(authErr)}) }()
}

func Page_AuthPage_SignUpContent(model any) any {
	return sky_call(sky_call(sky_htmlEl("div"), []any{sky_call(sky_attrSimple("class"), "auth-container")}), []any{sky_call(sky_call(sky_htmlEl("div"), []any{sky_call(sky_attrSimple("class"), "auth-card")}), []any{sky_call(sky_call(sky_htmlEl("h1"), []any{sky_call(sky_attrSimple("class"), "auth-title")}), []any{sky_htmlText("Create an account")}), Page_AuthPage_ViewAuthError(sky_asMap(model)["authError"]), sky_call(sky_call(sky_htmlEl("form"), []any{sky_call(sky_evtHandler("submit"), DoSignUp)}), []any{sky_call(sky_call(sky_htmlEl("div"), []any{sky_call(sky_attrSimple("class"), "form-group")}), []any{sky_call(sky_call(sky_htmlEl("label"), []any{sky_call(sky_attrSimple("class"), "form-label")}), []any{sky_htmlText("Username")}), sky_call(sky_htmlVoid("input"), []any{sky_call(sky_attrSimple("type"), "text"), sky_call(sky_attrSimple("class"), "form-input"), sky_call(sky_attrSimple("placeholder"), "Choose a username"), sky_call(sky_attrSimple("value"), sky_asMap(model)["authUsername"]), sky_call(sky_evtHandler("input"), UpdateUsername)})}), sky_call(sky_call(sky_htmlEl("div"), []any{sky_call(sky_attrSimple("class"), "form-group")}), []any{sky_call(sky_call(sky_htmlEl("label"), []any{sky_call(sky_attrSimple("class"), "form-label")}), []any{sky_htmlText("Email")}), sky_call(sky_htmlVoid("input"), []any{sky_call(sky_attrSimple("type"), "email"), sky_call(sky_attrSimple("class"), "form-input"), sky_call(sky_attrSimple("placeholder"), "you@example.com"), sky_call(sky_attrSimple("value"), sky_asMap(model)["authEmail"]), sky_call(sky_evtHandler("input"), UpdateEmail)})}), sky_call(sky_call(sky_htmlEl("div"), []any{sky_call(sky_attrSimple("class"), "form-group")}), []any{sky_call(sky_call(sky_htmlEl("label"), []any{sky_call(sky_attrSimple("class"), "form-label")}), []any{sky_htmlText("Password")}), sky_call(sky_htmlVoid("input"), []any{sky_call(sky_attrSimple("type"), "password"), sky_call(sky_attrSimple("class"), "form-input"), sky_call(sky_attrSimple("placeholder"), "At least 8 characters"), sky_call(sky_attrSimple("value"), sky_asMap(model)["authPassword"]), sky_call(sky_evtHandler("input"), UpdatePassword)})}), sky_call(sky_call(sky_htmlEl("button"), []any{sky_call(sky_attrSimple("type"), "submit"), sky_call(sky_attrSimple("class"), "btn btn-primary"), sky_call(sky_attrSimple("class"), "auth-btn-full")}), []any{sky_htmlText("Create account")})}), sky_call(sky_call(sky_htmlEl("div"), []any{sky_call(sky_attrSimple("class"), "auth-footer")}), []any{sky_htmlText("Already have an account? "), sky_call(sky_call(sky_htmlEl("a"), []any{sky_call(sky_attrSimple("href"), "/auth/signin"), sky_call(sky_attrCustom("sky-nav"), "")}), []any{sky_htmlText("Sign in")})})})})
}

func Page_AuthPage_ViewSignUp(model any) any {
	return Ui_Layout_Page(model, Page_AuthPage_SignUpContent(model))
}

func Page_AuthPage_SignInContent(model any) any {
	return sky_call(sky_call(sky_htmlEl("div"), []any{sky_call(sky_attrSimple("class"), "auth-container")}), []any{sky_call(sky_call(sky_htmlEl("div"), []any{sky_call(sky_attrSimple("class"), "auth-card")}), []any{sky_call(sky_call(sky_htmlEl("h1"), []any{sky_call(sky_attrSimple("class"), "auth-title")}), []any{sky_htmlText("Welcome back")}), Page_AuthPage_ViewAuthError(sky_asMap(model)["authError"]), sky_call(sky_call(sky_htmlEl("form"), []any{sky_call(sky_evtHandler("submit"), DoSignIn)}), []any{sky_call(sky_call(sky_htmlEl("div"), []any{sky_call(sky_attrSimple("class"), "form-group")}), []any{sky_call(sky_call(sky_htmlEl("label"), []any{sky_call(sky_attrSimple("class"), "form-label")}), []any{sky_htmlText("Email")}), sky_call(sky_htmlVoid("input"), []any{sky_call(sky_attrSimple("type"), "email"), sky_call(sky_attrSimple("class"), "form-input"), sky_call(sky_attrSimple("placeholder"), "you@example.com"), sky_call(sky_attrSimple("value"), sky_asMap(model)["authEmail"]), sky_call(sky_evtHandler("input"), UpdateEmail)})}), sky_call(sky_call(sky_htmlEl("div"), []any{sky_call(sky_attrSimple("class"), "form-group")}), []any{sky_call(sky_call(sky_htmlEl("label"), []any{sky_call(sky_attrSimple("class"), "form-label")}), []any{sky_htmlText("Password")}), sky_call(sky_htmlVoid("input"), []any{sky_call(sky_attrSimple("type"), "password"), sky_call(sky_attrSimple("class"), "form-input"), sky_call(sky_attrSimple("placeholder"), "Your password"), sky_call(sky_attrSimple("value"), sky_asMap(model)["authPassword"]), sky_call(sky_evtHandler("input"), UpdatePassword)})}), sky_call(sky_call(sky_htmlEl("button"), []any{sky_call(sky_attrSimple("type"), "submit"), sky_call(sky_attrSimple("class"), "btn btn-primary"), sky_call(sky_attrSimple("class"), "auth-btn-full")}), []any{sky_htmlText("Sign in")})}), sky_call(sky_call(sky_htmlEl("div"), []any{sky_call(sky_attrSimple("class"), "auth-footer")}), []any{sky_htmlText("Don't have an account? "), sky_call(sky_call(sky_htmlEl("a"), []any{sky_call(sky_attrSimple("href"), "/auth/signup"), sky_call(sky_attrCustom("sky-nav"), "")}), []any{sky_htmlText("Sign up")})})})})
}

func Page_AuthPage_ViewSignIn(model any) any {
	return Ui_Layout_Page(model, Page_AuthPage_SignInContent(model))
}