// hash:3-11
func Page_Roadmap_ViewRoadmap(model any) any {
	return func() any { planned := Lib_Ideas_GetIdeasByStatus("planned"); _ = planned; inProgress := Lib_Ideas_GetIdeasByStatus("in-progress"); _ = inProgress; done := Lib_Ideas_GetIdeasByStatus("done"); _ = done; open_ := Lib_Ideas_GetIdeasByStatus("open"); _ = open_; return Ui_Layout_Page(model, sky_call(sky_call(sky_htmlEl("div"), []any{sky_call(sky_attrSimple("class"), "mt-32")}), []any{sky_call(sky_call(sky_htmlEl("h1"), []any{sky_call(sky_attrSimple("class"), "page-title")}), []any{sky_htmlText("Roadmap")}), sky_call(sky_call(sky_htmlEl("p"), []any{sky_call(sky_attrSimple("class"), "page-subtitle")}), []any{sky_htmlText("Track the progress of community ideas from submission to completion.")}), sky_call(sky_call(sky_htmlEl("div"), []any{sky_call(sky_attrSimple("class"), "roadmap-grid")}), []any{Page_Roadmap_RoadmapColumn("Open", "Awaiting review", open_), Page_Roadmap_RoadmapColumn("Planned", "On the roadmap", planned), Page_Roadmap_RoadmapColumn("In Progress", "Currently being built", inProgress), Page_Roadmap_RoadmapColumn("Done", "Shipped!", done)})})) }()
}

func Page_Roadmap_RoadmapColumn(title any, subtitle any, items any) any {
	return sky_call(sky_call(sky_htmlEl("div"), []any{sky_call(sky_attrSimple("class"), "roadmap-column")}), []any{sky_call(sky_call(sky_htmlEl("div"), []any{sky_call(sky_attrSimple("class"), "roadmap-column-title")}), []any{sky_htmlText(title), sky_call(sky_call(sky_htmlEl("span"), []any{sky_call(sky_attrSimple("class"), "roadmap-count")}), []any{sky_htmlText(sky_concat("(", sky_concat(sky_stringFromInt(sky_listLength(items)), ")")))})}), sky_call(sky_call(sky_htmlEl("p"), []any{sky_call(sky_attrSimple("class"), "roadmap-subtitle")}), []any{sky_htmlText(subtitle)}), sky_call(sky_call(sky_htmlEl("div"), []any{}), func() any { if sky_asBool(sky_listIsEmpty(items)) { return []any{sky_call(sky_call(sky_htmlEl("p"), []any{sky_call(sky_attrSimple("class"), "roadmap-empty")}), []any{sky_htmlText("Nothing here yet")})} }; return sky_call(sky_listMap(Page_Roadmap_RoadmapItem), items) }())})
}

func Page_Roadmap_RoadmapItem(idea any) any {
	return func() any { ideaId := Lib_Db_GetField("id", idea); _ = ideaId; voteCount := Lib_Db_GetField("vote_count", idea); _ = voteCount; return sky_call(sky_call(sky_htmlEl("div"), []any{sky_call(sky_attrSimple("class"), "roadmap-item")}), []any{sky_call(sky_call(sky_htmlEl("button"), []any{sky_call(sky_evtHandler("click"), ViewIdea(ideaId)), sky_call(sky_attrSimple("class"), "roadmap-item-title")}), []any{sky_htmlText(Lib_Db_GetField("title", idea))}), sky_call(sky_call(sky_htmlEl("div"), []any{sky_call(sky_attrSimple("class"), "roadmap-item-votes")}), []any{sky_htmlText(sky_concat(voteCount, " votes"))})}) }()(0, 0)
}