// hash:9-11
func Page_Detail_ViewDetail(model any) any {
	return func() any { return func() any { __subject := sky_asMap(model)["selectedIdea"]; if sky_asSkyMaybe(__subject).SkyName == "Just" { idea := sky_asSkyMaybe(__subject).JustValue; _ = idea; return Ui_Layout_Page(model, Page_Detail_ViewIdeaDetail(model, idea)) };  if sky_asSkyMaybe(__subject).SkyName == "Nothing" { return Ui_Layout_Page(model, Page_Detail_ViewNotFound(model)) };  panic("non-exhaustive case expression") }() }()
}

func Page_Detail_ViewNotFound(model any) any {
	return sky_call(sky_call(sky_htmlEl("div"), []any{sky_call(sky_attrSimple("class"), "mt-32")}), []any{emptyState("Idea not found."), sky_call(sky_call(sky_htmlEl("div"), []any{sky_call(sky_attrSimple("class"), "text-center")}), []any{sky_call(sky_call(sky_htmlEl("button"), []any{sky_call(sky_evtHandler("click"), BackToBoard), sky_call(sky_attrSimple("class"), "btn btn-secondary")}), []any{sky_htmlText("Back to Board")})})})
}

func Page_Detail_ViewIdeaDetail(model any, idea any) any {
	return func() any { ideaId := Lib_Db_GetField("id", idea); _ = ideaId; voteCount := Lib_Db_GetField("vote_count", idea); _ = voteCount; commentCount := Lib_Db_GetField("comment_count", idea); _ = commentCount; status := Lib_Db_GetField("status", idea); _ = status; category := Lib_Db_GetField("category", idea); _ = category; return sky_call(sky_call(sky_htmlEl("div"), []any{sky_call(sky_attrSimple("class"), "mt-32")}), []any{sky_call(sky_call(sky_htmlEl("button"), []any{sky_call(sky_evtHandler("click"), BackToBoard), sky_call(sky_attrSimple("class"), "btn btn-ghost btn-sm mb-16")}), []any{sky_htmlText("< Back to Board")}), sky_call(sky_call(sky_htmlEl("div"), []any{sky_call(sky_attrSimple("class"), "card")}), []any{sky_call(sky_call(sky_htmlEl("div"), []any{sky_call(sky_attrSimple("class"), "detail-header")}), []any{sky_call(sky_call(sky_htmlEl("div"), []any{sky_call(sky_attrSimple("class"), "flex-row-gap-8")}), []any{Page_Detail_ViewCategoryBadge(category), statusBadge(status)}), sky_call(sky_call(sky_htmlEl("h1"), []any{sky_call(sky_attrSimple("class"), "detail-title")}), []any{sky_htmlText(Lib_Db_GetField("title", idea))}), sky_call(sky_call(sky_htmlEl("div"), []any{sky_call(sky_attrSimple("class"), "idea-meta")}), []any{sky_call(sky_call(sky_htmlEl("span"), []any{}), []any{sky_htmlText(sky_concat("by ", Lib_Db_GetField("author_name", idea)))}), sky_call(sky_call(sky_htmlEl("span"), []any{}), []any{sky_htmlText(Lib_Db_GetField("created_at", idea))})})}), sky_call(sky_call(sky_htmlEl("div"), []any{sky_call(sky_attrSimple("class"), "detail-body")}), []any{sky_call(sky_call(sky_htmlEl("p"), []any{}), []any{sky_htmlText(Lib_Db_GetField("description", idea))})}), sky_call(sky_call(sky_htmlEl("div"), []any{sky_call(sky_attrSimple("class"), "detail-actions")}), []any{sky_call(sky_call(sky_htmlEl("button"), []any{sky_call(sky_evtHandler("click"), ToggleVote(ideaId)), sky_call(sky_attrSimple("class"), "vote-btn")}), []any{sky_call(sky_call(sky_htmlEl("span"), []any{sky_call(sky_attrSimple("class"), "vote-count")}), []any{sky_htmlText(voteCount)}), sky_call(sky_call(sky_htmlEl("span"), []any{sky_call(sky_attrSimple("class"), "vote-label")}), []any{sky_htmlText("votes")})}), sky_call(sky_call(sky_htmlEl("span"), []any{sky_call(sky_attrSimple("class"), "idea-meta")}), []any{sky_htmlText(sky_concat(commentCount, " comments"))})})}), Page_Detail_ViewComments(model)}) }()
}

func Page_Detail_ViewCategoryBadge(category any) any {
	return func() any { if sky_asBool(sky_equal(category, "bug")) { return sky_call(sky_call(sky_htmlEl("span"), []any{sky_call(sky_attrSimple("class"), "badge badge-bug")}), []any{sky_htmlText("Bug")}) }; if sky_asBool(sky_equal(category, "improvement")) { return sky_call(sky_call(sky_htmlEl("span"), []any{sky_call(sky_attrSimple("class"), "badge badge-improvement")}), []any{sky_htmlText("Improvement")}) }; return sky_call(sky_call(sky_htmlEl("span"), []any{sky_call(sky_attrSimple("class"), "badge badge-feature")}), []any{sky_htmlText("Feature")}) }()
}

func Page_Detail_ViewComments(model any) any {
	return sky_call(sky_call(sky_htmlEl("div"), []any{sky_call(sky_attrSimple("class"), "comments-section")}), []any{sky_call(sky_call(sky_htmlEl("h2"), []any{sky_call(sky_attrSimple("class"), "comments-title")}), []any{sky_htmlText(sky_concat("Comments (", sky_concat(sky_stringFromInt(sky_listLength(sky_asMap(model)["ideaComments"])), ")")))}), Page_Detail_ViewCommentForm(model), Page_Detail_ViewCommentList(model)})
}

func Page_Detail_ViewCommentList(model any) any {
	return sky_call(sky_call(sky_htmlEl("div"), []any{}), func() any { if sky_asBool(sky_listIsEmpty(sky_asMap(model)["ideaComments"])) { return []any{sky_call(sky_call(sky_htmlEl("p"), []any{sky_call(sky_attrSimple("class"), "text-muted-sm")}), []any{sky_htmlText("No comments yet. Be the first to share your thoughts!")})} }; return sky_call(sky_listMap(Page_Detail_ViewComment), sky_asMap(model)["ideaComments"]) }())
}

func Page_Detail_ViewComment(comment any) any {
	return sky_call(sky_call(sky_htmlEl("div"), []any{sky_call(sky_attrSimple("class"), "comment")}), []any{sky_call(sky_call(sky_htmlEl("div"), []any{sky_call(sky_attrSimple("class"), "comment-header")}), []any{sky_call(sky_call(sky_htmlEl("span"), []any{sky_call(sky_attrSimple("class"), "comment-author")}), []any{sky_htmlText(Lib_Db_GetField("author_name", comment))}), sky_call(sky_call(sky_htmlEl("span"), []any{sky_call(sky_attrSimple("class"), "comment-date")}), []any{sky_htmlText(Lib_Db_GetField("created_at", comment))})}), sky_call(sky_call(sky_htmlEl("div"), []any{sky_call(sky_attrSimple("class"), "comment-body")}), []any{sky_htmlText(Lib_Db_GetField("content", comment))})})
}

func Page_Detail_ViewCommentForm(model any) any {
	return func() any { return func() any { __subject := sky_asMap(model)["currentUser"]; if sky_asSkyMaybe(__subject).SkyName == "Just" { return Page_Detail_ViewCommentFormAuth(model) };  if sky_asSkyMaybe(__subject).SkyName == "Nothing" { return sky_call(sky_call(sky_htmlEl("p"), []any{sky_call(sky_attrSimple("class"), "text-secondary-sm")}), []any{sky_htmlText("Sign in to leave a comment.")}) };  panic("non-exhaustive case expression") }() }()
}

func Page_Detail_ViewCommentFormAuth(model any) any {
	return sky_call(sky_call(sky_htmlEl("form"), []any{sky_call(sky_evtHandler("submit"), SubmitComment), sky_call(sky_attrSimple("class"), "comment-form mb-20")}), []any{sky_call(sky_call(sky_htmlEl("div"), []any{sky_call(sky_attrSimple("class"), "form-group")}), []any{sky_call(sky_call(sky_htmlEl("textarea"), []any{sky_call(sky_attrSimple("class"), "form-input"), sky_call(sky_attrSimple("placeholder"), "Share your thoughts..."), sky_call(sky_attrSimple("value"), sky_asMap(model)["newComment"]), sky_call(sky_evtHandler("input"), UpdateComment), sky_call(sky_attrSimple("rows"), 3)}), []any{})}), sky_call(sky_call(sky_htmlEl("button"), []any{sky_call(sky_attrSimple("type"), "submit"), sky_call(sky_attrSimple("class"), "btn btn-primary btn-sm")}), []any{sky_htmlText("Post Comment")})})
}