// hash:5-9
func Ui_Layout_ViewNotification(model any) any {
	return func() any { if sky_asBool(sky_equal(sky_asMap(model)["notification"], "")) { return sky_htmlText("") }; return sky_call(sky_call(sky_htmlEl("div"), []any{sky_call(sky_attrSimple("class"), "notification")}), []any{sky_htmlText(sky_asMap(model)["notification"])}) }()
}

func Ui_Layout_Page(model any, content any) any {
	return sky_call(sky_call(sky_htmlEl("div"), []any{}), []any{sky_call(sky_htmlStyleNode([]any{}), globalStyles), Ui_Layout_ViewHeader(model), sky_call(sky_call(sky_htmlEl("div"), []any{sky_call(sky_attrSimple("class"), "container")}), []any{Ui_Layout_ViewNotification(model), content})})
}

func Ui_Layout_PageWithAuth(model any, content any) any {
	return func() any { return func() any { __subject := sky_asMap(model)["currentUser"]; if sky_asSkyMaybe(__subject).SkyName == "Just" { return Ui_Layout_Page(model, content) };  if sky_asSkyMaybe(__subject).SkyName == "Nothing" { return Ui_Layout_Page(model, sky_call(sky_call(sky_htmlEl("div"), []any{sky_call(sky_attrSimple("class"), "auth-container")}), []any{sky_call(sky_call(sky_htmlEl("div"), []any{sky_call(sky_attrSimple("class"), "card")}), []any{sky_call(sky_call(sky_htmlEl("p"), []any{sky_call(sky_attrSimple("class"), "auth-prompt")}), []any{sky_htmlText("Please "), sky_call(sky_call(sky_htmlEl("a"), []any{sky_call(sky_attrSimple("href"), "/auth/signin"), sky_call(sky_attrCustom("sky-nav"), "")}), []any{sky_htmlText("sign in")}), sky_htmlText(" to access this page.")})})})) };  panic("non-exhaustive case expression") }() }()
}

func Ui_Layout_ViewHeader(model any) any {
	return sky_call(sky_call(sky_htmlEl("header"), []any{sky_call(sky_attrSimple("class"), "header")}), []any{sky_call(sky_call(sky_htmlEl("div"), []any{sky_call(sky_attrSimple("class"), "header-inner")}), []any{sky_call(sky_call(sky_htmlEl("a"), []any{sky_call(sky_attrSimple("href"), "/"), sky_call(sky_attrCustom("sky-nav"), ""), sky_call(sky_attrSimple("class"), "logo")}), []any{sky_htmlText("SkyVote")}), sky_call(sky_call(sky_htmlEl("nav"), []any{sky_call(sky_attrSimple("class"), "nav")}), []any{sky_call(sky_call(sky_htmlEl("a"), []any{sky_call(sky_attrSimple("href"), "/"), sky_call(sky_attrCustom("sky-nav"), ""), sky_call(sky_attrSimple("class"), "nav-link")}), []any{sky_htmlText("Board")}), sky_call(sky_call(sky_htmlEl("a"), []any{sky_call(sky_attrSimple("href"), "/roadmap"), sky_call(sky_attrCustom("sky-nav"), ""), sky_call(sky_attrSimple("class"), "nav-link")}), []any{sky_htmlText("Roadmap")}), sky_call(sky_call(sky_htmlEl("a"), []any{sky_call(sky_attrSimple("href"), "/about"), sky_call(sky_attrCustom("sky-nav"), ""), sky_call(sky_attrSimple("class"), "nav-link")}), []any{sky_htmlText("About")}), Ui_Layout_ViewAuthNav(model)})})})
}

func Ui_Layout_ViewAuthNav(model any) any {
	return func() any { return func() any { __subject := sky_asMap(model)["currentUser"]; if sky_asSkyMaybe(__subject).SkyName == "Just" { user := sky_asSkyMaybe(__subject).JustValue; _ = user; return sky_call(sky_call(sky_htmlEl("span"), []any{sky_call(sky_attrSimple("class"), "auth-nav")}), []any{sky_call(sky_call(sky_htmlEl("a"), []any{sky_call(sky_attrSimple("href"), "/submit"), sky_call(sky_attrCustom("sky-nav"), ""), sky_call(sky_attrSimple("class"), "btn btn-primary btn-sm")}), []any{sky_htmlText("Submit Idea")}), sky_call(sky_call(sky_htmlEl("span"), []any{sky_call(sky_attrSimple("class"), "nav-link")}), []any{sky_htmlText(Lib_Db_GetField("username", user))}), sky_call(sky_call(sky_htmlEl("button"), []any{sky_call(sky_evtHandler("click"), DoSignOut), sky_call(sky_attrSimple("class"), "btn btn-ghost btn-sm")}), []any{sky_htmlText("Sign out")})}) };  if sky_asSkyMaybe(__subject).SkyName == "Nothing" { return sky_call(sky_call(sky_htmlEl("span"), []any{sky_call(sky_attrSimple("class"), "auth-nav-anon")}), []any{sky_call(sky_call(sky_htmlEl("a"), []any{sky_call(sky_attrSimple("href"), "/auth/signin"), sky_call(sky_attrCustom("sky-nav"), ""), sky_call(sky_attrSimple("class"), "nav-link")}), []any{sky_htmlText("Sign in")}), sky_call(sky_call(sky_htmlEl("a"), []any{sky_call(sky_attrSimple("href"), "/auth/signup"), sky_call(sky_attrCustom("sky-nav"), ""), sky_call(sky_attrSimple("class"), "btn btn-primary btn-sm")}), []any{sky_htmlText("Sign up")})}) };  panic("non-exhaustive case expression") }() }()
}