// Code generated by sky-ffi-inspect from github.com/joho/godotenv. DO NOT EDIT.
// Re-run `sky add github.com/joho/godotenv` to regenerate.
//
// Wrapper functions are in `package rt` with names <Kernel>_<lowerFn>.
// Sky source resolves `import Github.Com.Joho.Godotenv as X` and calls `X.<lowerFn>` — the canonicaliser routes it via
// the FFI registry to these typed Go functions. Every wrapper wraps
// panics in Err[any, any] via SkyFfiRecover.

package rt

import (
	pkg "github.com/joho/godotenv"
	"fmt"
	io "io"
)

// [fallible] typed wrapper for Go_Godotenv_exec (P7 adaptor target)
func Go_Godotenv_execT(arg0 []string, arg1 string, arg2 []string, arg3 bool) (out SkyResult[any, struct{}]) {
	defer SkyFfiRecoverT(&out)()
	err := pkg.Exec(arg0, arg1, arg2, arg3)
	if err != nil { out = Err[any,struct{}](ErrFfi(err.Error())); return }
	out = Ok[any,struct{}](struct{}{})
	return
}

// [fallible] typed wrapper for Go_Godotenv_load (P7 adaptor target)
func Go_Godotenv_loadT(arg0 []string) (out SkyResult[any, struct{}]) {
	defer SkyFfiRecoverT(&out)()
	err := pkg.Load(arg0...)
	if err != nil { out = Err[any,struct{}](ErrFfi(err.Error())); return }
	out = Ok[any,struct{}](struct{}{})
	return
}

// [fallible] typed wrapper for Go_Godotenv_marshal (P7 adaptor target)
func Go_Godotenv_marshalT(arg0 map[string]string) (out SkyResult[any, string]) {
	defer SkyFfiRecoverT(&out)()
	r0, err := pkg.Marshal(arg0)
	if err != nil { out = Err[any,string](ErrFfi(err.Error())); return }
	out = Ok[any,string](r0)
	return
}

// [fallible] typed wrapper for Go_Godotenv_overload (P7 adaptor target)
func Go_Godotenv_overloadT(arg0 []string) (out SkyResult[any, struct{}]) {
	defer SkyFfiRecoverT(&out)()
	err := pkg.Overload(arg0...)
	if err != nil { out = Err[any,struct{}](ErrFfi(err.Error())); return }
	out = Ok[any,struct{}](struct{}{})
	return
}

type FfiT_Go_Godotenv_parse_P0 = io.Reader
// [fallible] typed wrapper for Go_Godotenv_parse (P7 adaptor target)
func Go_Godotenv_parseT(arg0 io.Reader) (out SkyResult[any, map[string]string]) {
	defer SkyFfiRecoverT(&out)()
	r0, err := pkg.Parse(arg0)
	if err != nil { out = Err[any,map[string]string](ErrFfi(err.Error())); return }
	out = Ok[any,map[string]string](r0)
	return
}

// [fallible] typed wrapper for Go_Godotenv_read (P7 adaptor target)
func Go_Godotenv_readT(arg0 []string) (out SkyResult[any, map[string]string]) {
	defer SkyFfiRecoverT(&out)()
	r0, err := pkg.Read(arg0...)
	if err != nil { out = Err[any,map[string]string](ErrFfi(err.Error())); return }
	out = Ok[any,map[string]string](r0)
	return
}

// [fallible] typed wrapper for Go_Godotenv_unmarshal (P7 adaptor target)
func Go_Godotenv_unmarshalT(arg0 string) (out SkyResult[any, map[string]string]) {
	defer SkyFfiRecoverT(&out)()
	r0, err := pkg.Unmarshal(arg0)
	if err != nil { out = Err[any,map[string]string](ErrFfi(err.Error())); return }
	out = Ok[any,map[string]string](r0)
	return
}

// [fallible] typed wrapper for Go_Godotenv_unmarshalBytes (P7 adaptor target)
func Go_Godotenv_unmarshalBytesT(arg0 []byte) (out SkyResult[any, map[string]string]) {
	defer SkyFfiRecoverT(&out)()
	r0, err := pkg.UnmarshalBytes(arg0)
	if err != nil { out = Err[any,map[string]string](ErrFfi(err.Error())); return }
	out = Ok[any,map[string]string](r0)
	return
}

// [fallible] typed wrapper for Go_Godotenv_write (P7 adaptor target)
func Go_Godotenv_writeT(arg0 map[string]string, arg1 string) (out SkyResult[any, struct{}]) {
	defer SkyFfiRecoverT(&out)()
	err := pkg.Write(arg0, arg1)
	if err != nil { out = Err[any,struct{}](ErrFfi(err.Error())); return }
	out = Ok[any,struct{}](struct{}{})
	return
}


// Pin fmt against "imported and not used" across partial files.
var _ = fmt.Sprintf
