//! E-5: every stdlib name collision a release introduces is listed, reviewed
//! and printed in the CHANGELOG's Breaking section.
//!
//! WHY. `import A exposing (..)` + `import B exposing (..)` is legal, and an
//! unqualified name both modules export is `[E1012]` at its use. So a name a
//! stdlib module STARTS to export can break a program that compiled with the
//! previous release, with no change on the user's side:
//! `import Std.Html.Attributes exposing (..)` + `import Sky.Core.Json.Decode
//! exposing (..)` + a bare `value` compiled with v0.26.1 and is ambiguous in
//! v0.27.0, where `Json.Decode.value` was added. That break is loud and has a
//! one-line fix, so it is allowed, but only when it is known.
//!
//! The SILENT case is worse. An `exposing (..)` import (the Open layer) beats
//! the ambient Prelude and builtins with no diagnostic
//! (`hir/src/resolve.rs`, `BindLayer`). A new stdlib export equal to an ambient
//! name would change what an old program computes without any error.
//!
//! This test compares the stdlib's exports now with the committed snapshot of
//! the previous release (`hir/data/stdlib-exports-v0.26.1.tsv`, regenerated by
//! `hir/tests/regen-stdlib-exports-snapshot.sh`), for values, types and
//! constructors, and for kernel pseudo-modules (`import Auth exposing (..)`).
//! It fails on a collision not in [`EXPECTED_COLLISIONS`], on a listed one that
//! no longer happens, and on any silent rebinding of an ambient name.

use base::FileId;
use hir::stdlib_history::{parse_export_rows, ExportRow, PREVIOUS_EXPORTS_TSV};
use hir::SourceDb;
use std::collections::{BTreeMap, BTreeSet};
use std::path::{Path, PathBuf};

/// The collisions the current stdlib introduces against the previous release,
/// as `namespace name`. Each one is a Breaking entry in the CHANGELOG: an old
/// program that imports two of the listed modules with `exposing (..)` and
/// uses the name bare now gets `[E1012]`, whose message names the new export
/// and both fixes (qualify the name, or narrow one `exposing` list).
///
/// A new entry here is a decision, not a formality: prefer a name that does not
/// collide. The failure message lists the module pairs for each name.
const EXPECTED_COLLISIONS: &[&str] = &[
    "ctor Done",
    "type Event",
    "type Running",
    "type Step",
    "value address",
    "value close",
    "value island",
    "value onIslandEvent",
    "value raw",
    "value rpc",
    "value serve",
    "value spawn",
    "value stop",
    "value toMaybe",
    "value value",
    "value withClientCrypto",
    "value withEmbedded",
    "value withName",
    "value withSessionTransport",
];

/// Names a module NEW in this release shares with a module that existed
/// before. No old program imports the new module, so these break nothing that
/// compiled; a user who adds the import gets `[E1012]` at a bare use and
/// qualifies it. Listed so the set is reviewed, and so a rename that would
/// avoid a clash is considered before the release rather than after.
const EXPECTED_NEW_MODULE_OVERLAPS: &[&str] = &[
    "ctor High",
    "ctor Low",
    "ctor Medium",
    "type Point",
    "type Shape",
    "value close",
    "value encode",
    "value fill",
    "value finish",
    "value fontSize",
    "value get",
    "value group",
    "value line",
    "value onClick",
    "value opacity",
    "value path",
    "value rotate",
    "value rows",
    "value scale",
    "value size",
    "value start",
    "value text",
    "value translate",
    "value update",
];

fn repo_root() -> PathBuf {
    let mut dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    loop {
        if dir.join("sky-stdlib").is_dir() {
            return dir;
        }
        if !dir.pop() {
            panic!("could not locate repo root (no sky-stdlib ancestor)");
        }
    }
}

fn collect_sky(dir: &Path, out: &mut Vec<PathBuf>) {
    let Ok(rd) = std::fs::read_dir(dir) else {
        return;
    };
    let mut entries: Vec<PathBuf> = rd.filter_map(|e| e.ok().map(|e| e.path())).collect();
    entries.sort();
    for p in entries {
        if p.is_dir() {
            collect_sky(&p, out);
        } else if p.extension().and_then(|e| e.to_str()) == Some("sky") {
            out.push(p);
        }
    }
}

/// The export rows of a stdlib tree plus a kernel-function table, computed with
/// the SAME `hir::compute_exports` the resolver uses.
fn export_rows(stdlib: &Path, kernel_functions: &[(String, Vec<String>)]) -> BTreeSet<ExportRow> {
    let mut files = Vec::new();
    collect_sky(stdlib, &mut files);
    assert!(
        !files.is_empty(),
        "no .sky files under {}",
        stdlib.display()
    );
    let mut db = SourceDb::new();
    let mut names = Vec::new();
    for (i, path) in files.iter().enumerate() {
        let src = std::fs::read_to_string(path).unwrap();
        let parse = syntax::parse(&src, FileId(i as u32));
        let Some(name) = parse
            .tree()
            .module_header()
            .and_then(|h| h.name())
            .map(|n| n.text())
            .filter(|s| !s.is_empty())
        else {
            continue;
        };
        db.add_module(&name, parse);
        names.push(name);
    }
    let row = |kind: &str, module: &str, name: &str| ExportRow {
        kind: kind.to_string(),
        module: module.to_string(),
        name: name.to_string(),
    };
    let mut out = BTreeSet::new();
    for name in &names {
        let m = db.module_by_name(name).unwrap();
        let ex = db.module_exports(m);
        out.insert(row("module", name, ""));
        for (v, _) in &ex.values {
            out.insert(row("value", name, v.as_str()));
        }
        for u in &ex.unions {
            out.insert(row("type", name, u.name.as_str()));
            for c in &u.ctors {
                out.insert(row("ctor", name, c.name.as_str()));
            }
        }
        for a in &ex.aliases {
            out.insert(row("type", name, a.name.as_str()));
        }
    }
    for (pseudo, fns) in kernel_functions {
        let module = format!("kernel:{pseudo}");
        out.insert(row("module", &module, ""));
        for f in fns {
            out.insert(row("value", &module, f));
        }
    }
    out
}

fn current_kernel_functions() -> Vec<(String, Vec<String>)> {
    hir::KERNEL_FUNCTIONS
        .iter()
        .map(|(m, fns)| (m.to_string(), fns.iter().map(|f| f.to_string()).collect()))
        .collect()
}

/// `KERNEL_FUNCTIONS` read from a `hir/src/kernel.rs` source text (the previous
/// release's, for the snapshot). The table is a list of `("Mod", &[ "f", … ])`
/// entries; only string literals inside it matter.
fn kernel_functions_from_source(src: &str) -> Vec<(String, Vec<String>)> {
    let start = src
        .find("pub const KERNEL_FUNCTIONS")
        .expect("kernel.rs has KERNEL_FUNCTIONS");
    let body = &src[start..];
    let end = body.find("\n];").expect("KERNEL_FUNCTIONS ends with `];`");
    let body = &body[..end];
    let mut out: Vec<(String, Vec<String>)> = Vec::new();
    // Walk string literals; a literal followed (after whitespace) by `,` and
    // then `&[` opens a new module, others are members of the current one.
    let bytes = body.as_bytes();
    let mut i = 0;
    while i < bytes.len() {
        if bytes[i] == b'"' {
            let j = i + 1 + body[i + 1..].find('"').unwrap();
            let lit = &body[i + 1..j];
            let rest = body[j + 1..].trim_start();
            let rest = rest.strip_prefix(',').unwrap_or(rest).trim_start();
            if rest.starts_with("&[") {
                out.push((lit.to_string(), Vec::new()));
            } else if let Some(last) = out.last_mut() {
                last.1.push(lit.to_string());
            }
            i = j + 1;
        } else if bytes[i] == b'/' && bytes.get(i + 1) == Some(&b'/') {
            i += body[i..].find('\n').unwrap_or(body.len() - i);
        } else {
            i += 1;
        }
    }
    out
}

/// The namespace a row's name lives in for unqualified lookup.
fn namespace(kind: &str) -> Option<&'static str> {
    match kind {
        "value" => Some("value"),
        "type" => Some("type"),
        "ctor" => Some("ctor"),
        _ => None,
    }
}

type ByName = BTreeMap<(String, String), BTreeSet<String>>;

fn by_name(rows: &BTreeSet<ExportRow>) -> ByName {
    let mut m: ByName = BTreeMap::new();
    for r in rows {
        if let Some(ns) = namespace(&r.kind) {
            m.entry((ns.to_string(), r.name.clone()))
                .or_default()
                .insert(r.module.clone());
        }
    }
    m
}

fn modules(rows: &BTreeSet<ExportRow>) -> BTreeSet<String> {
    rows.iter()
        .filter(|r| r.kind == "module")
        .map(|r| r.module.clone())
        .collect()
}

/// True when one of the two is the kernel pseudo-module the other `.sky` module
/// is the typed face of (`Sky.Core.Encoding` and `kernel:Encoding`). Importing a
/// module and its own bare kernel alias together is not a program anyone
/// writes, and the pair gains every new member of that module at once, so it
/// would bury the real collisions.
fn same_kernel(a: &str, b: &str) -> bool {
    let face = |m: &str, k: &str| {
        k.strip_prefix("kernel:").is_some_and(|pseudo| {
            hir::KERNEL_MODULES
                .iter()
                .any(|(path, p)| *path == m && *p == pseudo)
        })
    };
    face(a, b) || face(b, a)
}

/// `(namespace name) -> ["A + B", …]`: pairs of modules that both existed in
/// the previous release and both export the name now, but did not both export
/// it then. Exactly the pairs an old program can import together and newly
/// meet `[E1012]` on.
fn new_collisions(
    old: &BTreeSet<ExportRow>,
    new: &BTreeSet<ExportRow>,
) -> BTreeMap<String, Vec<String>> {
    let old_mods = modules(old);
    let old_by = by_name(old);
    let mut out: BTreeMap<String, Vec<String>> = BTreeMap::new();
    for ((ns, name), mods) in by_name(new) {
        let mods: Vec<&String> = mods.iter().filter(|m| old_mods.contains(*m)).collect();
        let before = old_by.get(&(ns.clone(), name.clone()));
        for (i, a) in mods.iter().enumerate() {
            for b in &mods[i + 1..] {
                let both_before = before.is_some_and(|s| s.contains(*a) && s.contains(*b));
                if !both_before && !same_kernel(a, b) {
                    out.entry(format!("{ns} {name}"))
                        .or_default()
                        .push(format!("{a} + {b}"));
                }
            }
        }
    }
    out
}

/// Names an unqualified reference gets from the ambient layer: the builtins and
/// the Prelude (`import Sky.Core.Prelude exposing (..)`, the `Basics` kernel
/// pseudo-module).
fn ambient_names() -> BTreeSet<(String, String)> {
    let mut s = BTreeSet::new();
    for (n, _, _) in hir::BUILTIN_VARS {
        s.insert(("value".to_string(), n.to_string()));
    }
    for (n, _) in hir::BUILTIN_TYPES {
        s.insert(("type".to_string(), n.to_string()));
    }
    for (n, _, _, _) in hir::BUILTIN_CTORS {
        s.insert(("ctor".to_string(), n.to_string()));
    }
    for f in hir::kernel_functions("Basics").unwrap_or(&[]) {
        s.insert(("value".to_string(), f.to_string()));
    }
    s
}

fn previous_rows() -> BTreeSet<ExportRow> {
    parse_export_rows(PREVIOUS_EXPORTS_TSV)
        .into_iter()
        .collect()
}

fn current_rows() -> BTreeSet<ExportRow> {
    export_rows(&repo_root().join("sky-stdlib"), &current_kernel_functions())
}

#[test]
fn snapshot_is_well_formed() {
    let old = previous_rows();
    let mods = modules(&old);
    assert!(
        mods.contains("Sky.Core.Json.Decode"),
        "snapshot lists modules"
    );
    assert!(
        mods.contains("kernel:Basics"),
        "snapshot lists kernel pseudo-modules"
    );
    assert!(
        old.iter().all(|r| mods.contains(&r.module)),
        "every row's module has a `module` row"
    );
    // A known v0.26.1 fact and a known v0.27.0 addition, so a stale or empty
    // snapshot cannot pass the comparison below vacuously.
    let has = |kind: &str, m: &str, n: &str| {
        old.iter()
            .any(|r| r.kind == kind && r.module == m && r.name == n)
    };
    assert!(has("value", "Std.Html.Attributes", "value"));
    assert!(!has("value", "Sky.Core.Json.Decode", "value"));
}

#[test]
fn every_new_stdlib_collision_is_listed() {
    let found = new_collisions(&previous_rows(), &current_rows());
    let expected: BTreeSet<String> = EXPECTED_COLLISIONS.iter().map(|s| s.to_string()).collect();
    let got: BTreeSet<String> = found.keys().cloned().collect();
    let unlisted: Vec<String> = got
        .difference(&expected)
        .map(|k| format!("  {k}: {}", found[k].join(", ")))
        .collect();
    let stale: Vec<&String> = expected.difference(&got).collect();
    assert!(
        unlisted.is_empty() && stale.is_empty(),
        "stdlib name collisions against the previous release changed.\n\
         Unlisted (a new export makes an old `exposing (..)` pair ambiguous; rename it, or \
         add it to EXPECTED_COLLISIONS and a Breaking line to the CHANGELOG):\n{}\n\
         Listed but no longer colliding (remove from EXPECTED_COLLISIONS):\n  {stale:?}",
        unlisted.join("\n")
    );
}

#[test]
fn every_new_module_overlap_is_listed() {
    let old = previous_rows();
    let old_mods = modules(&old);
    let now = current_rows();
    let now_by = by_name(&now);
    let mut found: BTreeMap<String, BTreeSet<String>> = BTreeMap::new();
    for ((ns, name), mods) in &now_by {
        let fresh: Vec<&String> = mods.iter().filter(|m| !old_mods.contains(*m)).collect();
        let older: Vec<&String> = mods.iter().filter(|m| old_mods.contains(*m)).collect();
        if fresh.is_empty() || older.is_empty() {
            continue;
        }
        for f in &fresh {
            for o in &older {
                if !same_kernel(f, o) {
                    found
                        .entry(format!("{ns} {name}"))
                        .or_default()
                        .insert(format!("{f} + {o}"));
                }
            }
        }
    }
    let expected: BTreeSet<String> = EXPECTED_NEW_MODULE_OVERLAPS
        .iter()
        .map(|s| s.to_string())
        .collect();
    let got: BTreeSet<String> = found.keys().cloned().collect();
    let unlisted: Vec<String> = got
        .difference(&expected)
        .map(|k| {
            format!(
                "  {k}: {}",
                found[k].iter().cloned().collect::<Vec<_>>().join(", ")
            )
        })
        .collect();
    let stale: Vec<&String> = expected.difference(&got).collect();
    assert!(
        unlisted.is_empty() && stale.is_empty(),
        "names shared between a NEW stdlib module and an older one changed.\n\
         Unlisted:\n{}\nListed but gone:\n  {stale:?}",
        unlisted.join("\n")
    );
}

#[test]
fn no_new_stdlib_export_silently_rebinds_an_ambient_name() {
    let old = previous_rows();
    let old_mods = modules(&old);
    let ambient = ambient_names();
    let mut silent = Vec::new();
    for r in current_rows() {
        let Some(ns) = namespace(&r.kind) else {
            continue;
        };
        // The ambient layer itself (`kernel:Basics`) and modules no old program
        // could import are not a rebinding hazard.
        if r.module == "kernel:Basics" || !old_mods.contains(&r.module) {
            continue;
        }
        let existed = old
            .iter()
            .any(|o| o.kind == r.kind && o.module == r.module && o.name == r.name);
        if !existed && ambient.contains(&(ns.to_string(), r.name.clone())) {
            silent.push(format!("{ns} {}.{}", r.module, r.name));
        }
    }
    assert!(
        silent.is_empty(),
        "a new stdlib export equals an ambient (Prelude/builtin) name. Under `exposing (..)` \
         it would silently replace the ambient meaning in programs that compiled before, with \
         no diagnostic. Rename it:\n  {}",
        silent.join("\n  ")
    );
}

/// Writes the snapshot. Run by `hir/tests/regen-stdlib-exports-snapshot.sh`,
/// which extracts the previous release's `sky-stdlib/` and `hir/src/kernel.rs`
/// and points these variables at them.
#[test]
#[ignore = "generator: run through regen-stdlib-exports-snapshot.sh"]
fn regenerate_previous_release_snapshot() {
    let stdlib = std::env::var("SKY_SNAPSHOT_STDLIB").expect("SKY_SNAPSHOT_STDLIB");
    let kernel_rs = std::env::var("SKY_SNAPSHOT_KERNEL_RS").expect("SKY_SNAPSHOT_KERNEL_RS");
    let tag = std::env::var("SKY_SNAPSHOT_TAG").expect("SKY_SNAPSHOT_TAG");
    let out = std::env::var("SKY_SNAPSHOT_OUT").expect("SKY_SNAPSHOT_OUT");
    let kernel = kernel_functions_from_source(&std::fs::read_to_string(kernel_rs).unwrap());
    assert!(!kernel.is_empty(), "no KERNEL_FUNCTIONS parsed");
    let rows = export_rows(Path::new(&stdlib), &kernel);
    let mut text = format!(
        "# Stdlib exports of Sky {tag}: <kind>\\t<module>\\t<name>.\n\
         # Generated by rust/crates/hir/tests/regen-stdlib-exports-snapshot.sh. Do not edit.\n"
    );
    for r in rows {
        text.push_str(&format!("{}\t{}\t{}\n", r.kind, r.module, r.name));
    }
    std::fs::write(out, text).unwrap();
}

#[test]
fn kernel_table_parser_reads_the_current_table() {
    // The generator parses kernel.rs as text; prove it reads the live table the
    // same way the compiler does.
    let src = std::fs::read_to_string(repo_root().join("rust/crates/hir/src/kernel.rs")).unwrap();
    assert_eq!(
        kernel_functions_from_source(&src),
        current_kernel_functions()
    );
}

fn resolve_main(modules: &[(&str, &str)]) -> hir::ResolveResult {
    let mut db = SourceDb::new();
    for (i, (m, src)) in modules.iter().enumerate() {
        db.add_module(m, syntax::parse(src, FileId(i as u32)));
    }
    hir::resolve(&db, db.module_by_name("Main").unwrap())
}

fn e1012(r: &hir::ResolveResult) -> Vec<String> {
    r.diagnostics
        .iter()
        .filter(|d| d.code.0 == "E1012")
        .map(|d| d.message.clone())
        .collect()
}

#[test]
fn e1012_names_the_export_that_is_new_since_the_previous_release() {
    // The reported break: both modules existed in v0.26.1, only
    // `Std.Html.Attributes` exported `value` there.
    let attrs = "module Std.Html.Attributes exposing (..)\nvalue x =\n    x\n";
    let dec = "module Sky.Core.Json.Decode exposing (..)\nvalue =\n    1\n";
    let main = "module Main exposing (main)\n\
                import Std.Html.Attributes exposing (..)\n\
                import Sky.Core.Json.Decode exposing (..)\n\n\
                main =\n    value\n";
    let r = resolve_main(&[
        ("Std.Html.Attributes", attrs),
        ("Sky.Core.Json.Decode", dec),
        ("Main", main),
    ]);
    let msgs = e1012(&r);
    assert_eq!(msgs.len(), 1, "{:?}", r.diagnostics);
    assert!(
        msgs[0].contains("`Sky.Core.Json.Decode.value` is new since Sky v0.26.1"),
        "{}",
        msgs[0]
    );
    assert!(
        !msgs[0].contains("`Std.Html.Attributes.value` is new"),
        "an export the previous release had is not new: {}",
        msgs[0]
    );
    // The two one-line fixes that keep the old meaning, and the migration guide.
    assert!(
        msgs[0].contains("`import Std.Html.Attributes exposing (value)`"),
        "{}",
        msgs[0]
    );
    assert!(
        msgs[0].contains(".value`, or import it by name"),
        "{}",
        msgs[0]
    );
    assert!(
        msgs[0].ends_with("See docs/migration/v0.27.md#new-stdlib-names"),
        "{}",
        msgs[0]
    );
    // The general fixes are still offered.
    assert!(msgs[0].contains("Qualify the reference"), "{}", msgs[0]);
    assert!(msgs[0].contains("narrow one import"), "{}", msgs[0]);
}

#[test]
fn e1012_between_two_old_exports_does_not_claim_a_new_name() {
    // Twin: both `raw` exports existed in v0.26.1 (`Std.Html`, `Std.Css`), so the
    // ambiguity is not caused by the upgrade and the message must not say so.
    let html = "module Std.Html exposing (..)\nraw x =\n    x\n";
    let css = "module Std.Css exposing (..)\nraw x =\n    x\n";
    let main = "module Main exposing (main)\n\
                import Std.Html exposing (..)\n\
                import Std.Css exposing (..)\n\n\
                main =\n    raw 1\n";
    let r = resolve_main(&[("Std.Html", html), ("Std.Css", css), ("Main", main)]);
    let msgs = e1012(&r);
    assert_eq!(msgs.len(), 1, "{:?}", r.diagnostics);
    assert!(!msgs[0].contains("new since"), "{}", msgs[0]);
    assert!(!msgs[0].contains("docs/migration"), "{}", msgs[0]);
}
