{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE OverloadedStrings #-}
-- | Sky.Doc.KernelRegistry — enumerate the kernel-side stdlib
-- symbols that aren't surfaced via the on-disk module sources
-- (sky-stdlib/) yet.
--
-- The Sky compiler's kernel registry lives at
-- `Sky.Type.Constrain.Expression.lookupKernelType` — a 317-arm
-- pattern match keyed by `(moduleName, funcName)`. Sky.Core.List
-- / Maybe / Result migrated to Sky source as part of v0.13 Layer
-- 3, but Sky.Core.String / Crypto / Encoding / Time / Json.*
-- / Http / File / Io / Random / Path / Char / System / Process
-- / Log / Db / Auth / Server / Task / Cmd / Sub / Uuid etc. all
-- still live as kernel-only entries. The LSP index doesn't see
-- them (they have no .sky file), so `sky doc` couldn't surface
-- their type signatures — which is what most users actually want
-- to search for.
--
-- This module fixes that by scraping the registry source file at
-- TH compile time. We regex-match every `("Module", "func") ->`
-- header line, emit a `[(String, String)]` list, and at runtime
-- look up each entry's actual type via `lookupKernelType`. The
-- list is intentionally lossless — every kernel entry appears.
module Sky.Doc.KernelRegistry
    ( kernelSymbols
    , kernelSigString
    , kernelDocFor
    ) where

import qualified Data.List as List
import           Data.Maybe (fromMaybe)
import qualified Sky.Type.Constrain.Expression as KE
import qualified Sky.Type.Type as T

import qualified Sky.Build.KernelRegistryEntries as Entries


-- | All kernel symbols, in (module, name) order.  Generated by
-- scraping `Sky.Type.Constrain.Expression.lookupKernelType` at
-- TH compile time — see `Sky.Build.KernelRegistryEntries`.
kernelSymbols :: [(String, String)]
kernelSymbols = Entries.kernelEntries


-- | Lookup the kernel type for `Module.func` and pretty-print it
-- as a signature string of the shape "func : Type -> Type".
-- Returns Nothing if `lookupKernelType` returned Nothing (a
-- documented-but-never-defined entry — shouldn't happen but the
-- function is total).
kernelSigString :: String -> String -> Maybe String
kernelSigString modName funcName =
    case KE.lookupKernelType modName funcName of
        Nothing -> Nothing
        Just (T.Forall _ ty) ->
            Just (funcName ++ " : " ++ renderType ty)


-- | Generic doc string for a kernel function. The kernel
-- registry doesn't carry per-function docstrings (it's a type
-- table); we surface a uniform marker so users know the symbol
-- is a kernel binding rather than a Sky-source definition.
kernelDocFor :: String -> String -> String
kernelDocFor modName funcName =
    "Kernel binding (defined in the compiler runtime — see "
    ++ "`Sky.Type.Constrain.Expression.lookupKernelType` " ++ modName
    ++ "/" ++ funcName ++ ")."


-- ─── Type pretty-printer ─────────────────────────────────────────

-- | Render a Sky internal type as a stdlib-shaped signature
-- string ("Currency -> Int -> Money"). Strips internal TVar
-- prefixes (_lit / _empty / _ambig) and renders parametric type
-- applications with spaces, not constructor-syntax parens.
--
-- Intentionally simple — the compiler's full printer
-- (Sky.Reporting.Render) is overkill for the doc-tool target.
renderType :: T.Type -> String
renderType = go False
  where
    -- `inFn` controls whether arrows on the right side of a
    -- TLambda need parens (they do, but not for the LEFT side
    -- of a top-level arrow — `a -> b -> c` is right-assoc).
    go inFn ty = case ty of
        T.TVar n -> sanitise n
        T.TUnit -> "()"
        T.TLambda l r ->
            let body = go False l ++ " -> " ++ go True r
            in if inFn then "(" ++ body ++ ")" else body
        T.TTuple a b cs ->
            "(" ++ List.intercalate ", " (map (go False) (a:b:cs)) ++ ")"
        T.TRecord _ _ -> "{ ... }"  -- doc-tool simplification
        T.TType _ name args ->
            case args of
                [] -> name
                _  -> name ++ " " ++ List.intercalate " "
                                        (map (parenIfNested . go False) args)
        T.TAlias _ name _ _ -> name
    parenIfNested s
        | ' ' `elem` s = "(" ++ s ++ ")"
        | otherwise = s
    -- TVars in the kernel registry use canonical names ("a", "b",
    -- "msg", "model", etc.). Internal sentinels ("_lit", "_empty",
    -- "_ambig") leak through as bare names — strip the underscore
    -- prefix for presentational clarity.
    sanitise n = fromMaybe n (List.stripPrefix "_" n)
