//! `corpus/manifest.toml` — the ONLY membership authority (v2 §3.1).
//!
//! No gate calls `read_dir` on the corpus. The discovery-by-listing model has
//! already produced two live defects in this repository: `39-hub-demo` was
//! invisible to all six gates, and the two reject faces diverged on discovery
//! (`ty/tests/reject.rs` recursive vs `xtask/src/reject_gate.rs` flat) so a file
//! in a subdirectory would be seen by one and not the other.
//!
//! # Why the manifest is checked in but the case SOURCES are not
//!
//! The generator is deterministic, so the sources are a pure function of the
//! generator plus the axis space — checking in thousands of `.sky` files would
//! add review noise without adding information. What must be reviewable is
//! **membership and classification**: which cases exist, which axes each one
//! varies, whether it carries an independently-derivable expected value
//! (`class = V`) or is only a change-detector (`class = D`), and whether it is
//! forbidden from batching. That is what the manifest records, and a gate
//! (`--check-manifest`) fails when the generator and the manifest disagree — so
//! a generator edit that silently adds, drops, or reclassifies a case is a
//! failing build rather than a quiet change in what "100 % covered" means.
//!
//! **Pinned historical repros are the exception**: they are checked-in `.sky`
//! files under `corpus/repro/`, never generator output, so a generator edit
//! cannot silently renumber or reword them.

use super::gen::{Class, Expect, Isolation};
use std::fmt::Write as _;
use std::path::Path;

/// `N_iso`'s declared ceiling (v2 §3.3).
///
/// > `N_iso` is the term that can break the budget, and it is therefore capped by
/// > the manifest: a gate fails if `N_iso` exceeds its declared ceiling. Growing
/// > a forbidden family is a *budget decision*, made visibly, not a side effect
/// > of adding cases.
///
/// Phase 3 measured `c_u` = 0.70 s/unit warm on this host, which makes
/// `N_iso · c_u` the entire cost model — the static term is 1.02 ms/case and has
/// stopped binding. Raising this number is a deliberate act that costs
/// `Δ · 0.70 s` of every run, and it must be justified in the commit that raises
/// it.
/// History of this number, because v2 §3.3 makes raising it a decision that must
/// be justified where it is made:
///
/// * `40` — the initial four isolated strata (`fieldset_collision` 4×5,
///   `import_shape` 5×4).
/// * `44` — **raised deliberately** to admit the `fieldset_ctor` stratum
///   (2 `construction` × 2 `collider`). It costs `4 × 0.70 s ≈ 2.8 s` per run and
///   it bought a **live runtime-panic defect** the corpus had otherwise missed
///   (see `gen::blocked_reason`). That is the trade this cap exists to make
///   visible, and it is the right side of it.
pub const N_ISO_CEILING: usize = 44;

pub fn render() -> String {
    let cases = super::all_cases();
    let mut s = String::new();

    s.push_str(
        "# Layer 1 corpus — the membership authority (CI/test-architecture v2 §3.1).\n\
         #\n\
         # GENERATED by `xtask corpus --emit-manifest`. Checked in so that\n\
         # membership and classification are reviewable in git; verified by\n\
         # `xtask corpus --check-manifest`, which fails when the generator and\n\
         # this file disagree.\n\
         #\n\
         # class = V  the generator CONSTRUCTED the expected value, so the case can\n\
         #            establish correctness (v2 §4.4). Counted in coverage.\n\
         # class = D  change-detector only. **Excluded from the coverage number**\n\
         #            (v2 §5.5) — counting these would inflate the figure with\n\
         #            cases that cannot establish correctness.\n\
         #\n\
         # isolation = unit  forbidden from batching (v2 §3.2): the case's verdict\n\
         #            would otherwise depend on its neighbours, because\n\
         #            `record_fieldsets` is built over the whole compilation\n\
         #            (lower/src/lower.rs:246-266).\n\n",
    );

    let n_iso = cases
        .iter()
        .filter(|c| c.isolation == Isolation::Unit)
        .count();
    let n_v = cases.iter().filter(|c| c.class == Class::V).count();

    let _ = writeln!(s, "[corpus]");
    let _ = writeln!(s, "n_min = {}", cases.len());
    let _ = writeln!(s, "n_iso = {n_iso}");
    let _ = writeln!(s, "n_iso_ceiling = {N_ISO_CEILING}");
    let _ = writeln!(s, "class_v = {n_v}");
    let _ = writeln!(s, "class_d = {}", cases.len() - n_v);
    s.push('\n');

    for c in &cases {
        let _ = writeln!(s, "[[case]]");
        let _ = writeln!(s, "id         = \"{}\"", c.id);
        let _ = writeln!(s, "family     = \"{}\"", c.family.label());
        let _ = writeln!(s, "stratum    = \"{}\"", c.stratum);
        let _ = writeln!(s, "mode       = \"{}\"", c.mode.label());
        let _ = writeln!(s, "isolation  = \"{}\"", c.isolation.label());
        let _ = writeln!(s, "class      = \"{}\"", c.class.label());
        let _ = writeln!(s, "witness    = \"{}\"", c.witness.label());
        let axes: Vec<String> = c
            .axes
            .0
            .iter()
            .map(|(k, v)| format!("{k} = \"{v}\""))
            .collect();
        let _ = writeln!(s, "axes       = {{ {} }}", axes.join(", "));
        if let Some(co) = &c.coordinate {
            let _ = writeln!(s, "coordinate = \"{co}\"");
        }
        match &c.expect {
            Expect::Accept { stdout } => {
                let _ = writeln!(s, "expect     = \"accept\"");
                let _ = writeln!(s, "stdout     = \"{stdout}\"");
            }
            Expect::Reject { code } => {
                let _ = writeln!(s, "expect     = \"reject\"");
                let _ = writeln!(s, "code       = \"{code}\"");
            }
        }
        s.push('\n');
    }

    s
}

fn path(root: &Path) -> std::path::PathBuf {
    root.join("corpus/manifest.toml")
}

pub fn emit(root: &Path) -> i32 {
    let p = path(root);
    if let Some(parent) = p.parent() {
        if let Err(e) = std::fs::create_dir_all(parent) {
            eprintln!("corpus: mkdir {}: {e}", parent.display());
            return 1;
        }
    }
    let body = render();
    if let Err(e) = std::fs::write(&p, &body) {
        eprintln!("corpus: write {}: {e}", p.display());
        return 1;
    }
    let cases = super::all_cases();
    println!("wrote {} ({} cases)", p.display(), cases.len());
    0
}

/// Fail when the generator and the checked-in manifest disagree.
pub fn check(root: &Path) -> i32 {
    let p = path(root);
    let Ok(on_disk) = std::fs::read_to_string(&p) else {
        eprintln!(
            "corpus: no manifest at {} — run `xtask corpus --emit-manifest`. \
             A corpus with no membership authority has not been reviewed.",
            p.display()
        );
        return 1;
    };
    let expected = render();
    if on_disk == expected {
        let n = super::all_cases().len();
        println!("CORPUS MANIFEST: PASS ({n} cases, generator and manifest agree)");
        return 0;
    }

    // Report WHICH ids moved, not just "files differ" — a diff of 4,000 lines is
    // not an actionable message.
    let ids = |s: &str| -> Vec<String> {
        s.lines()
            .filter_map(|l| l.strip_prefix("id         = \""))
            .map(|l| l.trim_end_matches('"').to_string())
            .collect()
    };
    let a: std::collections::BTreeSet<String> = ids(&on_disk).into_iter().collect();
    let b: std::collections::BTreeSet<String> = ids(&expected).into_iter().collect();

    println!("CORPUS MANIFEST: FAIL — the generator and corpus/manifest.toml disagree.");
    let added: Vec<&String> = b.difference(&a).collect();
    let removed: Vec<&String> = a.difference(&b).collect();
    if !added.is_empty() {
        println!("  {} case(s) the generator produces that the manifest lacks:", added.len());
        for id in added.iter().take(20) {
            println!("    + {id}");
        }
    }
    if !removed.is_empty() {
        println!("  {} case(s) the manifest declares that the generator no longer produces:", removed.len());
        for id in removed.iter().take(20) {
            println!("    - {id}");
        }
    }
    if added.is_empty() && removed.is_empty() {
        println!("  membership is identical; a case's CLASSIFICATION or expected value changed.");
    }
    println!("  Re-run `xtask corpus --emit-manifest` and review the diff before committing.");
    1
}

#[cfg(test)]
mod tests {
    use super::*;

    /// `N_iso` must stay under its declared ceiling. Growing a
    /// forbidden-from-batching family is a budget decision (v2 §3.3), and this is
    /// where it becomes visible instead of silently costing `Δ · c_u` per run.
    #[test]
    fn n_iso_is_under_its_declared_ceiling() {
        let n_iso = super::super::all_cases()
            .iter()
            .filter(|c| c.isolation == Isolation::Unit)
            .count();
        assert!(
            n_iso <= N_ISO_CEILING,
            "N_iso = {n_iso} exceeds the declared ceiling {N_ISO_CEILING}. \
             At the measured c_u = 0.70 s/unit this run just got {:.1}s slower. \
             Raise the ceiling deliberately, in a commit that says why.",
            (n_iso - N_ISO_CEILING) as f64 * 0.70,
        );
    }

    /// The manifest render is deterministic — otherwise `--check-manifest` would
    /// fail spuriously and be disabled, which is how a membership authority stops
    /// being one.
    #[test]
    fn render_is_deterministic() {
        assert_eq!(render(), render());
    }
}
