//! Static kernel + builtin tables, ported verbatim from
//! `Sky.Canonicalise.Environment` (doc 05 §9, §10). These change rarely; a diff
//! against the Haskell lists is the compat check. Data only, no logic.

/// Is `path` inside a **reserved Sky namespace** — `Std.*` or `Sky.*`?
///
/// A real Go-FFI package is an import path (`github.com/…` → `Github.Com.…`) or
/// a Go std package (`fmt`, `strings`); the FFI generator derives the Sky
/// qualifier from the Go module path, so it can never mint one under `Std.` or
/// `Sky.`. A path in those namespaces that resolves to neither a parsed Sky
/// module nor a kernel pseudo-module is therefore an **unknown / misspelled Sky
/// module** — never a package `sky install` could fetch.
///
/// This is the ONE definition of that predicate. It had a private copy at the
/// Go-FFI *call* site (`lower.rs`, the "unknown Sky module" message) and no copy
/// at all at the other three sites that reach the same `ImportSource::Foreign`
/// fallback — a value reference, a type reference, and an unused import — which
/// is why `import Std.NoSuchModule as Nope` + `Nope.answer` type-checked, built,
/// and panicked at runtime with `rt.AsInt: expected numeric value, got <nil>`.
/// Both call sites now read this function; a second copy is how the two would
/// drift apart again.
pub fn is_reserved_sky_namespace(path: &str) -> bool {
    path.starts_with("Std.") || path.starts_with("Sky.") || path == "Std" || path == "Sky"
}

/// `staticKernelModules` (Environment.hs:348-503): Sky import path (and bare
/// alias) → kernel pseudo-module. Drives the `Res::Kernel` qualifier fallback
/// (doc 05 §9) so `Crypto.sha256` resolves with no `import`.
pub const KERNEL_MODULES: &[(&str, &str)] = &[
    ("Sky.Core.Basics", "Basics"),
    ("Sky.Core.String", "String"),
    ("Sky.Core.List", "List"),
    ("Sky.Core.Dict", "Dict"),
    ("Sky.Core.Set", "Set"),
    ("Sky.Core.Maybe", "Maybe"),
    ("Sky.Core.Result", "Result"),
    ("Sky.Core.Task", "Task"),
    ("Sky.Core.Math", "Math"),
    ("Sky.Core.Regex", "Regex"),
    ("Sky.Core.Crypto", "Crypto"),
    ("Sky.Core.Encoding", "Encoding"),
    ("Sky.Core.Char", "Char"),
    ("Sky.Core.Path", "Path"),
    ("Std.Log", "Log"),
    ("Std.Cmd", "Cmd"),
    ("Std.Sub", "Sub"),
    ("Std.Db", "Db"),
    ("Std.Auth", "Auth"),
    ("Sky.Core.Io", "Io"),
    ("Io", "Io"),
    ("Sky.Core.File", "File"),
    ("Sky.Core.Process", "Process"),
    ("Sky.Core.Time", "Time"),
    ("Std.Time", "Time"),
    ("Sky.Core.Random", "Random"),
    ("Sky.Core.Http", "Http"),
    ("Sky.Http.Server", "Server"),
    ("Std.Live", "Live"),
    ("Std.Jobs", "Jobs"),
    ("Sky.Cli", "Cli"),
    ("Std.Cli", "Cli"),
    ("Sky.Tui", "Tui"),
    ("Std.Tui", "Tui"),
    ("Sky.Webview", "Webview"),
    ("Std.Webview", "Webview"),
    ("Sky.Core.Json.Encode", "JsonEnc"),
    ("Sky.Core.Json.Decode", "JsonDec"),
    ("Sky.Core.Json.Decode.Pipeline", "JsonDecP"),
    ("Sky.Core.Uuid", "Uuid"),
    ("Sky.Core.System", "System"),
    ("Std.System", "System"),
    ("System", "System"),
    ("Context", "Context"),
    ("Fmt", "Fmt"),
    ("Time", "Time"),
    ("Crypto", "Crypto"),
    ("Encoding", "Encoding"),
    ("Sky.Http.RateLimit", "RateLimit"),
    ("Sky.Http.Middleware", "Middleware"),
    ("Sky.Ffi", "Ffi"),
    ("Sky.Core.Prelude", "Basics"),
    // ---- bare-name aliases ----
    ("Log", "Log"),
    ("Cmd", "Cmd"),
    ("Sub", "Sub"),
    ("Db", "Db"),
    ("Auth", "Auth"),
    ("File", "File"),
    ("Process", "Process"),
    ("Random", "Random"),
    ("Http", "Http"),
    ("Server", "Server"),
    ("Live", "Live"),
    ("Jobs", "Jobs"),
    ("Cli", "Cli"),
    ("Tui", "Tui"),
    ("Webview", "Webview"),
    ("JsonEnc", "JsonEnc"),
    ("JsonDec", "JsonDec"),
    ("JsonDecP", "JsonDecP"),
    ("Uuid", "Uuid"),
    ("RateLimit", "RateLimit"),
    ("Middleware", "Middleware"),
    ("Ffi", "Ffi"),
    ("Basics", "Basics"),
    ("String", "String"),
    ("List", "List"),
    ("Dict", "Dict"),
    ("Set", "Set"),
    ("Maybe", "Maybe"),
    ("Result", "Result"),
    ("Task", "Task"),
    ("Math", "Math"),
    ("Regex", "Regex"),
    ("Char", "Char"),
    ("Path", "Path"),
];

/// `builtinVars` (Environment.hs:212): unconditional Prelude values, each a
/// `Res::Kernel`. `(name, kernel-module, kernel-func)`.
pub const BUILTIN_VARS: &[(&str, &str, &str)] = &[
    ("identity", "Basics", "identity"),
    ("always", "Basics", "always"),
    ("not", "Basics", "not"),
    ("toString", "Basics", "toString"),
    ("modBy", "Basics", "modBy"),
    ("clamp", "Basics", "clamp"),
    ("fst", "Basics", "fst"),
    ("snd", "Basics", "snd"),
    ("errorToString", "Basics", "errorToString"),
    ("println", "Log", "println"),
    ("js", "Basics", "js"),
];

/// `builtinTypes` (Environment.hs:229): `(name, arity)`. `Error` is auto-imported
/// from `Sky.Core.Error` (C19) so `Result Error a` needs no explicit import.
pub const BUILTIN_TYPES: &[(&str, u16)] = &[
    ("Int", 0),
    ("Float", 0),
    ("Bool", 0),
    ("String", 0),
    ("Char", 0),
    ("List", 1),
    ("Maybe", 1),
    ("Result", 2),
    ("Task", 2),
    ("Error", 0),
];

/// `builtinCtors` (Environment.hs:249): `(ctor, type, index, arity)`.
pub const BUILTIN_CTORS: &[(&str, &str, u16, u16)] = &[
    ("True", "Bool", 0, 0),
    ("False", "Bool", 1, 0),
    ("Just", "Maybe", 0, 1),
    ("Nothing", "Maybe", 1, 0),
    ("Ok", "Result", 0, 1),
    ("Err", "Result", 1, 1),
];

/// `preludeQualifiers` (Environment.hs:114): auto-available `Qual.fn` kernel
/// functions with no explicit `import` (doc 05 §10). `(qualifier, [funcs])`.
pub const PRELUDE_QUALIFIERS: &[(&str, &[&str])] = &[
    (
        "String",
        &[
            "length",
            "reverse",
            "append",
            "split",
            "join",
            "contains",
            "startsWith",
            "endsWith",
            "toInt",
            "fromInt",
            "toFloat",
            "fromFloat",
            "toUpper",
            "toLower",
            "trim",
            "replace",
            "slice",
            "isEmpty",
            "toBytes",
            "fromBytes",
            "fromChar",
            "toChar",
            "left",
            "right",
            "padLeft",
            "padRight",
            "repeat",
            "lines",
            "words",
            "htmlEscape",
            "truncate",
            "ellipsize",
        ],
    ),
    (
        "List",
        &[
            "map",
            "filter",
            "foldl",
            "foldr",
            "length",
            "head",
            "tail",
            "take",
            "drop",
            "append",
            "concat",
            "concatMap",
            "reverse",
            "sort",
            "member",
            "any",
            "all",
            "range",
            "zip",
            "filterMap",
            "isEmpty",
            "cons",
        ],
    ),
    (
        "Dict",
        &[
            "empty", "insert", "get", "remove", "member", "keys", "values", "toList", "fromList",
            "map", "foldl", "union",
        ],
    ),
    (
        "Set",
        &[
            "empty",
            "insert",
            "remove",
            "member",
            "union",
            "diff",
            "intersect",
            "fromList",
        ],
    ),
    ("Maybe", &["withDefault", "map", "andThen"]),
    (
        "Result",
        &[
            "withDefault",
            "map",
            "andThen",
            "mapError",
            "map2",
            "map3",
            "map4",
            "map5",
            "andMap",
            "combine",
            "traverse",
            "andThenTask",
        ],
    ),
    (
        "Basics",
        &[
            "identity", "always", "not", "toString", "modBy", "clamp", "fst", "snd", "compare",
            "negate", "abs", "sqrt", "min", "max",
        ],
    ),
    ("Cmd", &["none", "batch", "perform"]),
    ("Sub", &["none", "every", "batch"]),
    (
        "Task",
        &[
            "succeed",
            "fail",
            "map",
            "andThen",
            "perform",
            "sequence",
            "parallel",
            "parallelN",
            "lazy",
            "run",
            "map2",
            "map3",
            "map4",
            "map5",
            "andMap",
            "fromResult",
            "andThenResult",
            "mapError",
            "onError",
        ],
    ),
];

/// `staticKernelFunctions` (Module.hs:1752-1861): the known function names each
/// kernel pseudo-module exposes. This is the source of truth for a kernel
/// `import M exposing (..)` — it binds exactly these names (like the oracle's
/// `kernelVarsFor`/`addExposed`, Module.hs:700-703), so an unknown bare name is
/// NOT lenient-resolved to a bogus `rt.<Mod>_<name>` kernel ref but falls
/// through to `Res::Error` + `[E1001] Undefined name` (doc 05 §9, C-`sky check ≡
/// sky build`). Ported verbatim; a diff against the Haskell list is the compat
/// check. In batch bring-up the FFI kernel-function channel is empty, matching
/// the LSP single-module path (`Map.empty` → static-only, Module.hs:820-827).
pub const KERNEL_FUNCTIONS: &[(&str, &[&str])] = &[
    (
        "Basics",
        &[
            "identity", "always", "not", "toString", "modBy", "clamp", "fst", "snd", "compare",
            "negate", "abs", "sqrt", "min", "max", "errorToString", "js",
        ],
    ),
    (
        "String",
        &[
            "length",
            "reverse",
            "append",
            "concat",
            "split",
            "join",
            "contains",
            "startsWith",
            "endsWith",
            "toInt",
            "fromInt",
            "toFloat",
            "fromFloat",
            "toUpper",
            "toLower",
            "trim",
            "replace",
            "slice",
            "isEmpty",
            "toBytes",
            "fromBytes",
            "fromChar",
            "toChar",
            "fromList",
            "toList",
            "left",
            "right",
            "dropLeft",
            "dropRight",
            "padLeft",
            "padRight",
            "repeat",
            "lines",
            "words",
            "isValid",
            "normalize",
            "normalizeNFD",
            "casefold",
            "equalFold",
            "graphemes",
            "trimStart",
            "trimEnd",
            "isEmail",
            "isUrl",
            "slugify",
            "htmlEscape",
            "truncate",
            "ellipsize",
        ],
    ),
    (
        "List",
        &[
            "map",
            "filter",
            "foldl",
            "foldr",
            "length",
            "head",
            "tail",
            "cons",
            "take",
            "drop",
            "append",
            "concat",
            "concatMap",
            "reverse",
            "sort",
            "sortBy",
            "sortWith",
            "member",
            "any",
            "all",
            "range",
            "zip",
            "filterMap",
            "isEmpty",
            "indexedMap",
            "find",
        ],
    ),
    (
        "Dict",
        &[
            "empty", "insert", "get", "remove", "member", "keys", "values", "toList", "fromList",
            "map", "foldl", "union", "isEmpty", "size",
        ],
    ),
    (
        "Set",
        &[
            "empty",
            "fromList",
            "insert",
            "remove",
            "member",
            "toList",
            "size",
            "union",
            "intersect",
            "diff",
        ],
    ),
    (
        "Maybe",
        &[
            "withDefault",
            "map",
            "andThen",
            "map2",
            "map3",
            "map4",
            "map5",
            "andMap",
            "combine",
            "traverse",
        ],
    ),
    (
        "Result",
        &[
            "withDefault",
            "map",
            "andThen",
            "mapError",
            "map2",
            "map3",
            "map4",
            "map5",
            "andMap",
            "combine",
            "traverse",
            "andThenTask",
        ],
    ),
    (
        "Task",
        &[
            "succeed",
            "fail",
            "map",
            "andThen",
            "perform",
            "sequence",
            "parallel",
            "parallelN",
            "lazy",
            "run",
            "map2",
            "map3",
            "map4",
            "map5",
            "andMap",
            "fromResult",
            "andThenResult",
            "mapError",
            "onError",
            "retryWith",
        ],
    ),
    (
        "Log",
        &[
            "println",
            "debug",
            "info",
            "warn",
            "error",
            "debugWith",
            "infoWith",
            "warnWith",
            "errorWith",
            "with",
        ],
    ),
    ("Cmd", &["none", "batch", "perform", "publish", "publishNoEcho"]),
    (
        "Time",
        &[
            "now",
            "sleep",
            "every",
            "unixMillis",
            "timeString",
            "formatISO8601",
            "formatRFC3339",
            "formatHTTP",
            "format",
            "parseISO8601",
            "parse",
            "addMillis",
            "diffMillis",
        ],
    ),
    (
        "Random",
        &[
            "int",
            "float",
            "choice",
            "choiceMaybe",
            "shuffle",
            "weighted",
            "seededInt",
            "seededFloat",
            "seededChoice",
        ],
    ),
    (
        "Math",
        &[
            "sqrt", "pow", "abs", "floor", "ceil", "round", "sin", "cos", "tan", "pi", "e", "log",
            "min", "max", "acos", "acosh", "asin", "asinh", "atan", "atan2", "atanh", "cbrt",
            "cosh", "exp", "exp2", "hypot", "inf", "isNaN", "log10", "log2", "mod", "nan", "phi",
            "remainder", "sinh", "sqrt2", "tanh", "trunc",
        ],
    ),
    (
        "Io",
        &[
            "readLine",
            "writeStdout",
            "writeStderr",
            "writeString",
        ],
    ),
    (
        "File",
        &[
            "readFile",
            "readFileLimit",
            "readFileBytes",
            "writeFile",
            "append",
            "mkdirAll",
            "readDir",
            "exists",
            "remove",
            "isDir",
            "tempFile",
            "tempDir",
            "copy",
            "rename",
        ],
    ),
    ("Process", &["run"]),
    ("Http", &["get", "post", "request", "parseQuery"]),
    (
        "Server",
        &[
            "listen",
            "get",
            "post",
            "put",
            "delete",
            "api",
            "static",
            "text",
            "json",
            "html",
            "withStatus",
            "redirect",
            "param",
            "queryParam",
            "header",
            "getCookie",
            "cookie",
            "withCookie",
            "withHeader",
            "any",
            "method",
            "formValue",
            "body",
            "path",
            "group",
            "use",
            "csrfIssue",
            "csrfVerify",
        ],
    ),
    (
        "Crypto",
        &[
            "sha256",
            "sha512",
            "sha1",
            "md5",
            "hmacSha256",
            "hmacSha512",
            "constantTimeEqual",
            "randomBytes",
            "randomToken",
            "aesGcmEncrypt",
            "aesGcmDecrypt",
            "aesKeyFromPassword",
            "chacha20Encrypt",
            "chacha20Decrypt",
            "chachaKeyFromPassword",
            "rsaSha256Sign",
            "rsaSha256Verify",
        ],
    ),
    (
        "Encoding",
        &[
            "base64Encode",
            "base64Decode",
            "urlEncode",
            "urlDecode",
            "hexEncode",
            "hexDecode",
        ],
    ),
    ("Regex", &["match", "find", "findAll", "replace", "split"]),
    (
        "Char",
        &[
            "isUpper", "isLower", "isDigit", "isAlpha", "toUpper", "toLower", "fromCode", "toCode",
        ],
    ),
    (
        "Path",
        &["join", "dir", "base", "ext", "isAbsolute", "safeJoin"],
    ),
    ("Uuid", &["v4", "v7", "parse"]),
    ("RateLimit", &["allow"]),
    (
        "Middleware",
        &[
            "withCors",
            "withLogging",
            "withBasicAuth",
            "withRateLimit",
            "rateLimit",
            "withCsrf",
        ],
    ),
    (
        "Ffi",
        &[
            "call", "callPure", "callTask", "has", "isPure", "toAny", "kernel",
        ],
    ),
    // Std.Live migrated to Layer-3 Sky source (sky-stdlib/Std/Live.sky) —
    // app/config/route/api/lifecycle/withX resolve Res::Def via qual_vars, so no
    // KERNEL_FUNCTIONS registry entry is needed (v0.19 kernel-metadata unification).
    // Std.Jobs migrated to Layer-3 Sky source (sky-stdlib/Std/Jobs.sky) —
    // resolves Res::Def via qual_vars, so it no longer needs a KERNEL_FUNCTIONS
    // registry entry (v0.19 kernel-metadata unification).
    (
        "Sub",
        &[
            "none",
            "every",
            "batch",
            "subscribeTopic",
            "subscribeStream",
            "subscribeWebSocket",
        ],
    ),
    (
        "JsonEnc",
        &[
            "string", "int", "float", "bool", "null", "list", "object", "encode",
        ],
    ),
    (
        "JsonDec",
        &[
            "decodeString",
            "string",
            "int",
            "float",
            "bool",
            "field",
            "index",
            "list",
            "map",
            "andThen",
            "succeed",
            "fail",
            "oneOf",
            "at",
            "map2",
            "map3",
            "map4",
            "map5",
        ],
    ),
    (
        "System",
        &[
            "args",
            "getArg",
            "getenv",
            "getenvOr",
            "getenvInt",
            "getenvBool",
            "cwd",
            "getcwd",
            "exit",
            "loadEnv",
            "setenv",
            "unsetenv",
        ],
    ),
    (
        "Context",
        &["background", "todo", "withValue", "withCancel"],
    ),
    ("Fmt", &["sprint", "sprintf", "sprintln", "errorf"]),
    (
        "Db",
        &[
            "connect",
            "open",
            "close",
            "exec",
            "execRaw",
            "query",
            "queryDecode",
            "insertRow",
            "insertFields",
            "insertFieldsReturning",
            "updateFields",
            "getById",
            "getByIdDecode",
            "updateById",
            "deleteById",
            "findWhere",
            "unsafeFindWhere",
            "findByConditions",
            "findOneByField",
            "findManyByField",
            "migrateApply",
            "withTransaction",
            "getField",
            "getFieldOr",
            "getString",
            "getInt",
            "getFloat",
            "getBool",
        ],
    ),
    (
        "Auth",
        &[
            "hashPassword",
            "verifyPassword",
            "signToken",
            "verifyToken",
            "signSlidingToken",
            "setSlidingCookie",
            "register",
            "login",
            "setRole",
            "disableUser",
            "enableUser",
            "isDisabled",
            "revokeUser",
            "isRevoked",
            "hashPasswordCost",
            "passwordStrength",
        ],
    ),
    (
        "JsonDecP",
        &["required", "optional", "custom", "requiredAt"],
    ),
];

/// Look up the known function names a kernel pseudo-module exposes. `None` means
/// we have no static enumeration for that pseudo — the caller keeps the lenient
/// `kernel_open` fallback for it (defensive; no such pseudo is imported
/// `exposing (..)` in the corpus).
pub fn kernel_functions(pseudo: &str) -> Option<&'static [&'static str]> {
    KERNEL_FUNCTIONS
        .iter()
        .find(|(m, _)| *m == pseudo)
        .map(|(_, fns)| *fns)
}

/// Kernel-implicit Prelude types (Module.hs:520): globally-available
/// runtime types with no `type alias` in any `.sky` source. Accepted as a no-op
/// in `exposing (…)` and resolvable unqualified (C12).
pub const KERNEL_IMPLICIT_TYPES: &[&str] = &[
    "Decoder",
    "Value",
    "Attribute",
    "Handler",
    "Middleware",
    "Session",
    "Store",
    "Route",
    "VNode",
    "Request",
    "Response",
    "Cmd",
    "Sub",
    "Db",
    "Error",
];

/// Prelude-protected names (Module.hs:872): a user union whose type or ctor name
/// collides with one of these is a hard error (C14), except at the name's own
/// canonical home.
pub const PRELUDE_PROTECTED: &[&str] = &[
    "Int", "Float", "Bool", "String", "Char", "List", "Maybe", "Result", "Task", "Error", "True",
    "False", "Just", "Nothing", "Ok", "Err",
];
