package sky_wrappers

import (
	_ffi_fmt "fmt"
	_ffi_reflect "reflect"
	v2 "fyne.io/fyne/v2"
)

var _ = _ffi_fmt.Sprintf
// Auto-generated by Sky compiler

func Sky_fyne_io_fyne_v2_CurrentApp(_ any) any {
	
	return func() any {
		defer func() { recover() }()
		result := v2.CurrentApp()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_CurrentDevice(_ any) any {
	
	return func() any {
		defer func() { recover() }()
		result := v2.CurrentDevice()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_IsHorizontal(arg0 any) any {
	_arg0 := arg0.(v2.DeviceOrientation)
	return func() any {
		defer func() { recover() }()
		result := v2.IsHorizontal(_arg0)
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_IsVertical(arg0 any) any {
	_arg0 := arg0.(v2.DeviceOrientation)
	return func() any {
		defer func() { recover() }()
		result := v2.IsVertical(_arg0)
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_LoadResourceFromPath(arg0 any) any {
	_arg0 := sky_asString(arg0)
	return func() any {
		defer func() { recover() }()
		result, err := v2.LoadResourceFromPath(_arg0)
		if err != nil { return SkyErr(err.Error()) }
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_LoadResourceFromURLString(arg0 any) any {
	_arg0 := sky_asString(arg0)
	return func() any {
		defer func() { recover() }()
		result, err := v2.LoadResourceFromURLString(_arg0)
		if err != nil { return SkyErr(err.Error()) }
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_LogError(arg0 any, arg1 any) any {
	_arg0 := sky_asString(arg0)
	_arg1 := sky_asError(arg1)
	return func() any {
		defer func() { recover() }()
		v2.LogError(_arg0, _arg1)
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_Max(arg0 any, arg1 any) any {
	_arg0 := sky_asFloat32(arg0)
	_arg1 := sky_asFloat32(arg1)
	return func() any {
		defer func() { recover() }()
		result := v2.Max(_arg0, _arg1)
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_MeasureText(arg0 any, arg1 any, arg2 any) any {
	_arg0 := sky_asString(arg0)
	_arg1 := sky_asFloat32(arg1)
	_arg2 := arg2.(v2.TextStyle)
	return func() any {
		defer func() { recover() }()
		result := v2.MeasureText(_arg0, _arg1, _arg2)
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_Min(arg0 any, arg1 any) any {
	_arg0 := sky_asFloat32(arg0)
	_arg1 := sky_asFloat32(arg1)
	return func() any {
		defer func() { recover() }()
		result := v2.Min(_arg0, _arg1)
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_NewContainer(arg0 any) any {
	
	return func() any {
		defer func() { recover() }()
		result := v2.NewContainer()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_NewContainerWithLayout(arg0 any, arg1 any) any {
	_arg0 := arg0.(v2.Layout)
	return func() any {
		defer func() { recover() }()
		result := v2.NewContainerWithLayout(_arg0)
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_NewContainerWithoutLayout(arg0 any) any {
	
	return func() any {
		defer func() { recover() }()
		result := v2.NewContainerWithoutLayout()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_NewDelta(arg0 any, arg1 any) any {
	_arg0 := sky_asFloat32(arg0)
	_arg1 := sky_asFloat32(arg1)
	return func() any {
		defer func() { recover() }()
		result := v2.NewDelta(_arg0, _arg1)
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_NewMainMenu(arg0 any) any {
	
	return func() any {
		defer func() { recover() }()
		result := v2.NewMainMenu()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_NewMenu(arg0 any, arg1 any) any {
	_arg0 := sky_asString(arg0)
	return func() any {
		defer func() { recover() }()
		result := v2.NewMenu(_arg0)
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_NewMenuItemSeparator(_ any) any {
	
	return func() any {
		defer func() { recover() }()
		result := v2.NewMenuItemSeparator()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_NewNotification(arg0 any, arg1 any) any {
	_arg0 := sky_asString(arg0)
	_arg1 := sky_asString(arg1)
	return func() any {
		defer func() { recover() }()
		result := v2.NewNotification(_arg0, _arg1)
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_NewPos(arg0 any, arg1 any) any {
	_arg0 := sky_asFloat32(arg0)
	_arg1 := sky_asFloat32(arg1)
	return func() any {
		defer func() { recover() }()
		result := v2.NewPos(_arg0, _arg1)
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_NewSize(arg0 any, arg1 any) any {
	_arg0 := sky_asFloat32(arg0)
	_arg1 := sky_asFloat32(arg1)
	return func() any {
		defer func() { recover() }()
		result := v2.NewSize(_arg0, _arg1)
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_NewSquareOffsetPos(arg0 any) any {
	_arg0 := sky_asFloat32(arg0)
	return func() any {
		defer func() { recover() }()
		result := v2.NewSquareOffsetPos(_arg0)
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_NewSquareSize(arg0 any) any {
	_arg0 := sky_asFloat32(arg0)
	return func() any {
		defer func() { recover() }()
		result := v2.NewSquareSize(_arg0)
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_NewStaticResource(arg0 any, arg1 any) any {
	_arg0 := sky_asString(arg0)
	_arg1 := sky_asBytes(arg1)
	return func() any {
		defer func() { recover() }()
		result := v2.NewStaticResource(_arg0, _arg1)
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_SetCurrentApp(arg0 any) any {
	_arg0 := arg0.(v2.App)
	return func() any {
		defer func() { recover() }()
		v2.SetCurrentApp(_arg0)
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_AnimationStart(receiver any) any {
	_receiver := receiver.(*v2.Animation)
	return func() any {
		defer func() { recover() }()
		_receiver.Start()
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_AnimationStop(receiver any) any {
	_receiver := receiver.(*v2.Animation)
	return func() any {
		defer func() { recover() }()
		_receiver.Stop()
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_AppClipboard(receiver any) any {
	_receiver := receiver.(v2.App)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Clipboard()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_AppCloudProvider(receiver any) any {
	_receiver := receiver.(v2.App)
	return func() any {
		defer func() { recover() }()
		result := _receiver.CloudProvider()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_AppDriver(receiver any) any {
	_receiver := receiver.(v2.App)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Driver()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_AppIcon(receiver any) any {
	_receiver := receiver.(v2.App)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Icon()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_AppLifecycle(receiver any) any {
	_receiver := receiver.(v2.App)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Lifecycle()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_AppMetadata(receiver any) any {
	_receiver := receiver.(v2.App)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Metadata()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_AppNewWindow(receiver any, arg0 any) any {
	_receiver := receiver.(v2.App)
	_arg0 := sky_asString(arg0)
	return func() any {
		defer func() { recover() }()
		result := _receiver.NewWindow(_arg0)
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_AppPreferences(receiver any) any {
	_receiver := receiver.(v2.App)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Preferences()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_AppQuit(receiver any) any {
	_receiver := receiver.(v2.App)
	return func() any {
		defer func() { recover() }()
		_receiver.Quit()
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_AppRun(receiver any) any {
	_receiver := receiver.(v2.App)
	return func() any {
		defer func() { recover() }()
		_receiver.Run()
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_AppSendNotification(receiver any, arg0 any) any {
	_receiver := receiver.(v2.App)
	_arg0 := arg0.(*v2.Notification)
	return func() any {
		defer func() { recover() }()
		_receiver.SendNotification(_arg0)
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_AppSetCloudProvider(receiver any, arg0 any) any {
	_receiver := receiver.(v2.App)
	_arg0 := arg0.(v2.CloudProvider)
	return func() any {
		defer func() { recover() }()
		_receiver.SetCloudProvider(_arg0)
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_AppSetIcon(receiver any, arg0 any) any {
	_receiver := receiver.(v2.App)
	_arg0 := arg0.(v2.Resource)
	return func() any {
		defer func() { recover() }()
		_receiver.SetIcon(_arg0)
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_AppSettings(receiver any) any {
	_receiver := receiver.(v2.App)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Settings()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_AppStorage(receiver any) any {
	_receiver := receiver.(v2.App)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Storage()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_AppUniqueID(receiver any) any {
	_receiver := receiver.(v2.App)
	return func() any {
		defer func() { recover() }()
		result := _receiver.UniqueID()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_CanvasCapture(receiver any) any {
	_receiver := receiver.(v2.Canvas)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Capture()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_CanvasContent(receiver any) any {
	_receiver := receiver.(v2.Canvas)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Content()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_CanvasFocus(receiver any, arg0 any) any {
	_receiver := receiver.(v2.Canvas)
	_arg0 := arg0.(v2.Focusable)
	return func() any {
		defer func() { recover() }()
		_receiver.Focus(_arg0)
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_CanvasFocusNext(receiver any) any {
	_receiver := receiver.(v2.Canvas)
	return func() any {
		defer func() { recover() }()
		_receiver.FocusNext()
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_CanvasFocusPrevious(receiver any) any {
	_receiver := receiver.(v2.Canvas)
	return func() any {
		defer func() { recover() }()
		_receiver.FocusPrevious()
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_CanvasFocused(receiver any) any {
	_receiver := receiver.(v2.Canvas)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Focused()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_CanvasInteractiveArea(receiver any) any {
	_receiver := receiver.(v2.Canvas)
	return func() any {
		defer func() { recover() }()
		_r0, _r1 := _receiver.InteractiveArea()
		return SkyOk(SkyTuple2{_r0, _r1})
	}()
}

func Sky_fyne_io_fyne_v2_CanvasOverlays(receiver any) any {
	_receiver := receiver.(v2.Canvas)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Overlays()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_CanvasPixelCoordinateForPosition(receiver any, arg0 any) any {
	_receiver := receiver.(v2.Canvas)
	_arg0 := arg0.(v2.Position)
	return func() any {
		defer func() { recover() }()
		_r0, _r1 := _receiver.PixelCoordinateForPosition(_arg0)
		return SkyOk(SkyTuple2{_r0, _r1})
	}()
}

func Sky_fyne_io_fyne_v2_CanvasRefresh(receiver any, arg0 any) any {
	_receiver := receiver.(v2.Canvas)
	_arg0 := arg0.(v2.CanvasObject)
	return func() any {
		defer func() { recover() }()
		_receiver.Refresh(_arg0)
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_CanvasRemoveShortcut(receiver any, arg0 any) any {
	_receiver := receiver.(v2.Canvas)
	_arg0 := arg0.(v2.Shortcut)
	return func() any {
		defer func() { recover() }()
		_receiver.RemoveShortcut(_arg0)
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_CanvasScale(receiver any) any {
	_receiver := receiver.(v2.Canvas)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Scale()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_CanvasSetContent(receiver any, arg0 any) any {
	_receiver := receiver.(v2.Canvas)
	_arg0 := arg0.(v2.CanvasObject)
	return func() any {
		defer func() { recover() }()
		_receiver.SetContent(_arg0)
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_CanvasSize(receiver any) any {
	_receiver := receiver.(v2.Canvas)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Size()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_CanvasUnfocus(receiver any) any {
	_receiver := receiver.(v2.Canvas)
	return func() any {
		defer func() { recover() }()
		_receiver.Unfocus()
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_CanvasObjectHide(receiver any) any {
	_receiver := receiver.(v2.CanvasObject)
	return func() any {
		defer func() { recover() }()
		_receiver.Hide()
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_CanvasObjectMinSize(receiver any) any {
	_receiver := receiver.(v2.CanvasObject)
	return func() any {
		defer func() { recover() }()
		result := _receiver.MinSize()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_CanvasObjectMove(receiver any, arg0 any) any {
	_receiver := receiver.(v2.CanvasObject)
	_arg0 := arg0.(v2.Position)
	return func() any {
		defer func() { recover() }()
		_receiver.Move(_arg0)
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_CanvasObjectPosition(receiver any) any {
	_receiver := receiver.(v2.CanvasObject)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Position()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_CanvasObjectRefresh(receiver any) any {
	_receiver := receiver.(v2.CanvasObject)
	return func() any {
		defer func() { recover() }()
		_receiver.Refresh()
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_CanvasObjectResize(receiver any, arg0 any) any {
	_receiver := receiver.(v2.CanvasObject)
	_arg0 := arg0.(v2.Size)
	return func() any {
		defer func() { recover() }()
		_receiver.Resize(_arg0)
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_CanvasObjectShow(receiver any) any {
	_receiver := receiver.(v2.CanvasObject)
	return func() any {
		defer func() { recover() }()
		_receiver.Show()
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_CanvasObjectSize(receiver any) any {
	_receiver := receiver.(v2.CanvasObject)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Size()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_CanvasObjectVisible(receiver any) any {
	_receiver := receiver.(v2.CanvasObject)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Visible()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_ClipboardContent(receiver any) any {
	_receiver := receiver.(v2.Clipboard)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Content()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_ClipboardSetContent(receiver any, arg0 any) any {
	_receiver := receiver.(v2.Clipboard)
	_arg0 := sky_asString(arg0)
	return func() any {
		defer func() { recover() }()
		_receiver.SetContent(_arg0)
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_CloudProviderCleanup(receiver any, arg0 any) any {
	_receiver := receiver.(v2.CloudProvider)
	_arg0 := arg0.(v2.App)
	return func() any {
		defer func() { recover() }()
		_receiver.Cleanup(_arg0)
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_CloudProviderProviderDescription(receiver any) any {
	_receiver := receiver.(v2.CloudProvider)
	return func() any {
		defer func() { recover() }()
		result := _receiver.ProviderDescription()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_CloudProviderProviderIcon(receiver any) any {
	_receiver := receiver.(v2.CloudProvider)
	return func() any {
		defer func() { recover() }()
		result := _receiver.ProviderIcon()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_CloudProviderProviderName(receiver any) any {
	_receiver := receiver.(v2.CloudProvider)
	return func() any {
		defer func() { recover() }()
		result := _receiver.ProviderName()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_CloudProviderSetup(receiver any, arg0 any) any {
	_receiver := receiver.(v2.CloudProvider)
	_arg0 := arg0.(v2.App)
	return func() any {
		defer func() { recover() }()
		err := _receiver.Setup(_arg0)
		if err != nil { return SkyErr(err.Error()) }
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_CloudProviderPreferencesCloudPreferences(receiver any, arg0 any) any {
	_receiver := receiver.(v2.CloudProviderPreferences)
	_arg0 := arg0.(v2.App)
	return func() any {
		defer func() { recover() }()
		result := _receiver.CloudPreferences(_arg0)
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_CloudProviderStorageCloudStorage(receiver any, arg0 any) any {
	_receiver := receiver.(v2.CloudProviderStorage)
	_arg0 := arg0.(v2.App)
	return func() any {
		defer func() { recover() }()
		result := _receiver.CloudStorage(_arg0)
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_ContainerAdd(receiver any, arg0 any) any {
	_receiver := receiver.(*v2.Container)
	_arg0 := arg0.(v2.CanvasObject)
	return func() any {
		defer func() { recover() }()
		_receiver.Add(_arg0)
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_ContainerAddObject(receiver any, arg0 any) any {
	_receiver := receiver.(*v2.Container)
	_arg0 := arg0.(v2.CanvasObject)
	return func() any {
		defer func() { recover() }()
		_receiver.AddObject(_arg0)
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_ContainerHide(receiver any) any {
	_receiver := receiver.(*v2.Container)
	return func() any {
		defer func() { recover() }()
		_receiver.Hide()
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_ContainerMinSize(receiver any) any {
	_receiver := receiver.(*v2.Container)
	return func() any {
		defer func() { recover() }()
		result := _receiver.MinSize()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_ContainerMove(receiver any, arg0 any) any {
	_receiver := receiver.(*v2.Container)
	_arg0 := arg0.(v2.Position)
	return func() any {
		defer func() { recover() }()
		_receiver.Move(_arg0)
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_ContainerPosition(receiver any) any {
	_receiver := receiver.(*v2.Container)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Position()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_ContainerRefresh(receiver any) any {
	_receiver := receiver.(*v2.Container)
	return func() any {
		defer func() { recover() }()
		_receiver.Refresh()
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_ContainerRemove(receiver any, arg0 any) any {
	_receiver := receiver.(*v2.Container)
	_arg0 := arg0.(v2.CanvasObject)
	return func() any {
		defer func() { recover() }()
		_receiver.Remove(_arg0)
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_ContainerRemoveAll(receiver any) any {
	_receiver := receiver.(*v2.Container)
	return func() any {
		defer func() { recover() }()
		_receiver.RemoveAll()
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_ContainerResize(receiver any, arg0 any) any {
	_receiver := receiver.(*v2.Container)
	_arg0 := arg0.(v2.Size)
	return func() any {
		defer func() { recover() }()
		_receiver.Resize(_arg0)
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_ContainerShow(receiver any) any {
	_receiver := receiver.(*v2.Container)
	return func() any {
		defer func() { recover() }()
		_receiver.Show()
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_ContainerSize(receiver any) any {
	_receiver := receiver.(*v2.Container)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Size()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_ContainerVisible(receiver any) any {
	_receiver := receiver.(*v2.Container)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Visible()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_DeltaComponents(receiver any) any {
	_receiver := receiver.(*v2.Delta)
	return func() any {
		defer func() { recover() }()
		_r0, _r1 := _receiver.Components()
		return SkyOk(SkyTuple2{_r0, _r1})
	}()
}

func Sky_fyne_io_fyne_v2_DeltaIsZero(receiver any) any {
	_receiver := receiver.(*v2.Delta)
	return func() any {
		defer func() { recover() }()
		result := _receiver.IsZero()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_DeviceHasKeyboard(receiver any) any {
	_receiver := receiver.(v2.Device)
	return func() any {
		defer func() { recover() }()
		result := _receiver.HasKeyboard()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_DeviceIsBrowser(receiver any) any {
	_receiver := receiver.(v2.Device)
	return func() any {
		defer func() { recover() }()
		result := _receiver.IsBrowser()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_DeviceIsMobile(receiver any) any {
	_receiver := receiver.(v2.Device)
	return func() any {
		defer func() { recover() }()
		result := _receiver.IsMobile()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_DeviceLocale(receiver any) any {
	_receiver := receiver.(v2.Device)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Locale()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_DeviceOrientation(receiver any) any {
	_receiver := receiver.(v2.Device)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Orientation()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_DeviceSystemScaleForWindow(receiver any, arg0 any) any {
	_receiver := receiver.(v2.Device)
	_arg0 := arg0.(v2.Window)
	return func() any {
		defer func() { recover() }()
		result := _receiver.SystemScaleForWindow(_arg0)
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_DisableableDisable(receiver any) any {
	_receiver := receiver.(v2.Disableable)
	return func() any {
		defer func() { recover() }()
		_receiver.Disable()
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_DisableableDisabled(receiver any) any {
	_receiver := receiver.(v2.Disableable)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Disabled()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_DisableableEnable(receiver any) any {
	_receiver := receiver.(v2.Disableable)
	return func() any {
		defer func() { recover() }()
		_receiver.Enable()
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_DoubleTappableDoubleTapped(receiver any, arg0 any) any {
	_receiver := receiver.(v2.DoubleTappable)
	_arg0 := arg0.(*v2.PointEvent)
	return func() any {
		defer func() { recover() }()
		_receiver.DoubleTapped(_arg0)
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_DraggableDragEnd(receiver any) any {
	_receiver := receiver.(v2.Draggable)
	return func() any {
		defer func() { recover() }()
		_receiver.DragEnd()
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_DraggableDragged(receiver any, arg0 any) any {
	_receiver := receiver.(v2.Draggable)
	_arg0 := arg0.(*v2.DragEvent)
	return func() any {
		defer func() { recover() }()
		_receiver.Dragged(_arg0)
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_DriverAbsolutePositionForObject(receiver any, arg0 any) any {
	_receiver := receiver.(v2.Driver)
	_arg0 := arg0.(v2.CanvasObject)
	return func() any {
		defer func() { recover() }()
		result := _receiver.AbsolutePositionForObject(_arg0)
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_DriverAllWindows(receiver any) any {
	_receiver := receiver.(v2.Driver)
	return func() any {
		defer func() { recover() }()
		result := _receiver.AllWindows()
		return SkyOk(result[:])
	}()
}

func Sky_fyne_io_fyne_v2_DriverCanvasForObject(receiver any, arg0 any) any {
	_receiver := receiver.(v2.Driver)
	_arg0 := arg0.(v2.CanvasObject)
	return func() any {
		defer func() { recover() }()
		result := _receiver.CanvasForObject(_arg0)
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_DriverCreateWindow(receiver any, arg0 any) any {
	_receiver := receiver.(v2.Driver)
	_arg0 := sky_asString(arg0)
	return func() any {
		defer func() { recover() }()
		result := _receiver.CreateWindow(_arg0)
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_DriverDevice(receiver any) any {
	_receiver := receiver.(v2.Driver)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Device()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_DriverQuit(receiver any) any {
	_receiver := receiver.(v2.Driver)
	return func() any {
		defer func() { recover() }()
		_receiver.Quit()
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_DriverRenderedTextSize(receiver any, arg0 any, arg1 any, arg2 any, arg3 any) any {
	_receiver := receiver.(v2.Driver)
	_arg0 := sky_asString(arg0)
	_arg1 := sky_asFloat32(arg1)
	_arg2 := arg2.(v2.TextStyle)
	_arg3 := arg3.(v2.Resource)
	return func() any {
		defer func() { recover() }()
		_r0, _r1 := _receiver.RenderedTextSize(_arg0, _arg1, _arg2, _arg3)
		return SkyOk(SkyTuple2{_r0, _r1})
	}()
}

func Sky_fyne_io_fyne_v2_DriverRun(receiver any) any {
	_receiver := receiver.(v2.Driver)
	return func() any {
		defer func() { recover() }()
		_receiver.Run()
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_DriverSetDisableScreenBlanking(receiver any, arg0 any) any {
	_receiver := receiver.(v2.Driver)
	_arg0 := sky_asBool(arg0)
	return func() any {
		defer func() { recover() }()
		_receiver.SetDisableScreenBlanking(_arg0)
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_DriverStartAnimation(receiver any, arg0 any) any {
	_receiver := receiver.(v2.Driver)
	_arg0 := arg0.(*v2.Animation)
	return func() any {
		defer func() { recover() }()
		_receiver.StartAnimation(_arg0)
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_DriverStopAnimation(receiver any, arg0 any) any {
	_receiver := receiver.(v2.Driver)
	_arg0 := arg0.(*v2.Animation)
	return func() any {
		defer func() { recover() }()
		_receiver.StopAnimation(_arg0)
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_FocusableFocusGained(receiver any) any {
	_receiver := receiver.(v2.Focusable)
	return func() any {
		defer func() { recover() }()
		_receiver.FocusGained()
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_FocusableFocusLost(receiver any) any {
	_receiver := receiver.(v2.Focusable)
	return func() any {
		defer func() { recover() }()
		_receiver.FocusLost()
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_FocusableTypedKey(receiver any, arg0 any) any {
	_receiver := receiver.(v2.Focusable)
	_arg0 := arg0.(*v2.KeyEvent)
	return func() any {
		defer func() { recover() }()
		_receiver.TypedKey(_arg0)
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_KeyboardShortcutKey(receiver any) any {
	_receiver := receiver.(v2.KeyboardShortcut)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Key()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_KeyboardShortcutMod(receiver any) any {
	_receiver := receiver.(v2.KeyboardShortcut)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Mod()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_KeyboardShortcutShortcutName(receiver any) any {
	_receiver := receiver.(v2.KeyboardShortcut)
	return func() any {
		defer func() { recover() }()
		result := _receiver.ShortcutName()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_LayoutLayout(receiver any, arg0 any, arg1 any) any {
	_receiver := receiver.(v2.Layout)
	_arg0 := sky_asList(arg0)
	_arg1 := arg1.(v2.Size)
	return func() any {
		defer func() { recover() }()
		_receiver.Layout(_arg0, _arg1)
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_LayoutMinSize(receiver any, arg0 any) any {
	_receiver := receiver.(v2.Layout)
	_arg0 := sky_asList(arg0)
	return func() any {
		defer func() { recover() }()
		result := _receiver.MinSize(_arg0)
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_LegacyThemeIconInlineSize(receiver any) any {
	_receiver := receiver.(v2.LegacyTheme)
	return func() any {
		defer func() { recover() }()
		result := _receiver.IconInlineSize()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_LegacyThemePadding(receiver any) any {
	_receiver := receiver.(v2.LegacyTheme)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Padding()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_LegacyThemeScrollBarSize(receiver any) any {
	_receiver := receiver.(v2.LegacyTheme)
	return func() any {
		defer func() { recover() }()
		result := _receiver.ScrollBarSize()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_LegacyThemeScrollBarSmallSize(receiver any) any {
	_receiver := receiver.(v2.LegacyTheme)
	return func() any {
		defer func() { recover() }()
		result := _receiver.ScrollBarSmallSize()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_LegacyThemeTextBoldFont(receiver any) any {
	_receiver := receiver.(v2.LegacyTheme)
	return func() any {
		defer func() { recover() }()
		result := _receiver.TextBoldFont()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_LegacyThemeTextBoldItalicFont(receiver any) any {
	_receiver := receiver.(v2.LegacyTheme)
	return func() any {
		defer func() { recover() }()
		result := _receiver.TextBoldItalicFont()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_LegacyThemeTextFont(receiver any) any {
	_receiver := receiver.(v2.LegacyTheme)
	return func() any {
		defer func() { recover() }()
		result := _receiver.TextFont()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_LegacyThemeTextItalicFont(receiver any) any {
	_receiver := receiver.(v2.LegacyTheme)
	return func() any {
		defer func() { recover() }()
		result := _receiver.TextItalicFont()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_LegacyThemeTextMonospaceFont(receiver any) any {
	_receiver := receiver.(v2.LegacyTheme)
	return func() any {
		defer func() { recover() }()
		result := _receiver.TextMonospaceFont()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_LegacyThemeTextSize(receiver any) any {
	_receiver := receiver.(v2.LegacyTheme)
	return func() any {
		defer func() { recover() }()
		result := _receiver.TextSize()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_ListableURIAuthority(receiver any) any {
	_receiver := receiver.(v2.ListableURI)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Authority()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_ListableURIExtension(receiver any) any {
	_receiver := receiver.(v2.ListableURI)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Extension()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_ListableURIFragment(receiver any) any {
	_receiver := receiver.(v2.ListableURI)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Fragment()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_ListableURIList(receiver any) any {
	_receiver := receiver.(v2.ListableURI)
	return func() any {
		defer func() { recover() }()
		result, err := _receiver.List()
		if err != nil { return SkyErr(err.Error()) }
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_ListableURIMimeType(receiver any) any {
	_receiver := receiver.(v2.ListableURI)
	return func() any {
		defer func() { recover() }()
		result := _receiver.MimeType()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_ListableURIName(receiver any) any {
	_receiver := receiver.(v2.ListableURI)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Name()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_ListableURIPath(receiver any) any {
	_receiver := receiver.(v2.ListableURI)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Path()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_ListableURIQuery(receiver any) any {
	_receiver := receiver.(v2.ListableURI)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Query()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_ListableURIScheme(receiver any) any {
	_receiver := receiver.(v2.ListableURI)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Scheme()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_ListableURIString(receiver any) any {
	_receiver := receiver.(v2.ListableURI)
	return func() any {
		defer func() { recover() }()
		result := _receiver.String()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_LocaleLanguageString(receiver any) any {
	_receiver := receiver.(*v2.Locale)
	return func() any {
		defer func() { recover() }()
		result := _receiver.LanguageString()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_LocaleString(receiver any) any {
	_receiver := receiver.(*v2.Locale)
	return func() any {
		defer func() { recover() }()
		result := _receiver.String()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_MainMenuRefresh(receiver any) any {
	_receiver := receiver.(*v2.MainMenu)
	return func() any {
		defer func() { recover() }()
		_receiver.Refresh()
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_MenuRefresh(receiver any) any {
	_receiver := receiver.(*v2.Menu)
	return func() any {
		defer func() { recover() }()
		_receiver.Refresh()
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_OverlayStackAdd(receiver any, arg0 any) any {
	_receiver := receiver.(v2.OverlayStack)
	_arg0 := arg0.(v2.CanvasObject)
	return func() any {
		defer func() { recover() }()
		_receiver.Add(_arg0)
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_OverlayStackList(receiver any) any {
	_receiver := receiver.(v2.OverlayStack)
	return func() any {
		defer func() { recover() }()
		result := _receiver.List()
		return SkyOk(result[:])
	}()
}

func Sky_fyne_io_fyne_v2_OverlayStackRemove(receiver any, arg0 any) any {
	_receiver := receiver.(v2.OverlayStack)
	_arg0 := arg0.(v2.CanvasObject)
	return func() any {
		defer func() { recover() }()
		_receiver.Remove(_arg0)
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_OverlayStackTop(receiver any) any {
	_receiver := receiver.(v2.OverlayStack)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Top()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_PositionAdd(receiver any, arg0 any) any {
	_receiver := receiver.(*v2.Position)
	_arg0 := arg0.(v2.Vector2)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Add(_arg0)
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_PositionAddXY(receiver any, arg0 any, arg1 any) any {
	_receiver := receiver.(*v2.Position)
	_arg0 := sky_asFloat32(arg0)
	_arg1 := sky_asFloat32(arg1)
	return func() any {
		defer func() { recover() }()
		result := _receiver.AddXY(_arg0, _arg1)
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_PositionComponents(receiver any) any {
	_receiver := receiver.(*v2.Position)
	return func() any {
		defer func() { recover() }()
		_r0, _r1 := _receiver.Components()
		return SkyOk(SkyTuple2{_r0, _r1})
	}()
}

func Sky_fyne_io_fyne_v2_PositionIsZero(receiver any) any {
	_receiver := receiver.(*v2.Position)
	return func() any {
		defer func() { recover() }()
		result := _receiver.IsZero()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_PositionSubtract(receiver any, arg0 any) any {
	_receiver := receiver.(*v2.Position)
	_arg0 := arg0.(v2.Vector2)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Subtract(_arg0)
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_PositionSubtractXY(receiver any, arg0 any, arg1 any) any {
	_receiver := receiver.(*v2.Position)
	_arg0 := sky_asFloat32(arg0)
	_arg1 := sky_asFloat32(arg1)
	return func() any {
		defer func() { recover() }()
		result := _receiver.SubtractXY(_arg0, _arg1)
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_PreferencesBool(receiver any, arg0 any) any {
	_receiver := receiver.(v2.Preferences)
	_arg0 := sky_asString(arg0)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Bool(_arg0)
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_PreferencesBoolWithFallback(receiver any, arg0 any, arg1 any) any {
	_receiver := receiver.(v2.Preferences)
	_arg0 := sky_asString(arg0)
	_arg1 := sky_asBool(arg1)
	return func() any {
		defer func() { recover() }()
		result := _receiver.BoolWithFallback(_arg0, _arg1)
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_PreferencesFloat(receiver any, arg0 any) any {
	_receiver := receiver.(v2.Preferences)
	_arg0 := sky_asString(arg0)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Float(_arg0)
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_PreferencesFloatWithFallback(receiver any, arg0 any, arg1 any) any {
	_receiver := receiver.(v2.Preferences)
	_arg0 := sky_asString(arg0)
	_arg1 := sky_asFloat(arg1)
	return func() any {
		defer func() { recover() }()
		result := _receiver.FloatWithFallback(_arg0, _arg1)
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_PreferencesInt(receiver any, arg0 any) any {
	_receiver := receiver.(v2.Preferences)
	_arg0 := sky_asString(arg0)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Int(_arg0)
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_PreferencesIntWithFallback(receiver any, arg0 any, arg1 any) any {
	_receiver := receiver.(v2.Preferences)
	_arg0 := sky_asString(arg0)
	_arg1 := sky_asInt(arg1)
	return func() any {
		defer func() { recover() }()
		result := _receiver.IntWithFallback(_arg0, _arg1)
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_PreferencesRemoveValue(receiver any, arg0 any) any {
	_receiver := receiver.(v2.Preferences)
	_arg0 := sky_asString(arg0)
	return func() any {
		defer func() { recover() }()
		_receiver.RemoveValue(_arg0)
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_PreferencesSetBool(receiver any, arg0 any, arg1 any) any {
	_receiver := receiver.(v2.Preferences)
	_arg0 := sky_asString(arg0)
	_arg1 := sky_asBool(arg1)
	return func() any {
		defer func() { recover() }()
		_receiver.SetBool(_arg0, _arg1)
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_PreferencesSetFloat(receiver any, arg0 any, arg1 any) any {
	_receiver := receiver.(v2.Preferences)
	_arg0 := sky_asString(arg0)
	_arg1 := sky_asFloat(arg1)
	return func() any {
		defer func() { recover() }()
		_receiver.SetFloat(_arg0, _arg1)
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_PreferencesSetInt(receiver any, arg0 any, arg1 any) any {
	_receiver := receiver.(v2.Preferences)
	_arg0 := sky_asString(arg0)
	_arg1 := sky_asInt(arg1)
	return func() any {
		defer func() { recover() }()
		_receiver.SetInt(_arg0, _arg1)
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_PreferencesSetString(receiver any, arg0 any, arg1 any) any {
	_receiver := receiver.(v2.Preferences)
	_arg0 := sky_asString(arg0)
	_arg1 := sky_asString(arg1)
	return func() any {
		defer func() { recover() }()
		_receiver.SetString(_arg0, _arg1)
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_PreferencesSetStringList(receiver any, arg0 any, arg1 any) any {
	_receiver := receiver.(v2.Preferences)
	_arg0 := sky_asString(arg0)
	_arg1 := sky_asStringSlice(arg1)
	return func() any {
		defer func() { recover() }()
		_receiver.SetStringList(_arg0, _arg1)
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_PreferencesString(receiver any, arg0 any) any {
	_receiver := receiver.(v2.Preferences)
	_arg0 := sky_asString(arg0)
	return func() any {
		defer func() { recover() }()
		result := _receiver.String(_arg0)
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_PreferencesStringList(receiver any, arg0 any) any {
	_receiver := receiver.(v2.Preferences)
	_arg0 := sky_asString(arg0)
	return func() any {
		defer func() { recover() }()
		result := _receiver.StringList(_arg0)
		return SkyOk(result[:])
	}()
}

func Sky_fyne_io_fyne_v2_PreferencesStringListWithFallback(receiver any, arg0 any, arg1 any) any {
	_receiver := receiver.(v2.Preferences)
	_arg0 := sky_asString(arg0)
	_arg1 := sky_asStringSlice(arg1)
	return func() any {
		defer func() { recover() }()
		result := _receiver.StringListWithFallback(_arg0, _arg1)
		return SkyOk(result[:])
	}()
}

func Sky_fyne_io_fyne_v2_PreferencesStringWithFallback(receiver any, arg0 any, arg1 any) any {
	_receiver := receiver.(v2.Preferences)
	_arg0 := sky_asString(arg0)
	_arg1 := sky_asString(arg1)
	return func() any {
		defer func() { recover() }()
		result := _receiver.StringWithFallback(_arg0, _arg1)
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_ResourceContent(receiver any) any {
	_receiver := receiver.(v2.Resource)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Content()
		return SkyOk(result[:])
	}()
}

func Sky_fyne_io_fyne_v2_ResourceName(receiver any) any {
	_receiver := receiver.(v2.Resource)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Name()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_ScrollableScrolled(receiver any, arg0 any) any {
	_receiver := receiver.(v2.Scrollable)
	_arg0 := arg0.(*v2.ScrollEvent)
	return func() any {
		defer func() { recover() }()
		_receiver.Scrolled(_arg0)
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_SecondaryTappableTappedSecondary(receiver any, arg0 any) any {
	_receiver := receiver.(v2.SecondaryTappable)
	_arg0 := arg0.(*v2.PointEvent)
	return func() any {
		defer func() { recover() }()
		_receiver.TappedSecondary(_arg0)
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_SettingsBuildType(receiver any) any {
	_receiver := receiver.(v2.Settings)
	return func() any {
		defer func() { recover() }()
		result := _receiver.BuildType()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_SettingsPrimaryColor(receiver any) any {
	_receiver := receiver.(v2.Settings)
	return func() any {
		defer func() { recover() }()
		result := _receiver.PrimaryColor()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_SettingsScale(receiver any) any {
	_receiver := receiver.(v2.Settings)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Scale()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_SettingsSetTheme(receiver any, arg0 any) any {
	_receiver := receiver.(v2.Settings)
	_arg0 := arg0.(v2.Theme)
	return func() any {
		defer func() { recover() }()
		_receiver.SetTheme(_arg0)
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_SettingsShowAnimations(receiver any) any {
	_receiver := receiver.(v2.Settings)
	return func() any {
		defer func() { recover() }()
		result := _receiver.ShowAnimations()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_SettingsTheme(receiver any) any {
	_receiver := receiver.(v2.Settings)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Theme()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_SettingsThemeVariant(receiver any) any {
	_receiver := receiver.(v2.Settings)
	return func() any {
		defer func() { recover() }()
		result := _receiver.ThemeVariant()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_ShortcutShortcutName(receiver any) any {
	_receiver := receiver.(v2.Shortcut)
	return func() any {
		defer func() { recover() }()
		result := _receiver.ShortcutName()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_ShortcutCopyKey(receiver any) any {
	_receiver := receiver.(*v2.ShortcutCopy)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Key()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_ShortcutCopyMod(receiver any) any {
	_receiver := receiver.(*v2.ShortcutCopy)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Mod()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_ShortcutCopyShortcutName(receiver any) any {
	_receiver := receiver.(*v2.ShortcutCopy)
	return func() any {
		defer func() { recover() }()
		result := _receiver.ShortcutName()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_ShortcutCutKey(receiver any) any {
	_receiver := receiver.(*v2.ShortcutCut)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Key()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_ShortcutCutMod(receiver any) any {
	_receiver := receiver.(*v2.ShortcutCut)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Mod()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_ShortcutCutShortcutName(receiver any) any {
	_receiver := receiver.(*v2.ShortcutCut)
	return func() any {
		defer func() { recover() }()
		result := _receiver.ShortcutName()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_ShortcutHandlerRemoveShortcut(receiver any, arg0 any) any {
	_receiver := receiver.(*v2.ShortcutHandler)
	_arg0 := arg0.(v2.Shortcut)
	return func() any {
		defer func() { recover() }()
		_receiver.RemoveShortcut(_arg0)
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_ShortcutHandlerTypedShortcut(receiver any, arg0 any) any {
	_receiver := receiver.(*v2.ShortcutHandler)
	_arg0 := arg0.(v2.Shortcut)
	return func() any {
		defer func() { recover() }()
		_receiver.TypedShortcut(_arg0)
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_ShortcutPasteKey(receiver any) any {
	_receiver := receiver.(*v2.ShortcutPaste)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Key()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_ShortcutPasteMod(receiver any) any {
	_receiver := receiver.(*v2.ShortcutPaste)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Mod()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_ShortcutPasteShortcutName(receiver any) any {
	_receiver := receiver.(*v2.ShortcutPaste)
	return func() any {
		defer func() { recover() }()
		result := _receiver.ShortcutName()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_ShortcutRedoKey(receiver any) any {
	_receiver := receiver.(*v2.ShortcutRedo)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Key()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_ShortcutRedoMod(receiver any) any {
	_receiver := receiver.(*v2.ShortcutRedo)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Mod()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_ShortcutRedoShortcutName(receiver any) any {
	_receiver := receiver.(*v2.ShortcutRedo)
	return func() any {
		defer func() { recover() }()
		result := _receiver.ShortcutName()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_ShortcutSelectAllKey(receiver any) any {
	_receiver := receiver.(*v2.ShortcutSelectAll)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Key()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_ShortcutSelectAllMod(receiver any) any {
	_receiver := receiver.(*v2.ShortcutSelectAll)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Mod()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_ShortcutSelectAllShortcutName(receiver any) any {
	_receiver := receiver.(*v2.ShortcutSelectAll)
	return func() any {
		defer func() { recover() }()
		result := _receiver.ShortcutName()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_ShortcutUndoKey(receiver any) any {
	_receiver := receiver.(*v2.ShortcutUndo)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Key()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_ShortcutUndoMod(receiver any) any {
	_receiver := receiver.(*v2.ShortcutUndo)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Mod()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_ShortcutUndoShortcutName(receiver any) any {
	_receiver := receiver.(*v2.ShortcutUndo)
	return func() any {
		defer func() { recover() }()
		result := _receiver.ShortcutName()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_ShortcutableTypedShortcut(receiver any, arg0 any) any {
	_receiver := receiver.(v2.Shortcutable)
	_arg0 := arg0.(v2.Shortcut)
	return func() any {
		defer func() { recover() }()
		_receiver.TypedShortcut(_arg0)
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_SizeAdd(receiver any, arg0 any) any {
	_receiver := receiver.(*v2.Size)
	_arg0 := arg0.(v2.Vector2)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Add(_arg0)
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_SizeAddWidthHeight(receiver any, arg0 any, arg1 any) any {
	_receiver := receiver.(*v2.Size)
	_arg0 := sky_asFloat32(arg0)
	_arg1 := sky_asFloat32(arg1)
	return func() any {
		defer func() { recover() }()
		result := _receiver.AddWidthHeight(_arg0, _arg1)
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_SizeComponents(receiver any) any {
	_receiver := receiver.(*v2.Size)
	return func() any {
		defer func() { recover() }()
		_r0, _r1 := _receiver.Components()
		return SkyOk(SkyTuple2{_r0, _r1})
	}()
}

func Sky_fyne_io_fyne_v2_SizeIsZero(receiver any) any {
	_receiver := receiver.(*v2.Size)
	return func() any {
		defer func() { recover() }()
		result := _receiver.IsZero()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_SizeMax(receiver any, arg0 any) any {
	_receiver := receiver.(*v2.Size)
	_arg0 := arg0.(v2.Vector2)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Max(_arg0)
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_SizeMin(receiver any, arg0 any) any {
	_receiver := receiver.(*v2.Size)
	_arg0 := arg0.(v2.Vector2)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Min(_arg0)
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_SizeSubtract(receiver any, arg0 any) any {
	_receiver := receiver.(*v2.Size)
	_arg0 := arg0.(v2.Vector2)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Subtract(_arg0)
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_SizeSubtractWidthHeight(receiver any, arg0 any, arg1 any) any {
	_receiver := receiver.(*v2.Size)
	_arg0 := sky_asFloat32(arg0)
	_arg1 := sky_asFloat32(arg1)
	return func() any {
		defer func() { recover() }()
		result := _receiver.SubtractWidthHeight(_arg0, _arg1)
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_StaticResourceContent(receiver any) any {
	_receiver := receiver.(*v2.StaticResource)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Content()
		return SkyOk(result[:])
	}()
}

func Sky_fyne_io_fyne_v2_StaticResourceGoString(receiver any) any {
	_receiver := receiver.(*v2.StaticResource)
	return func() any {
		defer func() { recover() }()
		result := _receiver.GoString()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_StaticResourceName(receiver any) any {
	_receiver := receiver.(*v2.StaticResource)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Name()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_StorageCreate(receiver any, arg0 any) any {
	_receiver := receiver.(v2.Storage)
	_arg0 := sky_asString(arg0)
	return func() any {
		defer func() { recover() }()
		result, err := _receiver.Create(_arg0)
		if err != nil { return SkyErr(err.Error()) }
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_StorageList(receiver any) any {
	_receiver := receiver.(v2.Storage)
	return func() any {
		defer func() { recover() }()
		result := _receiver.List()
		return SkyOk(result[:])
	}()
}

func Sky_fyne_io_fyne_v2_StorageOpen(receiver any, arg0 any) any {
	_receiver := receiver.(v2.Storage)
	_arg0 := sky_asString(arg0)
	return func() any {
		defer func() { recover() }()
		result, err := _receiver.Open(_arg0)
		if err != nil { return SkyErr(err.Error()) }
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_StorageRemove(receiver any, arg0 any) any {
	_receiver := receiver.(v2.Storage)
	_arg0 := sky_asString(arg0)
	return func() any {
		defer func() { recover() }()
		err := _receiver.Remove(_arg0)
		if err != nil { return SkyErr(err.Error()) }
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_StorageRootURI(receiver any) any {
	_receiver := receiver.(v2.Storage)
	return func() any {
		defer func() { recover() }()
		result := _receiver.RootURI()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_StorageSave(receiver any, arg0 any) any {
	_receiver := receiver.(v2.Storage)
	_arg0 := sky_asString(arg0)
	return func() any {
		defer func() { recover() }()
		result, err := _receiver.Save(_arg0)
		if err != nil { return SkyErr(err.Error()) }
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_TabbableAcceptsTab(receiver any) any {
	_receiver := receiver.(v2.Tabbable)
	return func() any {
		defer func() { recover() }()
		result := _receiver.AcceptsTab()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_TappableTapped(receiver any, arg0 any) any {
	_receiver := receiver.(v2.Tappable)
	_arg0 := arg0.(*v2.PointEvent)
	return func() any {
		defer func() { recover() }()
		_receiver.Tapped(_arg0)
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_ThemeFont(receiver any, arg0 any) any {
	_receiver := receiver.(v2.Theme)
	_arg0 := arg0.(v2.TextStyle)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Font(_arg0)
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_ThemeIcon(receiver any, arg0 any) any {
	_receiver := receiver.(v2.Theme)
	_arg0 := arg0.(v2.ThemeIconName)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Icon(_arg0)
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_ThemeSize(receiver any, arg0 any) any {
	_receiver := receiver.(v2.Theme)
	_arg0 := arg0.(v2.ThemeSizeName)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Size(_arg0)
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_ThemedResourceContent(receiver any) any {
	_receiver := receiver.(v2.ThemedResource)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Content()
		return SkyOk(result[:])
	}()
}

func Sky_fyne_io_fyne_v2_ThemedResourceName(receiver any) any {
	_receiver := receiver.(v2.ThemedResource)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Name()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_ThemedResourceThemeColorName(receiver any) any {
	_receiver := receiver.(v2.ThemedResource)
	return func() any {
		defer func() { recover() }()
		result := _receiver.ThemeColorName()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_URIAuthority(receiver any) any {
	_receiver := receiver.(v2.URI)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Authority()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_URIExtension(receiver any) any {
	_receiver := receiver.(v2.URI)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Extension()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_URIFragment(receiver any) any {
	_receiver := receiver.(v2.URI)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Fragment()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_URIMimeType(receiver any) any {
	_receiver := receiver.(v2.URI)
	return func() any {
		defer func() { recover() }()
		result := _receiver.MimeType()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_URIName(receiver any) any {
	_receiver := receiver.(v2.URI)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Name()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_URIPath(receiver any) any {
	_receiver := receiver.(v2.URI)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Path()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_URIQuery(receiver any) any {
	_receiver := receiver.(v2.URI)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Query()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_URIScheme(receiver any) any {
	_receiver := receiver.(v2.URI)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Scheme()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_URIString(receiver any) any {
	_receiver := receiver.(v2.URI)
	return func() any {
		defer func() { recover() }()
		result := _receiver.String()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_URIReadCloserClose(receiver any) any {
	_receiver := receiver.(v2.URIReadCloser)
	return func() any {
		defer func() { recover() }()
		err := _receiver.Close()
		if err != nil { return SkyErr(err.Error()) }
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_URIReadCloserRead(receiver any, arg0 any) any {
	_receiver := receiver.(v2.URIReadCloser)
	_arg0 := sky_asBytes(arg0)
	return func() any {
		defer func() { recover() }()
		result, err := _receiver.Read(_arg0)
		if err != nil { return SkyErr(err.Error()) }
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_URIReadCloserURI(receiver any) any {
	_receiver := receiver.(v2.URIReadCloser)
	return func() any {
		defer func() { recover() }()
		result := _receiver.URI()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_URIWithIconAuthority(receiver any) any {
	_receiver := receiver.(v2.URIWithIcon)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Authority()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_URIWithIconExtension(receiver any) any {
	_receiver := receiver.(v2.URIWithIcon)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Extension()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_URIWithIconFragment(receiver any) any {
	_receiver := receiver.(v2.URIWithIcon)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Fragment()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_URIWithIconIcon(receiver any) any {
	_receiver := receiver.(v2.URIWithIcon)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Icon()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_URIWithIconMimeType(receiver any) any {
	_receiver := receiver.(v2.URIWithIcon)
	return func() any {
		defer func() { recover() }()
		result := _receiver.MimeType()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_URIWithIconName(receiver any) any {
	_receiver := receiver.(v2.URIWithIcon)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Name()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_URIWithIconPath(receiver any) any {
	_receiver := receiver.(v2.URIWithIcon)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Path()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_URIWithIconQuery(receiver any) any {
	_receiver := receiver.(v2.URIWithIcon)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Query()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_URIWithIconScheme(receiver any) any {
	_receiver := receiver.(v2.URIWithIcon)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Scheme()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_URIWithIconString(receiver any) any {
	_receiver := receiver.(v2.URIWithIcon)
	return func() any {
		defer func() { recover() }()
		result := _receiver.String()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_URIWriteCloserClose(receiver any) any {
	_receiver := receiver.(v2.URIWriteCloser)
	return func() any {
		defer func() { recover() }()
		err := _receiver.Close()
		if err != nil { return SkyErr(err.Error()) }
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_URIWriteCloserURI(receiver any) any {
	_receiver := receiver.(v2.URIWriteCloser)
	return func() any {
		defer func() { recover() }()
		result := _receiver.URI()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_URIWriteCloserWrite(receiver any, arg0 any) any {
	_receiver := receiver.(v2.URIWriteCloser)
	_arg0 := sky_asBytes(arg0)
	return func() any {
		defer func() { recover() }()
		result, err := _receiver.Write(_arg0)
		if err != nil { return SkyErr(err.Error()) }
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_ValidatableValidate(receiver any) any {
	_receiver := receiver.(v2.Validatable)
	return func() any {
		defer func() { recover() }()
		err := _receiver.Validate()
		if err != nil { return SkyErr(err.Error()) }
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_Vector2Components(receiver any) any {
	_receiver := receiver.(v2.Vector2)
	return func() any {
		defer func() { recover() }()
		_r0, _r1 := _receiver.Components()
		return SkyOk(SkyTuple2{_r0, _r1})
	}()
}

func Sky_fyne_io_fyne_v2_Vector2IsZero(receiver any) any {
	_receiver := receiver.(v2.Vector2)
	return func() any {
		defer func() { recover() }()
		result := _receiver.IsZero()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_WidgetCreateRenderer(receiver any) any {
	_receiver := receiver.(v2.Widget)
	return func() any {
		defer func() { recover() }()
		result := _receiver.CreateRenderer()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_WidgetHide(receiver any) any {
	_receiver := receiver.(v2.Widget)
	return func() any {
		defer func() { recover() }()
		_receiver.Hide()
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_WidgetMinSize(receiver any) any {
	_receiver := receiver.(v2.Widget)
	return func() any {
		defer func() { recover() }()
		result := _receiver.MinSize()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_WidgetMove(receiver any, arg0 any) any {
	_receiver := receiver.(v2.Widget)
	_arg0 := arg0.(v2.Position)
	return func() any {
		defer func() { recover() }()
		_receiver.Move(_arg0)
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_WidgetPosition(receiver any) any {
	_receiver := receiver.(v2.Widget)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Position()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_WidgetRefresh(receiver any) any {
	_receiver := receiver.(v2.Widget)
	return func() any {
		defer func() { recover() }()
		_receiver.Refresh()
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_WidgetResize(receiver any, arg0 any) any {
	_receiver := receiver.(v2.Widget)
	_arg0 := arg0.(v2.Size)
	return func() any {
		defer func() { recover() }()
		_receiver.Resize(_arg0)
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_WidgetShow(receiver any) any {
	_receiver := receiver.(v2.Widget)
	return func() any {
		defer func() { recover() }()
		_receiver.Show()
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_WidgetSize(receiver any) any {
	_receiver := receiver.(v2.Widget)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Size()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_WidgetVisible(receiver any) any {
	_receiver := receiver.(v2.Widget)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Visible()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_WidgetRendererDestroy(receiver any) any {
	_receiver := receiver.(v2.WidgetRenderer)
	return func() any {
		defer func() { recover() }()
		_receiver.Destroy()
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_WidgetRendererLayout(receiver any, arg0 any) any {
	_receiver := receiver.(v2.WidgetRenderer)
	_arg0 := arg0.(v2.Size)
	return func() any {
		defer func() { recover() }()
		_receiver.Layout(_arg0)
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_WidgetRendererMinSize(receiver any) any {
	_receiver := receiver.(v2.WidgetRenderer)
	return func() any {
		defer func() { recover() }()
		result := _receiver.MinSize()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_WidgetRendererObjects(receiver any) any {
	_receiver := receiver.(v2.WidgetRenderer)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Objects()
		return SkyOk(result[:])
	}()
}

func Sky_fyne_io_fyne_v2_WidgetRendererRefresh(receiver any) any {
	_receiver := receiver.(v2.WidgetRenderer)
	return func() any {
		defer func() { recover() }()
		_receiver.Refresh()
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_WindowCanvas(receiver any) any {
	_receiver := receiver.(v2.Window)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Canvas()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_WindowCenterOnScreen(receiver any) any {
	_receiver := receiver.(v2.Window)
	return func() any {
		defer func() { recover() }()
		_receiver.CenterOnScreen()
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_WindowClipboard(receiver any) any {
	_receiver := receiver.(v2.Window)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Clipboard()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_WindowClose(receiver any) any {
	_receiver := receiver.(v2.Window)
	return func() any {
		defer func() { recover() }()
		_receiver.Close()
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_WindowContent(receiver any) any {
	_receiver := receiver.(v2.Window)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Content()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_WindowFixedSize(receiver any) any {
	_receiver := receiver.(v2.Window)
	return func() any {
		defer func() { recover() }()
		result := _receiver.FixedSize()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_WindowFullScreen(receiver any) any {
	_receiver := receiver.(v2.Window)
	return func() any {
		defer func() { recover() }()
		result := _receiver.FullScreen()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_WindowHide(receiver any) any {
	_receiver := receiver.(v2.Window)
	return func() any {
		defer func() { recover() }()
		_receiver.Hide()
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_WindowIcon(receiver any) any {
	_receiver := receiver.(v2.Window)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Icon()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_WindowMainMenu(receiver any) any {
	_receiver := receiver.(v2.Window)
	return func() any {
		defer func() { recover() }()
		result := _receiver.MainMenu()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_WindowPadded(receiver any) any {
	_receiver := receiver.(v2.Window)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Padded()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_WindowRequestFocus(receiver any) any {
	_receiver := receiver.(v2.Window)
	return func() any {
		defer func() { recover() }()
		_receiver.RequestFocus()
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_WindowResize(receiver any, arg0 any) any {
	_receiver := receiver.(v2.Window)
	_arg0 := arg0.(v2.Size)
	return func() any {
		defer func() { recover() }()
		_receiver.Resize(_arg0)
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_WindowSetContent(receiver any, arg0 any) any {
	_receiver := receiver.(v2.Window)
	_arg0 := arg0.(v2.CanvasObject)
	return func() any {
		defer func() { recover() }()
		_receiver.SetContent(_arg0)
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_WindowSetFixedSize(receiver any, arg0 any) any {
	_receiver := receiver.(v2.Window)
	_arg0 := sky_asBool(arg0)
	return func() any {
		defer func() { recover() }()
		_receiver.SetFixedSize(_arg0)
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_WindowSetFullScreen(receiver any, arg0 any) any {
	_receiver := receiver.(v2.Window)
	_arg0 := sky_asBool(arg0)
	return func() any {
		defer func() { recover() }()
		_receiver.SetFullScreen(_arg0)
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_WindowSetIcon(receiver any, arg0 any) any {
	_receiver := receiver.(v2.Window)
	_arg0 := arg0.(v2.Resource)
	return func() any {
		defer func() { recover() }()
		_receiver.SetIcon(_arg0)
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_WindowSetMainMenu(receiver any, arg0 any) any {
	_receiver := receiver.(v2.Window)
	_arg0 := arg0.(*v2.MainMenu)
	return func() any {
		defer func() { recover() }()
		_receiver.SetMainMenu(_arg0)
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_WindowSetMaster(receiver any) any {
	_receiver := receiver.(v2.Window)
	return func() any {
		defer func() { recover() }()
		_receiver.SetMaster()
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_WindowSetPadded(receiver any, arg0 any) any {
	_receiver := receiver.(v2.Window)
	_arg0 := sky_asBool(arg0)
	return func() any {
		defer func() { recover() }()
		_receiver.SetPadded(_arg0)
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_WindowSetTitle(receiver any, arg0 any) any {
	_receiver := receiver.(v2.Window)
	_arg0 := sky_asString(arg0)
	return func() any {
		defer func() { recover() }()
		_receiver.SetTitle(_arg0)
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_WindowShow(receiver any) any {
	_receiver := receiver.(v2.Window)
	return func() any {
		defer func() { recover() }()
		_receiver.Show()
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_WindowShowAndRun(receiver any) any {
	_receiver := receiver.(v2.Window)
	return func() any {
		defer func() { recover() }()
		_receiver.ShowAndRun()
		return SkyOk(struct{}{})
	}()
}

func Sky_fyne_io_fyne_v2_WindowTitle(receiver any) any {
	_receiver := receiver.(v2.Window)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Title()
		return SkyOk(result)
	}()
}

func Sky_fyne_io_fyne_v2_FIELD_Animation_AutoReverse(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr { v = v.Elem() }
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("AutoReverse")
		if f.IsValid() { return f.Interface() }
	}
	return nil
}

func Sky_fyne_io_fyne_v2_FIELD_Animation_Curve(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr { v = v.Elem() }
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("Curve")
		if f.IsValid() { return f.Interface() }
	}
	return nil
}

func Sky_fyne_io_fyne_v2_FIELD_Animation_Duration(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr { v = v.Elem() }
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("Duration")
		if f.IsValid() { return f.Interface() }
	}
	return nil
}

func Sky_fyne_io_fyne_v2_FIELD_Animation_RepeatCount(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr { v = v.Elem() }
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("RepeatCount")
		if f.IsValid() { return f.Interface() }
	}
	return nil
}

func Sky_fyne_io_fyne_v2_FIELD_Animation_Tick(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr { v = v.Elem() }
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("Tick")
		if f.IsValid() { return f.Interface() }
	}
	return nil
}

func Sky_fyne_io_fyne_v2_FIELD_AppMetadata_ID(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr { v = v.Elem() }
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("ID")
		if f.IsValid() { return f.Interface() }
	}
	return nil
}

func Sky_fyne_io_fyne_v2_FIELD_AppMetadata_Name(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr { v = v.Elem() }
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("Name")
		if f.IsValid() { return f.Interface() }
	}
	return nil
}

func Sky_fyne_io_fyne_v2_FIELD_AppMetadata_Version(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr { v = v.Elem() }
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("Version")
		if f.IsValid() { return f.Interface() }
	}
	return nil
}

func Sky_fyne_io_fyne_v2_FIELD_AppMetadata_Build(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr { v = v.Elem() }
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("Build")
		if f.IsValid() { return f.Interface() }
	}
	return nil
}

func Sky_fyne_io_fyne_v2_FIELD_AppMetadata_Icon(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr { v = v.Elem() }
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("Icon")
		if f.IsValid() { return f.Interface() }
	}
	return nil
}

func Sky_fyne_io_fyne_v2_FIELD_AppMetadata_Release(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr { v = v.Elem() }
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("Release")
		if f.IsValid() { return f.Interface() }
	}
	return nil
}

func Sky_fyne_io_fyne_v2_FIELD_AppMetadata_Custom(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr { v = v.Elem() }
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("Custom")
		if f.IsValid() { return f.Interface() }
	}
	return nil
}

func Sky_fyne_io_fyne_v2_FIELD_AppMetadata_Migrations(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr { v = v.Elem() }
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("Migrations")
		if f.IsValid() { return f.Interface() }
	}
	return nil
}

func Sky_fyne_io_fyne_v2_FIELD_Container_Hidden(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr { v = v.Elem() }
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("Hidden")
		if f.IsValid() { return f.Interface() }
	}
	return nil
}

func Sky_fyne_io_fyne_v2_FIELD_Container_Layout(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr { v = v.Elem() }
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("Layout")
		if f.IsValid() { return f.Interface() }
	}
	return nil
}

func Sky_fyne_io_fyne_v2_FIELD_Container_Objects(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr { v = v.Elem() }
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("Objects")
		if f.IsValid() { return f.Interface() }
	}
	return nil
}

func Sky_fyne_io_fyne_v2_FIELD_Delta_DX(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr { v = v.Elem() }
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("DX")
		if f.IsValid() { return f.Interface() }
	}
	return nil
}

func Sky_fyne_io_fyne_v2_FIELD_Delta_DY(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr { v = v.Elem() }
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("DY")
		if f.IsValid() { return f.Interface() }
	}
	return nil
}

func Sky_fyne_io_fyne_v2_FIELD_DragEvent_PointEvent(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr { v = v.Elem() }
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("PointEvent")
		if f.IsValid() { return f.Interface() }
	}
	return nil
}

func Sky_fyne_io_fyne_v2_FIELD_DragEvent_Dragged(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr { v = v.Elem() }
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("Dragged")
		if f.IsValid() { return f.Interface() }
	}
	return nil
}

func Sky_fyne_io_fyne_v2_FIELD_HardwareKey_ScanCode(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr { v = v.Elem() }
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("ScanCode")
		if f.IsValid() { return f.Interface() }
	}
	return nil
}

func Sky_fyne_io_fyne_v2_FIELD_KeyEvent_Name(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr { v = v.Elem() }
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("Name")
		if f.IsValid() { return f.Interface() }
	}
	return nil
}

func Sky_fyne_io_fyne_v2_FIELD_KeyEvent_Physical(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr { v = v.Elem() }
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("Physical")
		if f.IsValid() { return f.Interface() }
	}
	return nil
}

func Sky_fyne_io_fyne_v2_FIELD_MainMenu_Items(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr { v = v.Elem() }
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("Items")
		if f.IsValid() { return f.Interface() }
	}
	return nil
}

func Sky_fyne_io_fyne_v2_FIELD_Menu_Label(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr { v = v.Elem() }
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("Label")
		if f.IsValid() { return f.Interface() }
	}
	return nil
}

func Sky_fyne_io_fyne_v2_FIELD_Menu_Items(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr { v = v.Elem() }
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("Items")
		if f.IsValid() { return f.Interface() }
	}
	return nil
}

func Sky_fyne_io_fyne_v2_FIELD_MenuItem_ChildMenu(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr { v = v.Elem() }
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("ChildMenu")
		if f.IsValid() { return f.Interface() }
	}
	return nil
}

func Sky_fyne_io_fyne_v2_FIELD_MenuItem_IsQuit(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr { v = v.Elem() }
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("IsQuit")
		if f.IsValid() { return f.Interface() }
	}
	return nil
}

func Sky_fyne_io_fyne_v2_FIELD_MenuItem_IsSeparator(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr { v = v.Elem() }
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("IsSeparator")
		if f.IsValid() { return f.Interface() }
	}
	return nil
}

func Sky_fyne_io_fyne_v2_FIELD_MenuItem_Label(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr { v = v.Elem() }
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("Label")
		if f.IsValid() { return f.Interface() }
	}
	return nil
}

func Sky_fyne_io_fyne_v2_FIELD_MenuItem_Action(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr { v = v.Elem() }
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("Action")
		if f.IsValid() { return f.Interface() }
	}
	return nil
}

func Sky_fyne_io_fyne_v2_FIELD_MenuItem_Disabled(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr { v = v.Elem() }
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("Disabled")
		if f.IsValid() { return f.Interface() }
	}
	return nil
}

func Sky_fyne_io_fyne_v2_FIELD_MenuItem_Checked(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr { v = v.Elem() }
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("Checked")
		if f.IsValid() { return f.Interface() }
	}
	return nil
}

func Sky_fyne_io_fyne_v2_FIELD_MenuItem_Icon(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr { v = v.Elem() }
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("Icon")
		if f.IsValid() { return f.Interface() }
	}
	return nil
}

func Sky_fyne_io_fyne_v2_FIELD_MenuItem_Shortcut(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr { v = v.Elem() }
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("Shortcut")
		if f.IsValid() { return f.Interface() }
	}
	return nil
}

func Sky_fyne_io_fyne_v2_FIELD_Notification_Title(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr { v = v.Elem() }
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("Title")
		if f.IsValid() { return f.Interface() }
	}
	return nil
}

func Sky_fyne_io_fyne_v2_FIELD_Notification_Content(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr { v = v.Elem() }
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("Content")
		if f.IsValid() { return f.Interface() }
	}
	return nil
}

func Sky_fyne_io_fyne_v2_FIELD_PointEvent_AbsolutePosition(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr { v = v.Elem() }
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("AbsolutePosition")
		if f.IsValid() { return f.Interface() }
	}
	return nil
}

func Sky_fyne_io_fyne_v2_FIELD_PointEvent_Position(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr { v = v.Elem() }
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("Position")
		if f.IsValid() { return f.Interface() }
	}
	return nil
}

func Sky_fyne_io_fyne_v2_FIELD_Position_X(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr { v = v.Elem() }
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("X")
		if f.IsValid() { return f.Interface() }
	}
	return nil
}

func Sky_fyne_io_fyne_v2_FIELD_Position_Y(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr { v = v.Elem() }
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("Y")
		if f.IsValid() { return f.Interface() }
	}
	return nil
}

func Sky_fyne_io_fyne_v2_FIELD_ScrollEvent_PointEvent(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr { v = v.Elem() }
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("PointEvent")
		if f.IsValid() { return f.Interface() }
	}
	return nil
}

func Sky_fyne_io_fyne_v2_FIELD_ScrollEvent_Scrolled(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr { v = v.Elem() }
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("Scrolled")
		if f.IsValid() { return f.Interface() }
	}
	return nil
}

func Sky_fyne_io_fyne_v2_FIELD_ShortcutCopy_Clipboard(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr { v = v.Elem() }
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("Clipboard")
		if f.IsValid() { return f.Interface() }
	}
	return nil
}

func Sky_fyne_io_fyne_v2_FIELD_ShortcutCut_Clipboard(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr { v = v.Elem() }
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("Clipboard")
		if f.IsValid() { return f.Interface() }
	}
	return nil
}

func Sky_fyne_io_fyne_v2_FIELD_ShortcutPaste_Clipboard(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr { v = v.Elem() }
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("Clipboard")
		if f.IsValid() { return f.Interface() }
	}
	return nil
}

func Sky_fyne_io_fyne_v2_FIELD_Size_Width(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr { v = v.Elem() }
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("Width")
		if f.IsValid() { return f.Interface() }
	}
	return nil
}

func Sky_fyne_io_fyne_v2_FIELD_Size_Height(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr { v = v.Elem() }
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("Height")
		if f.IsValid() { return f.Interface() }
	}
	return nil
}

func Sky_fyne_io_fyne_v2_FIELD_StaticResource_StaticName(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr { v = v.Elem() }
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("StaticName")
		if f.IsValid() { return f.Interface() }
	}
	return nil
}

func Sky_fyne_io_fyne_v2_FIELD_StaticResource_StaticContent(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr { v = v.Elem() }
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("StaticContent")
		if f.IsValid() { return f.Interface() }
	}
	return nil
}

func Sky_fyne_io_fyne_v2_FIELD_TextStyle_Bold(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr { v = v.Elem() }
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("Bold")
		if f.IsValid() { return f.Interface() }
	}
	return nil
}

func Sky_fyne_io_fyne_v2_FIELD_TextStyle_Italic(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr { v = v.Elem() }
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("Italic")
		if f.IsValid() { return f.Interface() }
	}
	return nil
}

func Sky_fyne_io_fyne_v2_FIELD_TextStyle_Monospace(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr { v = v.Elem() }
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("Monospace")
		if f.IsValid() { return f.Interface() }
	}
	return nil
}

func Sky_fyne_io_fyne_v2_FIELD_TextStyle_Symbol(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr { v = v.Elem() }
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("Symbol")
		if f.IsValid() { return f.Interface() }
	}
	return nil
}

func Sky_fyne_io_fyne_v2_FIELD_TextStyle_TabWidth(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr { v = v.Elem() }
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("TabWidth")
		if f.IsValid() { return f.Interface() }
	}
	return nil
}

func Sky_fyne_io_fyne_v2_FIELD_TextStyle_Underline(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr { v = v.Elem() }
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("Underline")
		if f.IsValid() { return f.Interface() }
	}
	return nil
}

func Sky_fyne_io_fyne_v2_AnimationEaseIn(_ any) any {
	return v2.AnimationEaseIn
}

func Sky_fyne_io_fyne_v2_AnimationEaseInOut(_ any) any {
	return v2.AnimationEaseInOut
}

func Sky_fyne_io_fyne_v2_AnimationEaseOut(_ any) any {
	return v2.AnimationEaseOut
}

func Sky_fyne_io_fyne_v2_AnimationLinear(_ any) any {
	return v2.AnimationLinear
}

func Sky_fyne_io_fyne_v2_BuildDebug(_ any) any {
	return v2.BuildDebug
}

func Sky_fyne_io_fyne_v2_BuildRelease(_ any) any {
	return v2.BuildRelease
}

func Sky_fyne_io_fyne_v2_BuildStandard(_ any) any {
	return v2.BuildStandard
}

func Sky_fyne_io_fyne_v2_Key0(_ any) any {
	return v2.Key0
}

func Sky_fyne_io_fyne_v2_Key1(_ any) any {
	return v2.Key1
}

func Sky_fyne_io_fyne_v2_Key2(_ any) any {
	return v2.Key2
}

func Sky_fyne_io_fyne_v2_Key3(_ any) any {
	return v2.Key3
}

func Sky_fyne_io_fyne_v2_Key4(_ any) any {
	return v2.Key4
}

func Sky_fyne_io_fyne_v2_Key5(_ any) any {
	return v2.Key5
}

func Sky_fyne_io_fyne_v2_Key6(_ any) any {
	return v2.Key6
}

func Sky_fyne_io_fyne_v2_Key7(_ any) any {
	return v2.Key7
}

func Sky_fyne_io_fyne_v2_Key8(_ any) any {
	return v2.Key8
}

func Sky_fyne_io_fyne_v2_Key9(_ any) any {
	return v2.Key9
}

func Sky_fyne_io_fyne_v2_KeyA(_ any) any {
	return v2.KeyA
}

func Sky_fyne_io_fyne_v2_KeyApostrophe(_ any) any {
	return v2.KeyApostrophe
}

func Sky_fyne_io_fyne_v2_KeyAsterisk(_ any) any {
	return v2.KeyAsterisk
}

func Sky_fyne_io_fyne_v2_KeyB(_ any) any {
	return v2.KeyB
}

func Sky_fyne_io_fyne_v2_KeyBackTick(_ any) any {
	return v2.KeyBackTick
}

func Sky_fyne_io_fyne_v2_KeyBackslash(_ any) any {
	return v2.KeyBackslash
}

func Sky_fyne_io_fyne_v2_KeyBackspace(_ any) any {
	return v2.KeyBackspace
}

func Sky_fyne_io_fyne_v2_KeyC(_ any) any {
	return v2.KeyC
}

func Sky_fyne_io_fyne_v2_KeyComma(_ any) any {
	return v2.KeyComma
}

func Sky_fyne_io_fyne_v2_KeyD(_ any) any {
	return v2.KeyD
}

func Sky_fyne_io_fyne_v2_KeyDelete(_ any) any {
	return v2.KeyDelete
}

func Sky_fyne_io_fyne_v2_KeyDown(_ any) any {
	return v2.KeyDown
}

func Sky_fyne_io_fyne_v2_KeyE(_ any) any {
	return v2.KeyE
}

func Sky_fyne_io_fyne_v2_KeyEnd(_ any) any {
	return v2.KeyEnd
}

func Sky_fyne_io_fyne_v2_KeyEnter(_ any) any {
	return v2.KeyEnter
}

func Sky_fyne_io_fyne_v2_KeyEqual(_ any) any {
	return v2.KeyEqual
}

func Sky_fyne_io_fyne_v2_KeyEscape(_ any) any {
	return v2.KeyEscape
}

func Sky_fyne_io_fyne_v2_KeyF(_ any) any {
	return v2.KeyF
}

func Sky_fyne_io_fyne_v2_KeyF1(_ any) any {
	return v2.KeyF1
}

func Sky_fyne_io_fyne_v2_KeyF10(_ any) any {
	return v2.KeyF10
}

func Sky_fyne_io_fyne_v2_KeyF11(_ any) any {
	return v2.KeyF11
}

func Sky_fyne_io_fyne_v2_KeyF12(_ any) any {
	return v2.KeyF12
}

func Sky_fyne_io_fyne_v2_KeyF2(_ any) any {
	return v2.KeyF2
}

func Sky_fyne_io_fyne_v2_KeyF3(_ any) any {
	return v2.KeyF3
}

func Sky_fyne_io_fyne_v2_KeyF4(_ any) any {
	return v2.KeyF4
}

func Sky_fyne_io_fyne_v2_KeyF5(_ any) any {
	return v2.KeyF5
}

func Sky_fyne_io_fyne_v2_KeyF6(_ any) any {
	return v2.KeyF6
}

func Sky_fyne_io_fyne_v2_KeyF7(_ any) any {
	return v2.KeyF7
}

func Sky_fyne_io_fyne_v2_KeyF8(_ any) any {
	return v2.KeyF8
}

func Sky_fyne_io_fyne_v2_KeyF9(_ any) any {
	return v2.KeyF9
}

func Sky_fyne_io_fyne_v2_KeyG(_ any) any {
	return v2.KeyG
}

func Sky_fyne_io_fyne_v2_KeyH(_ any) any {
	return v2.KeyH
}

func Sky_fyne_io_fyne_v2_KeyHome(_ any) any {
	return v2.KeyHome
}

func Sky_fyne_io_fyne_v2_KeyI(_ any) any {
	return v2.KeyI
}

func Sky_fyne_io_fyne_v2_KeyInsert(_ any) any {
	return v2.KeyInsert
}

func Sky_fyne_io_fyne_v2_KeyJ(_ any) any {
	return v2.KeyJ
}

func Sky_fyne_io_fyne_v2_KeyK(_ any) any {
	return v2.KeyK
}

func Sky_fyne_io_fyne_v2_KeyL(_ any) any {
	return v2.KeyL
}

func Sky_fyne_io_fyne_v2_KeyLeft(_ any) any {
	return v2.KeyLeft
}

func Sky_fyne_io_fyne_v2_KeyLeftBracket(_ any) any {
	return v2.KeyLeftBracket
}

func Sky_fyne_io_fyne_v2_KeyM(_ any) any {
	return v2.KeyM
}

func Sky_fyne_io_fyne_v2_KeyMinus(_ any) any {
	return v2.KeyMinus
}

func Sky_fyne_io_fyne_v2_KeyModifierAlt(_ any) any {
	return v2.KeyModifierAlt
}

func Sky_fyne_io_fyne_v2_KeyModifierControl(_ any) any {
	return v2.KeyModifierControl
}

func Sky_fyne_io_fyne_v2_KeyModifierShift(_ any) any {
	return v2.KeyModifierShift
}

func Sky_fyne_io_fyne_v2_KeyModifierShortcutDefault(_ any) any {
	return v2.KeyModifierShortcutDefault
}

func Sky_fyne_io_fyne_v2_KeyModifierSuper(_ any) any {
	return v2.KeyModifierSuper
}

func Sky_fyne_io_fyne_v2_KeyN(_ any) any {
	return v2.KeyN
}

func Sky_fyne_io_fyne_v2_KeyO(_ any) any {
	return v2.KeyO
}

func Sky_fyne_io_fyne_v2_KeyP(_ any) any {
	return v2.KeyP
}

func Sky_fyne_io_fyne_v2_KeyPageDown(_ any) any {
	return v2.KeyPageDown
}

func Sky_fyne_io_fyne_v2_KeyPageUp(_ any) any {
	return v2.KeyPageUp
}

func Sky_fyne_io_fyne_v2_KeyPeriod(_ any) any {
	return v2.KeyPeriod
}

func Sky_fyne_io_fyne_v2_KeyPlus(_ any) any {
	return v2.KeyPlus
}

func Sky_fyne_io_fyne_v2_KeyQ(_ any) any {
	return v2.KeyQ
}

func Sky_fyne_io_fyne_v2_KeyR(_ any) any {
	return v2.KeyR
}

func Sky_fyne_io_fyne_v2_KeyReturn(_ any) any {
	return v2.KeyReturn
}

func Sky_fyne_io_fyne_v2_KeyRight(_ any) any {
	return v2.KeyRight
}

func Sky_fyne_io_fyne_v2_KeyRightBracket(_ any) any {
	return v2.KeyRightBracket
}

func Sky_fyne_io_fyne_v2_KeyS(_ any) any {
	return v2.KeyS
}

func Sky_fyne_io_fyne_v2_KeySemicolon(_ any) any {
	return v2.KeySemicolon
}

func Sky_fyne_io_fyne_v2_KeySlash(_ any) any {
	return v2.KeySlash
}

func Sky_fyne_io_fyne_v2_KeySpace(_ any) any {
	return v2.KeySpace
}

func Sky_fyne_io_fyne_v2_KeyT(_ any) any {
	return v2.KeyT
}

func Sky_fyne_io_fyne_v2_KeyTab(_ any) any {
	return v2.KeyTab
}

func Sky_fyne_io_fyne_v2_KeyU(_ any) any {
	return v2.KeyU
}

func Sky_fyne_io_fyne_v2_KeyUnknown(_ any) any {
	return v2.KeyUnknown
}

func Sky_fyne_io_fyne_v2_KeyUp(_ any) any {
	return v2.KeyUp
}

func Sky_fyne_io_fyne_v2_KeyV(_ any) any {
	return v2.KeyV
}

func Sky_fyne_io_fyne_v2_KeyW(_ any) any {
	return v2.KeyW
}

func Sky_fyne_io_fyne_v2_KeyX(_ any) any {
	return v2.KeyX
}

func Sky_fyne_io_fyne_v2_KeyY(_ any) any {
	return v2.KeyY
}

func Sky_fyne_io_fyne_v2_KeyZ(_ any) any {
	return v2.KeyZ
}

func Sky_fyne_io_fyne_v2_OrientationHorizontalLeft(_ any) any {
	return v2.OrientationHorizontalLeft
}

func Sky_fyne_io_fyne_v2_OrientationHorizontalRight(_ any) any {
	return v2.OrientationHorizontalRight
}

func Sky_fyne_io_fyne_v2_OrientationVertical(_ any) any {
	return v2.OrientationVertical
}

func Sky_fyne_io_fyne_v2_OrientationVerticalUpsideDown(_ any) any {
	return v2.OrientationVerticalUpsideDown
}

func Sky_fyne_io_fyne_v2_ScrollBoth(_ any) any {
	return v2.ScrollBoth
}

func Sky_fyne_io_fyne_v2_ScrollHorizontalOnly(_ any) any {
	return v2.ScrollHorizontalOnly
}

func Sky_fyne_io_fyne_v2_ScrollNone(_ any) any {
	return v2.ScrollNone
}

func Sky_fyne_io_fyne_v2_ScrollVerticalOnly(_ any) any {
	return v2.ScrollVerticalOnly
}

func Sky_fyne_io_fyne_v2_TextAlignCenter(_ any) any {
	return v2.TextAlignCenter
}

func Sky_fyne_io_fyne_v2_TextAlignLeading(_ any) any {
	return v2.TextAlignLeading
}

func Sky_fyne_io_fyne_v2_TextAlignTrailing(_ any) any {
	return v2.TextAlignTrailing
}

func Sky_fyne_io_fyne_v2_TextTruncate(_ any) any {
	return v2.TextTruncate
}

func Sky_fyne_io_fyne_v2_TextTruncateClip(_ any) any {
	return v2.TextTruncateClip
}

func Sky_fyne_io_fyne_v2_TextTruncateEllipsis(_ any) any {
	return v2.TextTruncateEllipsis
}

func Sky_fyne_io_fyne_v2_TextTruncateOff(_ any) any {
	return v2.TextTruncateOff
}

func Sky_fyne_io_fyne_v2_TextWrapBreak(_ any) any {
	return v2.TextWrapBreak
}

func Sky_fyne_io_fyne_v2_TextWrapOff(_ any) any {
	return v2.TextWrapOff
}

func Sky_fyne_io_fyne_v2_TextWrapWord(_ any) any {
	return v2.TextWrapWord
}