//! `sky add` / `install` / `remove` / `update` — the ONLY verbs that fetch deps
//! and run the Go FFI inspector (doc 09 §D). They are the FFI analogue of
//! `cargo add`: an explicit, out-of-band mutation of the manifest (`sky.toml`),
//! the resolved deps (`sky-out/go.mod` + `.skydeps/`), and the generated surface
//! (`sky-ffi/`), never part of `build` (which is read-only). The inspector is
//! pinned to `linux/amd64` and its output normalised, so the same declared
//! versions regenerate the same surface.
//!
//! The generated surface is a gitignored build ARTIFACT — regenerated by
//! `sky install`, not committed (see doc 09 §C.1):
//! ```text
//! <project>/sky-ffi/<slug>.kernel.json     # machine surface (compiler reads)
//! <project>/sky-ffi/<slug>.skyi            # human catalogue (sky doc / review)
//! <project>/sky-ffi/go/<slug>_bindings.go  # the `package rt` Go wrapper
//! <project>/.skydeps/<slug>/src/           # fetched Sky-source dependencies
//! ```

use std::path::{Path, PathBuf};
use std::process::Command;

/// Structured outcome of an FFI verb — human-facing lines + a hard-fail flag.
pub struct FfiReport {
    pub lines: Vec<String>,
    pub ok: bool,
}

impl FfiReport {
    fn new() -> Self {
        FfiReport {
            lines: Vec::new(),
            ok: true,
        }
    }
    fn say(&mut self, m: impl Into<String>) {
        self.lines.push(m.into());
    }
    fn fail(mut self, m: impl Into<String>) -> Self {
        self.lines.push(m.into());
        self.ok = false;
        self
    }
}

// ---------------------------------------------------------------------------
// sky add
// ---------------------------------------------------------------------------

/// `sky add <import-path>` — resolve+pin the Go dep, inspect it (pinned target),
/// emit the canonical surface, commit it under `sky-ffi/`, and record the dep in
/// `sky.toml`.
pub fn add(project_dir: &Path, repo_root: &Path, pkg: &str, spec: Option<&str>) -> FfiReport {
    let mut r = FfiReport::new();
    // `explicit_spec` = what the user typed after `@` (None if they gave just the
    // path). `resolve_spec` is what `go get` fetches against.
    let explicit_spec = spec;
    let resolve_spec = spec_or_latest(explicit_spec.unwrap_or("latest"));
    if let Err(e) = validate_spec(pkg, resolve_spec) {
        return r.fail(format!("sky add: {e}"));
    }
    let sky_out = project_dir.join("sky-out");
    if let Err(e) = ensure_go_mod(repo_root, &sky_out) {
        return r.fail(format!("sky add: {e}"));
    }

    // External modules resolve at `path@<spec>`; stdlib paths (`net/http`) carry
    // no module version, so `go get` sees the bare path (a no-op download).
    let target = if is_external_module(pkg) {
        format!("{pkg}@{resolve_spec}")
    } else {
        pkg.to_string()
    };
    r.say(format!("Resolving {target} (go get)…"));
    if let Err(e) = go_get(&sky_out, &[target]) {
        // Non-fatal: some paths (stdlib) need no download; surface as a note.
        r.say(format!("  note: go get: {e}"));
    }

    // Stdlib packages (`net/http`, `io`) carry no external module + their surface
    // is part of the runtime baseline; the oracle still inspects them, so do too,
    // but skip the go.mod require dance (go get is a no-op for stdlib).
    let bin = match ffi::ensure_inspector(repo_root) {
        Ok(b) => b,
        Err(e) => return r.fail(format!("sky add: {e}")),
    };

    r.say(format!(
        "Inspecting {pkg} (GOOS={}/{}, normalised)…",
        ffi::inspect::PIN_GOOS,
        ffi::inspect::PIN_GOARCH
    ));
    let info = match ffi::run_inspector(&bin, &sky_out, &[pkg.to_string()]) {
        Ok(mut v) if !v.is_empty() => v.remove(0),
        Ok(_) => return r.fail(format!("sky add: inspector returned no package for {pkg}")),
        Err(e) => return r.fail(format!("sky add: {e}")),
    };

    match write_surface(project_dir, &info) {
        Ok(slug) => r.say(format!(
            "  wrote sky-ffi/{slug}.{{kernel.json,skyi}} + go/{slug}_bindings.go"
        )),
        Err(e) => return r.fail(format!("sky add: {e}")),
    }

    // Pin-by-default: when the user gave no explicit version, record the EXACT
    // version `go get` just resolved (reproducible builds out of the box). An
    // explicit spec — including a deliberate `"latest"` or a branch — is written
    // verbatim so an intentional float stays a float.
    let write_spec: String = match explicit_spec {
        Some(s) => s.to_string(),
        None if is_external_module(pkg) => {
            resolved_module_version(&sky_out, pkg).unwrap_or_else(|| "latest".to_string())
        }
        None => "latest".to_string(),
    };

    // Upsert: re-adding a dep (or `sky add pkg@newversion`) updates the recorded
    // spec — the most recent `sky add` wins — so sky.toml never disagrees with the
    // surface we just regenerated.
    match upsert_go_dependency(&project_dir.join("sky.toml"), pkg, &write_spec) {
        Ok(DepEdit::Added) => r.say(format!(
            "  recorded {pkg} = \"{write_spec}\" in sky.toml [\"go.dependencies\"]"
        )),
        Ok(DepEdit::Updated(old)) => r.say(format!(
            "  updated {pkg} in sky.toml: \"{old}\" → \"{write_spec}\""
        )),
        Ok(DepEdit::Unchanged) => r.say(format!("  {pkg} already at \"{write_spec}\"")),
        Err(e) => r.say(format!("  warn: sky.toml update: {e}")),
    }
    r.say(format!("Added {pkg}."));
    r
}

// ---------------------------------------------------------------------------
// sky remove
// ---------------------------------------------------------------------------

/// `sky remove <pkg>` — drop the committed surface files, remove the dep from
/// `go.mod` (`go mod edit -droprequire` + `go mod tidy`) and `sky.toml`.
pub fn remove(project_dir: &Path, pkg: &str) -> FfiReport {
    let mut r = FfiReport::new();
    // Locate the committed surface whose "package" == pkg → delete its files.
    if let Some(slug) = slug_for_package(project_dir, pkg) {
        for rel in [
            format!("sky-ffi/{slug}.kernel.json"),
            format!("sky-ffi/{slug}.skyi"),
            format!("sky-ffi/go/{slug}_bindings.go"),
        ] {
            let p = project_dir.join(&rel);
            if p.exists() && std::fs::remove_file(&p).is_ok() {
                r.say(format!("  removed {rel}"));
            }
        }
    } else {
        r.say(format!(
            "  no committed surface found for {pkg} (nothing to delete)"
        ));
    }

    let sky_out = project_dir.join("sky-out");
    if sky_out.join("go.mod").is_file() {
        let _ = run_go(&sky_out, &["mod", "edit", "-droprequire", pkg]);
        let _ = run_go(&sky_out, &["mod", "tidy"]);
        r.say(format!("  dropped {pkg} from sky-out/go.mod"));
    }

    match remove_go_dependency(&project_dir.join("sky.toml"), pkg) {
        Ok(true) => r.say(format!("  removed {pkg} from sky.toml")),
        Ok(false) => {}
        Err(e) => r.say(format!("  warn: sky.toml update: {e}")),
    }
    r.say(format!("Removed {pkg}."));
    r
}

// ---------------------------------------------------------------------------
// sky add --sky / sky remove --sky  (Sky external packages)
// ---------------------------------------------------------------------------

/// `sky add --sky <path>[@ref]` — git-clone a Sky-source package into
/// `.skydeps/<slug>/`, then pin-by-default record it under `[dependencies]`:
/// an explicit `@ref` is written verbatim (including `"latest"`); no ref → the
/// resolved concrete ref (a tag or SHA) is written for reproducible builds.
pub fn add_sky(project_dir: &Path, pkg: &str, spec: Option<&str>) -> FfiReport {
    let mut r = FfiReport::new();
    let explicit_spec = spec;
    let resolve_spec = spec_or_latest(explicit_spec.unwrap_or("latest"));
    if let Err(e) = validate_spec(pkg, resolve_spec) {
        return r.fail(format!("sky add --sky: {e}"));
    }
    let skydeps = project_dir.join(".skydeps");
    r.say(format!(
        "Fetching Sky package {pkg} ({resolve_spec}) via git…"
    ));
    let resolved = match fetch_sky_dep(&skydeps, pkg, resolve_spec) {
        Ok(re) => {
            let slug = pkg.replace('/', "_");
            r.say(format!("  cloned into .skydeps/{slug}/ (resolved {re})"));
            re
        }
        Err(e) => return r.fail(format!("sky add --sky: {e}")),
    };
    // Pin-by-default: explicit ref → verbatim; none → the resolved concrete ref.
    let write_spec: String = match explicit_spec {
        Some(s) => s.to_string(),
        None => resolved,
    };
    match upsert_sky_dependency(&project_dir.join("sky.toml"), pkg, &write_spec) {
        Ok(DepEdit::Added) => r.say(format!(
            "  recorded {pkg} = \"{write_spec}\" in sky.toml [dependencies]"
        )),
        Ok(DepEdit::Updated(old)) => r.say(format!(
            "  updated {pkg} in sky.toml: \"{old}\" → \"{write_spec}\""
        )),
        Ok(DepEdit::Unchanged) => r.say(format!("  {pkg} already at \"{write_spec}\"")),
        Err(e) => r.say(format!("  warn: sky.toml update: {e}")),
    }
    r.say(format!("Added Sky package {pkg}."));
    r
}

/// `sky remove --sky <path>` — drop the `[dependencies]` entry and the fetched
/// `.skydeps/<slug>/` tree.
pub fn remove_sky(project_dir: &Path, pkg: &str) -> FfiReport {
    let mut r = FfiReport::new();
    let slug = pkg.replace('/', "_");
    let dir = project_dir.join(".skydeps").join(&slug);
    if dir.exists() {
        match std::fs::remove_dir_all(&dir) {
            Ok(()) => r.say(format!("  removed .skydeps/{slug}/")),
            Err(e) => r.say(format!("  warn: could not remove .skydeps/{slug}/: {e}")),
        }
    } else {
        r.say(format!("  no .skydeps/{slug}/ to delete"));
    }
    match remove_sky_dependency(&project_dir.join("sky.toml"), pkg) {
        Ok(true) => r.say(format!("  removed {pkg} from sky.toml [dependencies]")),
        Ok(false) => {}
        Err(e) => r.say(format!("  warn: sky.toml update: {e}")),
    }
    r.say(format!("Removed Sky package {pkg}."));
    r
}

// ---------------------------------------------------------------------------
// sky install  (the fresh-clone / CI entry point)
// ---------------------------------------------------------------------------

/// `sky install` — ensure `go.mod` deps are present and regenerate any committed
/// surface that is ABSENT; for present surfaces, verify they match a fresh
/// inspection and report drift (doc 09 §D.2). Does not overwrite a present,
/// matching surface.
pub fn install(project_dir: &Path, repo_root: &Path) -> FfiReport {
    let mut r = FfiReport::new();
    let sky_toml = project_dir.join("sky.toml");
    let deps = read_go_dependencies(&sky_toml);
    let sky_deps = read_sky_dependencies(&sky_toml);
    if deps.is_empty() && sky_deps.is_empty() {
        r.say(
            "sky install: no [\"go.dependencies\"] or [dependencies] in sky.toml — nothing to do.",
        );
        return r;
    }
    if !deps.is_empty() {
        install_go_deps(project_dir, repo_root, &deps, &mut r);
    }
    if !sky_deps.is_empty() {
        install_sky_deps(project_dir, &sky_deps, &mut r);
    }
    r
}

/// The Go-FFI half of `sky install` — ensure `go.mod` deps, then regenerate any
/// ABSENT committed surface + verify present ones for drift (doc 09 §D.2).
fn install_go_deps(
    project_dir: &Path,
    repo_root: &Path,
    deps: &[(String, String)],
    r: &mut FfiReport,
) {
    // Reject unresolvable specs up front — a bad constraint must not silently
    // fall through to `@latest`.
    for (path, spec) in deps {
        if let Err(e) = validate_spec(path, spec) {
            r.ok = false;
            r.say(format!("sky install: {e}"));
            return;
        }
    }
    let sky_out = project_dir.join("sky-out");
    if let Err(e) = ensure_go_mod(repo_root, &sky_out) {
        r.ok = false;
        r.say(format!("sky install: {e}"));
        return;
    }
    // Ensure every declared external dep is pinned in go.mod at its declared spec
    // (`path@<spec>`). An EXACT pin is forced even when the inherited runtime
    // go.mod already `require`s a different version — the sky.toml pin must win
    // (and `go get path@vX.Y.Z` is idempotent when already matching). A
    // `latest`/branch spec is fetched only when missing (so it doesn't re-float
    // on every CI install).
    let to_fetch: Vec<String> = deps
        .iter()
        .filter(|(path, spec)| {
            is_external_module(path) && (is_exact_pin(spec) || !module_required(&sky_out, path))
        })
        .map(|(path, spec)| format!("{path}@{}", spec_or_latest(spec)))
        .collect();
    if !to_fetch.is_empty() {
        r.say(format!("Fetching {} module(s)…", to_fetch.len()));
        if let Err(e) = go_get(&sky_out, &to_fetch) {
            r.say(format!("  note: go get: {e}"));
        }
    }

    let bin = match ffi::ensure_inspector(repo_root) {
        Ok(b) => b,
        Err(e) => {
            r.ok = false;
            r.say(format!("sky install: {e}"));
            return;
        }
    };

    let mut regenerated = 0usize;
    let mut verified = 0usize;
    let mut drifted = 0usize;
    for (dep, _spec) in deps {
        let present = slug_for_package(project_dir, dep).is_some();
        if present {
            // Verify: re-inspect + regenerate in-memory, compare to committed.
            match regenerate_in_memory(&bin, &sky_out, dep) {
                Ok(surface) => {
                    let committed = project_dir
                        .join("sky-ffi")
                        .join(format!("{}.kernel.json", surface.slug));
                    match std::fs::read_to_string(&committed) {
                        Ok(on_disk) if on_disk == surface.kernel_json => verified += 1,
                        Ok(_) => {
                            drifted += 1;
                            r.say(format!(
                                "  DRIFT: committed sky-ffi/{}.kernel.json differs from a fresh inspection of {dep} (run `sky update`)",
                                surface.slug
                            ));
                        }
                        Err(_) => verified += 1,
                    }
                }
                Err(e) => r.say(format!("  note: could not verify {dep}: {e}")),
            }
        } else {
            match regenerate_committed(&bin, &sky_out, project_dir, dep) {
                Ok(slug) => {
                    regenerated += 1;
                    r.say(format!("  generated missing surface sky-ffi/{slug}.*"));
                }
                Err(e) => r.say(format!("  note: could not generate {dep}: {e}")),
            }
        }
    }
    r.say(format!(
        "sky install: {verified} verified, {regenerated} generated, {drifted} drifted ({} deps).",
        deps.len()
    ));
    if drifted > 0 {
        r.ok = false;
    }
}

/// The Sky-package half of `sky install` — for each `[dependencies]` entry, fetch
/// into `.skydeps/<slug>/` when it is absent, floating (`latest`/branch), or an
/// exact pin whose on-disk ref no longer matches; otherwise leave it. Reports
/// `N fetched / M present`.
fn install_sky_deps(project_dir: &Path, sky_deps: &[(String, String)], r: &mut FfiReport) {
    for (path, spec) in sky_deps {
        if let Err(e) = validate_spec(path, spec) {
            r.ok = false;
            r.say(format!("sky install: {e}"));
            return;
        }
    }
    let skydeps = project_dir.join(".skydeps");
    let mut fetched = 0usize;
    let mut present = 0usize;
    for (path, spec) in sky_deps {
        let slug = path.replace('/', "_");
        let dir = skydeps.join(&slug);
        let need = if !dir.is_dir() {
            true // never fetched
        } else if !is_exact_pin(spec) {
            true // floating (latest/branch) — track the moving target
        } else {
            // Exact pin: fetch only when the on-disk ref drifted from the spec.
            on_disk_ref(&dir)
                .map(|cur| !ref_satisfies(&cur, spec_or_latest(spec)))
                .unwrap_or(true)
        };
        if need {
            match fetch_sky_dep(&skydeps, path, spec) {
                Ok(resolved) => {
                    fetched += 1;
                    r.say(format!("  fetched {path} ({resolved})"));
                }
                Err(e) => {
                    r.ok = false;
                    r.say(format!("  ERROR fetching {path}: {e}"));
                }
            }
        } else {
            present += 1;
        }
    }
    r.say(format!(
        "sky install (sky deps): {fetched} fetched, {present} present ({} deps).",
        sky_deps.len()
    ));
}

// ---------------------------------------------------------------------------
// sky update
// ---------------------------------------------------------------------------

/// `sky update` — bump dep versions (`go get -u ./... && go mod tidy`), then
/// re-inspect + re-commit every declared surface so the version bump shows up as
/// a reviewable diff in the committed `kernel.json`.
pub fn update(project_dir: &Path, repo_root: &Path) -> FfiReport {
    let mut r = FfiReport::new();
    let sky_toml = project_dir.join("sky.toml");
    let deps = read_go_dependencies(&sky_toml);
    let sky_deps = read_sky_dependencies(&sky_toml);
    if deps.is_empty() && sky_deps.is_empty() {
        r.say("sky update: no declared surfaces to regenerate.");
        return r;
    }
    if !deps.is_empty() {
        if let Err(msg) = update_go_deps(project_dir, repo_root, &deps, &mut r) {
            return r.fail(msg);
        }
    }
    if !sky_deps.is_empty() {
        update_sky_deps(project_dir, &sky_deps, &mut r);
    }
    r
}

/// The Go-FFI half of `sky update`. Returns `Err` on a hard failure (no go.mod /
/// bad spec / inspector missing) so the caller can `r.fail` it.
fn update_go_deps(
    project_dir: &Path,
    repo_root: &Path,
    deps: &[(String, String)],
    r: &mut FfiReport,
) -> Result<(), String> {
    let sky_out = project_dir.join("sky-out");
    if !sky_out.join("go.mod").is_file() {
        return Err(
            "sky update: no sky-out/go.mod — run `sky build` or `sky install` first.".to_string(),
        );
    }
    for (path, spec) in deps {
        if let Err(e) = validate_spec(path, spec) {
            return Err(format!("sky update: {e}"));
        }
    }
    // Per-dep: `latest` / branch re-floats (`go get -u <path>`); an exact
    // `vX.Y.Z` / commit SHA is a deliberate pin and is left untouched.
    r.say("Updating Go deps (exact pins skipped)…");
    for (path, spec) in deps {
        if !is_external_module(path) {
            continue; // stdlib — no module version to bump.
        }
        if is_exact_pin(spec) {
            r.say(format!("  {path}: pinned at {spec}, skipped"));
        } else {
            let _ = run_go(&sky_out, &["get", "-u", path]);
            r.say(format!("  {path}: re-floated ({spec})"));
        }
    }
    let _ = run_go(&sky_out, &["mod", "tidy"]);

    let bin = ffi::ensure_inspector(repo_root).map_err(|e| format!("sky update: {e}"))?;
    let mut n = 0usize;
    for (dep, _spec) in deps {
        match regenerate_committed(&bin, &sky_out, project_dir, dep) {
            Ok(slug) => {
                n += 1;
                r.say(format!("  regenerated sky-ffi/{slug}.*"));
            }
            Err(e) => r.say(format!("  note: {dep}: {e}")),
        }
    }
    r.say(format!("sky update: regenerated {n} surface(s)."));
    Ok(())
}

/// The Sky-package half of `sky update` — re-float each floating `[dependencies]`
/// entry to its tracked HEAD; an exact pin is left untouched. A branch re-floats
/// via `git fetch --depth 1 origin <branch>` + `reset --hard FETCH_HEAD`; `latest`
/// (and any fetch/reset failure) falls back to a clean re-clone.
fn update_sky_deps(project_dir: &Path, sky_deps: &[(String, String)], r: &mut FfiReport) {
    r.say("Updating Sky deps (exact pins skipped)…");
    let skydeps = project_dir.join(".skydeps");
    for (path, spec) in sky_deps {
        if let Err(e) = validate_spec(path, spec) {
            r.ok = false;
            r.say(format!("  {path}: {e}"));
            continue;
        }
        if is_exact_pin(spec) {
            r.say(format!("  {path}: pinned at {spec}, skipped"));
            continue;
        }
        let slug = path.replace('/', "_");
        let dir = skydeps.join(&slug);
        // Branch: fetch + hard-reset to the branch HEAD in place. `latest` has no
        // named ref to fetch, so it (and any failure) falls through to re-clone.
        let refloated = spec_or_latest(spec) != "latest"
            && dir.join(".git").is_dir()
            && run_git(&dir, &["fetch", "--depth", "1", "origin", spec]).is_ok()
            && run_git(&dir, &["reset", "--hard", "FETCH_HEAD"]).is_ok();
        if refloated {
            r.say(format!("  {path}: re-floated ({spec})"));
        } else {
            match fetch_sky_dep(&skydeps, path, spec) {
                Ok(resolved) => r.say(format!("  {path}: re-cloned ({resolved})")),
                Err(e) => {
                    r.ok = false;
                    r.say(format!("  {path}: {e}"));
                }
            }
        }
    }
}

// ---------------------------------------------------------------------------
// shared helpers
// ---------------------------------------------------------------------------

/// Inspect `pkg` and return its generated surface (no disk write).
fn regenerate_in_memory(
    bin: &Path,
    sky_out: &Path,
    pkg: &str,
) -> Result<ffi::GeneratedSurface, String> {
    let info = match ffi::run_inspector(bin, sky_out, &[pkg.to_string()]) {
        Ok(mut v) if !v.is_empty() => v.remove(0),
        Ok(_) => return Err(format!("inspector returned no package for {pkg}")),
        Err(e) => return Err(e),
    };
    Ok(ffi::generate(&info))
}

/// Inspect `pkg` and commit its surface files; returns the slug.
fn regenerate_committed(
    bin: &Path,
    sky_out: &Path,
    project_dir: &Path,
    pkg: &str,
) -> Result<String, String> {
    let info = match ffi::run_inspector(bin, sky_out, &[pkg.to_string()]) {
        Ok(mut v) if !v.is_empty() => v.remove(0),
        Ok(_) => return Err(format!("inspector returned no package for {pkg}")),
        Err(e) => return Err(e),
    };
    write_surface(project_dir, &info)
}

/// Write the three committed surface files for one inspected package. Returns
/// the slug. `info` is already normalised by `run_inspector`.
fn write_surface(project_dir: &Path, info: &ffi::PackageInfo) -> Result<String, String> {
    let surface = ffi::generate(info);
    let ffi_dir = project_dir.join("sky-ffi");
    let go_dir = ffi_dir.join("go");
    std::fs::create_dir_all(&go_dir).map_err(|e| format!("mkdir sky-ffi/go: {e}"))?;
    let slug = &surface.slug;
    std::fs::write(
        ffi_dir.join(format!("{slug}.kernel.json")),
        &surface.kernel_json,
    )
    .map_err(|e| format!("write {slug}.kernel.json: {e}"))?;
    std::fs::write(ffi_dir.join(format!("{slug}.skyi")), &surface.skyi)
        .map_err(|e| format!("write {slug}.skyi: {e}"))?;
    std::fs::write(
        go_dir.join(format!("{slug}_bindings.go")),
        &surface.bindings_go,
    )
    .map_err(|e| format!("write {slug}_bindings.go: {e}"))?;
    Ok(slug.clone())
}

/// Find the slug of a committed surface whose `kernel.json` `"package"` == `pkg`.
fn slug_for_package(project_dir: &Path, pkg: &str) -> Option<String> {
    let ffi_dir = project_dir.join("sky-ffi");
    let rd = std::fs::read_dir(&ffi_dir).ok()?;
    let mut entries: Vec<PathBuf> = rd.filter_map(|e| e.ok().map(|e| e.path())).collect();
    entries.sort();
    let needle = format!("\"package\": \"{pkg}\"");
    for p in entries {
        let is_kj = p
            .file_name()
            .and_then(|n| n.to_str())
            .is_some_and(|n| n.ends_with(".kernel.json"));
        if !is_kj {
            continue;
        }
        if let Ok(text) = std::fs::read_to_string(&p) {
            if text.contains(&needle) {
                let fname = p.file_name().and_then(|n| n.to_str()).unwrap_or("");
                return fname.strip_suffix(".kernel.json").map(str::to_string);
            }
        }
    }
    None
}

/// Ensure `sky-out/go.mod` exists — copy the runtime module's go.mod (+ go.sum)
/// as the baseline (module `sky-app`), mirroring the oracle.
fn ensure_go_mod(repo_root: &Path, sky_out: &Path) -> Result<(), String> {
    std::fs::create_dir_all(sky_out).map_err(|e| format!("mkdir sky-out: {e}"))?;
    let go_mod = sky_out.join("go.mod");
    if go_mod.is_file() {
        return Ok(());
    }
    let rt = repo_root.join("runtime-go");
    if rt.join("go.mod").is_file() {
        std::fs::copy(rt.join("go.mod"), &go_mod).map_err(|e| format!("copy go.mod: {e}"))?;
        if rt.join("go.sum").is_file() {
            let _ = std::fs::copy(rt.join("go.sum"), sky_out.join("go.sum"));
        }
    } else {
        std::fs::write(&go_mod, "module sky-app\n\ngo 1.25.0\n")
            .map_err(|e| format!("write go.mod stub: {e}"))?;
    }
    Ok(())
}

fn go_get(sky_out: &Path, pkgs: &[String]) -> Result<(), String> {
    let mut args = vec!["get".to_string()];
    args.extend(pkgs.iter().cloned());
    run_go(
        sky_out,
        &args.iter().map(String::as_str).collect::<Vec<_>>(),
    )
}

fn run_go(dir: &Path, args: &[&str]) -> Result<(), String> {
    let out = Command::new("go")
        .args(args)
        .current_dir(dir)
        .env("GOFLAGS", "-mod=mod")
        .output()
        .map_err(|e| format!("spawn go {}: {e}", args.join(" ")))?;
    if out.status.success() {
        Ok(())
    } else {
        Err(format!(
            "go {} failed: {}",
            args.join(" "),
            String::from_utf8_lossy(&out.stderr).trim()
        ))
    }
}

/// Run `git <args>` in `dir`, inheriting the ambient environment so the user's
/// git credential helper handles private repos. Errors carry git's stderr.
fn run_git(dir: &Path, args: &[&str]) -> Result<(), String> {
    let out = Command::new("git")
        .args(args)
        .current_dir(dir)
        .output()
        .map_err(|e| format!("spawn git {}: {e}", args.join(" ")))?;
    if out.status.success() {
        Ok(())
    } else {
        Err(format!(
            "git {} failed: {}",
            args.join(" "),
            String::from_utf8_lossy(&out.stderr).trim()
        ))
    }
}

/// Like [`run_git`] but returns captured stdout (trimmed by the caller).
fn git_output(dir: &Path, args: &[&str]) -> Result<String, String> {
    let out = Command::new("git")
        .args(args)
        .current_dir(dir)
        .output()
        .map_err(|e| format!("spawn git {}: {e}", args.join(" ")))?;
    if out.status.success() {
        Ok(String::from_utf8_lossy(&out.stdout).to_string())
    } else {
        Err(format!(
            "git {} failed: {}",
            args.join(" "),
            String::from_utf8_lossy(&out.stderr).trim()
        ))
    }
}

fn is_external_module(path: &str) -> bool {
    path.split('/')
        .next()
        .is_some_and(|head| head.contains('.'))
}

/// Whether a spec is a commit SHA (as opposed to an exact `vX.Y.Z` tag or a
/// branch name). A `v<digit>…` prefix is a semver tag (never a SHA); otherwise a
/// 7..=40-char all-hex token containing a digit is treated as a SHA. Used by
/// [`fetch_sky_dep`] to pick the clone strategy — `git clone --branch` rejects a
/// SHA and a shallow clone won't contain an arbitrary commit, so a SHA needs a
/// full clone + `checkout`.
fn is_commit_sha(spec: &str) -> bool {
    let s = spec_or_latest(spec);
    if let Some(rest) = s.strip_prefix('v') {
        if rest.chars().next().is_some_and(|c| c.is_ascii_digit()) {
            return false; // semver tag, not a SHA
        }
    }
    (7..=40).contains(&s.len())
        && s.chars().all(|c| c.is_ascii_hexdigit())
        && s.contains(|c: char| c.is_ascii_digit())
}

/// The concrete ref a fetched `.skydeps/<slug>` tree currently sits on — an exact
/// tag if the checkout is on one, else the HEAD commit SHA. `None` when the tree
/// isn't a readable git repo.
fn on_disk_ref(dir: &Path) -> Option<String> {
    git_output(dir, &["describe", "--tags", "--exact-match"])
        .ok()
        .map(|s| s.trim().to_string())
        .filter(|s| !s.is_empty())
        .or_else(|| {
            git_output(dir, &["rev-parse", "HEAD"])
                .ok()
                .map(|s| s.trim().to_string())
        })
}

/// Whether an on-disk ref satisfies a declared exact-pin spec — equal, or one a
/// prefix of the other (short-vs-full SHA).
fn ref_satisfies(on_disk: &str, spec: &str) -> bool {
    on_disk == spec || on_disk.starts_with(spec) || spec.starts_with(on_disk)
}

/// Fetch a Sky-source package dependency into `<skydeps_dir>/<slug>/` via `git`,
/// where slug = `path` with `/` → `_` (matches the on-disk layout, e.g.
/// `github.com_anzellai_sky-tailwind`). Clone URL is `https://<path>`. Fetches by
/// spec kind (Go-native grammar): an exact `vX.Y.Z` tag or a branch clone shallow
/// with `--branch`; `latest` clones the default-branch HEAD shallow; a commit SHA
/// needs a FULL clone (no `--depth 1`) then `git checkout <sha>` since `--branch`
/// rejects a SHA and a shallow tree won't hold an arbitrary commit. After the
/// clone, verifies a top-level `src/` exists (else removes the tree and errors —
/// not a Sky package). Returns the resolved concrete ref (exact tag if the
/// checkout lands on one, else the HEAD SHA) for pin-by-default recording. Keeps
/// `.git` so `sky update` can re-fetch; `.skydeps/` is gitignored.
fn fetch_sky_dep(skydeps_dir: &Path, path: &str, spec: &str) -> Result<String, String> {
    let spec = spec_or_latest(spec);
    let slug = path.replace('/', "_");
    let dest = skydeps_dir.join(&slug);
    let url = format!("https://{path}");
    // Remove any stale tree first so a re-fetch is deterministic.
    if dest.exists() {
        std::fs::remove_dir_all(&dest).map_err(|e| format!("rm .skydeps/{slug}: {e}"))?;
    }
    std::fs::create_dir_all(skydeps_dir).map_err(|e| format!("mkdir .skydeps: {e}"))?;
    let dest_s = dest.to_string_lossy().to_string();

    if is_commit_sha(spec) {
        run_git(skydeps_dir, &["clone", &url, &dest_s])?;
        run_git(&dest, &["checkout", spec])?;
    } else if spec == "latest" {
        run_git(skydeps_dir, &["clone", "--depth", "1", &url, &dest_s])?;
    } else {
        // exact tag OR branch — both accepted by `--branch`.
        run_git(
            skydeps_dir,
            &["clone", "--depth", "1", "--branch", spec, &url, &dest_s],
        )?;
    }

    // Must be a Sky package: a top-level `src/` the build loads modules from.
    if !dest.join("src").is_dir() {
        let _ = std::fs::remove_dir_all(&dest);
        return Err(format!("{path} is not a Sky package (no top-level src/)"));
    }

    Ok(on_disk_ref(&dest).unwrap_or_else(|| spec.to_string()))
}

fn module_required(sky_out: &Path, path: &str) -> bool {
    let Ok(text) = std::fs::read_to_string(sky_out.join("go.mod")) else {
        return false;
    };
    text.lines()
        .any(|l| l.split_whitespace().next() == Some(path) || l.trim() == path)
}

/// The exact version `go get` resolved for the module owning `path`, read from
/// `sky-out/go.mod` — the `require` line whose module path is the longest prefix
/// of `path` (so a subpackage like `.../v84/customer` maps to its module root).
/// Used for pin-by-default when the user gave `sky add` no explicit version.
fn resolved_module_version(sky_out: &Path, path: &str) -> Option<String> {
    let text = std::fs::read_to_string(sky_out.join("go.mod")).ok()?;
    let mut best: Option<(usize, String)> = None;
    for line in text.lines() {
        let l = line.trim().trim_start_matches("require").trim();
        let mut it = l.split_whitespace();
        let (Some(module), Some(version)) = (it.next(), it.next()) else {
            continue;
        };
        if !version.starts_with('v') {
            continue;
        }
        let is_match = path == module || path.starts_with(&format!("{module}/"));
        if is_match && best.as_ref().is_none_or(|(len, _)| module.len() > *len) {
            best = Some((module.len(), version.to_string()));
        }
    }
    best.map(|(_, v)| v)
}

// ---- sky.toml [go.dependencies] management (port of appendGoDependency) ----

/// Outcome of an [`upsert_go_dependency`] edit.
enum DepEdit {
    /// The dep was not present and was inserted.
    Added,
    /// The dep was present at a different spec, now replaced (carries the old).
    Updated(String),
    /// The dep was already recorded at exactly this spec.
    Unchanged,
}

/// Record `"<pkg>" = "<spec>"` under `[<section>]`. If `pkg` is already present
/// IN THAT SECTION, its spec is REPLACED (the most recent `sky add` wins — so
/// sky.toml never disagrees with the regenerated surface); if the spec is
/// unchanged it is a no-op. Only an exact-key match (`"<pkg>"` with its closing
/// quote) counts, so `foo` never collides with `foo/v2`. The replace + header
/// scan are scoped to `section` so a key present in the sibling section is never
/// touched.
fn upsert_dependency(
    sky_toml: &Path,
    section: &str,
    pkg: &str,
    spec: &str,
) -> Result<DepEdit, String> {
    let existing = std::fs::read_to_string(sky_toml).unwrap_or_default();
    let spec = spec_or_latest(spec);
    let quoted = format!("\"{pkg}\"");
    let mut lines: Vec<String> = existing.lines().map(str::to_string).collect();

    // Replace an existing exact-key entry within the target section only.
    let mut cur_in_section = false;
    for line in lines.iter_mut() {
        let t = line.trim();
        if t.starts_with('[') && t.ends_with(']') {
            cur_in_section = section_matches(t, section);
            continue;
        }
        if !cur_in_section {
            continue;
        }
        if let Some(rest) = line.trim_start().strip_prefix(&quoted) {
            if let Some(val) = rest.trim_start().strip_prefix('=') {
                let old = val.trim().trim_matches('"').to_string();
                if old == spec {
                    return Ok(DepEdit::Unchanged);
                }
                *line = format!("{quoted} = \"{spec}\"");
                write_lines(sky_toml, &lines)?;
                return Ok(DepEdit::Updated(old));
            }
        }
    }

    // Not present — insert under the `[<section>]` header (create it if absent).
    let entry = format!("{quoted} = \"{spec}\"");
    let header_idx = lines
        .iter()
        .position(|l| section_matches(l.trim(), section));
    match header_idx {
        Some(i) => lines.insert(i + 1, entry),
        None => {
            if !lines.is_empty() && !lines.last().map(|l| l.is_empty()).unwrap_or(true) {
                lines.push(String::new());
            }
            lines.push(canonical_header(section));
            lines.push(entry);
        }
    }
    write_lines(sky_toml, &lines)?;
    Ok(DepEdit::Added)
}

/// Upsert under `["go.dependencies"]`. Thin wrapper over [`upsert_dependency`].
fn upsert_go_dependency(sky_toml: &Path, pkg: &str, spec: &str) -> Result<DepEdit, String> {
    upsert_dependency(sky_toml, "go.dependencies", pkg, spec)
}

/// Upsert under `[dependencies]` (Sky external packages).
fn upsert_sky_dependency(sky_toml: &Path, pkg: &str, spec: &str) -> Result<DepEdit, String> {
    upsert_dependency(sky_toml, "dependencies", pkg, spec)
}

fn write_lines(sky_toml: &Path, lines: &[String]) -> Result<(), String> {
    let mut out = lines.join("\n");
    out.push('\n');
    std::fs::write(sky_toml, out).map_err(|e| format!("write sky.toml: {e}"))
}

/// Remove the `"<pkg>" = ...` line from `[<section>]` (scoped to that section, so
/// a matching key in the sibling section survives). Returns whether a line was
/// removed.
fn remove_dependency(sky_toml: &Path, section: &str, pkg: &str) -> Result<bool, String> {
    let Ok(existing) = std::fs::read_to_string(sky_toml) else {
        return Ok(false);
    };
    let quoted = format!("\"{pkg}\"");
    let mut cur_in_section = false;
    let mut removed = false;
    let mut kept: Vec<&str> = Vec::new();
    for l in existing.lines() {
        let t = l.trim();
        if t.starts_with('[') && t.ends_with(']') {
            cur_in_section = section_matches(t, section);
            kept.push(l);
            continue;
        }
        if cur_in_section && l.trim_start().starts_with(&quoted) && l.contains('=') {
            removed = true;
            continue;
        }
        kept.push(l);
    }
    if !removed {
        return Ok(false);
    }
    let mut out = kept.join("\n");
    out.push('\n');
    std::fs::write(sky_toml, out).map_err(|e| format!("write sky.toml: {e}"))?;
    Ok(true)
}

/// Remove from `["go.dependencies"]`. Thin wrapper over [`remove_dependency`].
fn remove_go_dependency(sky_toml: &Path, pkg: &str) -> Result<bool, String> {
    remove_dependency(sky_toml, "go.dependencies", pkg)
}

/// Remove from `[dependencies]` (Sky external packages).
fn remove_sky_dependency(sky_toml: &Path, pkg: &str) -> Result<bool, String> {
    remove_dependency(sky_toml, "dependencies", pkg)
}

/// Whether a trimmed `[header]` line names the target `section`, accepting both
/// the bare (`[dependencies]`) and dotted-quoted (`["go.dependencies"]`) TOML
/// spellings. Exact equality — so `dependencies` never matches
/// `["go.dependencies"]` and vice-versa.
fn section_matches(line: &str, section: &str) -> bool {
    line == format!("[\"{section}\"]") || line == format!("[{section}]")
}

/// The canonical header line to CREATE for `section` when it is absent — dotted
/// keys are quoted (`["go.dependencies"]`, TOML requires it), bare keys are not
/// (`[dependencies]`). Preserves the exact byte shape the go path emitted before
/// the section-generic refactor.
fn canonical_header(section: &str) -> String {
    if section.contains('.') {
        format!("[\"{section}\"]")
    } else {
        format!("[{section}]")
    }
}

/// Parse the deps declared under `[<section>]` (in declaration order) as
/// `(import-path, version-spec)` pairs. An empty / absent value becomes
/// `"latest"`. `section` is `"go.dependencies"` (Go FFI modules) or
/// `"dependencies"` (Sky external packages).
pub(crate) fn read_dependencies(sky_toml: &Path, section: &str) -> Vec<(String, String)> {
    let Ok(text) = std::fs::read_to_string(sky_toml) else {
        return Vec::new();
    };
    let mut out = Vec::new();
    let mut in_section = false;
    for raw in text.lines() {
        let line = raw.trim();
        if line.starts_with('[') && line.ends_with(']') {
            in_section = section_matches(line, section);
            continue;
        }
        if !in_section || line.is_empty() || line.starts_with('#') {
            continue;
        }
        // `"pkg" = "version"`
        if let Some((k, v)) = line.split_once('=') {
            let key = k.trim().trim_matches('"').to_string();
            if !key.is_empty() {
                let spec = v.trim().trim_matches('"').trim();
                let spec = if spec.is_empty() { "latest" } else { spec };
                out.push((key, spec.to_string()));
            }
        }
    }
    out
}

/// Deps under `["go.dependencies"]` (Go FFI modules). Thin wrapper — see
/// [`read_dependencies`]. Kept as its name for the many existing call sites and
/// the oracle-parity docs.
pub(crate) fn read_go_dependencies(sky_toml: &Path) -> Vec<(String, String)> {
    read_dependencies(sky_toml, "go.dependencies")
}

/// Deps under `[dependencies]` (Sky external packages fetched as source under
/// `.skydeps/<slug>/`).
pub(crate) fn read_sky_dependencies(sky_toml: &Path) -> Vec<(String, String)> {
    read_dependencies(sky_toml, "dependencies")
}

/// Normalise a version spec — an empty spec means `"latest"`.
pub(crate) fn spec_or_latest(spec: &str) -> &str {
    let s = spec.trim();
    if s.is_empty() {
        "latest"
    } else {
        s
    }
}

/// Validate a Go dependency version spec. Go's module system takes EXACT
/// versions, not ranges: accept `"latest"` (Go-native floating), an exact semver
/// tag (`vX.Y.Z…`), or a bare branch / commit token. Reject npm/cargo-style range
/// constraints (`>=`, `<=`, `~`, `^`, `*`, or a bare `>` / `<`) — Go cannot
/// resolve them, so a silent `@latest` fallthrough would be a lie.
pub(crate) fn validate_spec(dep: &str, spec: &str) -> Result<(), String> {
    let s = spec_or_latest(spec);
    // Any range-constraint operator anywhere in the spec is a hard reject.
    for ch in ['>', '<', '~', '^', '*'] {
        if s.contains(ch) {
            return Err(format!(
                "sky.toml [\"go.dependencies\"]: \"{dep}\" = \"{spec}\" is not a valid Go version. \
                 Go module versions are exact — use \"latest\", an exact tag like \"v1.6.0\", \
                 or a branch/commit; range constraints (found '{ch}') are not supported."
            ));
        }
    }
    Ok(())
}

/// Whether a spec is an EXACT pin that `sky update` must leave untouched — an
/// exact semver tag (`vX.Y.Z…`) or a commit SHA. `"latest"` and branch names are
/// floating and re-resolve on update.
pub(crate) fn is_exact_pin(spec: &str) -> bool {
    let s = spec_or_latest(spec);
    if s == "latest" {
        return false;
    }
    // Exact semver tag: `v` followed by a digit (`v1.6.0`, `v2.0.0-rc1`).
    if let Some(rest) = s.strip_prefix('v') {
        if rest.chars().next().is_some_and(|c| c.is_ascii_digit()) {
            return true;
        }
    }
    // Commit SHA: 7..=40 lowercase hex chars.
    let looks_like_sha = (7..=40).contains(&s.len())
        && s.chars().all(|c| c.is_ascii_hexdigit())
        && s.contains(|c: char| c.is_ascii_digit());
    looks_like_sha
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn go_dep_roundtrip_in_sky_toml() {
        let dir = std::env::temp_dir().join(format!("sky-ffi-ops-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let toml = dir.join("sky.toml");
        std::fs::write(&toml, "name = \"x\"\nversion = \"0.1.0\"\n").unwrap();
        // First add inserts.
        assert!(matches!(
            upsert_go_dependency(&toml, "github.com/google/uuid", "v1.3.0").unwrap(),
            DepEdit::Added
        ));
        // Re-add with a new spec UPDATES (the latest sky add wins), not a no-op.
        assert!(matches!(
            upsert_go_dependency(&toml, "github.com/google/uuid", "latest").unwrap(),
            DepEdit::Updated(old) if old == "v1.3.0"
        ));
        assert_eq!(
            read_go_dependencies(&toml),
            vec![("github.com/google/uuid".to_string(), "latest".to_string())]
        );
        // Re-add with the SAME spec is unchanged.
        assert!(matches!(
            upsert_go_dependency(&toml, "github.com/google/uuid", "latest").unwrap(),
            DepEdit::Unchanged
        ));
        // Exact-key match: `uuid` must not collide with `uuid/v2`.
        assert!(matches!(
            upsert_go_dependency(&toml, "github.com/google/uuid/v2", "v2.0.0").unwrap(),
            DepEdit::Added
        ));
        assert_eq!(read_go_dependencies(&toml).len(), 2);
        assert!(remove_go_dependency(&toml, "github.com/google/uuid").unwrap());
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn sky_dep_roundtrip_and_section_isolation() {
        let dir = std::env::temp_dir().join(format!("sky-ffi-ops-sky-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let toml = dir.join("sky.toml");
        // Seed BOTH sections with the same key to prove section scoping.
        std::fs::write(
            &toml,
            "name = \"x\"\n\n[dependencies]\n\"github.com/anzellai/sky-tailwind\" = \"latest\"\n\n[\"go.dependencies\"]\n\"github.com/anzellai/sky-tailwind\" = \"v1.0.0\"\n",
        )
        .unwrap();

        // read_sky_dependencies only sees the [dependencies] entry.
        assert_eq!(
            read_sky_dependencies(&toml),
            vec![(
                "github.com/anzellai/sky-tailwind".to_string(),
                "latest".to_string()
            )]
        );
        // read_go_dependencies only sees the ["go.dependencies"] entry.
        assert_eq!(
            read_go_dependencies(&toml),
            vec![(
                "github.com/anzellai/sky-tailwind".to_string(),
                "v1.0.0".to_string()
            )]
        );

        // Upsert into [dependencies] must NOT touch the go section's same-named key.
        assert!(matches!(
            upsert_sky_dependency(&toml, "github.com/anzellai/sky-tailwind", "v0.2.0").unwrap(),
            DepEdit::Updated(old) if old == "latest"
        ));
        assert_eq!(read_sky_dependencies(&toml)[0].1, "v0.2.0");
        assert_eq!(read_go_dependencies(&toml)[0].1, "v1.0.0"); // untouched

        // Remove from [dependencies] leaves the go section's key intact.
        assert!(remove_sky_dependency(&toml, "github.com/anzellai/sky-tailwind").unwrap());
        assert!(read_sky_dependencies(&toml).is_empty());
        assert_eq!(read_go_dependencies(&toml).len(), 1);

        // A fresh add creates the [dependencies] header when absent.
        std::fs::write(&toml, "name = \"x\"\n").unwrap();
        assert!(matches!(
            upsert_sky_dependency(&toml, "github.com/anzellai/sky-tailwind", "v0.1.0").unwrap(),
            DepEdit::Added
        ));
        let text = std::fs::read_to_string(&toml).unwrap();
        assert!(text.contains("[dependencies]"));
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn is_commit_sha_classifies_specs() {
        assert!(!is_commit_sha("latest"));
        assert!(!is_commit_sha("main")); // branch
        assert!(!is_commit_sha("v1.6.0")); // semver tag, not a SHA
        assert!(!is_commit_sha("v2.0.0-rc1"));
        assert!(is_commit_sha("a1b2c3d4")); // 8 hex + digit
        assert!(is_commit_sha("dead1beef")); // hex + a digit
                                             // All-hex but digit-free (like "deadbeef") lacks the digit heuristic and
                                             // is treated as a branch — same Go-native ambiguity as `is_exact_pin`.
        assert!(!is_commit_sha("deadbeef"));
    }

    #[test]
    fn read_go_dependencies_defaults_empty_value_to_latest() {
        let dir = std::env::temp_dir().join(format!("sky-ffi-ops-def-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let toml = dir.join("sky.toml");
        std::fs::write(
            &toml,
            "name = \"x\"\n[\"go.dependencies\"]\n\"github.com/google/uuid\" = \"\"\n",
        )
        .unwrap();
        let deps = read_go_dependencies(&toml);
        assert_eq!(deps[0].1, "latest");
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn validate_spec_accepts_go_native_rejects_ranges() {
        assert!(validate_spec("x", "latest").is_ok());
        assert!(validate_spec("x", "v1.6.0").is_ok());
        assert!(validate_spec("x", "v2.0.0-rc1").is_ok());
        assert!(validate_spec("x", "main").is_ok()); // branch
        assert!(validate_spec("x", "abc1234").is_ok()); // commit-ish
        assert!(validate_spec("x", ">=1.2").is_err());
        assert!(validate_spec("x", "<=1.2").is_err());
        assert!(validate_spec("x", "~1.2").is_err());
        assert!(validate_spec("x", "^1.2").is_err());
        assert!(validate_spec("x", "1.*").is_err());
    }

    #[test]
    fn is_exact_pin_classifies_specs() {
        assert!(!is_exact_pin("latest"));
        assert!(!is_exact_pin(""));
        assert!(!is_exact_pin("main")); // branch
        assert!(is_exact_pin("v1.6.0"));
        assert!(is_exact_pin("v2.0.0-rc1"));
        assert!(is_exact_pin("a1b2c3d4")); // sha-ish
    }
}
