package sky_wrappers

import (
	_ffi_fmt "fmt"
	_ffi_reflect "reflect"

	auth "firebase.google.com/go/v4/auth"
)

var _ = _ffi_fmt.Sprintf

// Auto-generated by Sky compiler

func Sky_firebase_google_com_go_v4_auth_ClientVerifyIDToken(receiver any, arg0 any, arg1 any) any {
	_receiver := receiver.(*auth.Client)
	_arg0 := sky_asContext(arg0)
	_arg1 := sky_asString(arg1)
	return func() any {
		defer func() { recover() }()
		result, err := _receiver.VerifyIDToken(_arg0, _arg1)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_firebase_google_com_go_v4_auth_FIELD_Token_UID(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr {
		v = v.Elem()
	}
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("UID")
		if f.IsValid() {
			return f.Interface()
		}
	}
	return nil
}

func Sky_firebase_google_com_go_v4_auth_FIELD_Token_Claims(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr {
		v = v.Elem()
	}
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("Claims")
		if f.IsValid() {
			return f.Interface()
		}
	}
	return nil
}
