package sky_wrappers

import (
	_ffi_fmt "fmt"
	strings "strings"
)

var _ = _ffi_fmt.Sprintf

// Auto-generated by Sky compiler

func Sky_strings_Clone(arg0 any) any {
	_arg0 := sky_asString(arg0)
	return func() any {
		defer func() { recover() }()
		result := strings.Clone(_arg0)
		return SkyOk(result)
	}
}

func Sky_strings_Compare(arg0 any, arg1 any) any {
	_arg0 := sky_asString(arg0)
	_arg1 := sky_asString(arg1)
	return func() any {
		defer func() { recover() }()
		result := strings.Compare(_arg0, _arg1)
		return SkyOk(result)
	}
}

func Sky_strings_Contains(arg0 any, arg1 any) any {
	_arg0 := sky_asString(arg0)
	_arg1 := sky_asString(arg1)
	return func() any {
		defer func() { recover() }()
		result := strings.Contains(_arg0, _arg1)
		return SkyOk(result)
	}
}

func Sky_strings_ContainsAny(arg0 any, arg1 any) any {
	_arg0 := sky_asString(arg0)
	_arg1 := sky_asString(arg1)
	return func() any {
		defer func() { recover() }()
		result := strings.ContainsAny(_arg0, _arg1)
		return SkyOk(result)
	}
}

func Sky_strings_Count(arg0 any, arg1 any) any {
	_arg0 := sky_asString(arg0)
	_arg1 := sky_asString(arg1)
	return func() any {
		defer func() { recover() }()
		result := strings.Count(_arg0, _arg1)
		return SkyOk(result)
	}
}

func Sky_strings_CutPrefix(arg0 any, arg1 any) any {
	_arg0 := sky_asString(arg0)
	_arg1 := sky_asString(arg1)
	return func() any {
		defer func() { recover() }()
		_r0, _r1 := strings.CutPrefix(_arg0, _arg1)
		return SkyOk(SkyTuple2{_r0, _r1})
	}
}

func Sky_strings_CutSuffix(arg0 any, arg1 any) any {
	_arg0 := sky_asString(arg0)
	_arg1 := sky_asString(arg1)
	return func() any {
		defer func() { recover() }()
		_r0, _r1 := strings.CutSuffix(_arg0, _arg1)
		return SkyOk(SkyTuple2{_r0, _r1})
	}
}

func Sky_strings_EqualFold(arg0 any, arg1 any) any {
	_arg0 := sky_asString(arg0)
	_arg1 := sky_asString(arg1)
	return func() any {
		defer func() { recover() }()
		result := strings.EqualFold(_arg0, _arg1)
		return SkyOk(result)
	}
}

func Sky_strings_Fields(arg0 any) any {
	_arg0 := sky_asString(arg0)
	return func() any {
		defer func() { recover() }()
		result := strings.Fields(_arg0)
		return SkyOk(result[:])
	}
}

func Sky_strings_FieldsSeq(arg0 any) any {
	_arg0 := sky_asString(arg0)
	return func() any {
		defer func() { recover() }()
		result := strings.FieldsSeq(_arg0)
		return SkyOk(result)
	}
}

func Sky_strings_HasPrefix(arg0 any, arg1 any) any {
	_arg0 := sky_asString(arg0)
	_arg1 := sky_asString(arg1)
	return func() any {
		defer func() { recover() }()
		result := strings.HasPrefix(_arg0, _arg1)
		return SkyOk(result)
	}
}

func Sky_strings_HasSuffix(arg0 any, arg1 any) any {
	_arg0 := sky_asString(arg0)
	_arg1 := sky_asString(arg1)
	return func() any {
		defer func() { recover() }()
		result := strings.HasSuffix(_arg0, _arg1)
		return SkyOk(result)
	}
}

func Sky_strings_Index(arg0 any, arg1 any) any {
	_arg0 := sky_asString(arg0)
	_arg1 := sky_asString(arg1)
	return func() any {
		defer func() { recover() }()
		result := strings.Index(_arg0, _arg1)
		return SkyOk(result)
	}
}

func Sky_strings_IndexAny(arg0 any, arg1 any) any {
	_arg0 := sky_asString(arg0)
	_arg1 := sky_asString(arg1)
	return func() any {
		defer func() { recover() }()
		result := strings.IndexAny(_arg0, _arg1)
		return SkyOk(result)
	}
}

func Sky_strings_Join(arg0 any, arg1 any) any {
	_arg0 := sky_asStringSlice(arg0)
	_arg1 := sky_asString(arg1)
	return func() any {
		defer func() { recover() }()
		result := strings.Join(_arg0, _arg1)
		return SkyOk(result)
	}
}

func Sky_strings_LastIndex(arg0 any, arg1 any) any {
	_arg0 := sky_asString(arg0)
	_arg1 := sky_asString(arg1)
	return func() any {
		defer func() { recover() }()
		result := strings.LastIndex(_arg0, _arg1)
		return SkyOk(result)
	}
}

func Sky_strings_LastIndexAny(arg0 any, arg1 any) any {
	_arg0 := sky_asString(arg0)
	_arg1 := sky_asString(arg1)
	return func() any {
		defer func() { recover() }()
		result := strings.LastIndexAny(_arg0, _arg1)
		return SkyOk(result)
	}
}

func Sky_strings_Lines(arg0 any) any {
	_arg0 := sky_asString(arg0)
	return func() any {
		defer func() { recover() }()
		result := strings.Lines(_arg0)
		return SkyOk(result)
	}
}

func Sky_strings_NewReader(arg0 any) any {
	_arg0 := sky_asString(arg0)
	return func() any {
		defer func() { recover() }()
		result := strings.NewReader(_arg0)
		return SkyOk(result)
	}
}

func Sky_strings_NewReplacer(arg0 any) any {
	_arg0 := sky_asStringSlice(arg0)
	return func() any {
		defer func() { recover() }()
		result := strings.NewReplacer(_arg0...)
		return SkyOk(result)
	}
}

func Sky_strings_Repeat(arg0 any, arg1 any) any {
	_arg0 := sky_asString(arg0)
	_arg1 := sky_asInt(arg1)
	return func() any {
		defer func() { recover() }()
		result := strings.Repeat(_arg0, _arg1)
		return SkyOk(result)
	}
}

func Sky_strings_Replace(arg0 any, arg1 any, arg2 any, arg3 any) any {
	_arg0 := sky_asString(arg0)
	_arg1 := sky_asString(arg1)
	_arg2 := sky_asString(arg2)
	_arg3 := sky_asInt(arg3)
	return func() any {
		defer func() { recover() }()
		result := strings.Replace(_arg0, _arg1, _arg2, _arg3)
		return SkyOk(result)
	}
}

func Sky_strings_ReplaceAll(arg0 any, arg1 any, arg2 any) any {
	_arg0 := sky_asString(arg0)
	_arg1 := sky_asString(arg1)
	_arg2 := sky_asString(arg2)
	return func() any {
		defer func() { recover() }()
		result := strings.ReplaceAll(_arg0, _arg1, _arg2)
		return SkyOk(result)
	}
}

func Sky_strings_Split(arg0 any, arg1 any) any {
	_arg0 := sky_asString(arg0)
	_arg1 := sky_asString(arg1)
	return func() any {
		defer func() { recover() }()
		result := strings.Split(_arg0, _arg1)
		return SkyOk(result[:])
	}
}

func Sky_strings_SplitAfter(arg0 any, arg1 any) any {
	_arg0 := sky_asString(arg0)
	_arg1 := sky_asString(arg1)
	return func() any {
		defer func() { recover() }()
		result := strings.SplitAfter(_arg0, _arg1)
		return SkyOk(result[:])
	}
}

func Sky_strings_SplitAfterN(arg0 any, arg1 any, arg2 any) any {
	_arg0 := sky_asString(arg0)
	_arg1 := sky_asString(arg1)
	_arg2 := sky_asInt(arg2)
	return func() any {
		defer func() { recover() }()
		result := strings.SplitAfterN(_arg0, _arg1, _arg2)
		return SkyOk(result[:])
	}
}

func Sky_strings_SplitAfterSeq(arg0 any, arg1 any) any {
	_arg0 := sky_asString(arg0)
	_arg1 := sky_asString(arg1)
	return func() any {
		defer func() { recover() }()
		result := strings.SplitAfterSeq(_arg0, _arg1)
		return SkyOk(result)
	}
}

func Sky_strings_SplitN(arg0 any, arg1 any, arg2 any) any {
	_arg0 := sky_asString(arg0)
	_arg1 := sky_asString(arg1)
	_arg2 := sky_asInt(arg2)
	return func() any {
		defer func() { recover() }()
		result := strings.SplitN(_arg0, _arg1, _arg2)
		return SkyOk(result[:])
	}
}

func Sky_strings_SplitSeq(arg0 any, arg1 any) any {
	_arg0 := sky_asString(arg0)
	_arg1 := sky_asString(arg1)
	return func() any {
		defer func() { recover() }()
		result := strings.SplitSeq(_arg0, _arg1)
		return SkyOk(result)
	}
}

func Sky_strings_Title(arg0 any) any {
	_arg0 := sky_asString(arg0)
	return func() any {
		defer func() { recover() }()
		result := strings.Title(_arg0)
		return SkyOk(result)
	}
}

func Sky_strings_ToLower(arg0 any) any {
	_arg0 := sky_asString(arg0)
	return func() any {
		defer func() { recover() }()
		result := strings.ToLower(_arg0)
		return SkyOk(result)
	}
}

func Sky_strings_ToTitle(arg0 any) any {
	_arg0 := sky_asString(arg0)
	return func() any {
		defer func() { recover() }()
		result := strings.ToTitle(_arg0)
		return SkyOk(result)
	}
}

func Sky_strings_ToUpper(arg0 any) any {
	_arg0 := sky_asString(arg0)
	return func() any {
		defer func() { recover() }()
		result := strings.ToUpper(_arg0)
		return SkyOk(result)
	}
}

func Sky_strings_ToValidUTF8(arg0 any, arg1 any) any {
	_arg0 := sky_asString(arg0)
	_arg1 := sky_asString(arg1)
	return func() any {
		defer func() { recover() }()
		result := strings.ToValidUTF8(_arg0, _arg1)
		return SkyOk(result)
	}
}

func Sky_strings_Trim(arg0 any, arg1 any) any {
	_arg0 := sky_asString(arg0)
	_arg1 := sky_asString(arg1)
	return func() any {
		defer func() { recover() }()
		result := strings.Trim(_arg0, _arg1)
		return SkyOk(result)
	}
}

func Sky_strings_TrimLeft(arg0 any, arg1 any) any {
	_arg0 := sky_asString(arg0)
	_arg1 := sky_asString(arg1)
	return func() any {
		defer func() { recover() }()
		result := strings.TrimLeft(_arg0, _arg1)
		return SkyOk(result)
	}
}

func Sky_strings_TrimPrefix(arg0 any, arg1 any) any {
	_arg0 := sky_asString(arg0)
	_arg1 := sky_asString(arg1)
	return func() any {
		defer func() { recover() }()
		result := strings.TrimPrefix(_arg0, _arg1)
		return SkyOk(result)
	}
}

func Sky_strings_TrimRight(arg0 any, arg1 any) any {
	_arg0 := sky_asString(arg0)
	_arg1 := sky_asString(arg1)
	return func() any {
		defer func() { recover() }()
		result := strings.TrimRight(_arg0, _arg1)
		return SkyOk(result)
	}
}

func Sky_strings_TrimSpace(arg0 any) any {
	_arg0 := sky_asString(arg0)
	return func() any {
		defer func() { recover() }()
		result := strings.TrimSpace(_arg0)
		return SkyOk(result)
	}
}

func Sky_strings_TrimSuffix(arg0 any, arg1 any) any {
	_arg0 := sky_asString(arg0)
	_arg1 := sky_asString(arg1)
	return func() any {
		defer func() { recover() }()
		result := strings.TrimSuffix(_arg0, _arg1)
		return SkyOk(result)
	}
}

func Sky_strings_BuilderCap(receiver any) any {
	_receiver := receiver.(*strings.Builder)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Cap()
		return SkyOk(result)
	}
}

func Sky_strings_BuilderGrow(receiver any, arg0 any) any {
	_receiver := receiver.(*strings.Builder)
	_arg0 := sky_asInt(arg0)
	return func() any {
		defer func() { recover() }()
		_receiver.Grow(_arg0)
		return SkyOk(struct{}{})
	}
}

func Sky_strings_BuilderLen(receiver any) any {
	_receiver := receiver.(*strings.Builder)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Len()
		return SkyOk(result)
	}
}

func Sky_strings_BuilderReset(receiver any) any {
	_receiver := receiver.(*strings.Builder)
	return func() any {
		defer func() { recover() }()
		_receiver.Reset()
		return SkyOk(struct{}{})
	}
}

func Sky_strings_BuilderString(receiver any) any {
	_receiver := receiver.(*strings.Builder)
	return func() any {
		defer func() { recover() }()
		result := _receiver.String()
		return SkyOk(result)
	}
}

func Sky_strings_BuilderWrite(receiver any, arg0 any) any {
	_receiver := receiver.(*strings.Builder)
	_arg0 := sky_asBytes(arg0)
	return func() any {
		defer func() { recover() }()
		result, err := _receiver.Write(_arg0)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}
}

func Sky_strings_BuilderWriteString(receiver any, arg0 any) any {
	_receiver := receiver.(*strings.Builder)
	_arg0 := sky_asString(arg0)
	return func() any {
		defer func() { recover() }()
		result, err := _receiver.WriteString(_arg0)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}
}

func Sky_strings_ReaderLen(receiver any) any {
	_receiver := receiver.(*strings.Reader)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Len()
		return SkyOk(result)
	}
}

func Sky_strings_ReaderRead(receiver any, arg0 any) any {
	_receiver := receiver.(*strings.Reader)
	_arg0 := sky_asBytes(arg0)
	return func() any {
		defer func() { recover() }()
		result, err := _receiver.Read(_arg0)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}
}

func Sky_strings_ReaderReadAt(receiver any, arg0 any, arg1 any) any {
	_receiver := receiver.(*strings.Reader)
	_arg0 := sky_asBytes(arg0)
	_arg1 := sky_asInt64(arg1)
	return func() any {
		defer func() { recover() }()
		result, err := _receiver.ReadAt(_arg0, _arg1)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}
}

func Sky_strings_ReaderReset(receiver any, arg0 any) any {
	_receiver := receiver.(*strings.Reader)
	_arg0 := sky_asString(arg0)
	return func() any {
		defer func() { recover() }()
		_receiver.Reset(_arg0)
		return SkyOk(struct{}{})
	}
}

func Sky_strings_ReaderSeek(receiver any, arg0 any, arg1 any) any {
	_receiver := receiver.(*strings.Reader)
	_arg0 := sky_asInt64(arg0)
	_arg1 := sky_asInt(arg1)
	return func() any {
		defer func() { recover() }()
		result, err := _receiver.Seek(_arg0, _arg1)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}
}

func Sky_strings_ReaderSize(receiver any) any {
	_receiver := receiver.(*strings.Reader)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Size()
		return SkyOk(result)
	}
}

func Sky_strings_ReaderUnreadByte(receiver any) any {
	_receiver := receiver.(*strings.Reader)
	return func() any {
		defer func() { recover() }()
		err := _receiver.UnreadByte()
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(struct{}{})
	}
}

func Sky_strings_ReaderUnreadRune(receiver any) any {
	_receiver := receiver.(*strings.Reader)
	return func() any {
		defer func() { recover() }()
		err := _receiver.UnreadRune()
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(struct{}{})
	}
}

func Sky_strings_ReplacerReplace(receiver any, arg0 any) any {
	_receiver := receiver.(*strings.Replacer)
	_arg0 := sky_asString(arg0)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Replace(_arg0)
		return SkyOk(result)
	}
}
