//! The G0.x cross-cutting gates — implementable with zero BlueDB code (§10.1,
//! phase P0).
//!
//! Every body here resolves paths through [`Ctx`] and nothing else. That is the
//! H3 contract: under `--verify-mutations` the `Ctx` root is a scratch git
//! worktree, and a body that reached the developer's tree instead — an absolute
//! path, an inherited `cwd` — would make every mutation report `PROVEN`
//! forever.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use super::registry::{Ctx, GateOutcome, REGISTRY};
use super::sha256;
use super::state::{GateState, ProofOutcome};
use super::status;

// ---------------------------------------------------------------------------
// G0.1 — STATUS.md is generated output
// ---------------------------------------------------------------------------

/// The gate reads the **snapshot** taken before this run regenerates the file.
/// Checking the file the run is about to write would be a tautology — the class
/// of regression test the mandate calls out by name.
pub fn g0_1_status_generated(ctx: &Ctx) -> GateOutcome {
    let Some(text) = ctx.status_snapshot.as_deref() else {
        return GateOutcome::fail(
            "docs/bluedb/STATUS.md is absent",
            vec!["STATUS.md is generated output and must be committed; run `cargo run -p xtask -- bluedb-gates`".into()],
        );
    };

    let mut findings = Vec::new();

    if !text.contains("<!-- GENERATED by `cargo run -p xtask -- bluedb-gates`. DO NOT EDIT. -->") {
        findings.push("STATUS.md is missing the GENERATED banner".into());
    }

    match status::split_body_and_sha(text) {
        None => findings.push(
            "STATUS.md has no trailing `<!-- body-sha256: … -->` line — hand edits would be undetectable"
                .into(),
        ),
        Some((body, recorded)) => {
            let actual = sha256::hex(body.as_bytes());
            if actual != recorded {
                findings.push(format!(
                    "body-sha256 mismatch: recorded {recorded}, actual {actual} — STATUS.md was hand-edited; regenerate with `cargo run -p xtask -- bluedb-gates`"
                ));
            }
        }
    }

    if findings.is_empty() {
        GateOutcome::pass("STATUS.md carries the generated banner and a matching body-sha256")
    } else {
        GateOutcome::fail("STATUS.md is not trustworthy generated output", findings)
    }
}

// ---------------------------------------------------------------------------
// G0.2 — layering
// ---------------------------------------------------------------------------

const GO_MODULE: &str = "sky-app";

/// `rt` must never import `bluedb`; `bluedb` may import only pebble + stdlib.
///
/// The first arm quantifies over `runtime-go/rt/`'s **actual** imports, so it is
/// a live assertion today and its declared mutation turns it red today. The
/// second arm is currently quantified over an empty set (P1 has not landed) and
/// is reported as such rather than counted as evidence.
pub fn g0_2_layering(ctx: &Ctx) -> GateOutcome {
    let mut findings = Vec::new();

    let rt_files = collect_go(&ctx.path("runtime-go/rt"));
    let mut rt_scanned = 0usize;
    for f in &rt_files {
        let Ok(text) = std::fs::read_to_string(f) else {
            continue;
        };
        rt_scanned += 1;
        for (line_no, imp) in go_imports(&text) {
            if imp == format!("{GO_MODULE}/bluedb") || imp.starts_with(&format!("{GO_MODULE}/bluedb/"))
            {
                findings.push(format!(
                    "forbidden edge rt -> bluedb: {}:{} imports {imp}",
                    rel(ctx, f),
                    line_no
                ));
            }
        }
    }

    let bluedb_files = collect_go(&ctx.path("runtime-go/bluedb"));
    for f in &bluedb_files {
        let Ok(text) = std::fs::read_to_string(f) else {
            continue;
        };
        for (line_no, imp) in go_imports(&text) {
            if !is_go_stdlib(&imp) && !is_allowed_bluedb_dep(&imp) {
                findings.push(format!(
                    "forbidden edge bluedb -> {imp}: {}:{} (bluedb may import only pebble + stdlib)",
                    rel(ctx, f),
                    line_no
                ));
            }
        }
    }

    if findings.is_empty() {
        GateOutcome::pass(format!(
            "{rt_scanned} rt files scanned, 0 edges to bluedb; {} bluedb files scanned",
            bluedb_files.len()
        ))
    } else {
        GateOutcome::fail("layering violated", findings)
    }
}

fn is_allowed_bluedb_dep(imp: &str) -> bool {
    imp.starts_with("github.com/cockroachdb/pebble")
        || imp.starts_with("github.com/cockroachdb/errors")
        || imp.starts_with("golang.org/x/")
}

// ---------------------------------------------------------------------------
// G0.3 — no pebble leak into a non-Persist app
// ---------------------------------------------------------------------------

/// Every arm of G0.3 — "links no pebble", "ships no `bluedb/`", "keeps a
/// non-`data` session store" — asserts that a thing which does not yet exist
/// has not leaked. With no pebble anywhere in the tree the assertion cannot
/// fail, and a gate that cannot fail is exactly what RULE ZERO clause 3
/// forbids. `NOT RUN` is the truthful state; the probe, not the author, decides
/// when that stops being true.
pub fn g0_3_no_pebble_leak(ctx: &Ctx) -> GateOutcome {
    super::pending::p1_substrate(ctx)
}

// ---------------------------------------------------------------------------
// G0.4 — no dead config key
// ---------------------------------------------------------------------------

/// Forward arm: every env name the compiler writes from `sky.toml` must be read
/// somewhere in `runtime-go/`.
/// Reverse arm: every `DB_*` / `DATA_*` env read by `runtime-go/` must be a name
/// the compiler writes (those two namespaces are the compiler's to own; `LIVE_*`
/// / `LOG_*` include operator-set names and are not claimed here).
pub fn g0_4_no_dead_config(ctx: &Ctx) -> GateOutcome {
    let Some(build_rs) = ctx.read("rust/crates/project/src/build.rs") else {
        return GateOutcome::fail(
            "cannot read rust/crates/project/src/build.rs",
            vec!["the config-writer table could not be located".into()],
        );
    };

    let written = written_env_keys(&build_rs);
    if written.is_empty() {
        return GateOutcome::fail(
            "found no `extra_defaults.push` sites in build.rs",
            vec!["the scan pattern no longer matches the compiler — G0.4 would be vacuous".into()],
        );
    }

    let read = runtime_env_literals(ctx);

    let mut findings = Vec::new();
    for (key, line) in &written {
        if read.contains_key(key) {
            continue;
        }
        // A key can have a legitimate consumer that is NOT `runtime-go/`: the
        // user's own app code. `docs/sky-toml.md` prescribes exactly that for
        // the `[auth]` family —
        //   ttl = System.getenvOr "SKY_AUTH_TOKEN_TTL" "86400"
        // — and `SetSkyDefault` really does `os.Setenv` the prefixed name
        // (runtime-go/rt/dotenv.go), so the seeded value reaches that read.
        // Scanning only `runtime-go/` therefore reported two working keys as
        // dead. It is a REAL exemption, not a waiver: the docs must actually
        // show user code reading the prefixed name, and this checks that they
        // do. A key nobody reads cannot be silenced by listing it here — it can
        // only be silenced by writing a doc that shows the read, which is the
        // thing that would make it true.
        match user_facing_read_site(ctx, key) {
            Some(site) => {
                let _ = site; // documented consumer found; not a dead key
            }
            None => findings.push(format!(
                "dead config key {key}: written by the compiler at rust/crates/project/src/build.rs:{line}, \
                 read by nothing in runtime-go/ and shown to no user code in docs/"
            )),
        }
    }
    for (key, site) in &read {
        if (key.starts_with("DB_") || key.starts_with("DATA_"))
            && !written.iter().any(|(k, _)| k == key)
        {
            findings.push(format!(
                "unwritten config key {key}: read at {site}, written by no `sky.toml` key"
            ));
        }
    }

    if findings.is_empty() {
        GateOutcome::pass(format!(
            "{} compiler-written env keys, all read in runtime-go/",
            written.len()
        ))
    } else {
        GateOutcome::fail(
            format!("{} dead config key(s)", findings.len()),
            findings,
        )
    }
}

/// Does the live documentation show USER CODE reading this key's env var?
///
/// The contract being verified is narrow and deliberately hard to fake: a
/// documentation line must contain BOTH a `System.getenv`-family call AND the
/// `SKY_`-prefixed name of the key. A mere mention — a table row saying the env
/// var exists, a prose reference to the prefix scheme — does not count, because
/// that is precisely what a dead key looks like. `SKY_AUTH_DRIVER` had a table
/// row and nothing else; `SKY_AUTH_TOKEN_TTL` has
/// `System.getenvOr "SKY_AUTH_TOKEN_TTL"` in a worked example.
///
/// `docs/history/` is excluded: frozen roadmaps are not a live contract, and
/// letting them satisfy this would resurrect keys the project already retired.
fn user_facing_read_site(ctx: &Ctx, key: &str) -> Option<String> {
    let prefixed = format!("SKY_{key}");
    for f in collect_docs(&ctx.path("docs")) {
        let rel_path = rel(ctx, &f);
        if rel_path.contains("docs/history/") || rel_path.contains("docs/bluedb/") {
            continue;
        }
        let Ok(text) = std::fs::read_to_string(&f) else {
            continue;
        };
        for (i, line) in text.lines().enumerate() {
            if line.contains(&prefixed) && line.contains("System.getenv") {
                return Some(format!("{rel_path}:{}", i + 1));
            }
        }
    }
    None
}

/// `cfg.extra_defaults.push(("KEY".into(), val))` -> (KEY, line).
fn written_env_keys(src: &str) -> Vec<(String, usize)> {
    let mut out = Vec::new();
    for (i, line) in src.lines().enumerate() {
        let Some(pos) = line.find("extra_defaults.push((\"") else {
            continue;
        };
        let rest = &line[pos + "extra_defaults.push((\"".len()..];
        if let Some(end) = rest.find('"') {
            out.push((rest[..end].to_string(), i + 1));
        }
    }
    out.sort();
    out.dedup();
    out
}

/// Every `"UPPER_SNAKE"` string literal appearing in `runtime-go/`, with one
/// citation site each. A literal is the only form the runtime uses to name an
/// env suffix (`skyGetenv("DB_PATH")`), so this is a genuinely lexical property
/// — grep is defensible here per RULE ZERO clause 5.
fn runtime_env_literals(ctx: &Ctx) -> BTreeMap<String, String> {
    let mut out = BTreeMap::new();
    for f in collect_go(&ctx.path("runtime-go")) {
        let Ok(text) = std::fs::read_to_string(&f) else {
            continue;
        };
        for (i, line) in text.lines().enumerate() {
            for lit in string_literals(line) {
                if lit.len() >= 3
                    && lit
                        .bytes()
                        .all(|b| b.is_ascii_uppercase() || b == b'_' || b.is_ascii_digit())
                    && lit.bytes().any(|b| b == b'_')
                {
                    out.entry(lit)
                        .or_insert_with(|| format!("{}:{}", rel(ctx, &f), i + 1));
                }
            }
        }
    }
    out
}

// ---------------------------------------------------------------------------
// G0.5 — the single go-build site carries the zstd tag
// ---------------------------------------------------------------------------

const ZSTD_TAG: &str = "pebblegozstd";

/// Arm (a) — `run_go_build_once` is the sole `go build` site — is asserted
/// unconditionally, and is the arm the declared mutation ("add a second site")
/// falsifies.
///
/// Arms (b) `-tags pebblegozstd` and (c) `go tool nm` finds no DataDog cgo zstd
/// symbols are asserted **iff `runtime-go/go.mod` requires pebble**. The tag
/// selects pebble's pure-Go zstd implementation; with no pebble in the module
/// graph it selects nothing, and asserting it would be theatre. The condition is
/// read from `go.mod`, not chosen by the gate author, and it ratchets: the
/// commit that adds pebble turns arms (b)/(c) live.
pub fn g0_5_zstd_tag(ctx: &Ctx) -> GateOutcome {
    let mut findings = Vec::new();

    let sites = go_build_sites(ctx);
    if sites.len() != 1 {
        findings.push(format!(
            "expected exactly 1 `go build` site in rust/crates/project/src, found {}: {}",
            sites.len(),
            sites
                .iter()
                .map(|(f, l)| format!("{f}:{l}"))
                .collect::<Vec<_>>()
                .join(", ")
        ));
    }

    let pebble_present = ctx
        .read("runtime-go/go.mod")
        .map(|m| m.contains("cockroachdb/pebble"))
        .unwrap_or(false);

    let build_rs = ctx.read("rust/crates/project/src/build.rs").unwrap_or_default();
    let tag_present = build_rs.contains(ZSTD_TAG);

    if pebble_present {
        if !tag_present {
            findings.push(format!(
                "runtime-go/go.mod requires pebble but no `-tags {ZSTD_TAG}` appears at the go build site — CI would link the cgo DataDog zstd while shipped apps link pure-Go klauspost"
            ));
        }
        findings.push(
            "arm (c) (`go tool nm` finds no DataDog cgo zstd symbols in a Persist binary) is not implemented, and pebble has landed — implement it with P1".into(),
        );
    }

    if findings.is_empty() {
        let arm_bc = if pebble_present {
            "asserted"
        } else {
            "not applicable — runtime-go/go.mod does not require pebble yet"
        };
        GateOutcome::pass(format!(
            "1 `go build` site ({}) [tier {}]; arms (b)/(c): {arm_bc}",
            sites
                .first()
                .map(|(f, l)| format!("{f}:{l}"))
                .unwrap_or_default(),
            ctx.tier.label()
        ))
    } else {
        GateOutcome::fail("go-build site / zstd tag contract broken", findings)
    }
}

/// A `Command::new("go")` whose command line contains `build` within the next
/// few lines. `go get` / `go tool` sites are not `go build` sites.
fn go_build_sites(ctx: &Ctx) -> Vec<(String, usize)> {
    let mut out = Vec::new();
    for f in collect_ext(&ctx.path("rust/crates/project/src"), "rs") {
        let Ok(text) = std::fs::read_to_string(&f) else {
            continue;
        };
        let lines: Vec<&str> = text.lines().collect();
        for (i, line) in lines.iter().enumerate() {
            if !line.contains("Command::new(\"go\")") {
                continue;
            }
            let window = lines[i..(i + 6).min(lines.len())].join(" ");
            if window.contains(".arg(\"build\")") || window.contains("\"build\",") {
                out.push((rel(ctx, &f), i + 1));
            }
        }
    }
    out
}

// ---------------------------------------------------------------------------
// G0.6 — every recorded mutation proof is present and current
// ---------------------------------------------------------------------------

/// `--verify-mutations` is the expensive re-derivation; G0.6 is the cheap
/// standing assertion that its results exist, cover every mutation of every
/// implemented gate, carry the expected RED output, and have not decayed.
pub fn g0_6_mutations_verified(ctx: &Ctx) -> GateOutcome {
    let state = GateState::load(ctx.root());
    let mut findings = Vec::new();
    let mut unauthored = 0usize;

    for gate in REGISTRY {
        for m in gate.mutations.as_slice() {
            let patch = ctx.path(m.patch);
            if !patch.exists() {
                if state.proofs.contains_key(m.id) {
                    findings.push(format!(
                        "{}: the ledger records a proof but the patch at {} is gone",
                        m.id, m.patch
                    ));
                } else {
                    // The gate is not authored yet. It already renders NOT RUN,
                    // which renders its goal UNKNOWN, so counting it here would
                    // drown the real findings without adding any signal. An
                    // *implemented* gate with no patch cannot hide this way:
                    // `--verify-mutations` records MUTATION-STALE for it, and
                    // that lands in the ledger and is caught below.
                    unauthored += 1;
                }
                continue;
            }
            let Some((outcome, sha)) = state.proofs.get(m.id) else {
                findings.push(format!(
                    "{}: recorded proof ledger is stale — no entry in {}",
                    m.id,
                    super::state::STATE_PATH
                ));
                continue;
            };
            let want = if gate.id == super::registry::CANARY_ID {
                ProofOutcome::Vacuous
            } else {
                ProofOutcome::Proven
            };
            if *outcome != want {
                findings.push(format!(
                    "{}: recorded {} but {} is required",
                    m.id,
                    outcome.label(),
                    want.label()
                ));
                continue;
            }
            // The canary declares `<never>`: it cannot go red, so there is no
            // RED output to record. Requiring one would be requiring evidence
            // the design says must not exist.
            if m.expect != "<never>" {
                let expected_file = expected_path(m.patch);
                match std::fs::read_to_string(ctx.path(&expected_file)) {
                    Err(_) => findings.push(format!(
                        "{}: recorded proof ledger is stale — no expected output at {expected_file}",
                        m.id
                    )),
                    Ok(text) => {
                        if !text.contains(m.expect) {
                            findings.push(format!(
                                "{}: recorded expected output does not contain the declared assertion {:?}",
                                m.id, m.expect
                            ));
                        }
                    }
                }
            }
            if super::mutations::targets_moved(ctx.root(), sha, m.targets) {
                findings.push(format!(
                    "{}: UNVERIFIED-SINCE {sha} — a declared target moved",
                    m.id
                ));
            }
        }
    }

    if findings.is_empty() {
        GateOutcome::pass(format!(
            "every authored mutation carries a current proof ({unauthored} not authored yet)"
        ))
    } else {
        GateOutcome::fail(
            format!(
                "{} mutation proof problem(s) ({unauthored} not authored yet)",
                findings.len()
            ),
            findings,
        )
    }
}

pub fn expected_path(patch: &str) -> String {
    patch
        .strip_suffix(".patch")
        .map(|s| format!("{s}.expected.txt"))
        .unwrap_or_else(|| format!("{patch}.expected.txt"))
}

// ---------------------------------------------------------------------------
// G0.7 — harness self-integrity + citation resolution
// ---------------------------------------------------------------------------

pub fn g0_7_self_integrity(ctx: &Ctx) -> GateOutcome {
    let mut findings = static_checks();

    let (cite_findings, cite_warnings, cite_total) = check_citations(ctx);
    findings.extend(cite_findings);

    // §9.6: a moved line is a warning, not a failure — surfaced on demand so a
    // signal that always fires never drowns the ones that matter.
    if ctx.verbose {
        for w in &cite_warnings {
            println!("  warn: {w}");
        }
    }

    if findings.is_empty() {
        GateOutcome::pass(format!(
            "3 static checks green over {} gates; {cite_total} citations resolved ({} warning(s))",
            REGISTRY.len(),
            cite_warnings.len()
        ))
    } else {
        GateOutcome::fail(
            format!("{} self-integrity finding(s)", findings.len()),
            findings,
        )
    }
}

/// §9.6's three checks. Run standalone by [`super::run`] before any gate
/// executes, and again inside G0.7 so the property is both a precondition and a
/// reported gate.
pub fn static_checks() -> Vec<String> {
    let mut findings = Vec::new();

    // 1. every goal 1..=5 owns at least one gate
    for goal in 1..=5u8 {
        if !REGISTRY.iter().any(|g| g.goal == goal) {
            findings.push(format!(
                "static check 1: goal {goal} has no gate — a goal with no gate is a FAIL, not an omission"
            ));
        }
    }

    // 2. every gate maps to exactly one goal, or is explicitly cross-cutting
    for g in REGISTRY {
        if g.goal > 5 {
            findings.push(format!(
                "static check 2: gate {} declares goal {} — must be 0 (cross-cutting) or 1..=5",
                g.id, g.goal
            ));
        }
    }

    // 3. every gate declares at least one mutation (H1's runtime backstop
    //    behind `Mutations::new`'s const-eval assertion)
    for g in REGISTRY {
        if g.mutations.is_empty() {
            findings.push(format!(
                "static check 3: gate {} declares no mutation — UNPROVEN, and its goal FAILs",
                g.id
            ));
        }
    }

    findings
}

/// Which tree a citation tag resolves against (the Citation provenance block).
fn tag_branch(tag: &str) -> Option<&'static str> {
    Some(match tag {
        "main" => "HEAD",
        "bdb" => "feat/bluedb",
        "p5e" => "salvage/p5e-foundation",
        "exp" => "exp/bluedb",
        _ => return None,
    })
}

pub struct Citation {
    pub line_no: usize,
    pub tag: Option<String>,
    pub path: String,
    pub line: usize,
    pub token: Option<String>,
}

/// Parse every `` `path:line` `` citation out of the architecture doc, together
/// with the branch tag governing it (the nearest `[main]`/`[bdb]`/`[p5e]`/`[exp]`
/// marker earlier on the same line) and the backticked identifier immediately
/// preceding it, if any.
pub fn parse_citations(doc: &str) -> Vec<Citation> {
    let mut out = Vec::new();
    let mut in_fence = false;
    for (i, line) in doc.lines().enumerate() {
        // Fenced blocks are illustrations — the §9.3 `STATUS.md` sample, the
        // §9.2 struct sketches — not claims about the code. Checking them would
        // report the example's invented `committer.go:214` as a stale citation.
        if line.trim_start().starts_with("```") {
            in_fence = !in_fence;
            continue;
        }
        if in_fence {
            continue;
        }
        for (col, path, lineno) in find_path_line_pairs(line) {
            let head = &line[..col];
            let tag = ["main", "bdb", "p5e", "exp"]
                .iter()
                .filter_map(|t| head.rfind(&format!("[{t}]")).map(|p| (p, (*t).to_string())))
                .max_by_key(|(p, _)| *p)
                .map(|(_, t)| t);
            out.push(Citation {
                line_no: i + 1,
                tag,
                path,
                line: lineno,
                token: preceding_backticked_ident(head),
            });
        }
    }
    out
}

/// Returns `(byte offset, path, line)` for every `path.ext:NNN` in `line`.
fn find_path_line_pairs(line: &str) -> Vec<(usize, String, usize)> {
    const EXTS: &[&str] = &[
        ".go", ".rs", ".sky", ".skyi", ".yml", ".yaml", ".md", ".toml", ".json",
    ];
    let bytes = line.as_bytes();
    let mut out = Vec::new();
    let mut i = 0;
    while i < line.len() {
        let Some(colon) = line[i..].find(':').map(|p| p + i) else {
            break;
        };
        // digits after the colon
        let mut j = colon + 1;
        while j < bytes.len() && bytes[j].is_ascii_digit() {
            j += 1;
        }
        if j == colon + 1 {
            i = colon + 1;
            continue;
        }
        // path before the colon
        let mut s = colon;
        while s > 0 {
            let b = bytes[s - 1];
            if b.is_ascii_alphanumeric() || matches!(b, b'.' | b'/' | b'_' | b'-') {
                s -= 1;
            } else {
                break;
            }
        }
        let path = &line[s..colon];
        if EXTS.iter().any(|e| path.ends_with(e)) {
            if let Ok(n) = line[colon + 1..j].parse::<usize>() {
                out.push((s, path.to_string(), n));
            }
        }
        i = j.max(colon + 1);
    }
    out
}

/// The `` `identifier` `` **immediately** preceding a citation, in the
/// document's canonical form:
///
/// ```text
/// `run_go_build_once` (`[main]` `build.rs:655-682`)
/// ```
///
/// Adjacency is required. A "nearest identifier anywhere to the left" heuristic
/// mis-associates every citation after the first in the dense changelog rows,
/// and a citation checker that invents failures is worse than one that checks
/// less: a signal nobody trusts is a signal nobody reads. Where no adjacent
/// identifier exists the citation is checked for line existence only.
fn preceding_backticked_ident(head: &str) -> Option<String> {
    // the citation's own opening backtick
    let s = head.strip_suffix('`')?;
    let s = s.trim_end();
    // an optional `[tag]` between the identifier and the citation
    let s = ["main", "bdb", "p5e", "exp"]
        .iter()
        .find_map(|t| s.strip_suffix(&format!("`[{t}]`")))
        .unwrap_or(s);
    let s = s.trim_end_matches([' ', '(', '\t']);
    let s = s.strip_suffix('`')?;
    let open = s.rfind('`')?;
    let inner = &s[open + 1..];
    let is_ident = !inner.is_empty()
        && inner
            .bytes()
            .all(|b| b.is_ascii_alphanumeric() || b == b'_')
        && !inner.bytes().all(|b| b.is_ascii_digit());
    if is_ident {
        Some(inner.to_string())
    } else {
        None
    }
}

/// Returns `(findings, warnings, total)`.
///
/// Severity follows §9.6: **a missing token is a FAIL; a moved line is a
/// warning.** Two cases §9.6 does not name are handled conservatively:
/// an untagged citation is a FAIL (Citation-provenance rule 3 — "a citation
/// without a tag is a defect, not a detail"), and a citation whose tagged
/// branch is not present in this clone is a warning, because absence of a
/// reference branch is a property of the checkout, not of the document.
fn check_citations(ctx: &Ctx) -> (Vec<String>, Vec<String>, usize) {
    let doc_rel = "docs/bluedb/v2-architecture.md";
    let Some(doc) = ctx.read(doc_rel) else {
        return (
            vec![format!("{doc_rel} is missing — G0.7 cannot check citations")],
            vec![],
            0,
        );
    };

    let cites = parse_citations(&doc);
    let mut findings = Vec::new();
    let mut warnings = Vec::new();
    let mut branch_cache: BTreeMap<String, bool> = BTreeMap::new();
    let mut listing_cache: BTreeMap<String, Vec<String>> = BTreeMap::new();

    for c in &cites {
        let Some(tag) = c.tag.as_deref() else {
            findings.push(format!(
                "{doc_rel}:{}: citation `{}:{}` carries no [main]/[bdb]/[p5e]/[exp] tag",
                c.line_no, c.path, c.line
            ));
            continue;
        };
        let Some(branch) = tag_branch(tag) else {
            findings.push(format!(
                "{doc_rel}:{}: unknown citation tag [{tag}]",
                c.line_no
            ));
            continue;
        };

        if branch != "HEAD" {
            let known = *branch_cache
                .entry(branch.to_string())
                .or_insert_with(|| git_rev_exists(ctx.root(), branch));
            if !known {
                warnings.push(format!(
                    "{doc_rel}:{}: [{tag}] branch `{branch}` is not present in this clone — `{}:{}` unresolvable here",
                    c.line_no, c.path, c.line
                ));
                continue;
            }
        }

        let Some((resolved_path, text)) =
            resolve_cited_file(ctx, branch, tag, &c.path, c.token.as_deref(), &mut listing_cache)
        else {
            findings.push(format!(
                "{doc_rel}:{}: `{}:{}` [{tag}] does not resolve to a file on `{branch}`",
                c.line_no, c.path, c.line
            ));
            continue;
        };

        let n_lines = text.lines().count();
        if let Some(tok) = &c.token {
            if !text.contains(tok.as_str()) {
                findings.push(format!(
                    "{doc_rel}:{}: `{}:{}` [{tag}] no longer contains the cited token `{tok}` (resolved {resolved_path})",
                    c.line_no, c.path, c.line
                ));
                continue;
            }
            let at_line = text
                .lines()
                .nth(c.line.saturating_sub(1))
                .map(|l| l.contains(tok.as_str()))
                .unwrap_or(false);
            if !at_line {
                warnings.push(format!(
                    "{doc_rel}:{}: `{}:{}` [{tag}] — `{tok}` moved (still present in {resolved_path})",
                    c.line_no, c.path, c.line
                ));
            }
        } else if c.line > n_lines {
            findings.push(format!(
                "{doc_rel}:{}: `{}:{}` [{tag}] points past EOF ({resolved_path} has {n_lines} lines)",
                c.line_no, c.path, c.line
            ));
        }
    }

    (findings, warnings, cites.len())
}

fn git_rev_exists(root: &Path, rev: &str) -> bool {
    std::process::Command::new("git")
        .args(["rev-parse", "--verify", "--quiet", rev])
        .current_dir(root)
        .output()
        .map(|o| o.status.success())
        .unwrap_or(false)
}

/// Subtrees a tag's citations are expected to live in, most specific first,
/// used to break basename ambiguity. `[bdb]`'s engine path is
/// `runtime-go/bluedb/…`, never `runtime-go/rt/bluedb/…` (Citation provenance
/// rule 2), so the engine subtree wins over `rt` for a `[bdb]` citation.
fn tag_roots(tag: &str) -> &'static [&'static str] {
    match tag {
        "bdb" => &["runtime-go/bluedb/", "runtime-go/rt/", "runtime-go/"],
        "p5e" | "exp" => &["runtime-go/rt/", "runtime-go/"],
        _ => &[],
    }
}

fn branch_listing(ctx: &Ctx, branch: &str, cache: &mut BTreeMap<String, Vec<String>>) -> Vec<String> {
    if let Some(v) = cache.get(branch) {
        return v.clone();
    }
    let files = std::process::Command::new("git")
        .args(["ls-tree", "-r", "--name-only", branch])
        .current_dir(ctx.root())
        .output()
        .ok()
        .filter(|o| o.status.success())
        .map(|o| {
            String::from_utf8_lossy(&o.stdout)
                .lines()
                .map(|s| s.to_string())
                .collect::<Vec<_>>()
        })
        .unwrap_or_default();
    cache.insert(branch.to_string(), files.clone());
    files
}

/// Resolve a cited path against a branch.
///
/// The document cites a mix of full repo-relative paths (`runtime-go/rt/live.go`),
/// partial paths (`rt/jobs/sqlite_store.go`) and bare basenames
/// (`committer.go`). All three are accepted: the citation must **suffix-match
/// exactly one path** on the tagged branch, with ties broken in favour of the
/// tag's canonical subtree. An ambiguity that survives that is not resolvable,
/// and saying so is the point — an ambiguous citation cannot be checked.
fn resolve_cited_file(
    ctx: &Ctx,
    branch: &str,
    tag: &str,
    path: &str,
    token: Option<&str>,
    cache: &mut BTreeMap<String, Vec<String>>,
) -> Option<(String, String)> {
    let files = branch_listing(ctx, branch, cache);

    let mut matches: Vec<String> = files
        .iter()
        .filter(|p| *p == path || p.ends_with(&format!("/{path}")))
        .cloned()
        .collect();

    // 1. the tag's canonical subtrees, most specific first
    if matches.len() > 1 {
        for root in tag_roots(tag) {
            let narrowed: Vec<String> = matches
                .iter()
                .filter(|p| p.starts_with(root))
                .cloned()
                .collect();
            if narrowed.len() == 1 {
                matches = narrowed;
                break;
            }
            if narrowed.len() > 1 {
                matches = narrowed;
            }
        }
    }

    // 2. the cited token itself — `run_go_build_once` picks
    //    `rust/crates/project/src/build.rs` out of the three `build.rs` files
    //    without anyone hard-coding which one the document meant.
    if matches.len() > 1 {
        if let Some(tok) = token {
            let narrowed: Vec<String> = matches
                .iter()
                .filter(|p| {
                    git_show(ctx, branch, p)
                        .map(|t| t.contains(tok))
                        .unwrap_or(false)
                })
                .cloned()
                .collect();
            if narrowed.len() == 1 {
                matches = narrowed;
            }
        }
    }

    // 3. shallowest path — `AGENTS.md` cited bare means the repo-root file, not
    //    `templates/AGENTS.md`.
    if matches.len() > 1 {
        if let Some(min) = matches.iter().map(|p| p.matches('/').count()).min() {
            let narrowed: Vec<String> = matches
                .iter()
                .filter(|p| p.matches('/').count() == min)
                .cloned()
                .collect();
            if narrowed.len() == 1 {
                matches = narrowed;
            }
        }
    }

    if matches.len() != 1 {
        return None;
    }
    let cand = matches.remove(0);
    let text = git_show(ctx, branch, &cand)?;
    Some((cand, text))
}

fn git_show(ctx: &Ctx, branch: &str, path: &str) -> Option<String> {
    let out = std::process::Command::new("git")
        .args(["show", &format!("{branch}:{path}")])
        .current_dir(ctx.root())
        .output()
        .ok()?;
    if out.status.success() {
        Some(String::from_utf8_lossy(&out.stdout).to_string())
    } else {
        None
    }
}

// ---------------------------------------------------------------------------
// G0.C — the canary
// ---------------------------------------------------------------------------

/// Asserts nothing. Cannot fail. Its paired patch is a no-op.
///
/// This is the one place in the design where a **passing** gate is the failure
/// signal: `--verify-mutations` must report `VACUOUS` for it, and reporting
/// `PROVEN` proves the runner is not measuring what it claims (H3).
pub fn g0_c_canary(_ctx: &Ctx) -> GateOutcome {
    GateOutcome::pass_if(true)
}

// ---------------------------------------------------------------------------
// shared helpers
// ---------------------------------------------------------------------------

fn rel(ctx: &Ctx, p: &Path) -> String {
    p.strip_prefix(ctx.root())
        .unwrap_or(p)
        .to_string_lossy()
        .replace('\\', "/")
}

fn collect_go(dir: &Path) -> Vec<PathBuf> {
    collect_ext(dir, "go")
}

fn collect_docs(dir: &Path) -> Vec<PathBuf> {
    collect_ext(dir, "md")
}

fn collect_ext(dir: &Path, ext: &str) -> Vec<PathBuf> {
    let mut out = Vec::new();
    fn walk(dir: &Path, ext: &str, out: &mut Vec<PathBuf>) {
        let Ok(rd) = std::fs::read_dir(dir) else {
            return;
        };
        let mut entries: Vec<PathBuf> = rd.filter_map(|e| e.ok().map(|e| e.path())).collect();
        entries.sort();
        for p in entries {
            let name = p.file_name().and_then(|n| n.to_str()).unwrap_or("");
            if matches!(name, "sky-out" | ".skycache" | ".skydeps" | "target" | "node_modules") {
                continue;
            }
            if p.is_dir() {
                walk(&p, ext, out);
            } else if p.extension().and_then(|e| e.to_str()) == Some(ext) {
                out.push(p);
            }
        }
    }
    walk(dir, ext, &mut out);
    out
}

/// Import paths of a Go file, as `(line, path)`. Handles both the factored
/// `import ( … )` block and single-line `import "x"`.
fn go_imports(text: &str) -> Vec<(usize, String)> {
    let mut out = Vec::new();
    let mut in_block = false;
    for (i, raw) in text.lines().enumerate() {
        let line = raw.trim();
        if !in_block {
            if line.starts_with("import (") {
                in_block = true;
                continue;
            }
            if let Some(rest) = line.strip_prefix("import ") {
                if let Some(p) = string_literals(rest).into_iter().next() {
                    out.push((i + 1, p));
                }
            }
            continue;
        }
        if line == ")" {
            in_block = false;
            continue;
        }
        if let Some(p) = string_literals(line).into_iter().next() {
            out.push((i + 1, p));
        }
    }
    out
}

fn is_go_stdlib(imp: &str) -> bool {
    match imp.split('/').next() {
        Some(first) => !first.contains('.'),
        None => true,
    }
}

/// Double-quoted literals in a line, without escape handling — sufficient for
/// import paths and env-name literals, neither of which contain escapes.
fn string_literals(line: &str) -> Vec<String> {
    let mut out = Vec::new();
    let mut it = line.char_indices();
    while let Some((i, c)) = it.next() {
        if c != '"' {
            continue;
        }
        let rest = &line[i + 1..];
        if let Some(end) = rest.find('"') {
            out.push(rest[..end].to_string());
            for _ in 0..rest[..=end].chars().count() {
                if it.next().is_none() {
                    break;
                }
            }
        } else {
            break;
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn extracts_written_env_keys() {
        let src = "\
            x\n\
            cfg.extra_defaults.push((\"DB_DRIVER\".into(), val)),\n\
            cfg.extra_defaults.push((\"LIVE_TTL\".into(), val)),\n";
        let keys = written_env_keys(src);
        assert_eq!(
            keys,
            vec![("DB_DRIVER".to_string(), 2), ("LIVE_TTL".to_string(), 3)]
        );
    }

    #[test]
    fn parses_go_imports_block_and_single() {
        let src = "package rt\n\nimport (\n\t\"fmt\"\n\t_ \"sky-app/bluedb\"\n)\n";
        let imps: Vec<String> = go_imports(src).into_iter().map(|(_, p)| p).collect();
        assert_eq!(imps, vec!["fmt", "sky-app/bluedb"]);

        let single = "import \"os\"\n";
        assert_eq!(go_imports(single)[0].1, "os");
    }

    #[test]
    fn classifies_stdlib_vs_external() {
        assert!(is_go_stdlib("fmt"));
        assert!(is_go_stdlib("encoding/json"));
        assert!(!is_go_stdlib("github.com/cockroachdb/pebble"));
        assert!(is_allowed_bluedb_dep("github.com/cockroachdb/pebble/vfs"));
        assert!(!is_allowed_bluedb_dep("sky-app/rt"));
    }

    #[test]
    fn finds_path_line_citations_and_tags() {
        let doc = "see `run_go_build_once` (`[main]` `build.rs:655-682`) for the site";
        let cites = parse_citations(doc);
        assert_eq!(cites.len(), 1);
        assert_eq!(cites[0].path, "build.rs");
        assert_eq!(cites[0].line, 655);
        assert_eq!(cites[0].tag.as_deref(), Some("main"));
        assert_eq!(cites[0].token.as_deref(), Some("run_go_build_once"));
    }

    #[test]
    fn untagged_citation_has_no_tag() {
        let cites = parse_citations("`committer.go:343` moved");
        assert_eq!(cites.len(), 1);
        assert!(cites[0].tag.is_none());
    }

    #[test]
    fn ignores_section_refs_and_times() {
        // `§9.3` / `14:02:11` / a bare `2026-08-09` must not parse as citations.
        assert!(parse_citations("§9.3 and 14:02:11 on 2026-08-09").is_empty());
    }

    #[test]
    fn expected_path_pairs_with_the_patch() {
        assert_eq!(
            expected_path("docs/bluedb/mutations/G0.2.rt.patch"),
            "docs/bluedb/mutations/G0.2.rt.expected.txt"
        );
    }

    #[test]
    fn static_checks_are_green_on_the_shipped_registry() {
        assert!(static_checks().is_empty(), "{:?}", static_checks());
    }

    #[test]
    fn string_literals_are_extracted_pairwise() {
        assert_eq!(string_literals("a \"X\" b \"Y\""), vec!["X", "Y"]);
        assert_eq!(string_literals("no quotes"), Vec::<String>::new());
    }
}
