//! `docs/bluedb/STATUS.md` — generated output (§9.3).
//!
//! The single mechanical property that closes H2: **the table renders from the
//! [`REGISTRY`], not from the run's results.** Every registered gate appears
//! whether or not it executed, so a gate cannot disappear from the report by
//! not running, and a partial run cannot produce a green-looking file.
//!
//! `--only` never reaches this module (§9.1), and the goal column is computed
//! by [`super::registry::goal_verdict`] — there is no prose verdict anywhere.

use std::collections::BTreeMap;

use super::registry::{GateState, GoalVerdict, Tier};
use super::sha256;
use super::state::ProofOutcome;

pub const STATUS_PATH: &str = "docs/bluedb/STATUS.md";

const BANNER: &str = "<!-- GENERATED by `cargo run -p xtask -- bluedb-gates`. DO NOT EDIT. -->";
const SHA_PREFIX: &str = "<!-- body-sha256: ";

/// Per-gate result as the renderer sees it.
pub struct Row {
    pub id: &'static str,
    pub goal: u8,
    pub title: &'static str,
    pub tier: Tier,
    pub state: GateState,
    pub secs: Option<f64>,
    pub detail: String,
    pub findings: Vec<String>,
    /// Rendered "Mutation proof" cell.
    pub proof: String,
    /// Whether the proof is not known-good (`—`, `UNVERIFIED-SINCE`, …). Feeds
    /// the goal verdict exactly as `NOT RUN` does (MAJOR-17).
    pub proof_unknown: bool,
}

pub struct Header {
    pub commit: String,
    pub ran: String,
    pub host: String,
    pub tier: Tier,
    pub full_tier: Option<(String, String, String)>,
    /// `Some(n)` when HEAD is `n` commits ahead of the recorded full-tier run.
    pub full_tier_behind: Option<usize>,
}

/// Render the whole file. Deterministic: the same registry + rows + header
/// always produce byte-identical output, which is what makes `--check`
/// meaningful.
pub fn render(header: &Header, rows: &[Row]) -> String {
    let mut body = String::new();

    let stale = header.full_tier_behind.map(|n| n > 0).unwrap_or(true);

    body.push_str("\n# BlueDB v2 — STATUS\n\n");

    // --- goal roll-up ----------------------------------------------------
    let mut by_goal: BTreeMap<u8, Vec<&Row>> = BTreeMap::new();
    for r in rows {
        by_goal.entry(r.goal).or_default().push(r);
    }

    let mut unknown_goals: Vec<String> = Vec::new();
    let mut goal_lines: Vec<String> = Vec::new();
    for (goal, grows) in &by_goal {
        let states: Vec<(GateState, bool)> =
            grows.iter().map(|r| (r.state, r.proof_unknown)).collect();
        let verdict = super::registry::goal_verdict(&states);
        if verdict == GoalVerdict::Unknown {
            unknown_goals.push(goal_label_short(*goal));
        }
        let gates = grows
            .iter()
            .map(|r| format!("{}{}", r.state.marker(), r.id))
            .collect::<Vec<_>>()
            .join(" ");
        goal_lines.push(format!(
            "| {} | **{}** | {} |\n",
            goal_label(*goal),
            verdict.label(),
            gates
        ));
    }

    if stale {
        let behind = header
            .full_tier_behind
            .map(|n| format!("{n} commits behind HEAD"))
            .unwrap_or_else(|| "never run".to_string());
        body.push_str(&format!(
            "⚠️  FULL-TIER RESULTS ARE STALE — {behind}. Goals {} render UNKNOWN.\n\
             \x20   Run: cargo run -p xtask -- bluedb-gates --tier=full\n\n",
            if unknown_goals.is_empty() {
                "(none)".to_string()
            } else {
                unknown_goals.join(", ")
            }
        ));
    }

    body.push_str("| Goal | Verdict | Gates |\n|---|---|---|\n");
    for l in &goal_lines {
        body.push_str(l);
    }
    body.push_str("\nLegend: (blank)=PASS  ✗=FAIL  ⊘=NOT RUN  ⊗=UNPROVEN\n\n");

    // --- gate table ------------------------------------------------------
    body.push_str("| Gate | Goal | Title | Verdict | Tier | Time | Mutation proof |\n");
    body.push_str("|---|---|---|---|---|---|---|\n");
    for r in rows {
        let verdict = if r.state == GateState::Pass {
            r.state.label().to_string()
        } else {
            format!("**{}**", r.state.label())
        };
        let time = r
            .secs
            .map(|s| format!("{s:.1}s"))
            .unwrap_or_else(|| "—".to_string());
        body.push_str(&format!(
            "| {} | {} | {} | {} | {} | {} | {} |\n",
            r.id,
            r.goal,
            escape_cell(r.title),
            verdict,
            r.tier.label(),
            time,
            escape_cell(&r.proof)
        ));
    }

    body.push_str(
        "\nThe `Mutation proof` cell reads `PROVEN @ <sha>`: the sha `--verify-mutations` was RUN \
         against. That is necessarily an ANCESTOR of the commit recording it — the run happens, \
         then its transcripts and ledger are committed — so an older sha there is the normal \
         state, not a stale one. `UNVERIFIED-SINCE <sha>` is the stale state: a path the mutation \
         declares as a target changed after the proof was taken.\n",
    );

    // --- per-gate detail, PASS INCLUDED ----------------------------------
    //
    // This section used to be `## Failures` and rendered `detail` only for
    // non-PASS rows. A gate's `detail` is where it records what its TITLE does not
    // cover — G0.5's arm (c) reporting "quantified over an empty set", G0.6's "39
    // not authored yet" — and under the old rule those qualifications were
    // unreachable from the artefact the moment their gate went green. The title
    // is what a compacted session inherits; a qualification that only prints on
    // failure is a qualification that is never read.
    //
    // Rows with nothing to say (a NOT-RUN pending gate whose body returns no
    // detail) are omitted rather than padded, so the section stays readable — but
    // a row is included whenever it is non-PASS OR has anything of its own to
    // report, which is exactly the set that could carry a qualification.
    let detailed: Vec<&Row> = rows
        .iter()
        .filter(|r| r.state != GateState::Pass || !r.detail.is_empty() || !r.findings.is_empty())
        .collect();
    if !detailed.is_empty() {
        body.push_str(
            "\n## Gate detail — in each gate's own words, PASS included\n\n\
             A green row is not the whole verdict. Read the gate's own line below before quoting \
             its title: this is where a PASS records the clause it could not reach, the set it \
             quantified over, or the part of its subject that does not exist yet.\n",
        );
        for r in detailed {
            body.push_str(&format!("### {} — {} [{}]\n", r.id, r.title, r.state.label()));
            if !r.detail.is_empty() {
                body.push_str(&format!("    {}\n", r.detail));
            }
            for f in &r.findings {
                body.push_str(&format!("    {f}\n"));
            }
        }
    }

    // --- assemble --------------------------------------------------------
    let mut out = String::new();
    out.push_str(BANNER);
    out.push('\n');
    out.push_str(&format!(
        "<!-- commit:      {}  ran: {}  host: {}  tier: {} -->\n",
        header.commit,
        header.ran,
        header.host,
        header.tier.label()
    ));
    // WHAT THE STAMPS MEAN, stated in the file itself.
    //
    // `commit:` is HEAD at the moment this file was generated. It is NOT the
    // commit that contains this file, and it cannot be: the content must exist
    // before the commit that carries it, so the sha of that commit is not
    // computable while writing it. The stamp therefore always names an ANCESTOR of
    // the commit you are reading it in — normally the parent. The same is true one
    // level down for `PROVEN @ <sha>` in the table.
    //
    // This is inherent, so it is DESCRIBED rather than "fixed": a reader who does
    // not know it reads an older sha as evidence the file is stale, and a reader
    // who assumes it names the containing commit reads the file as claiming more
    // than it can.
    out.push_str(
        "<!-- stamps:      `commit` is HEAD when this file was GENERATED, and `PROVEN @ <sha>` \
         below is the sha `--verify-mutations` RAN at. Both necessarily name an ANCESTOR of the \
         commit that contains them (content precedes its own commit sha), normally the parent. \
         Staleness is reported explicitly instead: see `full-tier` on the next line and the \
         STALE banner in the body. -->\n",
    );
    match &header.full_tier {
        Some((c, ran, host)) => {
            let mark = match header.full_tier_behind {
                Some(0) | None => String::new(),
                Some(n) => format!("  STALE (HEAD is {n} commits ahead)"),
            };
            out.push_str(&format!(
                "<!-- full-tier:   {c}  ran: {ran}  host: {host}{mark} -->\n"
            ));
        }
        None => out.push_str("<!-- full-tier:   (never run)  STALE -->\n"),
    }
    out.push_str(&body);

    // THE HASH COVERS THE STAMPS, not just the body.
    //
    // It used to cover `body` alone, and that left the header comments — the
    // `commit:` / `ran:` / `full-tier:` stamps — outside the integrity envelope.
    // Those stamps are the staleness clock the `stamps:` line two blocks up
    // tells the reader to trust, so the one part of this file that asserts "this
    // evidence is current" was the one part a hand edit could rewrite with the
    // recorded sha still matching. `full-tier: deadbeef  ran: 2099-01-01…` and
    // G0.1 reported PASS.
    //
    // `out` at this point is banner + stamps + body. Hashing it and appending
    // the trailer afterwards is what keeps the self-reference well-founded: the
    // digest covers every byte of the file EXCEPT the trailer line that carries
    // it, which is the only region a sha can cover without containing itself.
    let hashed = out;
    let mut file = String::with_capacity(hashed.len() + 96);
    file.push_str(&hashed);
    file.push_str(&format!(
        "\n{SHA_PREFIX}{} -->\n",
        sha256::hex(hashed.as_bytes())
    ));
    file
}

fn escape_cell(s: &str) -> String {
    s.replace('|', "\\|").replace('\n', " ")
}

fn goal_label(goal: u8) -> String {
    match goal {
        0 => "0 — cross-cutting (RULE ZERO harness)".into(),
        1 => "1 — session-bounded Model state sync".into(),
        2 => "2 — unified store, real SERIALIZABLE".into(),
        3 => "3 — easy + simple".into(),
        4 => "4 — notify clients of changesets".into(),
        5 => "5 — console admin access (read+write)".into(),
        n => format!("{n} — ?"),
    }
}

fn goal_label_short(goal: u8) -> String {
    goal.to_string()
}

/// Split a rendered `STATUS.md` into `(hashed-region, recorded-sha)`.
///
/// # What the hash covers
///
/// **Everything except the trailer line that carries it.** That is: the
/// `GENERATED` banner, the `commit: … ran: … host: … tier: …` stamp, the
/// `stamps:` explainer, the `full-tier: … ran: … host: … [STALE …]` stamp, and
/// the whole rendered body (goal roll-up, gate table with its per-gate timings,
/// and the per-gate detail section). Every byte a hand edit could touch is in
/// the digest, and the caller's comparison is therefore a real integrity check
/// rather than a check of the parts nobody would bother forging.
///
/// # What it does NOT cover, and why that is not a hole
///
/// The `<!-- body-sha256: … -->` trailer itself. A digest cannot contain
/// itself; excluding exactly that one line — and nothing else — is what makes
/// the self-reference well-founded. Rewriting the trailer alone still fails,
/// because the recorded value then disagrees with the digest of everything
/// above it.
///
/// # This is NOT the "does it match a fresh run" comparison
///
/// The stamps are wall-clock and git state: a regeneration a minute later
/// legitimately writes a different `ran:`, and one commit later a different
/// `commit:`. Hashing them is fine — the generator recomputes the digest over
/// whatever it just wrote — but *comparing two independent renders* over them
/// would fail on every run for no reason. That comparison
/// (`bluedb-gates --check`) uses [`reproducible_body`] instead, and the stamps
/// get their own dedicated staleness clocks there (`commit:` vs HEAD,
/// `full_tier_behind`). Keeping the two questions in two functions is the point:
/// "was this file edited by hand" and "is this file what a re-run would produce"
/// are different questions with different answers.
///
/// Returns `None` when the trailer is absent.
pub fn split_body_and_sha(text: &str) -> Option<(String, String)> {
    let idx = text.rfind(SHA_PREFIX)?;
    let recorded = text[idx + SHA_PREFIX.len()..]
        .split_whitespace()
        .next()?
        .to_string();
    let head = &text[..idx];
    // `render` appends "\n{SHA_PREFIX}…" after the hashed region, so drop that
    // one separator newline — and nothing else. Header lines stay in.
    let region = head.strip_suffix('\n').unwrap_or(head).to_string();
    Some((region, recorded))
}

/// The part of a rendered `STATUS.md` a re-run reproduces from the same inputs:
/// the body, with the `<!--` header comments dropped.
///
/// Used only by `bluedb-gates --check` to ask "does the committed file match a
/// fresh render". It deliberately excludes the header stamps, which a fresh
/// render always rewrites (new `ran:` wall-clock, possibly a new `commit:`) —
/// those are checked against HEAD and the full-tier ledger directly, not by
/// string equality against another render.
///
/// It is NOT an integrity boundary. [`split_body_and_sha`] is; this is a
/// freshness comparison, and pointing a hand-edit check at it is exactly the
/// defect that let `full-tier: deadbeef  ran: 2099-01-01T00:00:00Z` pass G0.1.
pub fn reproducible_body(text: &str) -> Option<String> {
    let idx = text.rfind(SHA_PREFIX)?;
    let head = &text[..idx];
    let body = head.strip_suffix('\n').unwrap_or(head);
    let body = body
        .lines()
        .skip_while(|l| l.starts_with("<!--"))
        .collect::<Vec<_>>()
        .join("\n");
    Some(format!("{body}\n").trim_end_matches('\n').to_string() + "\n")
}

/// Render the "Mutation proof" cell for one gate (§9.4's table + MAJOR-17).
pub fn proof_cell(
    gate_id: &str,
    mutation_ids: &[&str],
    ledger: &BTreeMap<String, (ProofOutcome, String)>,
    moved: &dyn Fn(&str, &str) -> bool,
) -> (String, bool) {
    let canary = gate_id == super::registry::CANARY_ID;
    let mut cells = Vec::new();
    let mut unknown = false;

    for id in mutation_ids {
        match ledger.get(*id) {
            None => {
                cells.push("—".to_string());
                unknown = true;
            }
            Some((ProofOutcome::Proven, sha)) => {
                if moved(id, sha) {
                    cells.push(format!("UNVERIFIED-SINCE {sha}"));
                    unknown = true;
                } else {
                    cells.push(format!("PROVEN @ {sha}"));
                }
            }
            Some((ProofOutcome::Vacuous, sha)) if canary => {
                if moved(id, sha) {
                    cells.push(format!("UNVERIFIED-SINCE {sha}"));
                    unknown = true;
                } else {
                    cells.push("VACUOUS ✔".to_string());
                }
            }
            Some((o, sha)) => {
                // VACUOUS on a non-canary gate, MUTATION-STALE, WRONG-TREE,
                // INCONCLUSIVE-BASELINE-RED — all non-PASS.
                cells.push(format!("{} @ {sha}", o.label()));
                unknown = true;
            }
        }
    }

    (cells.join("; "), unknown)
}

#[cfg(test)]
mod tests {
    use super::super::registry::REGISTRY;
    use super::*;

    fn row(id: &'static str, goal: u8, state: GateState) -> Row {
        Row {
            id,
            goal,
            title: "t",
            tier: Tier::Fast,
            state,
            secs: Some(0.1),
            detail: String::new(),
            findings: vec![],
            proof: "PROVEN @ abc".into(),
            proof_unknown: false,
        }
    }

    fn header() -> Header {
        Header {
            commit: "aaaaaaa".into(),
            ran: "2026-08-09T00:00:00Z".into(),
            host: "darwin/arm64".into(),
            tier: Tier::Fast,
            full_tier: Some(("bbbbbbb".into(), "2026-08-08T00:00:00Z".into(), "linux".into())),
            full_tier_behind: Some(0),
        }
    }

    #[test]
    fn body_sha_round_trips_through_split() {
        let out = render(&header(), &[row("G0.1", 0, GateState::Pass)]);
        let (body, sha) = split_body_and_sha(&out).expect("trailer present");
        assert_eq!(sha256::hex(body.as_bytes()), sha);
    }

    #[test]
    fn a_hand_edit_breaks_the_recorded_sha() {
        let out = render(&header(), &[row("G0.1", 0, GateState::Pass)]);
        let tampered = out.replace("BlueDB v2 — STATUS", "BlueDB v2 — STATUS (all green!)");
        let (body, sha) = split_body_and_sha(&tampered).unwrap();
        assert_ne!(sha256::hex(body.as_bytes()), sha);
    }

    /// The Judge's exact hand edit: rewrite the `full-tier:` stamp — the
    /// staleness clock the `stamps:` line tells readers to trust — and leave
    /// everything else, sha included, untouched. This used to round-trip
    /// cleanly, so G0.1 reported PASS over a document claiming its hardest
    /// gates had run in 2099.
    #[test]
    fn editing_the_full_tier_stamp_breaks_the_recorded_sha() {
        let out = render(&header(), &[row("G0.1", 0, GateState::Pass)]);
        let tampered = out.replace(
            "<!-- full-tier:   bbbbbbb  ran: 2026-08-08T00:00:00Z  host: linux -->",
            "<!-- full-tier:   deadbeef  ran: 2099-01-01T00:00:00Z  host: linux -->",
        );
        assert_ne!(tampered, out, "the fixture must actually contain the stamp");

        let (region, sha) = split_body_and_sha(&tampered).unwrap();
        assert_ne!(
            sha256::hex(region.as_bytes()),
            sha,
            "the full-tier staleness stamp must be inside the integrity envelope"
        );
    }

    /// Same for the fast-tier stamp line and the GENERATED banner: the whole
    /// header is covered, not just the one line the regression was found on.
    #[test]
    fn editing_any_header_line_breaks_the_recorded_sha() {
        let out = render(&header(), &[row("G0.1", 0, GateState::Pass)]);
        for (from, to) in [
            ("commit:      aaaaaaa", "commit:      ffffff0"),
            ("ran: 2026-08-09T00:00:00Z", "ran: 2099-01-01T00:00:00Z"),
            ("tier: fast", "tier: full"),
            ("DO NOT EDIT.", "DO NOT EDIT!"),
        ] {
            let tampered = out.replace(from, to);
            assert_ne!(tampered, out, "fixture must contain {from:?}");
            let (region, sha) = split_body_and_sha(&tampered).unwrap();
            assert_ne!(
                sha256::hex(region.as_bytes()),
                sha,
                "hand edit to {from:?} went undetected"
            );
        }
    }

    /// The one region the digest cannot cover is the digest. Forging it alone
    /// must still be caught, or "excluded from the hash" would be a hole rather
    /// than a well-foundedness requirement.
    #[test]
    fn rewriting_the_sha_trailer_alone_is_still_caught() {
        let out = render(&header(), &[row("G0.1", 0, GateState::Pass)]);
        let (_, real) = split_body_and_sha(&out).unwrap();
        let tampered = out.replace(&real, &"0".repeat(real.len()));
        let (region, sha) = split_body_and_sha(&tampered).unwrap();
        assert_ne!(sha256::hex(region.as_bytes()), sha);
    }

    /// `--check`'s freshness comparison must NOT see the stamps, or it would go
    /// red on the wall clock alone. Two renders that differ only in `ran:` and
    /// `commit:` have the same reproducible body — and different digests.
    #[test]
    fn reproducible_body_excludes_the_stamps_that_every_run_rewrites() {
        let a = render(&header(), &[row("G0.1", 0, GateState::Pass)]);
        let mut h = header();
        h.commit = "ccccccc".into();
        h.ran = "2026-08-09T00:00:01Z".into();
        let b = render(&h, &[row("G0.1", 0, GateState::Pass)]);

        assert_ne!(a, b, "the stamps really did change");
        assert_eq!(
            reproducible_body(&a).unwrap(),
            reproducible_body(&b).unwrap(),
            "a re-run one second later must not read as a content change"
        );
        assert_ne!(
            split_body_and_sha(&a).unwrap().1,
            split_body_and_sha(&b).unwrap().1,
            "…while the integrity digest DOES move, because it covers the stamps"
        );
    }

    /// The hashed region is the whole file minus the trailer — asserted
    /// positively, so a future edit that quietly re-narrows it fails here.
    #[test]
    fn the_hashed_region_is_the_whole_file_minus_the_trailer() {
        let out = render(&header(), &[row("G0.1", 0, GateState::Pass)]);
        let (region, _) = split_body_and_sha(&out).unwrap();
        assert!(region.starts_with(BANNER));
        assert!(region.contains("<!-- commit:      aaaaaaa"));
        assert!(region.contains("<!-- full-tier:   bbbbbbb"));
        assert!(region.contains("# BlueDB v2 — STATUS"));
        assert!(!region.contains(SHA_PREFIX));
        assert_eq!(out, format!("{region}\n{SHA_PREFIX}{} -->\n", sha256::hex(region.as_bytes())));
    }

    #[test]
    fn a_not_run_gate_renders_its_goal_unknown_not_pass() {
        let out = render(
            &header(),
            &[
                row("G1.1", 1, GateState::Pass),
                row("G1.2", 1, GateState::NotRun),
            ],
        );
        assert!(out.contains("| 1 — session-bounded Model state sync | **UNKNOWN** |"));
        assert!(!out.contains("| 1 — session-bounded Model state sync | **PASS** |"));
    }

    #[test]
    fn every_registered_gate_appears_even_when_none_ran() {
        // The H2 property, asserted directly: render with every gate NOT RUN
        // and confirm the table still enumerates the whole registry.
        let rows: Vec<Row> = REGISTRY
            .iter()
            .map(|g| Row {
                id: g.id,
                goal: g.goal,
                title: g.title,
                tier: g.tier,
                state: GateState::NotRun,
                secs: None,
                detail: String::new(),
                findings: vec![],
                proof: "—".into(),
                proof_unknown: true,
            })
            .collect();
        let out = render(&header(), &rows);
        for g in REGISTRY {
            assert!(out.contains(&format!("| {} |", g.id)), "{} missing", g.id);
        }
        assert!(!out.contains("**PASS**"));
    }

    #[test]
    fn proof_cell_decays_to_unverified_since() {
        let mut ledger = BTreeMap::new();
        ledger.insert("G0.2/m".to_string(), (ProofOutcome::Proven, "abc1234".to_string()));

        let (cell, unknown) = proof_cell("G0.2", &["G0.2/m"], &ledger, &|_, _| false);
        assert_eq!(cell, "PROVEN @ abc1234");
        assert!(!unknown);

        let (cell, unknown) = proof_cell("G0.2", &["G0.2/m"], &ledger, &|_, _| true);
        assert_eq!(cell, "UNVERIFIED-SINCE abc1234");
        assert!(unknown, "an unrevalidated proof must render the goal UNKNOWN");
    }

    #[test]
    fn canary_vacuous_is_the_pass_state_only_for_the_canary() {
        let mut ledger = BTreeMap::new();
        ledger.insert("G0.C/noop".to_string(), (ProofOutcome::Vacuous, "abc".to_string()));
        let (cell, unknown) = proof_cell("G0.C", &["G0.C/noop"], &ledger, &|_, _| false);
        assert_eq!(cell, "VACUOUS ✔");
        assert!(!unknown);

        let mut ledger = BTreeMap::new();
        ledger.insert("G0.2/m".to_string(), (ProofOutcome::Vacuous, "abc".to_string()));
        let (_, unknown) = proof_cell("G0.2", &["G0.2/m"], &ledger, &|_, _| false);
        assert!(unknown, "VACUOUS on a real gate means the gate is a green lie");
    }

    #[test]
    fn missing_proof_is_not_silently_green() {
        let ledger = BTreeMap::new();
        let (cell, unknown) = proof_cell("G0.2", &["G0.2/m"], &ledger, &|_, _| false);
        assert_eq!(cell, "—");
        assert!(unknown);
    }
}
