// Code generated by sky-ffi-inspect from fyne.io/fyne/v2/app. DO NOT EDIT.
// Re-run `sky add fyne.io/fyne/v2/app` to regenerate.
//
// Wrapper functions are in `package rt` with names <Kernel>_<lowerFn>.
// Sky source resolves `import Fyne.Io.Fyne.V2.App as X` and calls `X.<lowerFn>` — the canonicaliser routes it via
// the FFI registry to these typed Go functions. Every wrapper wraps
// panics in Err[any, any] via SkyFfiRecover.

package rt

import (
	pkg "fyne.io/fyne/v2/app"
	"fmt"
	fyne "fyne.io/fyne/v2"
)

type FfiT_Go_App_new_R = fyne.App
// [pure] typed wrapper for Go_App_new (P7 adaptor target)
func Go_App_newT() (out SkyResult[any, fyne.App]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[any,fyne.App](pkg.New())
	return
}

type FfiT_Go_App_newWithID_R = fyne.App
// [pure] typed wrapper for Go_App_newWithID (P7 adaptor target)
func Go_App_newWithIDT(arg0 string) (out SkyResult[any, fyne.App]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[any,fyne.App](pkg.NewWithID(arg0))
	return
}

type FfiT_Go_App_setMetadata_P0 = fyne.AppMetadata
// [pure] typed wrapper for Go_App_setMetadata (P7 adaptor target)
func Go_App_setMetadataT(arg0 fyne.AppMetadata) (out SkyResult[any, struct{}]) {
	defer SkyFfiRecoverT(&out)()
	pkg.SetMetadata(arg0)
	out = Ok[any,struct{}](struct{}{})
	return
}

type FfiT_Go_App_settingsSchemaStoragePath_P0 = *pkg.SettingsSchema
// [pure] typed wrapper for Go_App_settingsSchemaStoragePath (P7 adaptor target)
func Go_App_settingsSchemaStoragePathT(arg0 *pkg.SettingsSchema) (out SkyResult[any, string]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[any,string](arg0.StoragePath())
	return
}

type FfiT_Go_App_settingsSchemaThemeName_P0 = *pkg.SettingsSchema
func Go_App_settingsSchemaThemeNameT(arg0 *pkg.SettingsSchema) string { return arg0.ThemeName }

type FfiT_Go_App_settingsSchemaSetThemeName_P1 = *pkg.SettingsSchema
func Go_App_settingsSchemaSetThemeNameT(value string, recv *pkg.SettingsSchema) *pkg.SettingsSchema { recv.ThemeName = value; return recv }

type FfiT_Go_App_settingsSchemaScale_P0 = *pkg.SettingsSchema
func Go_App_settingsSchemaScaleT(arg0 *pkg.SettingsSchema) float32 { return arg0.Scale }

type FfiT_Go_App_settingsSchemaSetScale_P1 = *pkg.SettingsSchema
func Go_App_settingsSchemaSetScaleT(value float32, recv *pkg.SettingsSchema) *pkg.SettingsSchema { recv.Scale = value; return recv }

type FfiT_Go_App_settingsSchemaPrimaryColor_P0 = *pkg.SettingsSchema
func Go_App_settingsSchemaPrimaryColorT(arg0 *pkg.SettingsSchema) string { return arg0.PrimaryColor }

type FfiT_Go_App_settingsSchemaSetPrimaryColor_P1 = *pkg.SettingsSchema
func Go_App_settingsSchemaSetPrimaryColorT(value string, recv *pkg.SettingsSchema) *pkg.SettingsSchema { recv.PrimaryColor = value; return recv }

type FfiT_Go_App_settingsSchemaCloudName_P0 = *pkg.SettingsSchema
func Go_App_settingsSchemaCloudNameT(arg0 *pkg.SettingsSchema) string { return arg0.CloudName }

type FfiT_Go_App_settingsSchemaSetCloudName_P1 = *pkg.SettingsSchema
func Go_App_settingsSchemaSetCloudNameT(value string, recv *pkg.SettingsSchema) *pkg.SettingsSchema { recv.CloudName = value; return recv }

type FfiT_Go_App_settingsSchemaCloudConfig_P0 = *pkg.SettingsSchema
func Go_App_settingsSchemaCloudConfigT(arg0 *pkg.SettingsSchema) string { return arg0.CloudConfig }

type FfiT_Go_App_settingsSchemaSetCloudConfig_P1 = *pkg.SettingsSchema
func Go_App_settingsSchemaSetCloudConfigT(value string, recv *pkg.SettingsSchema) *pkg.SettingsSchema { recv.CloudConfig = value; return recv }

type FfiT_Go_App_settingsSchemaDisableAnimations_P0 = *pkg.SettingsSchema
func Go_App_settingsSchemaDisableAnimationsT(arg0 *pkg.SettingsSchema) bool { return arg0.DisableAnimations }

type FfiT_Go_App_settingsSchemaSetDisableAnimations_P1 = *pkg.SettingsSchema
func Go_App_settingsSchemaSetDisableAnimationsT(value bool, recv *pkg.SettingsSchema) *pkg.SettingsSchema { recv.DisableAnimations = value; return recv }

func Go_App_newSettingsSchema(_ any) any { return new(pkg.SettingsSchema) }


// Pin fmt against "imported and not used" across partial files.
var _ = fmt.Sprintf
