// Code generated by sky-ffi-inspect from github.com/gorilla/mux. DO NOT EDIT.
// Re-run `sky add github.com/gorilla/mux` to regenerate.
// Surface format 3 (sky install regenerates a surface stamped otherwise).
//
// Wrapper functions are in `package skyffi` (a dot-import of base `rt`) with names <Kernel>_<lowerFn>.
// Sky source resolves `import Github.Com.Gorilla.Mux as X` and calls `X.<lowerFn>` — the canonicaliser routes it via
// the FFI registry to these typed Go functions. Every wrapper wraps
// panics and failed conversions in an Err via SkyFfiGuard(T).

package skyffi

import (
	. "sky-app/rt"
	pkg "github.com/gorilla/mux"
	"fmt"
	http "net/http"
	_ "net/url"  // aliased url; unused in emitted wrappers
)

// [pure] typed wrapper for Go_Mux_cORSMethodMiddleware (P7 adaptor target)
func Go_Mux_cORSMethodMiddlewareT(arg0 any) (out SkyResult[any, any]) {
	defer SkyFfiGuardT(&out)()
	out = Ok[any,any](FfiRet(pkg.CORSMethodMiddleware(FfiArg[*pkg.Router](arg0))))
	return
}

// [pure] typed wrapper for Go_Mux_currentRoute (P7 adaptor target)
func Go_Mux_currentRouteT(arg0 any) (out SkyResult[any, any]) {
	defer SkyFfiGuardT(&out)()
	out = Ok[any,any](FfiRet(pkg.CurrentRoute(FfiArg[*http.Request](arg0))))
	return
}

func Go_Mux_errMethodMismatch(_ any) (out any) {
	defer SkyFfiGuard(&out)()
	out = Ok[any, any](FfiRet(pkg.ErrMethodMismatch))
	return
}

func Go_Mux_errNotFound(_ any) (out any) {
	defer SkyFfiGuard(&out)()
	out = Ok[any, any](FfiRet(pkg.ErrNotFound))
	return
}

// [pure] typed wrapper for Go_Mux_matcherFuncMatch (P7 adaptor target)
func Go_Mux_matcherFuncMatchT(arg0 any, arg1 any, arg2 any) (out SkyResult[any, bool]) {
	defer SkyFfiGuardT(&out)()
	recv := FfiArg[pkg.MatcherFunc](arg0)
	out = Ok[any,bool](recv.Match(FfiArg[*http.Request](arg1), FfiArg[*pkg.RouteMatch](arg2)))
	return
}

// [pure] typed wrapper for Go_Mux_middlewareFuncMiddleware (P7 adaptor target)
func Go_Mux_middlewareFuncMiddlewareT(arg0 any, arg1 any) (out SkyResult[any, any]) {
	defer SkyFfiGuardT(&out)()
	recv := FfiArg[pkg.MiddlewareFunc](arg0)
	out = Ok[any,any](FfiRet(recv.Middleware(FfiArg[http.Handler](arg1))))
	return
}

func Go_Mux_newRoute(_ any) any { return Ok[any, any](FfiRet(new(pkg.Route))) }

func Go_Mux_newRouteMatch(_ any) any { return Ok[any, any](FfiRet(new(pkg.RouteMatch))) }

// [pure] typed wrapper for Go_Mux_newRouter (P7 adaptor target)
func Go_Mux_newRouterT() (out SkyResult[any, any]) {
	defer SkyFfiGuardT(&out)()
	out = Ok[any,any](FfiRet(pkg.NewRouter()))
	return
}

// [pure] typed wrapper for Go_Mux_routeBuildOnly (P7 adaptor target)
func Go_Mux_routeBuildOnlyT(arg0 any) (out SkyResult[any, any]) {
	defer SkyFfiGuardT(&out)()
	recv := FfiArg[*pkg.Route](arg0)
	if recv == nil { out = Err[any,any](ErrFfi("nil receiver: Route.BuildOnly")); return }
	out = Ok[any,any](FfiRet(recv.BuildOnly()))
	return
}

// [pure] typed wrapper for Go_Mux_routeBuildVarsFunc (P7 adaptor target)
func Go_Mux_routeBuildVarsFuncT(arg0 any, arg1 any) (out SkyResult[any, any]) {
	defer SkyFfiGuardT(&out)()
	recv := FfiArg[*pkg.Route](arg0)
	if recv == nil { out = Err[any,any](ErrFfi("nil receiver: Route.BuildVarsFunc")); return }
	out = Ok[any,any](FfiRet(recv.BuildVarsFunc(FfiArg[pkg.BuildVarsFunc](arg1))))
	return
}

// [fallible] typed wrapper for Go_Mux_routeGetError (P7 adaptor target)
func Go_Mux_routeGetErrorT(arg0 any) (out SkyResult[any, struct{}]) {
	defer SkyFfiGuardT(&out)()
	recv := FfiArg[*pkg.Route](arg0)
	if recv == nil { out = Err[any,struct{}](ErrFfi("nil receiver: Route.GetError")); return }
	err := recv.GetError()
	if err != nil { out = Err[any,struct{}](ErrFfi(err.Error())); return }
	out = Ok[any,struct{}](struct{}{})
	return
}

// [pure] typed wrapper for Go_Mux_routeGetHandler (P7 adaptor target)
func Go_Mux_routeGetHandlerT(arg0 any) (out SkyResult[any, any]) {
	defer SkyFfiGuardT(&out)()
	recv := FfiArg[*pkg.Route](arg0)
	if recv == nil { out = Err[any,any](ErrFfi("nil receiver: Route.GetHandler")); return }
	out = Ok[any,any](FfiRet(recv.GetHandler()))
	return
}

// [fallible] typed wrapper for Go_Mux_routeGetHostTemplate (P7 adaptor target)
func Go_Mux_routeGetHostTemplateT(arg0 any) (out SkyResult[any, string]) {
	defer SkyFfiGuardT(&out)()
	recv := FfiArg[*pkg.Route](arg0)
	if recv == nil { out = Err[any,string](ErrFfi("nil receiver: Route.GetHostTemplate")); return }
	r0, err := recv.GetHostTemplate()
	if err != nil { out = Err[any,string](ErrFfi(err.Error())); return }
	out = Ok[any,string](r0)
	return
}

// [fallible] typed wrapper for Go_Mux_routeGetMethods (P7 adaptor target)
func Go_Mux_routeGetMethodsT(arg0 any) (out SkyResult[any, any]) {
	defer SkyFfiGuardT(&out)()
	recv := FfiArg[*pkg.Route](arg0)
	if recv == nil { out = Err[any,any](ErrFfi("nil receiver: Route.GetMethods")); return }
	r0, err := recv.GetMethods()
	if err != nil { out = Err[any,any](ErrFfi(err.Error())); return }
	out = Ok[any,any](FfiRet(r0))
	return
}

// [pure] typed wrapper for Go_Mux_routeGetName (P7 adaptor target)
func Go_Mux_routeGetNameT(arg0 any) (out SkyResult[any, string]) {
	defer SkyFfiGuardT(&out)()
	recv := FfiArg[*pkg.Route](arg0)
	if recv == nil { out = Err[any,string](ErrFfi("nil receiver: Route.GetName")); return }
	out = Ok[any,string](recv.GetName())
	return
}

// [fallible] typed wrapper for Go_Mux_routeGetPathRegexp (P7 adaptor target)
func Go_Mux_routeGetPathRegexpT(arg0 any) (out SkyResult[any, string]) {
	defer SkyFfiGuardT(&out)()
	recv := FfiArg[*pkg.Route](arg0)
	if recv == nil { out = Err[any,string](ErrFfi("nil receiver: Route.GetPathRegexp")); return }
	r0, err := recv.GetPathRegexp()
	if err != nil { out = Err[any,string](ErrFfi(err.Error())); return }
	out = Ok[any,string](r0)
	return
}

// [fallible] typed wrapper for Go_Mux_routeGetPathTemplate (P7 adaptor target)
func Go_Mux_routeGetPathTemplateT(arg0 any) (out SkyResult[any, string]) {
	defer SkyFfiGuardT(&out)()
	recv := FfiArg[*pkg.Route](arg0)
	if recv == nil { out = Err[any,string](ErrFfi("nil receiver: Route.GetPathTemplate")); return }
	r0, err := recv.GetPathTemplate()
	if err != nil { out = Err[any,string](ErrFfi(err.Error())); return }
	out = Ok[any,string](r0)
	return
}

// [fallible] typed wrapper for Go_Mux_routeGetQueriesRegexp (P7 adaptor target)
func Go_Mux_routeGetQueriesRegexpT(arg0 any) (out SkyResult[any, any]) {
	defer SkyFfiGuardT(&out)()
	recv := FfiArg[*pkg.Route](arg0)
	if recv == nil { out = Err[any,any](ErrFfi("nil receiver: Route.GetQueriesRegexp")); return }
	r0, err := recv.GetQueriesRegexp()
	if err != nil { out = Err[any,any](ErrFfi(err.Error())); return }
	out = Ok[any,any](FfiRet(r0))
	return
}

// [fallible] typed wrapper for Go_Mux_routeGetQueriesTemplates (P7 adaptor target)
func Go_Mux_routeGetQueriesTemplatesT(arg0 any) (out SkyResult[any, any]) {
	defer SkyFfiGuardT(&out)()
	recv := FfiArg[*pkg.Route](arg0)
	if recv == nil { out = Err[any,any](ErrFfi("nil receiver: Route.GetQueriesTemplates")); return }
	r0, err := recv.GetQueriesTemplates()
	if err != nil { out = Err[any,any](ErrFfi(err.Error())); return }
	out = Ok[any,any](FfiRet(r0))
	return
}

// [fallible] typed wrapper for Go_Mux_routeGetVarNames (P7 adaptor target)
func Go_Mux_routeGetVarNamesT(arg0 any) (out SkyResult[any, any]) {
	defer SkyFfiGuardT(&out)()
	recv := FfiArg[*pkg.Route](arg0)
	if recv == nil { out = Err[any,any](ErrFfi("nil receiver: Route.GetVarNames")); return }
	r0, err := recv.GetVarNames()
	if err != nil { out = Err[any,any](ErrFfi(err.Error())); return }
	out = Ok[any,any](FfiRet(r0))
	return
}

// [pure] typed wrapper for Go_Mux_routeHandler (P7 adaptor target)
func Go_Mux_routeHandlerT(arg0 any, arg1 any) (out SkyResult[any, any]) {
	defer SkyFfiGuardT(&out)()
	recv := FfiArg[*pkg.Route](arg0)
	if recv == nil { out = Err[any,any](ErrFfi("nil receiver: Route.Handler")); return }
	out = Ok[any,any](FfiRet(recv.Handler(FfiArg[http.Handler](arg1))))
	return
}

// [pure] typed wrapper for Go_Mux_routeHandlerFunc (P7 adaptor target)
func Go_Mux_routeHandlerFuncT(arg0 any, arg1 any) (out SkyResult[any, any]) {
	defer SkyFfiGuardT(&out)()
	recv := FfiArg[*pkg.Route](arg0)
	if recv == nil { out = Err[any,any](ErrFfi("nil receiver: Route.HandlerFunc")); return }
	out = Ok[any,any](FfiRet(recv.HandlerFunc(FfiArg[func(http.ResponseWriter, *http.Request)](arg1))))
	return
}

// [pure] typed wrapper for Go_Mux_routeHeaders (P7 adaptor target)
func Go_Mux_routeHeadersT(arg0 any, arg1 any) (out SkyResult[any, any]) {
	defer SkyFfiGuardT(&out)()
	recv := FfiArg[*pkg.Route](arg0)
	if recv == nil { out = Err[any,any](ErrFfi("nil receiver: Route.Headers")); return }
	out = Ok[any,any](FfiRet(recv.Headers(FfiArg[[]string](arg1)...)))
	return
}

// [pure] typed wrapper for Go_Mux_routeHeadersRegexp (P7 adaptor target)
func Go_Mux_routeHeadersRegexpT(arg0 any, arg1 any) (out SkyResult[any, any]) {
	defer SkyFfiGuardT(&out)()
	recv := FfiArg[*pkg.Route](arg0)
	if recv == nil { out = Err[any,any](ErrFfi("nil receiver: Route.HeadersRegexp")); return }
	out = Ok[any,any](FfiRet(recv.HeadersRegexp(FfiArg[[]string](arg1)...)))
	return
}

// [pure] typed wrapper for Go_Mux_routeHost (P7 adaptor target)
func Go_Mux_routeHostT(arg0 any, arg1 string) (out SkyResult[any, any]) {
	defer SkyFfiGuardT(&out)()
	recv := FfiArg[*pkg.Route](arg0)
	if recv == nil { out = Err[any,any](ErrFfi("nil receiver: Route.Host")); return }
	out = Ok[any,any](FfiRet(recv.Host(arg1)))
	return
}

// [pure] typed wrapper for Go_Mux_routeMatch (P7 adaptor target)
func Go_Mux_routeMatchT(arg0 any, arg1 any, arg2 any) (out SkyResult[any, bool]) {
	defer SkyFfiGuardT(&out)()
	recv := FfiArg[*pkg.Route](arg0)
	if recv == nil { out = Err[any,bool](ErrFfi("nil receiver: Route.Match")); return }
	out = Ok[any,bool](recv.Match(FfiArg[*http.Request](arg1), FfiArg[*pkg.RouteMatch](arg2)))
	return
}

func Go_Mux_routeMatchHandlerT(arg0 any) (out SkyResult[any, any]) {
	defer SkyFfiGuardT(&out)()
	recv := FfiArg[*pkg.RouteMatch](arg0)
	if recv == nil { out = Err[any, any](ErrFfi("Handler: nil receiver")); return }
	out = Ok[any, any](FfiRet(recv.Handler))
	return
}
func Go_Mux_routeMatchHandler(arg0 any) any { return SkyFfiFieldGet3(arg0, "Handler") }

func Go_Mux_routeMatchMatchErrT(arg0 any) (out SkyResult[any, any]) {
	defer SkyFfiGuardT(&out)()
	recv := FfiArg[*pkg.RouteMatch](arg0)
	if recv == nil { out = Err[any, any](ErrFfi("MatchErr: nil receiver")); return }
	out = Ok[any, any](FfiRet(recv.MatchErr))
	return
}
func Go_Mux_routeMatchMatchErr(arg0 any) any { return SkyFfiFieldGet3(arg0, "MatchErr") }

func Go_Mux_routeMatchRouteT(arg0 any) (out SkyResult[any, any]) {
	defer SkyFfiGuardT(&out)()
	recv := FfiArg[*pkg.RouteMatch](arg0)
	if recv == nil { out = Err[any, any](ErrFfi("Route: nil receiver")); return }
	out = Ok[any, any](FfiRet(recv.Route))
	return
}
func Go_Mux_routeMatchRoute(arg0 any) any { return SkyFfiFieldGet3(arg0, "Route") }

func Go_Mux_routeMatchSetHandlerT(value any, recv any) (out SkyResult[any, any]) {
	defer SkyFfiGuardT(&out)()
	r := FfiArg[*pkg.RouteMatch](recv)
	if r == nil { out = Err[any, any](ErrFfi("Handler: nil receiver")); return }
	r.Handler = FfiArg[http.Handler](value)
	out = Ok[any, any](FfiRet(r))
	return
}
func Go_Mux_routeMatchSetHandler(value any, recv any) any { return SkyFfiFieldSet3(value, recv, "Handler") }

func Go_Mux_routeMatchSetRouteT(value any, recv any) (out SkyResult[any, any]) {
	defer SkyFfiGuardT(&out)()
	r := FfiArg[*pkg.RouteMatch](recv)
	if r == nil { out = Err[any, any](ErrFfi("Route: nil receiver")); return }
	r.Route = FfiArg[*pkg.Route](value)
	out = Ok[any, any](FfiRet(r))
	return
}
func Go_Mux_routeMatchSetRoute(value any, recv any) any { return SkyFfiFieldSet3(value, recv, "Route") }

func Go_Mux_routeMatchSetVarsT(value any, recv any) (out SkyResult[any, any]) {
	defer SkyFfiGuardT(&out)()
	r := FfiArg[*pkg.RouteMatch](recv)
	if r == nil { out = Err[any, any](ErrFfi("Vars: nil receiver")); return }
	r.Vars = FfiArg[map[string]string](value)
	out = Ok[any, any](FfiRet(r))
	return
}
func Go_Mux_routeMatchSetVars(value any, recv any) any { return SkyFfiFieldSet3(value, recv, "Vars") }

func Go_Mux_routeMatchVarsT(arg0 any) (out SkyResult[any, any]) {
	defer SkyFfiGuardT(&out)()
	recv := FfiArg[*pkg.RouteMatch](arg0)
	if recv == nil { out = Err[any, any](ErrFfi("Vars: nil receiver")); return }
	out = Ok[any, any](FfiRet(recv.Vars))
	return
}
func Go_Mux_routeMatchVars(arg0 any) any { return SkyFfiFieldGet3(arg0, "Vars") }

// [pure] typed wrapper for Go_Mux_routeMatcherFunc (P7 adaptor target)
func Go_Mux_routeMatcherFuncT(arg0 any, arg1 any) (out SkyResult[any, any]) {
	defer SkyFfiGuardT(&out)()
	recv := FfiArg[*pkg.Route](arg0)
	if recv == nil { out = Err[any,any](ErrFfi("nil receiver: Route.MatcherFunc")); return }
	out = Ok[any,any](FfiRet(recv.MatcherFunc(FfiArg[pkg.MatcherFunc](arg1))))
	return
}

// [pure] typed wrapper for Go_Mux_routeMethods (P7 adaptor target)
func Go_Mux_routeMethodsT(arg0 any, arg1 any) (out SkyResult[any, any]) {
	defer SkyFfiGuardT(&out)()
	recv := FfiArg[*pkg.Route](arg0)
	if recv == nil { out = Err[any,any](ErrFfi("nil receiver: Route.Methods")); return }
	out = Ok[any,any](FfiRet(recv.Methods(FfiArg[[]string](arg1)...)))
	return
}

// [pure] typed wrapper for Go_Mux_routeName (P7 adaptor target)
func Go_Mux_routeNameT(arg0 any, arg1 string) (out SkyResult[any, any]) {
	defer SkyFfiGuardT(&out)()
	recv := FfiArg[*pkg.Route](arg0)
	if recv == nil { out = Err[any,any](ErrFfi("nil receiver: Route.Name")); return }
	out = Ok[any,any](FfiRet(recv.Name(arg1)))
	return
}

// [pure] typed wrapper for Go_Mux_routePath (P7 adaptor target)
func Go_Mux_routePathT(arg0 any, arg1 string) (out SkyResult[any, any]) {
	defer SkyFfiGuardT(&out)()
	recv := FfiArg[*pkg.Route](arg0)
	if recv == nil { out = Err[any,any](ErrFfi("nil receiver: Route.Path")); return }
	out = Ok[any,any](FfiRet(recv.Path(arg1)))
	return
}

// [pure] typed wrapper for Go_Mux_routePathPrefix (P7 adaptor target)
func Go_Mux_routePathPrefixT(arg0 any, arg1 string) (out SkyResult[any, any]) {
	defer SkyFfiGuardT(&out)()
	recv := FfiArg[*pkg.Route](arg0)
	if recv == nil { out = Err[any,any](ErrFfi("nil receiver: Route.PathPrefix")); return }
	out = Ok[any,any](FfiRet(recv.PathPrefix(arg1)))
	return
}

// [pure] typed wrapper for Go_Mux_routeQueries (P7 adaptor target)
func Go_Mux_routeQueriesT(arg0 any, arg1 any) (out SkyResult[any, any]) {
	defer SkyFfiGuardT(&out)()
	recv := FfiArg[*pkg.Route](arg0)
	if recv == nil { out = Err[any,any](ErrFfi("nil receiver: Route.Queries")); return }
	out = Ok[any,any](FfiRet(recv.Queries(FfiArg[[]string](arg1)...)))
	return
}

// [pure] typed wrapper for Go_Mux_routeSchemes (P7 adaptor target)
func Go_Mux_routeSchemesT(arg0 any, arg1 any) (out SkyResult[any, any]) {
	defer SkyFfiGuardT(&out)()
	recv := FfiArg[*pkg.Route](arg0)
	if recv == nil { out = Err[any,any](ErrFfi("nil receiver: Route.Schemes")); return }
	out = Ok[any,any](FfiRet(recv.Schemes(FfiArg[[]string](arg1)...)))
	return
}

// [pure] typed wrapper for Go_Mux_routeSkipClean (P7 adaptor target)
func Go_Mux_routeSkipCleanT(arg0 any) (out SkyResult[any, bool]) {
	defer SkyFfiGuardT(&out)()
	recv := FfiArg[*pkg.Route](arg0)
	if recv == nil { out = Err[any,bool](ErrFfi("nil receiver: Route.SkipClean")); return }
	out = Ok[any,bool](recv.SkipClean())
	return
}

// [pure] typed wrapper for Go_Mux_routeSubrouter (P7 adaptor target)
func Go_Mux_routeSubrouterT(arg0 any) (out SkyResult[any, any]) {
	defer SkyFfiGuardT(&out)()
	recv := FfiArg[*pkg.Route](arg0)
	if recv == nil { out = Err[any,any](ErrFfi("nil receiver: Route.Subrouter")); return }
	out = Ok[any,any](FfiRet(recv.Subrouter()))
	return
}

// [fallible] typed wrapper for Go_Mux_routeURL (P7 adaptor target)
func Go_Mux_routeURLT(arg0 any, arg1 any) (out SkyResult[any, any]) {
	defer SkyFfiGuardT(&out)()
	recv := FfiArg[*pkg.Route](arg0)
	if recv == nil { out = Err[any,any](ErrFfi("nil receiver: Route.URL")); return }
	r0, err := recv.URL(FfiArg[[]string](arg1)...)
	if err != nil { out = Err[any,any](ErrFfi(err.Error())); return }
	out = Ok[any,any](FfiRet(r0))
	return
}

// [fallible] typed wrapper for Go_Mux_routeURLHost (P7 adaptor target)
func Go_Mux_routeURLHostT(arg0 any, arg1 any) (out SkyResult[any, any]) {
	defer SkyFfiGuardT(&out)()
	recv := FfiArg[*pkg.Route](arg0)
	if recv == nil { out = Err[any,any](ErrFfi("nil receiver: Route.URLHost")); return }
	r0, err := recv.URLHost(FfiArg[[]string](arg1)...)
	if err != nil { out = Err[any,any](ErrFfi(err.Error())); return }
	out = Ok[any,any](FfiRet(r0))
	return
}

// [fallible] typed wrapper for Go_Mux_routeURLPath (P7 adaptor target)
func Go_Mux_routeURLPathT(arg0 any, arg1 any) (out SkyResult[any, any]) {
	defer SkyFfiGuardT(&out)()
	recv := FfiArg[*pkg.Route](arg0)
	if recv == nil { out = Err[any,any](ErrFfi("nil receiver: Route.URLPath")); return }
	r0, err := recv.URLPath(FfiArg[[]string](arg1)...)
	if err != nil { out = Err[any,any](ErrFfi(err.Error())); return }
	out = Ok[any,any](FfiRet(r0))
	return
}

// [pure] typed wrapper for Go_Mux_routerBuildVarsFunc (P7 adaptor target)
func Go_Mux_routerBuildVarsFuncT(arg0 any, arg1 any) (out SkyResult[any, any]) {
	defer SkyFfiGuardT(&out)()
	recv := FfiArg[*pkg.Router](arg0)
	if recv == nil { out = Err[any,any](ErrFfi("nil receiver: Router.BuildVarsFunc")); return }
	out = Ok[any,any](FfiRet(recv.BuildVarsFunc(FfiArg[pkg.BuildVarsFunc](arg1))))
	return
}

// [pure] typed wrapper for Go_Mux_routerGet (P7 adaptor target)
func Go_Mux_routerGetT(arg0 any, arg1 string) (out SkyResult[any, any]) {
	defer SkyFfiGuardT(&out)()
	recv := FfiArg[*pkg.Router](arg0)
	if recv == nil { out = Err[any,any](ErrFfi("nil receiver: Router.Get")); return }
	out = Ok[any,any](FfiRet(recv.Get(arg1)))
	return
}

// [pure] typed wrapper for Go_Mux_routerGetRoute (P7 adaptor target)
func Go_Mux_routerGetRouteT(arg0 any, arg1 string) (out SkyResult[any, any]) {
	defer SkyFfiGuardT(&out)()
	recv := FfiArg[*pkg.Router](arg0)
	if recv == nil { out = Err[any,any](ErrFfi("nil receiver: Router.GetRoute")); return }
	out = Ok[any,any](FfiRet(recv.GetRoute(arg1)))
	return
}

// [pure] typed wrapper for Go_Mux_routerHandle (P7 adaptor target)
func Go_Mux_routerHandleT(arg0 any, arg1 string, arg2 any) (out SkyResult[any, any]) {
	defer SkyFfiGuardT(&out)()
	recv := FfiArg[*pkg.Router](arg0)
	if recv == nil { out = Err[any,any](ErrFfi("nil receiver: Router.Handle")); return }
	out = Ok[any,any](FfiRet(recv.Handle(arg1, FfiArg[http.Handler](arg2))))
	return
}

// [pure] typed wrapper for Go_Mux_routerHandleFunc (P7 adaptor target)
func Go_Mux_routerHandleFuncT(arg0 any, arg1 string, arg2 any) (out SkyResult[any, any]) {
	defer SkyFfiGuardT(&out)()
	recv := FfiArg[*pkg.Router](arg0)
	if recv == nil { out = Err[any,any](ErrFfi("nil receiver: Router.HandleFunc")); return }
	out = Ok[any,any](FfiRet(recv.HandleFunc(arg1, FfiArg[func(http.ResponseWriter, *http.Request)](arg2))))
	return
}

// [pure] typed wrapper for Go_Mux_routerHeaders (P7 adaptor target)
func Go_Mux_routerHeadersT(arg0 any, arg1 any) (out SkyResult[any, any]) {
	defer SkyFfiGuardT(&out)()
	recv := FfiArg[*pkg.Router](arg0)
	if recv == nil { out = Err[any,any](ErrFfi("nil receiver: Router.Headers")); return }
	out = Ok[any,any](FfiRet(recv.Headers(FfiArg[[]string](arg1)...)))
	return
}

// [pure] typed wrapper for Go_Mux_routerHost (P7 adaptor target)
func Go_Mux_routerHostT(arg0 any, arg1 string) (out SkyResult[any, any]) {
	defer SkyFfiGuardT(&out)()
	recv := FfiArg[*pkg.Router](arg0)
	if recv == nil { out = Err[any,any](ErrFfi("nil receiver: Router.Host")); return }
	out = Ok[any,any](FfiRet(recv.Host(arg1)))
	return
}

func Go_Mux_routerKeepContextT(arg0 any) (out SkyResult[any, any]) {
	defer SkyFfiGuardT(&out)()
	recv := FfiArg[*pkg.Router](arg0)
	if recv == nil { out = Err[any, any](ErrFfi("KeepContext: nil receiver")); return }
	out = Ok[any, any](FfiRet(recv.KeepContext))
	return
}
func Go_Mux_routerKeepContext(arg0 any) any { return SkyFfiFieldGet3(arg0, "KeepContext") }

// [pure] typed wrapper for Go_Mux_routerMatch (P7 adaptor target)
func Go_Mux_routerMatchT(arg0 any, arg1 any, arg2 any) (out SkyResult[any, bool]) {
	defer SkyFfiGuardT(&out)()
	recv := FfiArg[*pkg.Router](arg0)
	if recv == nil { out = Err[any,bool](ErrFfi("nil receiver: Router.Match")); return }
	out = Ok[any,bool](recv.Match(FfiArg[*http.Request](arg1), FfiArg[*pkg.RouteMatch](arg2)))
	return
}

// [pure] typed wrapper for Go_Mux_routerMatcherFunc (P7 adaptor target)
func Go_Mux_routerMatcherFuncT(arg0 any, arg1 any) (out SkyResult[any, any]) {
	defer SkyFfiGuardT(&out)()
	recv := FfiArg[*pkg.Router](arg0)
	if recv == nil { out = Err[any,any](ErrFfi("nil receiver: Router.MatcherFunc")); return }
	out = Ok[any,any](FfiRet(recv.MatcherFunc(FfiArg[pkg.MatcherFunc](arg1))))
	return
}

func Go_Mux_routerMethodNotAllowedHandlerT(arg0 any) (out SkyResult[any, any]) {
	defer SkyFfiGuardT(&out)()
	recv := FfiArg[*pkg.Router](arg0)
	if recv == nil { out = Err[any, any](ErrFfi("MethodNotAllowedHandler: nil receiver")); return }
	out = Ok[any, any](FfiRet(recv.MethodNotAllowedHandler))
	return
}
func Go_Mux_routerMethodNotAllowedHandler(arg0 any) any { return SkyFfiFieldGet3(arg0, "MethodNotAllowedHandler") }

// [pure] typed wrapper for Go_Mux_routerMethods (P7 adaptor target)
func Go_Mux_routerMethodsT(arg0 any, arg1 any) (out SkyResult[any, any]) {
	defer SkyFfiGuardT(&out)()
	recv := FfiArg[*pkg.Router](arg0)
	if recv == nil { out = Err[any,any](ErrFfi("nil receiver: Router.Methods")); return }
	out = Ok[any,any](FfiRet(recv.Methods(FfiArg[[]string](arg1)...)))
	return
}

// [pure] typed wrapper for Go_Mux_routerName (P7 adaptor target)
func Go_Mux_routerNameT(arg0 any, arg1 string) (out SkyResult[any, any]) {
	defer SkyFfiGuardT(&out)()
	recv := FfiArg[*pkg.Router](arg0)
	if recv == nil { out = Err[any,any](ErrFfi("nil receiver: Router.Name")); return }
	out = Ok[any,any](FfiRet(recv.Name(arg1)))
	return
}

// [pure] typed wrapper for Go_Mux_routerNewRoute (P7 adaptor target)
func Go_Mux_routerNewRouteT(arg0 any) (out SkyResult[any, any]) {
	defer SkyFfiGuardT(&out)()
	recv := FfiArg[*pkg.Router](arg0)
	if recv == nil { out = Err[any,any](ErrFfi("nil receiver: Router.NewRoute")); return }
	out = Ok[any,any](FfiRet(recv.NewRoute()))
	return
}

func Go_Mux_routerNotFoundHandlerT(arg0 any) (out SkyResult[any, any]) {
	defer SkyFfiGuardT(&out)()
	recv := FfiArg[*pkg.Router](arg0)
	if recv == nil { out = Err[any, any](ErrFfi("NotFoundHandler: nil receiver")); return }
	out = Ok[any, any](FfiRet(recv.NotFoundHandler))
	return
}
func Go_Mux_routerNotFoundHandler(arg0 any) any { return SkyFfiFieldGet3(arg0, "NotFoundHandler") }

// [pure] typed wrapper for Go_Mux_routerPath (P7 adaptor target)
func Go_Mux_routerPathT(arg0 any, arg1 string) (out SkyResult[any, any]) {
	defer SkyFfiGuardT(&out)()
	recv := FfiArg[*pkg.Router](arg0)
	if recv == nil { out = Err[any,any](ErrFfi("nil receiver: Router.Path")); return }
	out = Ok[any,any](FfiRet(recv.Path(arg1)))
	return
}

// [pure] typed wrapper for Go_Mux_routerPathPrefix (P7 adaptor target)
func Go_Mux_routerPathPrefixT(arg0 any, arg1 string) (out SkyResult[any, any]) {
	defer SkyFfiGuardT(&out)()
	recv := FfiArg[*pkg.Router](arg0)
	if recv == nil { out = Err[any,any](ErrFfi("nil receiver: Router.PathPrefix")); return }
	out = Ok[any,any](FfiRet(recv.PathPrefix(arg1)))
	return
}

// [pure] typed wrapper for Go_Mux_routerQueries (P7 adaptor target)
func Go_Mux_routerQueriesT(arg0 any, arg1 any) (out SkyResult[any, any]) {
	defer SkyFfiGuardT(&out)()
	recv := FfiArg[*pkg.Router](arg0)
	if recv == nil { out = Err[any,any](ErrFfi("nil receiver: Router.Queries")); return }
	out = Ok[any,any](FfiRet(recv.Queries(FfiArg[[]string](arg1)...)))
	return
}

// [pure] typed wrapper for Go_Mux_routerSchemes (P7 adaptor target)
func Go_Mux_routerSchemesT(arg0 any, arg1 any) (out SkyResult[any, any]) {
	defer SkyFfiGuardT(&out)()
	recv := FfiArg[*pkg.Router](arg0)
	if recv == nil { out = Err[any,any](ErrFfi("nil receiver: Router.Schemes")); return }
	out = Ok[any,any](FfiRet(recv.Schemes(FfiArg[[]string](arg1)...)))
	return
}

// [pure] typed wrapper for Go_Mux_routerServeHTTP (P7 adaptor target)
func Go_Mux_routerServeHTTPT(arg0 any, arg1 any, arg2 any) (out SkyResult[any, struct{}]) {
	defer SkyFfiGuardT(&out)()
	recv := FfiArg[*pkg.Router](arg0)
	if recv == nil { out = Err[any,struct{}](ErrFfi("nil receiver: Router.ServeHTTP")); return }
	recv.ServeHTTP(FfiArg[http.ResponseWriter](arg1), FfiArg[*http.Request](arg2))
	out = Ok[any,struct{}](struct{}{})
	return
}

func Go_Mux_routerSetKeepContextT(value any, recv any) (out SkyResult[any, any]) {
	defer SkyFfiGuardT(&out)()
	r := FfiArg[*pkg.Router](recv)
	if r == nil { out = Err[any, any](ErrFfi("KeepContext: nil receiver")); return }
	r.KeepContext = FfiArg[bool](value)
	out = Ok[any, any](FfiRet(r))
	return
}
func Go_Mux_routerSetKeepContext(value any, recv any) any { return SkyFfiFieldSet3(value, recv, "KeepContext") }

func Go_Mux_routerSetMethodNotAllowedHandlerT(value any, recv any) (out SkyResult[any, any]) {
	defer SkyFfiGuardT(&out)()
	r := FfiArg[*pkg.Router](recv)
	if r == nil { out = Err[any, any](ErrFfi("MethodNotAllowedHandler: nil receiver")); return }
	r.MethodNotAllowedHandler = FfiArg[http.Handler](value)
	out = Ok[any, any](FfiRet(r))
	return
}
func Go_Mux_routerSetMethodNotAllowedHandler(value any, recv any) any { return SkyFfiFieldSet3(value, recv, "MethodNotAllowedHandler") }

func Go_Mux_routerSetNotFoundHandlerT(value any, recv any) (out SkyResult[any, any]) {
	defer SkyFfiGuardT(&out)()
	r := FfiArg[*pkg.Router](recv)
	if r == nil { out = Err[any, any](ErrFfi("NotFoundHandler: nil receiver")); return }
	r.NotFoundHandler = FfiArg[http.Handler](value)
	out = Ok[any, any](FfiRet(r))
	return
}
func Go_Mux_routerSetNotFoundHandler(value any, recv any) any { return SkyFfiFieldSet3(value, recv, "NotFoundHandler") }

// [pure] typed wrapper for Go_Mux_routerSkipClean (P7 adaptor target)
func Go_Mux_routerSkipCleanT(arg0 any, arg1 bool) (out SkyResult[any, any]) {
	defer SkyFfiGuardT(&out)()
	recv := FfiArg[*pkg.Router](arg0)
	if recv == nil { out = Err[any,any](ErrFfi("nil receiver: Router.SkipClean")); return }
	out = Ok[any,any](FfiRet(recv.SkipClean(arg1)))
	return
}

// [pure] typed wrapper for Go_Mux_routerStrictSlash (P7 adaptor target)
func Go_Mux_routerStrictSlashT(arg0 any, arg1 bool) (out SkyResult[any, any]) {
	defer SkyFfiGuardT(&out)()
	recv := FfiArg[*pkg.Router](arg0)
	if recv == nil { out = Err[any,any](ErrFfi("nil receiver: Router.StrictSlash")); return }
	out = Ok[any,any](FfiRet(recv.StrictSlash(arg1)))
	return
}

// [pure] typed wrapper for Go_Mux_routerUse (P7 adaptor target)
func Go_Mux_routerUseT(arg0 any, arg1 any) (out SkyResult[any, struct{}]) {
	defer SkyFfiGuardT(&out)()
	recv := FfiArg[*pkg.Router](arg0)
	if recv == nil { out = Err[any,struct{}](ErrFfi("nil receiver: Router.Use")); return }
	recv.Use(FfiArg[[]pkg.MiddlewareFunc](arg1)...)
	out = Ok[any,struct{}](struct{}{})
	return
}

// [pure] typed wrapper for Go_Mux_routerUseEncodedPath (P7 adaptor target)
func Go_Mux_routerUseEncodedPathT(arg0 any) (out SkyResult[any, any]) {
	defer SkyFfiGuardT(&out)()
	recv := FfiArg[*pkg.Router](arg0)
	if recv == nil { out = Err[any,any](ErrFfi("nil receiver: Router.UseEncodedPath")); return }
	out = Ok[any,any](FfiRet(recv.UseEncodedPath()))
	return
}

// [fallible] typed wrapper for Go_Mux_routerWalk (P7 adaptor target)
func Go_Mux_routerWalkT(arg0 any, arg1 any) (out SkyResult[any, struct{}]) {
	defer SkyFfiGuardT(&out)()
	recv := FfiArg[*pkg.Router](arg0)
	if recv == nil { out = Err[any,struct{}](ErrFfi("nil receiver: Router.Walk")); return }
	err := recv.Walk(FfiArg[pkg.WalkFunc](arg1))
	if err != nil { out = Err[any,struct{}](ErrFfi(err.Error())); return }
	out = Ok[any,struct{}](struct{}{})
	return
}

// [pure] typed wrapper for Go_Mux_setURLVars (P7 adaptor target)
func Go_Mux_setURLVarsT(arg0 any, arg1 any) (out SkyResult[any, any]) {
	defer SkyFfiGuardT(&out)()
	out = Ok[any,any](FfiRet(pkg.SetURLVars(FfiArg[*http.Request](arg0), FfiArg[map[string]string](arg1))))
	return
}

func Go_Mux_skipRouter(_ any) (out any) {
	defer SkyFfiGuard(&out)()
	out = Ok[any, any](FfiRet(pkg.SkipRouter))
	return
}

// [pure] typed wrapper for Go_Mux_vars (P7 adaptor target)
func Go_Mux_varsT(arg0 any) (out SkyResult[any, any]) {
	defer SkyFfiGuardT(&out)()
	out = Ok[any,any](FfiRet(pkg.Vars(FfiArg[*http.Request](arg0))))
	return
}


// Pin fmt against "imported and not used" across partial files.
var _ = fmt.Sprintf
