//! Deterministic FFI surface generation — the Rust port of the "surface" half
//! of `src/Sky/Build/FfiGen.hs`: name transforms, the machine-readable
//! `kernel.json` (`emitKernelJson`), the human `.skyi` catalogue (`emitSkyi`),
//! and the Go→Sky type mapping (`goTypeToSky` / `wrapperSkyType`) the compiler's
//! type side consumes. The Go wrapper (`_bindings.go`) is generated by
//! [`crate::gen_bindings`]. All three come from one deterministic pass over a
//! normalised [`PackageInfo`] (doc 09 §C.5).

use crate::inspect::{Function, PackageInfo, Param};

/// The format of the surface this generator writes, stamped into all three
/// files (`"surfaceFormat"` in kernel.json, a header line in the `.skyi` and
/// the `_bindings.go`). Bump it whenever the generated bytes change in a way
/// that makes an older surface wrong or misleading: `sky install` then
/// regenerates every surface carrying another number (and one with no stamp,
/// which predates it), and the build warns about them. `sky install` also
/// compares all three files byte-for-byte against a fresh generation, so a
/// forgotten bump still refreshes the files there; the stamp is what lets the
/// build, which never runs the inspector, see an outdated surface.
///
/// Format history: 1 = unstamped (Task-era `.skyi` header); 2 = stamped,
/// `Result Error a` header; 3 = every slot typed from the inspector's
/// go/types rendering (`sky3`): nominal opaque Go types, pointers as `Maybe`,
/// typed map keys, typed callback results, and wrappers that convert and
/// range-check every value inside their recover (`rt/ffi_convert.go`).
pub const SURFACE_FORMAT: u32 = 3;

/// The stamp line in the `.skyi` and `_bindings.go` headers (after the
/// comment marker).
pub fn surface_format_line() -> String {
    format!(
        "Surface format {SURFACE_FORMAT} (sky install regenerates a surface stamped otherwise)."
    )
}

/// The three committed surface files, plus the derived identifiers `sky add`
/// needs to name them and record the dep.
#[derive(Clone, Debug, Default)]
pub struct GeneratedSurface {
    /// Sky module path the import binds (`Github.Com.Google.Uuid`).
    pub module_name: String,
    /// Kernel prefix for Go symbols (`Go_Uuid`).
    pub kernel_name: String,
    /// Filename slug (the Go package name, `.`/`/` → `_`).
    pub slug: String,
    pub kernel_json: String,
    pub skyi: String,
    pub bindings_go: String,
}

/// Produce the full committed surface for one inspected package. `info` MUST be
/// normalised (`inspect::normalize`) so the output is deterministic.
pub fn generate(info: &PackageInfo) -> GeneratedSurface {
    let module_name = pkg_to_module_name(&info.pkg);
    let kernel_name = kernel_name_from_pkg(&info.pkg);
    let slug = slugify(&info.name);
    GeneratedSurface {
        kernel_json: emit_kernel_json(&module_name, &kernel_name, info),
        skyi: emit_skyi(info),
        bindings_go: crate::gen_bindings::emit_go_file(&kernel_name, info),
        module_name,
        kernel_name,
        slug,
    }
}

// ---------------------------------------------------------------------------
// Name transforms (FfiGen.hs:314-379, 1931).
// ---------------------------------------------------------------------------

/// `github.com/google/uuid` → `Github.Com.Google.Uuid`;
/// `github.com/stripe/stripe-go/v84` → `Github.Com.Stripe.StripeGo.V84`.
/// Slash- and dot-split, hyphen-fold-camel, capitalise each segment.
pub fn pkg_to_module_name(path: &str) -> String {
    let mut segs: Vec<String> = Vec::new();
    for slash_seg in path.split('/') {
        for dot_seg in slash_seg.split('.') {
            segs.push(camel_hyphen(dot_seg));
        }
    }
    segs.into_iter()
        .filter(|s| !s.is_empty())
        .map(|s| cap_first(&s))
        .collect::<Vec<_>>()
        .join(".")
}

/// `stripe-go` → `stripeGo`; non-alphanumeric (other than `-`) → `_`.
fn camel_hyphen(s: &str) -> String {
    let mut out = String::new();
    let mut upper_next = false;
    for c in s.chars() {
        if c == '-' {
            upper_next = true;
        } else if upper_next {
            out.extend(c.to_uppercase());
            upper_next = false;
        } else if c.is_alphanumeric() {
            out.push(c);
        } else {
            out.push('_');
        }
    }
    out
}

/// `Go_` + capitalised last path segment; a trailing `vNN` version segment folds
/// onto the preceding one (`.../v84` → `PrevV84`). Mirrors `kernelNameFromPkg`.
pub fn kernel_name_from_pkg(path: &str) -> String {
    let segs: Vec<&str> = path.split('/').filter(|s| !s.is_empty()).collect();
    let cap_of = |s: &str| -> String {
        cap_first(
            &s.chars()
                .map(|c| if c.is_alphanumeric() { c } else { '_' })
                .collect::<String>(),
        )
    };
    let base = match segs.as_slice() {
        [.., prev, last] if is_version(last) => format!("{}{}", cap_of(prev), cap_of(last)),
        [.., last] => cap_of(last),
        [] => "Ffi".to_string(),
    };
    format!("Go_{base}")
}

fn is_version(s: &str) -> bool {
    if let Some(rest) = s.strip_prefix('v') {
        !rest.is_empty() && rest.chars().all(|c| c.is_ascii_digit())
    } else {
        false
    }
}

/// `map (\c -> if c ∈ "./" then '_' else c)`.
pub fn slugify(s: &str) -> String {
    s.chars()
        .map(|c| if c == '.' || c == '/' { '_' } else { c })
        .collect()
}

fn cap_first(s: &str) -> String {
    let mut chars = s.chars();
    match chars.next() {
        Some(c) => c.to_uppercase().chain(chars).collect(),
        None => String::new(),
    }
}

fn lower_first(s: &str) -> String {
    let mut chars = s.chars();
    match chars.next() {
        Some(c) => c.to_lowercase().chain(chars).collect(),
        None => String::new(),
    }
}

// ---------------------------------------------------------------------------
// shouldSkipFn (FfiGen.hs:549-583).
// ---------------------------------------------------------------------------

/// Skip functions that can't be realised at the FFI boundary: unresolvable
/// generics (unless a pure identity-pointer), anything referencing an
/// `internal/`/`vendor/` type Go forbids importing, and anything taking a Go
/// `error` value as a *parameter* (see [`has_error_param`]).
pub fn should_skip_fn(fn_: &Function) -> bool {
    let param_tys: Vec<&str> = fn_.params.iter().map(|p| p.ty.as_str()).collect();
    let result_tys: Vec<&str> = fn_.results.iter().map(|p| p.ty.as_str()).collect();
    let has_generic = param_tys.iter().any(|t| is_generic_type(t))
        || result_tys.iter().any(|t| is_generic_type(t))
        || param_tys.iter().any(|t| generic_hint(t))
        || result_tys.iter().any(|t| generic_hint(t));
    let is_id_pointer = fn_.params.len() == 1
        && fn_.results.len() == 1
        && is_bare_param(&fn_.params[0].ty)
        && is_star_bare_param(&fn_.results[0].ty);
    let refs_internal = param_tys.iter().any(|t| touches_internal(t))
        || result_tys.iter().any(|t| touches_internal(t));
    (has_generic && !is_id_pointer) || refs_internal || has_error_param(fn_)
}

/// True when any *parameter* is the Go `error` interface (bare `error`, or
/// decorated `*error` / `[]error`).
///
/// A Go `error` value cannot be constructed from a Sky value: `goTypeToSky`
/// maps `error` → `String` (correct for a *result*, where the error is peeled
/// into the `Result Error` wrap), but as a *parameter* that leaves the emitted
/// typed wrapper declaring `argN error` while the Sky surface type says
/// `String`. Any call then emits Go that passes a `string` where an `error` is
/// required — `go build` rejects it (`string does not implement error`),
/// breaking the hard `sky check ≡ sky build` invariant.
///
/// Such a function is genuinely inexpressible from pure Sky (there is no way to
/// materialise a Go `error` at the boundary — the idiomatic error channel is
/// `Result Error` on the *return*), so we skip generating the binding entirely.
/// The Sky surface never exposes the name, and a call to it is rejected cleanly
/// at name-resolution time (`undefined name`) instead of emitting broken Go.
///
/// This deliberately diverges from the Haskell oracle's `shouldSkipFn`
/// (`FfiGen.hs:549`), which lacks this arm and therefore emits the same broken
/// binding (e.g. `uuid.Must(uuid UUID, err error) UUID`). No corpus example
/// calls such a function, so the oracle bug is dormant; the divergence is a
/// pure correctness improvement, not a parity regression.
pub(crate) fn has_error_param(fn_: &Function) -> bool {
    fn_.params.iter().any(|p| is_error_type(&p.ty))
}

/// The Go `error` interface, ignoring pointer / slice decoration.
fn is_error_type(t: &str) -> bool {
    let t = t.trim_start_matches('*');
    let t = t.strip_prefix("[]").unwrap_or(t);
    t == "error"
}

fn touches_internal(t: &str) -> bool {
    t.contains("/internal.")
        || t.contains("/internal/")
        || t.contains("/vendor.")
        || t.contains("/vendor/")
}

fn generic_hint(t: &str) -> bool {
    t.contains("[T ")
        || t.contains("[T]")
        || t.contains("[T,")
        || t.contains("[K ")
        || t.contains("[V ")
        || t.contains("[]T")
        || t == "T"
        || t.ends_with("*T")
}

/// A single uppercase letter is a bare type parameter; or a bracketed generic
/// param appears anywhere. Mirrors `isGenericType`.
pub(crate) fn is_generic_type(t: &str) -> bool {
    if is_single_upper(t) {
        return true;
    }
    has_bracketed_param(t)
}

fn is_single_upper(t: &str) -> bool {
    let mut chars = t.chars();
    match (chars.next(), chars.next()) {
        (Some(c), None) => c.is_ascii_uppercase(),
        _ => false,
    }
}

fn has_bracketed_param(s: &str) -> bool {
    let mut rest = s;
    while let Some(open) = rest.find('[') {
        let after = &rest[open + 1..];
        let inside = after.split(']').next().unwrap_or("");
        if inside.split(',').any(|p| is_single_upper(p.trim())) {
            return true;
        }
        rest = match after.find(']') {
            Some(close) => &after[close + 1..],
            None => break,
        };
    }
    false
}

/// `isBareParam` (FfiGen.hs:1307): a bare generic type parameter — a SINGLE
/// uppercase letter (`"T"`), not a multi-char opaque type name.
fn is_bare_param(t: &str) -> bool {
    is_single_upper(t)
}

/// `isStarBareParam` (FfiGen.hs:1313): `*` followed by a bare param (`"*T"`).
fn is_star_bare_param(t: &str) -> bool {
    t.strip_prefix('*').is_some_and(is_bare_param)
}

// ---------------------------------------------------------------------------
// kernel.json (FfiGen.hs:386-441).
// ---------------------------------------------------------------------------

fn emit_kernel_json(module_name: &str, kernel_name: &str, info: &PackageInfo) -> String {
    let fns: Vec<&Function> = info
        .functions
        .iter()
        .filter(|f| !should_skip_fn(f))
        .collect();
    let fn_entries: Vec<String> = fns
        .iter()
        .map(|fn_| {
            let st = wrapper_sky_type(fn_);
            format!(
                "    {{\"name\": {}, \"arity\": {}, \"skyType\": {}}}",
                quote(&lower_first(&fn_.name)),
                fn_.params.len().max(1),
                quote(&st)
            )
        })
        .collect();

    let mut lines: Vec<String> = vec![
        "{".to_string(),
        format!("  \"moduleName\": {},", quote(module_name)),
        format!("  \"kernelName\": {},", quote(kernel_name)),
        format!("  \"package\": {},", quote(&info.pkg)),
        format!("  \"surfaceFormat\": {SURFACE_FORMAT},"),
        "  \"functions\": [".to_string(),
        fn_entries.join(",\n"),
        "  ]".to_string(),
    ];

    if !info.implements.is_empty() {
        let body = info
            .implements
            .iter()
            .map(|(k, vs)| {
                let items = vs.iter().map(|v| quote(v)).collect::<Vec<_>>().join(", ");
                format!("      {}: [{}]", quote(k), items)
            })
            .collect::<Vec<_>>()
            .join(",\n");
        lines.push("  ,".to_string());
        lines.push("  \"implements\": {".to_string());
        lines.push(body);
        lines.push("  }".to_string());
    }
    if !info.pkg_alias.is_empty() {
        let body = info
            .pkg_alias
            .iter()
            .map(|(k, v)| format!("      {}: {}", quote(k), quote(v)))
            .collect::<Vec<_>>()
            .join(",\n");
        lines.push("  ,".to_string());
        lines.push("  \"pkgAlias\": {".to_string());
        lines.push(body);
        lines.push("  }".to_string());
    }
    lines.push("}".to_string());
    // `unlines` appends a trailing newline.
    let mut s = lines.join("\n");
    s.push('\n');
    s
}

// ---------------------------------------------------------------------------
// The Sky type of a binding (surface format 3).
// ---------------------------------------------------------------------------

/// The full Sky signature of a binding, including the `Result Error` wrap:
/// the `skyType` kernel.json records and the checker types every call by
/// (`ty::ffi_sig`).
///
/// Every slot's type comes from the inspector's `sky3` rendering (computed
/// from the go/types structure, `tools/sky-ffi-inspect/sky3.go`); this
/// function only maps its opaque markers to the checker's nominal keys
/// ([`sky3_to_surface`]) and composes the result:
///
/// * a trailing `error` is peeled into the `Result Error` wrap;
/// * `(T, bool)` is `Maybe T` (the wrapper returns a Maybe);
/// * one other result is itself, two or three are a tuple, more are the
///   opaque `go@Go.GoTuple`.
///
/// A slot the inspector did not render (a report from an older inspector)
/// is the opaque `go@Go.GoUnknown`: never a wildcard.
pub fn wrapper_sky_type(fn_: &Function) -> String {
    let param_sig = if fn_.params.is_empty() {
        "()".to_string()
    } else {
        fn_.params
            .iter()
            .map(slot_sky)
            .collect::<Vec<_>>()
            .join(" -> ")
    };

    let non_err: Vec<&Param> = fn_.results.iter().filter(|p| p.ty != "error").collect();
    let is_comma_ok = fn_.results.len() == 2
        && fn_.results[1].ty == "bool"
        && fn_.results[0].ty != "bool"
        && fn_.results[0].ty != "error";
    let inner_ok = if non_err.is_empty() {
        "()".to_string()
    } else if is_comma_ok {
        format!("Maybe {}", wrap_if_multi(&slot_sky(&fn_.results[0])))
    } else if non_err.len() == 1 {
        slot_sky(non_err[0])
    } else if non_err.len() <= 3 {
        format!(
            "({})",
            non_err
                .iter()
                .map(|p| slot_sky(p))
                .collect::<Vec<_>>()
                .join(", ")
        )
    } else {
        OPAQUE_TUPLE.to_string()
    };
    let ok_type = if inner_ok.starts_with('(') {
        format!("Result Error {inner_ok}")
    } else {
        format!("Result Error {}", wrap_if_multi(&inner_ok))
    };
    format!("{param_sig} -> {ok_type}")
}

/// The opaque type of a Go result list with more than three values.
pub const OPAQUE_TUPLE: &str = "go@Go.GoTuple";

/// The Sky type of one slot.
fn slot_sky(p: &Param) -> String {
    if p.sky3.is_empty() {
        return "go@Go.GoUnknown".to_string();
    }
    sky3_to_surface(&p.sky3)
}

fn wrap_if_multi(s: &str) -> String {
    if s.contains(' ') && !s.starts_with('(') {
        format!("({s})")
    } else {
        s.to_string()
    }
}

/// Map the inspector's `sky3` markers to the checker's type keys:
///
/// * `Name@importPath` → `go@<Sky module of importPath>.Name`, the same key a
///   user annotation `Pkg.Name` gets (`ty::nominal::go_type`);
/// * `@kind` (an unnamed opaque Go type: `@func`, `@map`, `@any`, …) →
///   `go@Go.Go<Kind>`;
/// * `iface:X` (a non-empty interface a parameter receives) → `goi@<key of X>`.
pub fn sky3_to_surface(s: &str) -> String {
    let chars: Vec<char> = s.chars().collect();
    let mut out = String::new();
    let mut i = 0;
    while i < chars.len() {
        let c = chars[i];
        if is_atom_char(c) && !(c == '-' && chars.get(i + 1) == Some(&'>')) {
            let start = i;
            while i < chars.len()
                && is_atom_char(chars[i])
                && !(chars[i] == '-' && chars.get(i + 1) == Some(&'>'))
            {
                i += 1;
            }
            let atom: String = chars[start..i].iter().collect();
            out.push_str(&map_atom(&atom));
        } else {
            out.push(c);
            i += 1;
        }
    }
    out
}

fn is_atom_char(c: char) -> bool {
    c.is_alphanumeric() || matches!(c, '_' | '.' | '/' | '-' | '@' | ':' | '$' | '~' | '+')
}

fn map_atom(atom: &str) -> String {
    if let Some(rest) = atom.strip_prefix("iface:") {
        return format!("goi@{}", opaque_key(rest));
    }
    if atom.contains('@') {
        return format!("go@{}", opaque_key(atom));
    }
    atom.to_string()
}

/// `Name@importPath` → `Module.Name`; `@kind` → `Go.GoKind`.
fn opaque_key(marker: &str) -> String {
    match marker.split_once('@') {
        Some(("", kind)) => format!("Go.Go{}", cap_first(kind)),
        Some((name, path)) => format!("{}.{name}", pkg_to_module_name(path)),
        None => format!("Go.Go{}", cap_first(marker)),
    }
}

// ---------------------------------------------------------------------------
// .skyi catalogue (FfiGen.hs:1782-1822).
// ---------------------------------------------------------------------------

fn emit_skyi(info: &PackageInfo) -> String {
    let aliases = crate::gen_bindings::build_alias_table(info);
    let mut lines: Vec<String> = vec![
        format!("-- Auto-generated FFI binding catalogue for {}", info.pkg),
        format!("-- {}", surface_format_line()),
        "--".to_string(),
        "-- Every binding returns `Result Error a`, not a Task. The Go call runs".to_string(),
        "-- where the expression is evaluated (it is synchronous), and the Result".to_string(),
        "-- carries its outcome: a Go error, a nil, or a recovered panic is Err.".to_string(),
        "-- Handling it at every call site is deliberate: it marks the point where".to_string(),
        "-- a program leaves Sky's guarantees. Prefer the Sky stdlib where it".to_string(),
        "-- covers the job, and keep Go FFI for what it does not.".to_string(),
        "--".to_string(),
        "-- To run a call later, off `update` (for example with Cmd.perform),".to_string(),
        "-- wrap it in a Task yourself:".to_string(),
        "--     Task.lazy (\\_ -> call args) |> Task.andThen Task.fromResult".to_string(),
        "-- See docs/ffi/boundary-philosophy.md.".to_string(),
        "--".to_string(),
        "-- An opaque Go value (a struct, an interface, a func) has its own Sky".to_string(),
        "-- type, named through this module (`Pkg.Client`); use the bindings to".to_string(),
        "-- construct, read and update it.".to_string(),
        "--".to_string(),
        "-- Imports used in this package's wrapper:".to_string(),
    ];
    // sortOn fst over (path, alias): BTreeMap iterates by key (path) already.
    for (path, alias) in &aliases {
        lines.push(format!("--   {alias} \"{path}\""));
    }
    lines.push(String::new());
    lines.push(format!("package {}", info.name));
    for fn_ in &info.functions {
        lines.push(emit_skyi_fn(fn_));
    }
    let mut s = lines.join("\n");
    s.push('\n');
    s
}

// One line per binding with the type Sky code actually sees: the same
// `Result Error a` signature kernel.json records (`wrapper_sky_type`). This
// used to print the raw Go results followed by "runtime wrap: Task Error",
// which described neither the type nor the runtime behaviour.
fn emit_skyi_fn(fn_: &Function) -> String {
    format!(
        "-- [{}] {} : {}",
        fn_.effect,
        fn_.name,
        wrapper_sky_type(fn_)
    )
}

// ---------------------------------------------------------------------------
// quote (FfiGen.hs:1923).
// ---------------------------------------------------------------------------

fn quote(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            _ => out.push(c),
        }
    }
    out.push('"');
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::Path;

    fn fixture(name: &str) -> String {
        let p = Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("tests")
            .join("fixtures")
            .join(name);
        std::fs::read_to_string(p).unwrap()
    }

    #[test]
    fn name_transforms() {
        assert_eq!(
            pkg_to_module_name("github.com/google/uuid"),
            "Github.Com.Google.Uuid"
        );
        assert_eq!(
            pkg_to_module_name("github.com/stripe/stripe-go/v84"),
            "Github.Com.Stripe.StripeGo.V84"
        );
        assert_eq!(pkg_to_module_name("net/http"), "Net.Http");
        assert_eq!(kernel_name_from_pkg("github.com/google/uuid"), "Go_Uuid");
        // capOf sanitises the hyphen to `_` (matches the committed stripe
        // surface `Go_Stripe_goV84` — hyphen-fold camel is module-name only).
        assert_eq!(
            kernel_name_from_pkg("github.com/stripe/stripe-go/v84"),
            "Go_Stripe_goV84"
        );
        assert_eq!(slugify("uuid"), "uuid");
    }

    /// A Go `(T, bool)` comma-ok result is `Result Error (Maybe T)` — what the
    /// typed wrapper returns (`SkyMaybe[T]`). It rendered `(T, Bool)`, and the
    /// type checker reads this string to type the call.
    #[test]
    fn comma_ok_result_renders_as_maybe() {
        let p = |ty: &str| Param {
            ty: ty.to_string(),
            sky3: match ty {
                "string" => "String",
                "bool" => "Bool",
                "error" => "@error",
                _ => "",
            }
            .to_string(),
            ..Default::default()
        };
        let f = |params: Vec<Param>, results: Vec<Param>| Function {
            name: "F".into(),
            params,
            results,
            ..Default::default()
        };
        assert_eq!(
            wrapper_sky_type(&f(vec![p("string")], vec![p("string"), p("bool")])),
            "String -> Result Error (Maybe String)"
        );
        // Not comma-ok: two bools, a trailing error, three results.
        assert_eq!(
            wrapper_sky_type(&f(vec![], vec![p("bool"), p("bool")])),
            "() -> Result Error (Bool, Bool)"
        );
        assert_eq!(
            wrapper_sky_type(&f(vec![], vec![p("string"), p("bool"), p("error")])),
            "() -> Result Error (String, Bool)"
        );
        assert_eq!(
            wrapper_sky_type(&f(vec![], vec![p("string"), p("error")])),
            "() -> Result Error String"
        );
    }

    #[test]
    fn sky3_markers_map_to_the_checker_keys() {
        assert_eq!(sky3_to_surface("String"), "String");
        assert_eq!(
            sky3_to_surface("UUID@github.com/google/uuid"),
            "go@Github.Com.Google.Uuid.UUID"
        );
        assert_eq!(
            sky3_to_surface("iface:Writer@io"),
            "goi@Io.Writer",
            "an interface a parameter receives"
        );
        assert_eq!(sky3_to_surface("@func"), "go@Go.GoFunc");
        assert_eq!(sky3_to_surface("iface:@any"), "goi@Go.GoAny");
        assert_eq!(
            sky3_to_surface("(Maybe String -> Result Error ()) -> List (Client@net/http)"),
            "(Maybe String -> Result Error ()) -> List (go@Net.Http.Client)"
        );
        assert_eq!(
            sky3_to_surface("Dict Int (Thing@example.com/go-kit/v2)"),
            "Dict Int (go@Example.Com.GoKit.V2.Thing)"
        );
        // An unrendered slot is opaque, never a wildcard.
        let f = Function {
            name: "F".into(),
            params: vec![Param {
                ty: "x".into(),
                ..Default::default()
            }],
            ..Default::default()
        };
        assert_eq!(wrapper_sky_type(&f), "go@Go.GoUnknown -> Result Error ()");
    }

    #[test]
    fn error_param_functions_are_skipped() {
        // A Go `error` PARAMETER is not constructible from Sky. Such a binding
        // must be dropped from the surface (skipped), never emitted with an
        // `error`-typed wrapper param + `String` Sky type (which breaks
        // `go build`). Regression for the `uuid.Must(uuid, err error)` case.
        let err_param = Function {
            name: "Must".to_string(),
            params: vec![
                Param {
                    ty: "github.com/google/uuid.UUID".to_string(),
                    ..Default::default()
                },
                Param {
                    ty: "error".to_string(),
                    ..Default::default()
                },
            ],
            results: vec![Param {
                ty: "github.com/google/uuid.UUID".to_string(),
                ..Default::default()
            }],
            ..Default::default()
        };
        assert!(should_skip_fn(&err_param), "error-param fn must be skipped");
        assert!(is_error_type("error"));
        assert!(is_error_type("*error"));
        assert!(is_error_type("[]error"));
        assert!(!is_error_type("uuid.UUID"));

        // An `error` RESULT is fine — it peels into `Result Error`.
        let err_result = Function {
            name: "Parse".to_string(),
            params: vec![Param {
                ty: "string".to_string(),
                ..Default::default()
            }],
            results: vec![
                Param {
                    ty: "github.com/google/uuid.UUID".to_string(),
                    ..Default::default()
                },
                Param {
                    ty: "error".to_string(),
                    ..Default::default()
                },
            ],
            ..Default::default()
        };
        assert!(
            !should_skip_fn(&err_result),
            "error-result fn must NOT be skipped"
        );

        // End-to-end over the committed uuid inspector fixture: the generated
        // kernel.json drops `must` (error param) but keeps `mustParse`.
        let mut info = crate::inspect::parse_one(&fixture("uuid.inspector.json")).unwrap();
        crate::inspect::normalize(&mut info);
        let got = emit_kernel_json(
            &pkg_to_module_name(&info.pkg),
            &kernel_name_from_pkg(&info.pkg),
            &info,
        );
        assert!(
            !got.contains("\"name\": \"must\","),
            "kernel.json must not expose the error-param `must` binding"
        );
        assert!(
            got.contains("\"name\": \"mustParse\","),
            "kernel.json must still expose `mustParse`"
        );
    }

    /// Byte-identity for a committed package's kernel.json. `inspector` is
    /// already normalised; `generate` requires normalised input, so parse_one
    /// (idempotent re-normalize) is faithful.
    fn assert_kernel_json_matches(inspector: &str, golden: &str) {
        let info = crate::inspect::parse_one(&fixture(inspector)).unwrap();
        let got = crate::gen::generate(&info).kernel_json;
        let want = fixture(golden);
        assert!(!want.is_empty(), "committed golden {golden} is empty");
        assert_eq!(
            got, want,
            "kernel.json for {inspector} differs from committed {golden}"
        );
    }

    #[test]
    fn mux_kernel_json_byte_identical() {
        assert_kernel_json_matches("mux.inspector.json", "mux.expected.kernel.json");
    }

    #[test]
    fn net_http_kernel_json_byte_identical() {
        assert_kernel_json_matches("net_http.inspector.json", "net_http.expected.kernel.json");
    }

    #[test]
    fn kernel_json_matches_committed_uuid() {
        let mut info = crate::inspect::parse_one(&fixture("uuid.inspector.json")).unwrap();
        crate::inspect::normalize(&mut info);
        let got = emit_kernel_json(
            &pkg_to_module_name(&info.pkg),
            &kernel_name_from_pkg(&info.pkg),
            &info,
        );
        // Structural checks: the committed surface (function ORDER aside — we
        // sort for determinism) must carry the same header + every function's
        // skyType. Byte-equality is asserted separately once normalization order
        // is reconciled with the committed file.
        assert!(got.contains("\"moduleName\": \"Github.Com.Google.Uuid\""));
        assert!(got.contains("\"kernelName\": \"Go_Uuid\""));
        assert!(got.contains("\"package\": \"github.com/google/uuid\""));
        assert!(got.contains(
            "{\"name\": \"newString\", \"arity\": 1, \"skyType\": \"() -> Result Error String\"}"
        ));
        assert!(got.contains("\"implements\": {"));
        assert!(got.contains("\"pkgAlias\": {"));
        // Every committed function name appears.
        let committed = fixture("uuid.expected.kernel.json");
        for fn_ in &info.functions {
            if should_skip_fn(fn_) {
                continue;
            }
            let name = lower_first(&fn_.name);
            let needle = format!("\"name\": \"{name}\"");
            assert!(committed.contains(&needle), "committed missing {name}");
            assert!(got.contains(&needle), "generated missing {name}");
        }
    }

    /// Regenerates the committed fixtures from fresh inspector reports (the
    /// `<name>.raw.json` files in `SKY_FFI_REGEN_DIR`, produced by
    /// `tools/sky-ffi-inspect` under the pinned linux/amd64 target). A tool,
    /// not a gate: `cargo test -p ffi regenerate_fixtures -- --ignored`.
    #[test]
    #[ignore]
    fn regenerate_fixtures() {
        let src = std::env::var("SKY_FFI_REGEN_DIR").expect("SKY_FFI_REGEN_DIR");
        let out = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures");
        for name in ["uuid", "mux", "net_http"] {
            let raw =
                std::fs::read_to_string(Path::new(&src).join(format!("{name}.raw.json"))).unwrap();
            let mut info = crate::inspect::parse_one(&raw).unwrap();
            crate::inspect::normalize(&mut info);
            let mut json = serde_json::to_string_pretty(&info).unwrap();
            json.push('\n');
            std::fs::write(out.join(format!("{name}.inspector.json")), json).unwrap();
            let s = generate(&info);
            std::fs::write(
                out.join(format!("{name}.expected.kernel.json")),
                s.kernel_json,
            )
            .unwrap();
            std::fs::write(
                out.join(format!("{name}.expected_bindings.go")),
                s.bindings_go,
            )
            .unwrap();
        }
    }

    // The .skyi catalogue is the first thing a user reads about a Go package.
    // It used to say every call "returns Task Error a" and is callable via
    // `Sky.Ffi.callTask` (the dynamic escape hatch, not how generated bindings
    // are called), and marked each function    // "runtime wrap: Task Error". Bindings return `Result Error a`, run
    // synchronously, and are deferred only by the caller wrapping them.
    #[test]
    fn skyi_describes_result_not_task() {
        let mut info = crate::inspect::parse_one(&fixture("uuid.inspector.json")).unwrap();
        crate::inspect::normalize(&mut info);
        let skyi = emit_skyi(&info);
        assert!(
            !skyi.contains("Task Error a"),
            "the header must not promise a Task:\n{skyi}"
        );
        assert!(
            !skyi.contains("runtime wrap: Task"),
            "no line may claim a Task wrap:\n{skyi}"
        );
        assert!(
            !skyi.contains("callTask"),
            "generated bindings are not called through Sky.Ffi.callTask:\n{skyi}"
        );
        assert!(
            skyi.contains("returns `Result Error a`"),
            "the header must name the Result:\n{skyi}"
        );
        assert!(
            skyi.contains("Task.lazy"),
            "the header must show how to defer a call:\n{skyi}"
        );
        let fn_lines: Vec<&str> = skyi.lines().filter(|l| l.starts_with("-- [")).collect();
        assert!(
            !fn_lines.is_empty(),
            "the uuid fixture has bindings:\n{skyi}"
        );
        for line in fn_lines {
            assert!(
                line.contains("Result Error"),
                "every binding line shows its Result type: {line}"
            );
        }
    }
}
