//! Deterministic FFI surface generation — the Rust port of the "surface" half
//! of `src/Sky/Build/FfiGen.hs`: name transforms, the machine-readable
//! `kernel.json` (`emitKernelJson`), the human `.skyi` catalogue (`emitSkyi`),
//! and the Go→Sky type mapping (`goTypeToSky` / `wrapperSkyType`) the compiler's
//! type side consumes. The Go wrapper (`_bindings.go`) is generated by
//! [`crate::gen_bindings`]. All three come from one deterministic pass over a
//! normalised [`PackageInfo`] (doc 09 §C.5).

use crate::inspect::{Function, PackageInfo, Param};

/// The three committed surface files, plus the derived identifiers `sky add`
/// needs to name them and record the dep.
#[derive(Clone, Debug, Default)]
pub struct GeneratedSurface {
    /// Sky module path the import binds (`Github.Com.Google.Uuid`).
    pub module_name: String,
    /// Kernel prefix for Go symbols (`Go_Uuid`).
    pub kernel_name: String,
    /// Filename slug (the Go package name, `.`/`/` → `_`).
    pub slug: String,
    pub kernel_json: String,
    pub skyi: String,
    pub bindings_go: String,
}

/// Produce the full committed surface for one inspected package. `info` MUST be
/// normalised (`inspect::normalize`) so the output is deterministic.
pub fn generate(info: &PackageInfo) -> GeneratedSurface {
    let module_name = pkg_to_module_name(&info.pkg);
    let kernel_name = kernel_name_from_pkg(&info.pkg);
    let slug = slugify(&info.name);
    GeneratedSurface {
        kernel_json: emit_kernel_json(&module_name, &kernel_name, info),
        skyi: emit_skyi(info),
        bindings_go: crate::gen_bindings::emit_go_file(&kernel_name, info),
        module_name,
        kernel_name,
        slug,
    }
}

// ---------------------------------------------------------------------------
// Name transforms (FfiGen.hs:314-379, 1931).
// ---------------------------------------------------------------------------

/// `github.com/google/uuid` → `Github.Com.Google.Uuid`;
/// `github.com/stripe/stripe-go/v84` → `Github.Com.Stripe.StripeGo.V84`.
/// Slash- and dot-split, hyphen-fold-camel, capitalise each segment.
pub fn pkg_to_module_name(path: &str) -> String {
    let mut segs: Vec<String> = Vec::new();
    for slash_seg in path.split('/') {
        for dot_seg in slash_seg.split('.') {
            segs.push(camel_hyphen(dot_seg));
        }
    }
    segs.into_iter()
        .filter(|s| !s.is_empty())
        .map(|s| cap_first(&s))
        .collect::<Vec<_>>()
        .join(".")
}

/// `stripe-go` → `stripeGo`; non-alphanumeric (other than `-`) → `_`.
fn camel_hyphen(s: &str) -> String {
    let mut out = String::new();
    let mut upper_next = false;
    for c in s.chars() {
        if c == '-' {
            upper_next = true;
        } else if upper_next {
            out.extend(c.to_uppercase());
            upper_next = false;
        } else if c.is_alphanumeric() {
            out.push(c);
        } else {
            out.push('_');
        }
    }
    out
}

/// `Go_` + capitalised last path segment; a trailing `vNN` version segment folds
/// onto the preceding one (`.../v84` → `PrevV84`). Mirrors `kernelNameFromPkg`.
pub fn kernel_name_from_pkg(path: &str) -> String {
    let segs: Vec<&str> = path.split('/').filter(|s| !s.is_empty()).collect();
    let cap_of = |s: &str| -> String {
        cap_first(
            &s.chars()
                .map(|c| if c.is_alphanumeric() { c } else { '_' })
                .collect::<String>(),
        )
    };
    let base = match segs.as_slice() {
        [.., prev, last] if is_version(last) => format!("{}{}", cap_of(prev), cap_of(last)),
        [.., last] => cap_of(last),
        [] => "Ffi".to_string(),
    };
    format!("Go_{base}")
}

fn is_version(s: &str) -> bool {
    if let Some(rest) = s.strip_prefix('v') {
        !rest.is_empty() && rest.chars().all(|c| c.is_ascii_digit())
    } else {
        false
    }
}

/// `map (\c -> if c ∈ "./" then '_' else c)`.
pub fn slugify(s: &str) -> String {
    s.chars()
        .map(|c| if c == '.' || c == '/' { '_' } else { c })
        .collect()
}

fn cap_first(s: &str) -> String {
    let mut chars = s.chars();
    match chars.next() {
        Some(c) => c.to_uppercase().chain(chars).collect(),
        None => String::new(),
    }
}

fn lower_first(s: &str) -> String {
    let mut chars = s.chars();
    match chars.next() {
        Some(c) => c.to_lowercase().chain(chars).collect(),
        None => String::new(),
    }
}

// ---------------------------------------------------------------------------
// shouldSkipFn (FfiGen.hs:549-583).
// ---------------------------------------------------------------------------

/// Skip functions that can't be realised at the FFI boundary: unresolvable
/// generics (unless a pure identity-pointer) and anything referencing an
/// `internal/`/`vendor/` type Go forbids importing.
pub fn should_skip_fn(fn_: &Function) -> bool {
    let param_tys: Vec<&str> = fn_.params.iter().map(|p| p.ty.as_str()).collect();
    let result_tys: Vec<&str> = fn_.results.iter().map(|p| p.ty.as_str()).collect();
    let has_generic = param_tys.iter().any(|t| is_generic_type(t))
        || result_tys.iter().any(|t| is_generic_type(t))
        || param_tys.iter().any(|t| generic_hint(t))
        || result_tys.iter().any(|t| generic_hint(t));
    let is_id_pointer = fn_.params.len() == 1
        && fn_.results.len() == 1
        && is_bare_param(&fn_.params[0].ty)
        && is_star_bare_param(&fn_.results[0].ty);
    let refs_internal = param_tys.iter().any(|t| touches_internal(t))
        || result_tys.iter().any(|t| touches_internal(t));
    (has_generic && !is_id_pointer) || refs_internal
}

fn touches_internal(t: &str) -> bool {
    t.contains("/internal.")
        || t.contains("/internal/")
        || t.contains("/vendor.")
        || t.contains("/vendor/")
}

fn generic_hint(t: &str) -> bool {
    t.contains("[T ")
        || t.contains("[T]")
        || t.contains("[T,")
        || t.contains("[K ")
        || t.contains("[V ")
        || t.contains("[]T")
        || t == "T"
        || t.ends_with("*T")
}

/// A single uppercase letter is a bare type parameter; or a bracketed generic
/// param appears anywhere. Mirrors `isGenericType`.
pub(crate) fn is_generic_type(t: &str) -> bool {
    if is_single_upper(t) {
        return true;
    }
    has_bracketed_param(t)
}

fn is_single_upper(t: &str) -> bool {
    let mut chars = t.chars();
    match (chars.next(), chars.next()) {
        (Some(c), None) => c.is_ascii_uppercase(),
        _ => false,
    }
}

fn has_bracketed_param(s: &str) -> bool {
    let mut rest = s;
    while let Some(open) = rest.find('[') {
        let after = &rest[open + 1..];
        let inside = after.split(']').next().unwrap_or("");
        if inside.split(',').any(|p| is_single_upper(p.trim())) {
            return true;
        }
        rest = match after.find(']') {
            Some(close) => &after[close + 1..],
            None => break,
        };
    }
    false
}

/// `isBareParam` (FfiGen.hs:1307): a bare generic type parameter — a SINGLE
/// uppercase letter (`"T"`), not a multi-char opaque type name.
fn is_bare_param(t: &str) -> bool {
    is_single_upper(t)
}

/// `isStarBareParam` (FfiGen.hs:1313): `*` followed by a bare param (`"*T"`).
fn is_star_bare_param(t: &str) -> bool {
    t.strip_prefix('*').is_some_and(is_bare_param)
}

// ---------------------------------------------------------------------------
// kernel.json (FfiGen.hs:386-441).
// ---------------------------------------------------------------------------

fn emit_kernel_json(module_name: &str, kernel_name: &str, info: &PackageInfo) -> String {
    let fns: Vec<&Function> = info.functions.iter().filter(|f| !should_skip_fn(f)).collect();
    let fn_entries: Vec<String> = fns
        .iter()
        .map(|fn_| {
            let st = wrapper_sky_type(fn_);
            let base = format!(
                "    {{\"name\": {}, \"arity\": {}",
                quote(&lower_first(&fn_.name)),
                fn_.params.len().max(1)
            );
            if is_sky_parseable(&st) {
                format!("{base}, \"skyType\": {}}}", quote(&st))
            } else {
                format!("{base}}}")
            }
        })
        .collect();

    let mut lines: Vec<String> = vec![
        "{".to_string(),
        format!("  \"moduleName\": {},", quote(module_name)),
        format!("  \"kernelName\": {},", quote(kernel_name)),
        format!("  \"package\": {},", quote(&info.pkg)),
        "  \"functions\": [".to_string(),
        fn_entries.join(",\n"),
        "  ]".to_string(),
    ];

    if !info.implements.is_empty() {
        let body = info
            .implements
            .iter()
            .map(|(k, vs)| {
                let items = vs.iter().map(|v| quote(v)).collect::<Vec<_>>().join(", ");
                format!("      {}: [{}]", quote(k), items)
            })
            .collect::<Vec<_>>()
            .join(",\n");
        lines.push("  ,".to_string());
        lines.push("  \"implements\": {".to_string());
        lines.push(body);
        lines.push("  }".to_string());
    }
    if !info.pkg_alias.is_empty() {
        let body = info
            .pkg_alias
            .iter()
            .map(|(k, v)| format!("      {}: {}", quote(k), quote(v)))
            .collect::<Vec<_>>()
            .join(",\n");
        lines.push("  ,".to_string());
        lines.push("  \"pkgAlias\": {".to_string());
        lines.push(body);
        lines.push("  }".to_string());
    }
    lines.push("}".to_string());
    // `unlines` appends a trailing newline.
    let mut s = lines.join("\n");
    s.push('\n');
    s
}

// ---------------------------------------------------------------------------
// wrapperSkyType (FfiGen.hs:464-526) + isSkyParseable (536-545).
// ---------------------------------------------------------------------------

/// The full HM signature for a wrapper, including the `Result Error` wrap.
/// Mirrors `wrapperSkyType`.
pub fn wrapper_sky_type(fn_: &Function) -> String {
    let resolve = |p: &Param| -> String {
        if !p.sky_type_qualified.is_empty() {
            go_type_to_sky(&p.sky_type_qualified)
        } else if !p.sky_type.is_empty() {
            go_type_to_sky(&p.sky_type)
        } else {
            go_type_to_sky(&p.ty)
        }
    };

    let param_sig = if fn_.params.is_empty() {
        "()".to_string()
    } else {
        fn_.params.iter().map(&resolve).collect::<Vec<_>>().join(" -> ")
    };

    let non_err: Vec<&Param> = fn_.results.iter().filter(|p| p.ty != "error").collect();
    // `()` when: no results, a lone `error` result, or no non-error results.
    let is_unit = fn_.results.is_empty()
        || (fn_.results.len() == 1 && fn_.results[0].ty == "error")
        || non_err.is_empty();
    let inner_ok = if is_unit {
        "()".to_string()
    } else if non_err.len() == 1 {
        // comma-ok: (T, bool) with T != bool → Maybe T
        let is_comma_ok = fn_.results.len() == 2
            && fn_.results[1].ty == "bool"
            && fn_.results[0].ty != "bool";
        if is_comma_ok {
            format!("Maybe {}", wrap_if_multi(&resolve(non_err[0])))
        } else {
            resolve(non_err[0])
        }
    } else {
        format!(
            "({})",
            non_err.iter().map(|p| resolve(p)).collect::<Vec<_>>().join(", ")
        )
    };

    let ok_type = if inner_ok.starts_with('(') {
        format!("Result Error {inner_ok}")
    } else {
        format!("Result Error {}", wrap_if_multi(&inner_ok))
    };
    format!("{param_sig} -> {ok_type}")
}

fn wrap_if_multi(s: &str) -> String {
    if s.contains(' ') && !s.starts_with('(') {
        format!("({s})")
    } else {
        s.to_string()
    }
}

/// Reject Sky-type strings that still carry Go residue (channels, inline
/// struct/interface, un-stripped `func(`). Mirrors `isSkyParseable`.
pub fn is_sky_parseable(s: &str) -> bool {
    const BAD: [&str; 7] = ["<-", " chan ", "chan ", "interface{", "struct{", "func(", "{}"];
    !BAD.iter().any(|b| s.contains(b))
}

// ---------------------------------------------------------------------------
// goTypeToSky (FfiGen.hs:1836-1917).
// ---------------------------------------------------------------------------

/// Map a Go type expression to its Sky surface name. `[]*pkg.X` → `List X`,
/// `map[string]V` → `Dict String V`, pointers transparent, `[]byte` → `Bytes`.
pub fn go_type_to_sky(t: &str) -> String {
    if let Some(body) = t.strip_prefix("func(") {
        return format_func_type(body);
    }
    if t == "[]byte" {
        return "Bytes".to_string();
    }
    if let Some(inner) = t.strip_prefix("[]") {
        return format!("List {}", wrap_if_composite(&go_type_to_sky(inner)));
    }
    if let Some(inner) = t.strip_prefix('*') {
        return go_type_to_sky(inner);
    }
    if let Some(inner) = t.strip_prefix("map[string]") {
        return format!("Dict String {}", wrap_if_composite(&go_type_to_sky(inner)));
    }
    if let Some(rest) = t.strip_prefix("map[") {
        // map[K]V, K != string — surface as Dict String V.
        let (_k, v) = split_map_bracket(rest);
        return format!("Dict String {}", wrap_if_composite(&go_type_to_sky(v.trim())));
    }
    match t {
        "string" => "String".to_string(),
        "int" | "int64" | "int32" => "Int".to_string(),
        "float64" | "float32" => "Float".to_string(),
        "bool" => "Bool".to_string(),
        "error" => "String".to_string(),
        "interface{}" => "any".to_string(),
        "struct{}" => "()".to_string(),
        _ => strip_pkg(t),
    }
}

/// Qualified opaque markers (`Name@pkg`) keep their `@pkg` suffix intact; bare
/// dotted names drop the package prefix.
fn strip_pkg(s: &str) -> String {
    if s.contains('@') {
        s.to_string()
    } else {
        match s.rfind('.') {
            Some(i) => s[i + 1..].to_string(),
            None => s.to_string(),
        }
    }
}

fn wrap_if_composite(s: &str) -> String {
    if s.contains(' ') {
        format!("({s})")
    } else {
        s.to_string()
    }
}

/// For `map[K]V` (already past `map[`): return `(K, V)` splitting on the `]`
/// that matches the opening `[` (depth-aware for nested `[`).
fn split_map_bracket(s: &str) -> (&str, &str) {
    let mut depth = 1i32;
    for (i, c) in s.char_indices() {
        match c {
            '[' => depth += 1,
            ']' => {
                depth -= 1;
                if depth == 0 {
                    return (&s[..i], &s[i + 1..]);
                }
            }
            _ => {}
        }
    }
    (s, "")
}

fn format_func_type(body: &str) -> String {
    let (arg_part, ret_part) = split_at_close_paren(body);
    let sky_args: Vec<String> = split_commas(arg_part)
        .into_iter()
        .map(|a| go_type_to_sky(a.trim()))
        .collect();
    let sky_ret = if ret_part.trim().is_empty() {
        "()".to_string()
    } else {
        go_type_to_sky(ret_part.trim())
    };
    let mut parts = sky_args;
    parts.push(sky_ret);
    format!("({})", parts.join(" -> "))
}

/// Split `body` (interior of a `func(...)`, opening `(` already consumed) at the
/// matching close paren, returning `(args, rest-after-close)`.
fn split_at_close_paren(s: &str) -> (&str, &str) {
    let mut depth = 0i32;
    for (i, c) in s.char_indices() {
        match c {
            ')' if depth == 0 => return (&s[..i], &s[i + 1..]),
            '(' => depth += 1,
            ')' => depth -= 1,
            _ => {}
        }
    }
    (s, "")
}

fn split_commas(s: &str) -> Vec<&str> {
    if s.is_empty() {
        return vec![""];
    }
    s.split(',').collect()
}

// ---------------------------------------------------------------------------
// .skyi catalogue (FfiGen.hs:1782-1822).
// ---------------------------------------------------------------------------

fn emit_skyi(info: &PackageInfo) -> String {
    let aliases = crate::gen_bindings::build_alias_table(info);
    let mut lines: Vec<String> = vec![
        format!("-- Auto-generated FFI binding catalogue for {}", info.pkg),
        "--".to_string(),
        "-- All auto-generated bindings are registered effect-unknown and are".to_string(),
        "-- callable via Sky.Ffi.callTask. Every call returns Task Error a".to_string(),
        "-- with panic recovery — any Go panic is caught and surfaced as Err.".to_string(),
        "--".to_string(),
        "-- Opaque Go struct values flow through Sky as Any; use the bindings".to_string(),
        "-- to construct, read and update them. Sky records-with-methods can".to_string(),
        "-- bridge this gap idiomatically — define a record type whose methods".to_string(),
        "-- are the relevant callTask invocations.".to_string(),
        "--".to_string(),
        "-- Imports used in this package's wrapper:".to_string(),
    ];
    // sortOn fst over (path, alias): BTreeMap iterates by key (path) already.
    for (path, alias) in &aliases {
        lines.push(format!("--   {alias} \"{path}\""));
    }
    lines.push(String::new());
    lines.push(format!("package {}", info.name));
    for fn_ in &info.functions {
        lines.push(emit_skyi_fn(fn_));
    }
    let mut s = lines.join("\n");
    s.push('\n');
    s
}

fn emit_skyi_fn(fn_: &Function) -> String {
    let sig = if fn_.params.is_empty() {
        format!("() -> {}", go_results_to_sky(&fn_.results))
    } else {
        let params = fn_
            .params
            .iter()
            .map(|p| go_type_to_sky(&p.ty))
            .collect::<Vec<_>>()
            .join(" -> ");
        format!("{params} -> {}", go_results_to_sky(&fn_.results))
    };
    format!(
        "-- [{}] {} : {}   -- runtime wrap: Task Error",
        fn_.effect, fn_.name, sig
    )
}

fn go_results_to_sky(rs: &[Param]) -> String {
    match rs {
        [] => "()".to_string(),
        [one] => go_type_to_sky(&one.ty),
        many => format!(
            "({})",
            many.iter().map(|p| go_type_to_sky(&p.ty)).collect::<Vec<_>>().join(", ")
        ),
    }
}

// ---------------------------------------------------------------------------
// quote (FfiGen.hs:1923).
// ---------------------------------------------------------------------------

fn quote(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            _ => out.push(c),
        }
    }
    out.push('"');
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::Path;

    fn fixture(name: &str) -> String {
        let p = Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("tests")
            .join("fixtures")
            .join(name);
        std::fs::read_to_string(p).unwrap()
    }

    #[test]
    fn name_transforms() {
        assert_eq!(pkg_to_module_name("github.com/google/uuid"), "Github.Com.Google.Uuid");
        assert_eq!(
            pkg_to_module_name("github.com/stripe/stripe-go/v84"),
            "Github.Com.Stripe.StripeGo.V84"
        );
        assert_eq!(pkg_to_module_name("net/http"), "Net.Http");
        assert_eq!(kernel_name_from_pkg("github.com/google/uuid"), "Go_Uuid");
        // capOf sanitises the hyphen to `_` (matches the committed stripe
        // surface `Go_Stripe_goV84` — hyphen-fold camel is module-name only).
        assert_eq!(kernel_name_from_pkg("github.com/stripe/stripe-go/v84"), "Go_Stripe_goV84");
        assert_eq!(slugify("uuid"), "uuid");
    }

    #[test]
    fn go_type_mapping() {
        assert_eq!(go_type_to_sky("string"), "String");
        assert_eq!(go_type_to_sky("*github.com/google/uuid.UUID"), "UUID");
        assert_eq!(go_type_to_sky("[]byte"), "Bytes");
        assert_eq!(go_type_to_sky("[]string"), "List String");
        assert_eq!(go_type_to_sky("map[string]int"), "Dict String Int");
        assert_eq!(go_type_to_sky("UUID@github.com/google/uuid"), "UUID@github.com/google/uuid");
    }

    #[test]
    fn kernel_json_matches_committed_uuid() {
        let mut info = crate::inspect::parse_one(&fixture("uuid.inspector.json")).unwrap();
        crate::inspect::normalize(&mut info);
        let got = emit_kernel_json(
            &pkg_to_module_name(&info.pkg),
            &kernel_name_from_pkg(&info.pkg),
            &info,
        );
        // Structural checks: the committed surface (function ORDER aside — we
        // sort for determinism) must carry the same header + every function's
        // skyType. Byte-equality is asserted separately once normalization order
        // is reconciled with the committed file.
        assert!(got.contains("\"moduleName\": \"Github.Com.Google.Uuid\""));
        assert!(got.contains("\"kernelName\": \"Go_Uuid\""));
        assert!(got.contains("\"package\": \"github.com/google/uuid\""));
        assert!(got.contains(
            "{\"name\": \"newString\", \"arity\": 1, \"skyType\": \"() -> Result Error String\"}"
        ));
        assert!(got.contains("\"implements\": {"));
        assert!(got.contains("\"pkgAlias\": {"));
        // Every committed function name appears.
        let committed = fixture("uuid.expected.kernel.json");
        for fn_ in &info.functions {
            if should_skip_fn(fn_) {
                continue;
            }
            let name = lower_first(&fn_.name);
            let needle = format!("\"name\": \"{name}\"");
            assert!(committed.contains(&needle), "committed missing {name}");
            assert!(got.contains(&needle), "generated missing {name}");
        }
    }
}
