package sky_wrappers

import (
	_ffi_fmt "fmt"
	_ffi_reflect "reflect"
	uuid "github.com/google/uuid"
)

var _ = _ffi_fmt.Sprintf
// Auto-generated by Sky compiler

func Sky_github_com_google_uuid_ClockSequence(_ any) any {
	
	return func() any {
		defer func() { recover() }()
		result := uuid.ClockSequence()
		return SkyOk(result)
	}()
}

func Sky_github_com_google_uuid_DisableRandPool(_ any) any {
	
	return func() any {
		defer func() { recover() }()
		uuid.DisableRandPool()
		return SkyOk(struct{}{})
	}()
}

func Sky_github_com_google_uuid_EnableRandPool(_ any) any {
	
	return func() any {
		defer func() { recover() }()
		uuid.EnableRandPool()
		return SkyOk(struct{}{})
	}()
}

func Sky_github_com_google_uuid_FromBytes(arg0 any) any {
	_arg0 := sky_asBytes(arg0)
	return func() any {
		defer func() { recover() }()
		result, err := uuid.FromBytes(_arg0)
		if err != nil { return SkyErr(err.Error()) }
		return SkyOk(result)
	}()
}

func Sky_github_com_google_uuid_IsInvalidLengthError(arg0 any) any {
	_arg0 := sky_asError(arg0)
	return func() any {
		defer func() { recover() }()
		result := uuid.IsInvalidLengthError(_arg0)
		return SkyOk(result)
	}()
}

func Sky_github_com_google_uuid_Must(arg0 any, arg1 any) any {
	_arg0 := arg0.(uuid.UUID)
	_arg1 := sky_asError(arg1)
	return func() any {
		defer func() { recover() }()
		result := uuid.Must(_arg0, _arg1)
		return SkyOk(result)
	}()
}

func Sky_github_com_google_uuid_MustParse(arg0 any) any {
	_arg0 := sky_asString(arg0)
	return func() any {
		defer func() { recover() }()
		result := uuid.MustParse(_arg0)
		return SkyOk(result)
	}()
}

func Sky_github_com_google_uuid_New(_ any) any {
	
	return func() any {
		defer func() { recover() }()
		result := uuid.New()
		return SkyOk(result)
	}()
}

func Sky_github_com_google_uuid_NewDCEGroup(_ any) any {
	
	return func() any {
		defer func() { recover() }()
		result, err := uuid.NewDCEGroup()
		if err != nil { return SkyErr(err.Error()) }
		return SkyOk(result)
	}()
}

func Sky_github_com_google_uuid_NewDCEPerson(_ any) any {
	
	return func() any {
		defer func() { recover() }()
		result, err := uuid.NewDCEPerson()
		if err != nil { return SkyErr(err.Error()) }
		return SkyOk(result)
	}()
}

func Sky_github_com_google_uuid_NewDCESecurity(arg0 any, arg1 any) any {
	_arg0 := arg0.(uuid.Domain)
	_arg1 := sky_asUint32(arg1)
	return func() any {
		defer func() { recover() }()
		result, err := uuid.NewDCESecurity(_arg0, _arg1)
		if err != nil { return SkyErr(err.Error()) }
		return SkyOk(result)
	}()
}

func Sky_github_com_google_uuid_NewMD5(arg0 any, arg1 any) any {
	_arg0 := arg0.(uuid.UUID)
	_arg1 := sky_asBytes(arg1)
	return func() any {
		defer func() { recover() }()
		result := uuid.NewMD5(_arg0, _arg1)
		return SkyOk(result)
	}()
}

func Sky_github_com_google_uuid_NewRandom(_ any) any {
	
	return func() any {
		defer func() { recover() }()
		result, err := uuid.NewRandom()
		if err != nil { return SkyErr(err.Error()) }
		return SkyOk(result)
	}()
}

func Sky_github_com_google_uuid_NewSHA1(arg0 any, arg1 any) any {
	_arg0 := arg0.(uuid.UUID)
	_arg1 := sky_asBytes(arg1)
	return func() any {
		defer func() { recover() }()
		result := uuid.NewSHA1(_arg0, _arg1)
		return SkyOk(result)
	}()
}

func Sky_github_com_google_uuid_NewString(_ any) any {
	
	return func() any {
		defer func() { recover() }()
		result := uuid.NewString()
		return SkyOk(result)
	}()
}

func Sky_github_com_google_uuid_NewUUID(_ any) any {
	
	return func() any {
		defer func() { recover() }()
		result, err := uuid.NewUUID()
		if err != nil { return SkyErr(err.Error()) }
		return SkyOk(result)
	}()
}

func Sky_github_com_google_uuid_NewV6(_ any) any {
	
	return func() any {
		defer func() { recover() }()
		result, err := uuid.NewV6()
		if err != nil { return SkyErr(err.Error()) }
		return SkyOk(result)
	}()
}

func Sky_github_com_google_uuid_NewV7(_ any) any {
	
	return func() any {
		defer func() { recover() }()
		result, err := uuid.NewV7()
		if err != nil { return SkyErr(err.Error()) }
		return SkyOk(result)
	}()
}

func Sky_github_com_google_uuid_NodeID(_ any) any {
	
	return func() any {
		defer func() { recover() }()
		result := uuid.NodeID()
		return SkyOk(result[:])
	}()
}

func Sky_github_com_google_uuid_NodeInterface(_ any) any {
	
	return func() any {
		defer func() { recover() }()
		result := uuid.NodeInterface()
		return SkyOk(result)
	}()
}

func Sky_github_com_google_uuid_Parse(arg0 any) any {
	_arg0 := sky_asString(arg0)
	return func() any {
		defer func() { recover() }()
		result, err := uuid.Parse(_arg0)
		if err != nil { return SkyErr(err.Error()) }
		return SkyOk(result)
	}()
}

func Sky_github_com_google_uuid_ParseBytes(arg0 any) any {
	_arg0 := sky_asBytes(arg0)
	return func() any {
		defer func() { recover() }()
		result, err := uuid.ParseBytes(_arg0)
		if err != nil { return SkyErr(err.Error()) }
		return SkyOk(result)
	}()
}

func Sky_github_com_google_uuid_SetClockSequence(arg0 any) any {
	_arg0 := sky_asInt(arg0)
	return func() any {
		defer func() { recover() }()
		uuid.SetClockSequence(_arg0)
		return SkyOk(struct{}{})
	}()
}

func Sky_github_com_google_uuid_SetNodeID(arg0 any) any {
	_arg0 := sky_asBytes(arg0)
	return func() any {
		defer func() { recover() }()
		result := uuid.SetNodeID(_arg0)
		return SkyOk(result)
	}()
}

func Sky_github_com_google_uuid_SetNodeInterface(arg0 any) any {
	_arg0 := sky_asString(arg0)
	return func() any {
		defer func() { recover() }()
		result := uuid.SetNodeInterface(_arg0)
		return SkyOk(result)
	}()
}

func Sky_github_com_google_uuid_Validate(arg0 any) any {
	_arg0 := sky_asString(arg0)
	return func() any {
		defer func() { recover() }()
		err := uuid.Validate(_arg0)
		if err != nil { return SkyErr(err.Error()) }
		return SkyOk(struct{}{})
	}()
}

func Sky_github_com_google_uuid_DomainString(receiver any) any {
	_receiver := receiver.(*uuid.Domain)
	return func() any {
		defer func() { recover() }()
		result := _receiver.String()
		return SkyOk(result)
	}()
}

func Sky_github_com_google_uuid_NullUUIDMarshalBinary(receiver any) any {
	_receiver := receiver.(*uuid.NullUUID)
	return func() any {
		defer func() { recover() }()
		result, err := _receiver.MarshalBinary()
		if err != nil { return SkyErr(err.Error()) }
		return SkyOk(result)
	}()
}

func Sky_github_com_google_uuid_NullUUIDMarshalJSON(receiver any) any {
	_receiver := receiver.(*uuid.NullUUID)
	return func() any {
		defer func() { recover() }()
		result, err := _receiver.MarshalJSON()
		if err != nil { return SkyErr(err.Error()) }
		return SkyOk(result)
	}()
}

func Sky_github_com_google_uuid_NullUUIDMarshalText(receiver any) any {
	_receiver := receiver.(*uuid.NullUUID)
	return func() any {
		defer func() { recover() }()
		result, err := _receiver.MarshalText()
		if err != nil { return SkyErr(err.Error()) }
		return SkyOk(result)
	}()
}

func Sky_github_com_google_uuid_NullUUIDScan(receiver any, arg0 any) any {
	_receiver := receiver.(*uuid.NullUUID)
	_arg0 := arg0
	return func() any {
		defer func() { recover() }()
		err := _receiver.Scan(_arg0)
		if err != nil { return SkyErr(err.Error()) }
		return SkyOk(struct{}{})
	}()
}

func Sky_github_com_google_uuid_NullUUIDUnmarshalBinary(receiver any, arg0 any) any {
	_receiver := receiver.(*uuid.NullUUID)
	_arg0 := sky_asBytes(arg0)
	return func() any {
		defer func() { recover() }()
		err := _receiver.UnmarshalBinary(_arg0)
		if err != nil { return SkyErr(err.Error()) }
		return SkyOk(struct{}{})
	}()
}

func Sky_github_com_google_uuid_NullUUIDUnmarshalJSON(receiver any, arg0 any) any {
	_receiver := receiver.(*uuid.NullUUID)
	_arg0 := sky_asBytes(arg0)
	return func() any {
		defer func() { recover() }()
		err := _receiver.UnmarshalJSON(_arg0)
		if err != nil { return SkyErr(err.Error()) }
		return SkyOk(struct{}{})
	}()
}

func Sky_github_com_google_uuid_NullUUIDUnmarshalText(receiver any, arg0 any) any {
	_receiver := receiver.(*uuid.NullUUID)
	_arg0 := sky_asBytes(arg0)
	return func() any {
		defer func() { recover() }()
		err := _receiver.UnmarshalText(_arg0)
		if err != nil { return SkyErr(err.Error()) }
		return SkyOk(struct{}{})
	}()
}

func Sky_github_com_google_uuid_TimeUnixTime(receiver any) any {
	_receiver := receiver.(*uuid.Time)
	return func() any {
		defer func() { recover() }()
		_r0, _r1 := _receiver.UnixTime()
		return SkyOk(SkyTuple2{_r0, _r1})
	}()
}

func Sky_github_com_google_uuid_UUIDClockSequence(receiver any) any {
	_receiver := receiver.(*uuid.UUID)
	return func() any {
		defer func() { recover() }()
		result := _receiver.ClockSequence()
		return SkyOk(result)
	}()
}

func Sky_github_com_google_uuid_UUIDDomain(receiver any) any {
	_receiver := receiver.(*uuid.UUID)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Domain()
		return SkyOk(result)
	}()
}

func Sky_github_com_google_uuid_UUIDID(receiver any) any {
	_receiver := receiver.(*uuid.UUID)
	return func() any {
		defer func() { recover() }()
		result := _receiver.ID()
		return SkyOk(result)
	}()
}

func Sky_github_com_google_uuid_UUIDMarshalBinary(receiver any) any {
	_receiver := receiver.(*uuid.UUID)
	return func() any {
		defer func() { recover() }()
		result, err := _receiver.MarshalBinary()
		if err != nil { return SkyErr(err.Error()) }
		return SkyOk(result)
	}()
}

func Sky_github_com_google_uuid_UUIDMarshalText(receiver any) any {
	_receiver := receiver.(*uuid.UUID)
	return func() any {
		defer func() { recover() }()
		result, err := _receiver.MarshalText()
		if err != nil { return SkyErr(err.Error()) }
		return SkyOk(result)
	}()
}

func Sky_github_com_google_uuid_UUIDNodeID(receiver any) any {
	_receiver := receiver.(*uuid.UUID)
	return func() any {
		defer func() { recover() }()
		result := _receiver.NodeID()
		return SkyOk(result[:])
	}()
}

func Sky_github_com_google_uuid_UUIDScan(receiver any, arg0 any) any {
	_receiver := receiver.(*uuid.UUID)
	_arg0 := arg0
	return func() any {
		defer func() { recover() }()
		err := _receiver.Scan(_arg0)
		if err != nil { return SkyErr(err.Error()) }
		return SkyOk(struct{}{})
	}()
}

func Sky_github_com_google_uuid_UUIDString(receiver any) any {
	_receiver := receiver.(*uuid.UUID)
	return func() any {
		defer func() { recover() }()
		result := _receiver.String()
		return SkyOk(result)
	}()
}

func Sky_github_com_google_uuid_UUIDTime(receiver any) any {
	_receiver := receiver.(*uuid.UUID)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Time()
		return SkyOk(result)
	}()
}

func Sky_github_com_google_uuid_UUIDURN(receiver any) any {
	_receiver := receiver.(*uuid.UUID)
	return func() any {
		defer func() { recover() }()
		result := _receiver.URN()
		return SkyOk(result)
	}()
}

func Sky_github_com_google_uuid_UUIDUnmarshalBinary(receiver any, arg0 any) any {
	_receiver := receiver.(*uuid.UUID)
	_arg0 := sky_asBytes(arg0)
	return func() any {
		defer func() { recover() }()
		err := _receiver.UnmarshalBinary(_arg0)
		if err != nil { return SkyErr(err.Error()) }
		return SkyOk(struct{}{})
	}()
}

func Sky_github_com_google_uuid_UUIDUnmarshalText(receiver any, arg0 any) any {
	_receiver := receiver.(*uuid.UUID)
	_arg0 := sky_asBytes(arg0)
	return func() any {
		defer func() { recover() }()
		err := _receiver.UnmarshalText(_arg0)
		if err != nil { return SkyErr(err.Error()) }
		return SkyOk(struct{}{})
	}()
}

func Sky_github_com_google_uuid_UUIDVariant(receiver any) any {
	_receiver := receiver.(*uuid.UUID)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Variant()
		return SkyOk(result)
	}()
}

func Sky_github_com_google_uuid_UUIDVersion(receiver any) any {
	_receiver := receiver.(*uuid.UUID)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Version()
		return SkyOk(result)
	}()
}

func Sky_github_com_google_uuid_UUIDsStrings(receiver any) any {
	_receiver := receiver.(*uuid.UUIDs)
	return func() any {
		defer func() { recover() }()
		result := _receiver.Strings()
		return SkyOk(result[:])
	}()
}

func Sky_github_com_google_uuid_VariantString(receiver any) any {
	_receiver := receiver.(*uuid.Variant)
	return func() any {
		defer func() { recover() }()
		result := _receiver.String()
		return SkyOk(result)
	}()
}

func Sky_github_com_google_uuid_VersionString(receiver any) any {
	_receiver := receiver.(*uuid.Version)
	return func() any {
		defer func() { recover() }()
		result := _receiver.String()
		return SkyOk(result)
	}()
}

func Sky_github_com_google_uuid_FIELD_NullUUID_UUID(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr { v = v.Elem() }
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("UUID")
		if f.IsValid() { return f.Interface() }
	}
	return nil
}

func Sky_github_com_google_uuid_FIELD_NullUUID_Valid(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr { v = v.Elem() }
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("Valid")
		if f.IsValid() { return f.Interface() }
	}
	return nil
}

func Sky_github_com_google_uuid_Max(_ any) any {
	return uuid.Max
}

func Sky_github_com_google_uuid_NameSpaceDNS(_ any) any {
	return uuid.NameSpaceDNS
}

func Sky_github_com_google_uuid_NameSpaceOID(_ any) any {
	return uuid.NameSpaceOID
}

func Sky_github_com_google_uuid_NameSpaceURL(_ any) any {
	return uuid.NameSpaceURL
}

func Sky_github_com_google_uuid_NameSpaceX500(_ any) any {
	return uuid.NameSpaceX500
}

func Sky_github_com_google_uuid_Nil(_ any) any {
	return uuid.Nil
}

func Sky_github_com_google_uuid_Future(_ any) any {
	return uuid.Future
}

func Sky_github_com_google_uuid_Group(_ any) any {
	return uuid.Group
}

func Sky_github_com_google_uuid_Invalid(_ any) any {
	return uuid.Invalid
}

func Sky_github_com_google_uuid_Microsoft(_ any) any {
	return uuid.Microsoft
}

func Sky_github_com_google_uuid_Org(_ any) any {
	return uuid.Org
}

func Sky_github_com_google_uuid_Person(_ any) any {
	return uuid.Person
}

func Sky_github_com_google_uuid_RFC4122(_ any) any {
	return uuid.RFC4122
}

func Sky_github_com_google_uuid_Reserved(_ any) any {
	return uuid.Reserved
}