name = "notes-app"
version = "0.1.0"
entry = "src/Main.sky"

[source]
root = "src"

[database]
driver = "sqlite"
path = "skynotes.db"

["go.dependencies"]
"net/http" = "latest"
"github.com/gorilla/mux" = "latest"
"crypto/sha256" = "latest"
"encoding/hex" = "latest"
"github.com/google/uuid" = "latest"
"io" = "latest"
"os" = "latest"
