func Lib_Notify_NotifyOrderPlaced(cart any, items any, userName any, userEmail any) any {
	return func() any { env := sky_call(sky_resultWithDefault(""), Os_Getenv("ENV")); _ = env; cartId := Lib_Db_GetField("id", cart); _ = cartId; totalAmount := Lib_Db_GetField("total_amount", cart); _ = totalAmount; totalCurrency := Lib_Db_GetField("total_currency", cart); _ = totalCurrency; itemCount := sky_stringFromInt(sky_listLength(items)); _ = itemCount; prefix := func() any { if sky_asBool(sky_equal(env, "production")) { return "[REAL]" }; return "[Test]" }(); _ = prefix; subject := sky_concat(prefix, sky_concat(" New order from ", sky_concat(userName, sky_concat(" (", sky_concat(userEmail, ")"))))); _ = subject; body := sky_concat(subject, sky_concat(" - ", sky_concat(itemCount, sky_concat(" items, ", sky_concat(totalCurrency, sky_concat(" ", totalAmount)))))); _ = body; notificationId := sky_call(sky_resultWithDefault(""), Github_Com_Google_Uuid_NewString(struct{}{})); _ = notificationId; notificationData := sky_dictFromList([]any{SkyTuple2{V0: "id", V1: notificationId}, SkyTuple2{V0: "notification_type", V1: "order"}, SkyTuple2{V0: "subject", V1: subject}, SkyTuple2{V0: "body", V1: body}, SkyTuple2{V0: "sent", V1: Lib_Db_BoolVal(false)}}); _ = notificationData; sky_call(Lib_Notify_IgnoreResult, Lib_Db_SetDoc("notifications", notificationId, notificationData)); sky_println(sky_concat("[NOTIFY] ", body)); Lib_Notify_SendEmailNotification(notificationId, subject, body); return struct{}{} }()
}

func Lib_Notify_IgnoreResult(result any) any {
	return func() any { return func() any { __subject := result; if sky_asSkyResult(__subject).SkyName == "Ok" { return struct{}{} };  if sky_asSkyResult(__subject).SkyName == "Err" { return struct{}{} };  return nil }() }()
}

func Lib_Notify_SendEmailNotification(notificationId any, subject any, body any) any {
	return func() any { smtpHost := sky_call(sky_resultWithDefault(""), Os_Getenv("SMTP_HOST")); _ = smtpHost; notifyTo := sky_call(sky_resultWithDefault(""), Os_Getenv("NOTIFY_TO")); _ = notifyTo; return func() any { if sky_asBool(sky_asBool(sky_equal(smtpHost, "")) || sky_asBool(sky_equal(notifyTo, ""))) { return func() any { sky_println("[NOTIFY] Email not configured (SMTP_HOST or NOTIFY_TO missing), skipping."); return struct{}{} }() }; return func() any { sky_println(sky_concat("[NOTIFY] Would send email to ", sky_concat(notifyTo, sky_concat(": ", subject)))); func() any { return func() any { __subject := Lib_Db_GetDoc("notifications", notificationId); if sky_asSkyResult(__subject).SkyName == "Ok" && sky_asSkyMaybe(sky_asSkyResult(__subject).OkValue).SkyName == "Just" { notification := sky_asSkyMaybe(sky_asSkyResult(__subject).OkValue).JustValue; _ = notification; return Lib_Db_SetDoc("notifications", notificationId, sky_call2(sky_dictInsert("sent"), Lib_Db_BoolVal(true), notification)) };  if true { return SkyOk(struct{}{}) };  return nil }() }(); return struct{}{} }() }() }()
}