func Lib_Stripe_InitStripe() any {
	return func() any { key := sky_call(sky_resultWithDefault(""), Os_Getenv("STRIPE_API_KEY")); _ = key; Github_Com_Stripe_StripeGo_V84_SetKey(key); return key }()
}

func Lib_Stripe_ApiKey() any {
	return Lib_Stripe_InitStripe()
}

func Lib_Stripe_DomainUrl() any {
	return func() any { domain := sky_call(sky_resultWithDefault(""), Os_Getenv("DOMAIN")); _ = domain; port_ := sky_call(sky_resultWithDefault(""), Os_Getenv("SKY_LIVE_PORT")); _ = port_; return func() any { if sky_asBool(!sky_equal(domain, "")) { return domain }; return func() any { effectivePort := func() any { if sky_asBool(sky_equal(port_, "")) { return "4000" }; return port_ }(); _ = effectivePort; return sky_concat("http://localhost:", effectivePort) }() }() }()
}

func Lib_Stripe_GetOrCreateCustomer(userId any, userName any, userEmail any) any {
	return func() any { iter := Github_Com_Stripe_StripeGo_V84_Customer_List(map[string]any{"email": userEmail, "limit": 1}); _ = iter; return func() any { if sky_asBool(Github_Com_Stripe_StripeGo_V84_Customer_IterNext(iter)) { return func() any { c := Github_Com_Stripe_StripeGo_V84_Customer_IterCustomer(iter); _ = c; customerId := Github_Com_Stripe_StripeGo_V84_CustomerID(c); _ = customerId; sky_println(sky_concat("[STRIPE] Found existing customer: ", customerId)); return SkyOk(customerId) }() }; return Lib_Stripe_CreateCustomer(userId, userName, userEmail) }() }()
}

func Lib_Stripe_CreateCustomer(userId any, userName any, userEmail any) any {
	return func() any { params := map[string]any{"email": userEmail, "name": userName, "metadata": sky_dictFromList([]any{SkyTuple2{V0: "sky_uid", V1: userId}})}; _ = params; return func() any { return func() any { __subject := Github_Com_Stripe_StripeGo_V84_Customer_New_(params); if sky_asSkyResult(__subject).SkyName == "Ok" { c := sky_asSkyResult(__subject).OkValue; _ = c; return func() any { customerId := Github_Com_Stripe_StripeGo_V84_CustomerID(c); _ = customerId; sky_println(sky_concat("[STRIPE] Created customer: ", customerId)); return SkyOk(customerId) }() };  if sky_asSkyResult(__subject).SkyName == "Err" { e := sky_asSkyResult(__subject).ErrValue; _ = e; return SkyErr(sky_concat("Failed to create Stripe customer: ", sky_errorToString(e))) };  return nil }() }() }()
}

func Lib_Stripe_BuildLineItems(items any) any {
	return sky_call(sky_listMap(func(item any) any { return func() any { title := Lib_Db_GetField("title", item); _ = title; price := Lib_Db_GetInt("price_amount", item); _ = price; discount := Lib_Db_GetInt("price_discount", item); _ = discount; effectivePrice := func() any { if sky_asBool(sky_asInt(sky_asInt(price) - sky_asInt(discount)) > sky_asInt(0)) { return sky_asInt(price) - sky_asInt(discount) }; return price }(); _ = effectivePrice; qty := Lib_Db_GetInt("quantity", item); _ = qty; currency := sky_stringToLower(Lib_Db_GetField("price_currency", item)); _ = currency; return map[string]any{"price_data": map[string]any{"product_data": map[string]any{"name": title}, "unit_amount": effectivePrice, "currency": currency}, "quantity": qty} }() }), items)
}

func Lib_Stripe_CreateCheckoutSession(cartId any, items any, userId any, userName any, userEmail any, remarks any) any {
	return func() any { if sky_asBool(sky_equal(Lib_Stripe_ApiKey(), "")) { return SkyErr("Stripe API key not configured. Set STRIPE_API_KEY environment variable.") }; return func() any { return func() any { __subject := Lib_Stripe_GetOrCreateCustomer(userId, userName, userEmail); if sky_asSkyResult(__subject).SkyName == "Err" { e := sky_asSkyResult(__subject).ErrValue; _ = e; return SkyErr(e) };  if sky_asSkyResult(__subject).SkyName == "Ok" { customerId := sky_asSkyResult(__subject).OkValue; _ = customerId; return func() any { successUrl := sky_concat(Lib_Stripe_DomainUrl(), sky_concat("/order/", sky_concat(cartId, "/success"))); _ = successUrl; cancelUrl := sky_concat(Lib_Stripe_DomainUrl(), "/cart"); _ = cancelUrl; lineItems := Lib_Stripe_BuildLineItems(items); _ = lineItems; params := map[string]any{"mode": "payment", "success_url": successUrl, "cancel_url": cancelUrl, "customer": customerId, "line_items": lineItems, "shipping_address_collection": map[string]any{"allowed_countries": []any{"GB", "HK", "MO"}}, "phone_number_collection": map[string]any{"enabled": true}, "custom_fields": []any{map[string]any{"key": "remarks", "label": map[string]any{"type_": "custom", "custom": "Delivery remarks"}, "type_": "text", "optional": true}}, "metadata": sky_dictFromList([]any{SkyTuple2{V0: "cart_id", V1: cartId}, SkyTuple2{V0: "remarks", V1: remarks}})}; _ = params; sky_println(sky_concat("[STRIPE] Creating checkout session for cart: ", cartId)); return func() any { return func() any { __subject := Github_Com_Stripe_StripeGo_V84_Checkout_Session_New_(params); if sky_asSkyResult(__subject).SkyName == "Ok" { sess := sky_asSkyResult(__subject).OkValue; _ = sess; return func() any { sessionId := Github_Com_Stripe_StripeGo_V84_CheckoutSessionID(sess); _ = sessionId; sessionUrl := Github_Com_Stripe_StripeGo_V84_CheckoutSessionURL(sess); _ = sessionUrl; return SkyOk(map[string]any{"id": sessionId, "url": sessionUrl}) }() };  if sky_asSkyResult(__subject).SkyName == "Err" { e := sky_asSkyResult(__subject).ErrValue; _ = e; return func() any { sky_println(sky_concat("[STRIPE] API error: ", sky_errorToString(e))); return SkyErr(sky_concat("Stripe API error: ", sky_errorToString(e))) }() };  return nil }() }() }() };  return nil }() }() }()
}

func Lib_Stripe_VerifyPayment(orderId any) any {
	return func() any { doc := func() any { return func() any { __subject := Lib_Db_GetDoc("orders", orderId); if sky_asSkyResult(__subject).SkyName == "Ok" && sky_asSkyMaybe(sky_asSkyResult(__subject).OkValue).SkyName == "Just" { order := sky_asSkyMaybe(sky_asSkyResult(__subject).OkValue).JustValue; _ = order; return SkyJust(order) };  if true { return func() any { return func() any { __subject := Lib_Db_GetDoc("carts", orderId); if sky_asSkyResult(__subject).SkyName == "Ok" && sky_asSkyMaybe(sky_asSkyResult(__subject).OkValue).SkyName == "Just" { cart := sky_asSkyMaybe(sky_asSkyResult(__subject).OkValue).JustValue; _ = cart; return SkyJust(cart) };  if true { return SkyNothing() };  return nil }() }() };  return nil }() }(); _ = doc; return func() any { return func() any { __subject := doc; if sky_asSkyMaybe(__subject).SkyName == "Just" { order := sky_asSkyMaybe(__subject).JustValue; _ = order; return func() any { reference := Lib_Db_GetField("checkout_reference", order); _ = reference; return func() any { if sky_asBool(sky_equal(reference, "")) { return SkyErr("No checkout reference found.") }; return Lib_Stripe_VerifyStripeSession(orderId, reference) }() }() };  if sky_asSkyMaybe(__subject).SkyName == "Nothing" { return SkyErr("Order not found.") };  return nil }() }() }()
}

func Lib_Stripe_VerifyStripeSession(cartId any, sessionId any) any {
	return func() any { return func() any { __subject := Github_Com_Stripe_StripeGo_V84_Checkout_Session_Get(sessionId, sky_js); if sky_asSkyResult(__subject).SkyName == "Ok" { sess := sky_asSkyResult(__subject).OkValue; _ = sess; return func() any { status := Github_Com_Stripe_StripeGo_V84_CheckoutSessionStatus(sess); _ = status; paymentStatus := Github_Com_Stripe_StripeGo_V84_CheckoutSessionPaymentStatus(sess); _ = paymentStatus; return func() any { if sky_asBool(sky_asBool(sky_equal(status, Github_Com_Stripe_StripeGo_V84_CheckoutSessionStatusComplete())) && sky_asBool(sky_equal(paymentStatus, Github_Com_Stripe_StripeGo_V84_CheckoutSessionPaymentStatusPaid()))) { return func() any { sky_println(sky_concat("[STRIPE] Payment verified for cart: ", cartId)); customerDetails := Github_Com_Stripe_StripeGo_V84_CheckoutSessionCustomerDetails(sess); _ = customerDetails; custName := Github_Com_Stripe_StripeGo_V84_CheckoutSessionCustomerDetailsName(customerDetails); _ = custName; custEmail := Github_Com_Stripe_StripeGo_V84_CheckoutSessionCustomerDetailsEmail(customerDetails); _ = custEmail; custPhone := Github_Com_Stripe_StripeGo_V84_CheckoutSessionCustomerDetailsPhone(customerDetails); _ = custPhone; collectedInfo := Github_Com_Stripe_StripeGo_V84_CheckoutSessionCollectedInformation(sess); _ = collectedInfo; shippingDetails := Github_Com_Stripe_StripeGo_V84_CheckoutSessionCollectedInformationShippingDetails(collectedInfo); _ = shippingDetails; shippingName := Github_Com_Stripe_StripeGo_V84_CheckoutSessionCollectedInformationShippingDetailsName(shippingDetails); _ = shippingName; shippingAddr := Github_Com_Stripe_StripeGo_V84_CheckoutSessionCollectedInformationShippingDetailsAddress(shippingDetails); _ = shippingAddr; return SkyOk(map[string]any{"status": status, "paymentStatus": paymentStatus, "customerName": func() any { if sky_asBool(!sky_equal(custName, "")) { return custName }; return shippingName }(), "customerEmail": custEmail, "customerPhone": custPhone, "shippingLine1": Github_Com_Stripe_StripeGo_V84_AddressLine1(shippingAddr), "shippingLine2": Github_Com_Stripe_StripeGo_V84_AddressLine2(shippingAddr), "shippingCity": Github_Com_Stripe_StripeGo_V84_AddressCity(shippingAddr), "shippingCountry": Github_Com_Stripe_StripeGo_V84_AddressCountry(shippingAddr), "shippingPostalCode": Github_Com_Stripe_StripeGo_V84_AddressPostalCode(shippingAddr)}) }() }; return SkyErr("Payment not complete.") }() }() };  if sky_asSkyResult(__subject).SkyName == "Err" { e := sky_asSkyResult(__subject).ErrValue; _ = e; return SkyErr(sky_concat("Failed to retrieve checkout session: ", sky_errorToString(e))) };  return nil }() }()
}

func Lib_Stripe_DeductStock(orderId any) any {
	return func() any { orderItems := sky_call(sky_resultWithDefault([]any{}), Lib_Db_QueryWhere("order_items", "order_id", "==", orderId)); _ = orderItems; items := func() any { if sky_asBool(sky_listIsEmpty(orderItems)) { return sky_call(sky_resultWithDefault([]any{}), Lib_Db_QueryWhere("cart_items", "cart_id", "==", orderId)) }; return orderItems }(); _ = items; sky_call(sky_listMap(Lib_Stripe_DeductItemStock), items); sky_println(sky_concat("[STOCK] Deducted for order: ", orderId)); return struct{}{} }()
}

func Lib_Stripe_DeductItemStock(item any) any {
	return func() any { productId := Lib_Db_GetField("product_id", item); _ = productId; qty := Lib_Db_GetInt("quantity", item); _ = qty; return func() any { return func() any { __subject := Lib_Db_GetDoc("products", productId); if sky_asSkyResult(__subject).SkyName == "Ok" && sky_asSkyMaybe(sky_asSkyResult(__subject).OkValue).SkyName == "Just" { product := sky_asSkyMaybe(sky_asSkyResult(__subject).OkValue).JustValue; _ = product; return func() any { currentStock := Lib_Db_GetInt("stock", product); _ = currentStock; return func() any { if sky_asBool(sky_asInt(currentStock) >= sky_asInt(0)) { return func() any { newStock := func() any { if sky_asBool(sky_asInt(sky_asInt(currentStock) - sky_asInt(qty)) >= sky_asInt(0)) { return sky_asInt(currentStock) - sky_asInt(qty) }; return 0 }(); _ = newStock; updatedProduct := sky_call2(sky_dictInsert("stock"), Lib_Db_IntVal(newStock), product); _ = updatedProduct; Lib_Db_SetDoc("products", productId, updatedProduct); return struct{}{} }() }; return struct{}{} }() }() };  if true { return struct{}{} };  return nil }() }() }()
}