func Page_Static_ViewPrivacyPolicy(model any) any {
	return Ui_Layout_Page(model, sky_call(sky_call(sky_htmlEl("div"), []any{tw([]any{maxW3xl, mxAuto, py8})}), []any{sky_call(sky_call(sky_htmlEl("h1"), []any{tw([]any{text3xl, fontBold, mb6})}), []any{sky_htmlText("Privacy Policy")}), sky_call(sky_call(sky_htmlEl("div"), []any{tw([]any{textGray600, leadingRelaxed})}), []any{Page_Static_Section_("1. Information We Collect", "We collect personal information you provide when creating an account, placing an order, or contacting us. This includes your name, email address, phone number, shipping address, and payment information (processed securely through Stripe)."), Page_Static_Section_("2. How We Use Your Information", "We use your information to process orders, communicate with you about your purchases, improve our services, and comply with legal obligations. We do not sell your personal information to third parties."), Page_Static_Section_("3. Payment Security", "All payment processing is handled by Stripe, a PCI-compliant payment processor. We do not store credit card numbers or sensitive payment details on our servers."), Page_Static_Section_("4. Data Retention", "We retain your account information for as long as your account is active. Order history is kept for tax and legal compliance purposes. You may request deletion of your account by contacting us."), Page_Static_Section_("5. Cookies", "We use session cookies to maintain your login state and shopping cart. These are essential for the functioning of the website and cannot be disabled."), Page_Static_Section_("6. Your Rights", "You have the right to access, correct, or delete your personal data. You may also withdraw consent for data processing at any time by contacting us."), Page_Static_Section_("7. Contact", "For privacy-related inquiries, please contact us at privacy@example.com.")})}))
}

func Page_Static_ViewTerms(model any) any {
	return Ui_Layout_Page(model, sky_call(sky_call(sky_htmlEl("div"), []any{tw([]any{maxW3xl, mxAuto, py8})}), []any{sky_call(sky_call(sky_htmlEl("h1"), []any{tw([]any{text3xl, fontBold, mb6})}), []any{sky_htmlText("Terms & Conditions")}), sky_call(sky_call(sky_htmlEl("div"), []any{tw([]any{textGray600, leadingRelaxed})}), []any{Page_Static_Section_("1. General", "By using SkyShop, you agree to these terms and conditions. We reserve the right to modify these terms at any time."), Page_Static_Section_("2. Products", "All products are subject to availability. We make every effort to display accurate product descriptions and images. Prices are listed in the currency shown and include applicable taxes."), Page_Static_Section_("3. Orders", "Once an order is placed and payment is confirmed, it cannot be cancelled. We will process and ship your order as soon as possible."), Page_Static_Section_("4. Shipping", "Shipping is available to selected countries. Delivery times vary by location. We are not responsible for customs duties or import taxes."), Page_Static_Section_("5. Returns & Refunds", "Items may be returned within 14 days of receipt in their original condition. Refunds will be processed to the original payment method within 5-10 business days."), Page_Static_Section_("6. Limitation of Liability", "SkyShop is not liable for any indirect, incidental, or consequential damages arising from the use of our services or products."), Page_Static_Section_("7. Governing Law", "These terms are governed by the laws of the United Kingdom.")})}))
}

func Page_Static_Section_(title any, body any) any {
	return sky_call(sky_call(sky_htmlEl("div"), []any{tw([]any{mb6})}), []any{sky_call(sky_call(sky_htmlEl("h2"), []any{tw([]any{textLg, fontSemibold, mb2})}), []any{sky_htmlText(title)}), sky_call(sky_call(sky_htmlEl("p"), []any{}), []any{sky_htmlText(body)})})
}

func Page_Static_ViewNotFound(model any) any {
	return Ui_Layout_Page(model, sky_call(sky_call(sky_htmlEl("div"), []any{tw([]any{textCenter, py16})}), []any{sky_call(sky_call(sky_htmlEl("h1"), []any{tw([]any{text6xl, fontBold, textGray300, mb4})}), []any{sky_htmlText("404")}), sky_call(sky_call(sky_htmlEl("p"), []any{tw([]any{textLg, textGray500, mb6})}), []any{sky_htmlText("Page not found")}), sky_call(sky_call(sky_htmlEl("a"), []any{sky_call(sky_attrSimple("href"), "/"), sky_call(sky_attrCustom("sky-nav"), ""), tw([]any{bgBlue600, textWhite, px6, py3, roundedLg, fontSemibold, inlineBlock})}), []any{sky_htmlText("Go Home")})}))
}