func Page_Home_ViewHome(model any) any {
	return Ui_Layout_Page(model, sky_call(sky_call(sky_htmlEl("div"), []any{}), []any{Page_Home_ViewHero(model), Page_Home_ViewCategoryBar(model), Page_Home_ViewFeaturedProducts(model)}))
}

func Page_Home_ViewHero(model any) any {
	return func() any { lang := sky_asMap(model)["lang"]; _ = lang; return sky_call(sky_call(sky_htmlEl("div"), []any{tw([]any{bgGray900, textWhite, roundedXl, p6, md(p12), mb10, textCenter}), sky_call(sky_attrSimple("style"), "background:linear-gradient(135deg,#0f172a 0%,#1e293b 50%,#334155 100%)")}), []any{sky_call(sky_call(sky_htmlEl("p"), []any{tw([]any{textSm, uppercase, fontBold, textBlue400, mb3}), sky_call(sky_attrSimple("style"), "letter-spacing:.1em")}), []any{sky_htmlText(Lib_Translation_T(lang, "hero.badge"))}), sky_call(sky_call(sky_htmlEl("h1"), []any{tw([]any{text3xl, md(text5xl), fontBold, textWhite, mb4}), sky_call(sky_attrSimple("style"), "line-height:1.1;letter-spacing:-.025em")}), []any{sky_htmlText(Lib_Translation_T(lang, "app.name"))}), sky_call(sky_call(sky_htmlEl("p"), []any{tw([]any{textBase, md(textLg), textGray400, mb8, mxAuto}), sky_call(sky_attrSimple("style"), "max-width:480px")}), []any{sky_htmlText(Lib_Translation_T(lang, "hero.subtitle"))}), sky_call(sky_call(sky_htmlEl("div"), []any{tw([]any{flex, justifyCenter, gap3})}), []any{sky_call(sky_call(sky_htmlEl("a"), []any{sky_call(sky_attrSimple("href"), "/products"), sky_call(sky_attrCustom("sky-nav"), ""), tw([]any{inlineFlex, itemsCenter, gap2, bgWhite, textGray900, px6, py3, roundedMd, fontSemibold, textSm, hover(bgGray100)})}), []any{sky_htmlText(Lib_Translation_T(lang, "hero.cta"))})})}) }()
}

func Page_Home_ViewCategoryBar(model any) any {
	return sky_call(sky_call(sky_htmlEl("div"), []any{tw([]any{mb8, flex, flexWrap, gap2, justifyCenter})}), sky_call(sky_listMap(func(cat any) any { return sky_call(sky_call(sky_htmlEl("a"), []any{sky_call(sky_attrSimple("href"), "/products"), sky_call(sky_attrCustom("sky-nav"), ""), sky_call(sky_evtHandler("click"), SetCategoryFilter(cat)), tw([]any{inlineBlock, px4, py2, roundedFull, textSm, fontMedium, textGray500, bgGray100, hover(bgGray200), hover(textGray900)})}), []any{sky_htmlText(Lib_Translation_TCategory(sky_asMap(model)["lang"], cat))}) }), sky_call(sky_listTake(6), allCategories)))
}

func Page_Home_ViewFeaturedProducts(model any) any {
	return func() any { featured := sky_call(sky_listTake(8), sky_asMap(model)["products"]); _ = featured; return sky_call(sky_call(sky_htmlEl("div"), []any{}), []any{sky_call(sky_call(sky_htmlEl("div"), []any{tw([]any{flex, justifyBetween, itemsCenter, mb6})}), []any{sky_call(sky_call(sky_htmlEl("h2"), []any{tw([]any{text2xl, fontBold, textGray900})}), []any{sky_htmlText(Lib_Translation_T(sky_asMap(model)["lang"], "home.featured"))}), sky_call(sky_call(sky_htmlEl("a"), []any{sky_call(sky_attrSimple("href"), "/products"), sky_call(sky_attrCustom("sky-nav"), ""), tw([]any{textSm, fontSemibold, textBlue600})}), []any{sky_htmlText(Lib_Translation_T(sky_asMap(model)["lang"], "home.viewAll"))})}), Page_Home_ViewProductGrid(model, featured)}) }()
}

func Page_Home_ViewProducts(model any) any {
	return Ui_Layout_Page(model, sky_call(sky_call(sky_htmlEl("div"), []any{}), []any{sky_call(sky_call(sky_htmlEl("div"), []any{tw([]any{mb8})}), []any{sky_call(sky_call(sky_htmlEl("h1"), []any{tw([]any{text3xl, fontBold, textGray900})}), []any{sky_htmlText(Lib_Translation_T(sky_asMap(model)["lang"], "nav.products"))}), sky_call(sky_call(sky_htmlEl("p"), []any{tw([]any{textGray500, mt1})}), []any{sky_htmlText(Lib_Translation_T(sky_asMap(model)["lang"], "hero.browse"))})}), Page_Home_ViewToolbar(model), Page_Home_ViewProductGrid(model, sky_asMap(model)["products"])}))
}

func Page_Home_ViewToolbar(model any) any {
	return func() any { lang := sky_asMap(model)["lang"]; _ = lang; return sky_call(sky_call(sky_htmlEl("div"), []any{tw([]any{mb8, flex, flexCol, gap4})}), []any{sky_call(sky_htmlVoid("input"), []any{sky_call(sky_attrSimple("type"), "text"), sky_call(sky_attrSimple("placeholder"), Lib_Translation_T(lang, "product.search")), sky_call(sky_attrSimple("value"), sky_asMap(model)["search"]), sky_call(sky_evtHandler("input"), SetSearch), Ui_Layout_FormInput()}), sky_call(sky_call(sky_htmlEl("div"), []any{tw([]any{flex, flexWrap, gap2})}), sky_concat([]any{Page_Home_FilterBtn("all", Lib_Translation_T(lang, "product.all"), sky_asMap(model)["categoryFilter"])}, sky_call(sky_listMap(func(cat any) any { return Page_Home_FilterBtn(cat, Lib_Translation_TCategory(lang, cat), sky_asMap(model)["categoryFilter"]) }), allCategories))), sky_call(sky_call(sky_htmlEl("div"), []any{tw([]any{flex, gap2, itemsCenter})}), []any{sky_call(sky_call(sky_htmlEl("span"), []any{tw([]any{textSm, textGray500, mr2})}), []any{sky_htmlText(Lib_Translation_T(lang, "product.sortBy"))}), Page_Home_SortBtn("newest", Lib_Translation_T(lang, "product.sort.newest"), sky_asMap(model)["sortBy"]), Page_Home_SortBtn("price", Lib_Translation_T(lang, "product.sort.price"), sky_asMap(model)["sortBy"]), Page_Home_SortBtn("title", Lib_Translation_T(lang, "product.sort.title"), sky_asMap(model)["sortBy"]), sky_call(sky_call(sky_htmlEl("button"), []any{sky_call(sky_evtHandler("click"), ToggleSortDir), Ui_Layout_QtyBtn()}), []any{sky_htmlText(func() any { if sky_asBool(sky_equal(sky_asMap(model)["sortDir"], "asc")) { return "↑" }; return "↓" }())})})}) }()
}

func Page_Home_FilterBtn(filterValue any, label any, activeFilter any) any {
	return sky_call(sky_call(sky_htmlEl("button"), []any{sky_call(sky_evtHandler("click"), SetCategoryFilter(filterValue)), func() any { if sky_asBool(sky_equal(activeFilter, filterValue)) { return tw([]any{textSm, px4, py1, roundedFull, fontSemibold, bgBlue600, textWhite, border, borderBlue600}) }; return tw([]any{textSm, px4, py1, roundedFull, fontMedium, bgWhite, textGray500, border, borderGray200, hover(borderGray400)}) }()}), []any{sky_htmlText(label)})
}

func Page_Home_SortBtn(sortValue any, label any, activeSort any) any {
	return sky_call(sky_call(sky_htmlEl("button"), []any{sky_call(sky_evtHandler("click"), SetSortBy(sortValue)), func() any { if sky_asBool(sky_equal(activeSort, sortValue)) { return tw([]any{textSm, px3, py1, roundedMd, fontSemibold, bgGray900, textWhite, border, borderGray900}) }; return tw([]any{textSm, px3, py1, roundedMd, fontMedium, bgWhite, textGray500, border, borderGray200, hover(borderGray400)}) }()}), []any{sky_htmlText(label)})
}

func Page_Home_ViewProductGrid(model any, products any) any {
	return func() any { if sky_asBool(sky_listIsEmpty(products)) { return sky_call(sky_call(sky_htmlEl("div"), []any{tw([]any{textCenter, py16})}), []any{sky_call(sky_call(sky_htmlEl("div"), []any{Ui_Layout_EmptyIcon()}), []any{sky_htmlText("~")}), sky_call(sky_call(sky_htmlEl("p"), []any{tw([]any{textGray500})}), []any{sky_htmlText(Lib_Translation_T(sky_asMap(model)["lang"], "product.noResults"))})}) }; return sky_call(sky_call(sky_htmlEl("div"), []any{tw([]any{grid, gap6}), sky_call(sky_attrSimple("style"), "grid-template-columns:repeat(auto-fill,minmax(260px,1fr))")}), sky_call(sky_listMap(func(__pa0 any) any { return Page_Home_ViewProductCard(model, __pa0) }), products)) }()
}

func Page_Home_ViewProductCard(model any, product any) any {
	return func() any { productId := Lib_Db_GetField("id", product); _ = productId; title := Lib_Db_GetField("title", product); _ = title; category := Lib_Db_GetField("category", product); _ = category; pricing := Lib_Money_FormatPriceFromRow(product); _ = pricing; stock := Lib_Db_GetInt("stock", product); _ = stock; images := Lib_Products_ListProductImages(productId); _ = images; firstImage := func() any { return func() any { __subject := sky_listHead(images); if sky_asSkyMaybe(__subject).SkyName == "Just" { img := sky_asSkyMaybe(__subject).JustValue; _ = img; return Lib_Db_GetField("data", img) };  if sky_asSkyMaybe(__subject).SkyName == "Nothing" { return "" };  return nil }() }(); _ = firstImage; return sky_call(sky_call(sky_htmlEl("a"), []any{sky_call(sky_attrSimple("href"), sky_concat("/product/", productId)), sky_call(sky_attrCustom("sky-nav"), ""), tw([]any{bgWhite, roundedLg, overflowHidden, border, borderGray200, block, group}), sky_call(sky_attrSimple("class"), "product-card")}), []any{sky_call(sky_call(sky_htmlEl("div"), []any{sky_call(sky_attrSimple("style"), "aspect-ratio:4/3;overflow:hidden")}), []any{func() any { if sky_asBool(!sky_equal(firstImage, "")) { return sky_call(sky_htmlVoid("img"), []any{sky_call(sky_attrSimple("src"), firstImage), sky_call(sky_attrSimple("alt"), title), Ui_Layout_ObjectCover_()}) }; return sky_call(sky_call(sky_htmlEl("div"), []any{Ui_Layout_ImgPlaceholder(), sky_call(sky_attrSimple("style"), "aspect-ratio:4/3")}), []any{sky_htmlText("No image")}) }()}), sky_call(sky_call(sky_htmlEl("div"), []any{tw([]any{p4})}), []any{sky_call(sky_call(sky_htmlEl("div"), []any{tw([]any{flex, justifyBetween, itemsCenter, mb2})}), []any{sky_call(sky_call(sky_htmlEl("span"), []any{tw([]any{textXs, fontSemibold, uppercase, textBlue500}), sky_call(sky_attrSimple("style"), "letter-spacing:.1em")}), []any{sky_htmlText(Lib_Translation_TCategory(sky_asMap(model)["lang"], category))}), Page_Home_ViewStockDot(stock)}), sky_call(sky_call(sky_htmlEl("h3"), []any{tw([]any{fontSemibold, textGray900, mb2})}), []any{sky_htmlText(title)}), Page_Home_ViewPrice(pricing)})}) }()
}

func Page_Home_ViewPrice(pricing any) any {
	return func() any { if sky_asBool(sky_asMap(pricing)["hasDiscount"]) { return sky_call(sky_call(sky_htmlEl("div"), []any{tw([]any{flex, gap2, itemsCenter})}), []any{sky_call(sky_call(sky_htmlEl("span"), []any{tw([]any{fontBold, textLg, textRed600})}), []any{sky_htmlText(sky_asMap(pricing)["discounted"])}), sky_call(sky_call(sky_htmlEl("span"), []any{tw([]any{textSm, textGray400}), sky_call(sky_attrSimple("class"), "line-through")}), []any{sky_htmlText(sky_asMap(pricing)["original"])})}) }; return sky_call(sky_call(sky_htmlEl("div"), []any{}), []any{sky_call(sky_call(sky_htmlEl("span"), []any{tw([]any{fontBold, textLg, textGray900})}), []any{sky_htmlText(sky_asMap(pricing)["original"])})}) }()
}

func Page_Home_ViewStockDot(stock any) any {
	return func() any { if sky_asBool(sky_equal(stock, 0)) { return sky_call(sky_call(sky_htmlEl("span"), []any{tw([]any{w2, Ui_Layout_H2_(), roundedFull, bgRed500, inlineBlock})}), []any{}) }; return sky_call(sky_call(sky_htmlEl("span"), []any{tw([]any{w2, Ui_Layout_H2_(), roundedFull, bgGreen500, inlineBlock})}), []any{}) }()
}