// Code generated by sky-ffi-inspect from net/http. DO NOT EDIT.
// Re-run `sky add net/http` to regenerate.
//
// Wrapper functions are in `package rt` with names <Kernel>_<lowerFn>.
// Sky source resolves `import Net.Http as X` and calls `X.<lowerFn>` — the canonicaliser routes it via
// the FFI registry to these typed Go functions. Every wrapper wraps
// panics in Err[any, any] via SkyFfiRecover.

package rt

import (
	pkg "net/http"
	"fmt"
	bufio "bufio"
	context "context"
	io "io"
	fs "io/fs"
	_ "mime/multipart"  // aliased multipart; unused in emitted wrappers
	net "net"
	url "net/url"
	time "time"
)

// [pure] Go_Http.allowQuerySemicolons → pkg.AllowQuerySemicolons
func Go_Http_allowQuerySemicolons(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](pkg.AllowQuerySemicolons(p0.(pkg.Handler)))
	return
}

// [pure] Go_Http.canonicalHeaderKey → pkg.CanonicalHeaderKey
func Go_Http_canonicalHeaderKey(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](pkg.CanonicalHeaderKey(fmt.Sprintf("%v", p0)))
	return
}

// [fallible] Go_Http.clientGet → pkg.ClientGet
func Go_Http_clientGet(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	r0, err := p0.(*pkg.Client).Get(fmt.Sprintf("%v", p1))
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](r0)

	return
}

// [fallible] Go_Http.clientDo → pkg.ClientDo
func Go_Http_clientDo(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	r0, err := p0.(*pkg.Client).Do(p1.(*pkg.Request))
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](r0)

	return
}

// [fallible] Go_Http.clientPost → pkg.ClientPost
func Go_Http_clientPost(p0 any, p1 any, p2 any, p3 any) (out any) {
	defer SkyFfiRecover(&out)()
	r0, err := p0.(*pkg.Client).Post(fmt.Sprintf("%v", p1), fmt.Sprintf("%v", p2), p3.(io.Reader))
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](r0)

	return
}

// [fallible] Go_Http.clientPostForm → pkg.ClientPostForm
func Go_Http_clientPostForm(p0 any, p1 any, p2 any) (out any) {
	defer SkyFfiRecover(&out)()
	r0, err := p0.(*pkg.Client).PostForm(fmt.Sprintf("%v", p1), p2.(url.Values))
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](r0)

	return
}

// [fallible] Go_Http.clientHead → pkg.ClientHead
func Go_Http_clientHead(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	r0, err := p0.(*pkg.Client).Head(fmt.Sprintf("%v", p1))
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](r0)

	return
}

// [pure] Go_Http.clientCloseIdleConnections → pkg.ClientCloseIdleConnections
func Go_Http_clientCloseIdleConnections(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	p0.(*pkg.Client).CloseIdleConnections()
	out = Ok[any, any](struct{}{})
	return
}

// [fallible] Go_Http.clientConnClose → pkg.ClientConnClose
func Go_Http_clientConnClose(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	err := p0.(*pkg.ClientConn).Close()
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](struct{}{})

	return
}

// [fallible] Go_Http.clientConnErr → pkg.ClientConnErr
func Go_Http_clientConnErr(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	err := p0.(*pkg.ClientConn).Err()
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](struct{}{})

	return
}

// [fallible] Go_Http.clientConnRoundTrip → pkg.ClientConnRoundTrip
func Go_Http_clientConnRoundTrip(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	r0, err := p0.(*pkg.ClientConn).RoundTrip(p1.(*pkg.Request))
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](r0)

	return
}

// [pure] Go_Http.clientConnAvailable → pkg.ClientConnAvailable
func Go_Http_clientConnAvailable(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(*pkg.ClientConn).Available())
	return
}

// [pure] Go_Http.clientConnInFlight → pkg.ClientConnInFlight
func Go_Http_clientConnInFlight(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(*pkg.ClientConn).InFlight())
	return
}

// [fallible] Go_Http.clientConnReserve → pkg.ClientConnReserve
func Go_Http_clientConnReserve(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	err := p0.(*pkg.ClientConn).Reserve()
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](struct{}{})

	return
}

// [pure] Go_Http.clientConnRelease → pkg.ClientConnRelease
func Go_Http_clientConnRelease(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	p0.(*pkg.ClientConn).Release()
	out = Ok[any, any](struct{}{})
	return
}

// [pure] Go_Http.clientConnSetStateHook → pkg.ClientConnSetStateHook
func Go_Http_clientConnSetStateHook(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	p0.(*pkg.ClientConn).SetStateHook(p1.(func(*pkg.ClientConn)))
	out = Ok[any, any](struct{}{})
	return
}

// [pure] Go_Http.connStateString → pkg.ConnStateString
func Go_Http_connStateString(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(pkg.ConnState).String())
	return
}

// [pure] Go_Http.cookieString → pkg.CookieString
func Go_Http_cookieString(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(*pkg.Cookie).String())
	return
}

// [fallible] Go_Http.cookieValid → pkg.CookieValid
func Go_Http_cookieValid(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	err := p0.(*pkg.Cookie).Valid()
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](struct{}{})

	return
}

// [fallible] Go_Http.crossOriginProtectionAddTrustedOrigin → pkg.CrossOriginProtectionAddTrustedOrigin
func Go_Http_crossOriginProtectionAddTrustedOrigin(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	err := p0.(*pkg.CrossOriginProtection).AddTrustedOrigin(fmt.Sprintf("%v", p1))
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](struct{}{})

	return
}

// [pure] Go_Http.crossOriginProtectionAddInsecureBypassPattern → pkg.CrossOriginProtectionAddInsecureBypassPattern
func Go_Http_crossOriginProtectionAddInsecureBypassPattern(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	p0.(*pkg.CrossOriginProtection).AddInsecureBypassPattern(fmt.Sprintf("%v", p1))
	out = Ok[any, any](struct{}{})
	return
}

// [pure] Go_Http.crossOriginProtectionSetDenyHandler → pkg.CrossOriginProtectionSetDenyHandler
func Go_Http_crossOriginProtectionSetDenyHandler(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	p0.(*pkg.CrossOriginProtection).SetDenyHandler(p1.(pkg.Handler))
	out = Ok[any, any](struct{}{})
	return
}

// [fallible] Go_Http.crossOriginProtectionCheck → pkg.CrossOriginProtectionCheck
func Go_Http_crossOriginProtectionCheck(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	err := p0.(*pkg.CrossOriginProtection).Check(p1.(*pkg.Request))
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](struct{}{})

	return
}

// [pure] Go_Http.crossOriginProtectionHandler → pkg.CrossOriginProtectionHandler
func Go_Http_crossOriginProtectionHandler(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(*pkg.CrossOriginProtection).Handler(p1.(pkg.Handler)))
	return
}

// [pure] Go_Http.detectContentType → pkg.DetectContentType
func Go_Http_detectContentType(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](pkg.DetectContentType(SkyFfiArg_bytes(p0)))
	return
}

// [fallible] Go_Http.dirOpen → pkg.DirOpen
func Go_Http_dirOpen(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	r0, err := p0.(pkg.Dir).Open(fmt.Sprintf("%v", p1))
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](r0)

	return
}

// [pure] Go_Http.error → pkg.Error
func Go_Http_error(p0 any, p1 any, p2 any) (out any) {
	defer SkyFfiRecover(&out)()
	pkg.Error(p0.(pkg.ResponseWriter), fmt.Sprintf("%v", p1), AsInt(p2))
	out = Ok[any, any](struct{}{})
	return
}

// [pure] Go_Http.fS → pkg.FS
func Go_Http_fS(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](pkg.FS(p0.(fs.FS)))
	return
}

// [pure] Go_Http.fileServer → pkg.FileServer
func Go_Http_fileServer(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](pkg.FileServer(p0.(pkg.FileSystem)))
	return
}

// [pure] Go_Http.fileServerFS → pkg.FileServerFS
func Go_Http_fileServerFS(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](pkg.FileServerFS(p0.(fs.FS)))
	return
}

// [fallible] Go_Http.get → pkg.Get
func Go_Http_get(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	r0, err := pkg.Get(fmt.Sprintf("%v", p0))
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](r0)

	return
}

// [pure] Go_Http.handle → pkg.Handle
func Go_Http_handle(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	pkg.Handle(fmt.Sprintf("%v", p0), p1.(pkg.Handler))
	out = Ok[any, any](struct{}{})
	return
}

// [pure] Go_Http.handleFunc → pkg.HandleFunc
func Go_Http_handleFunc(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	pkg.HandleFunc(fmt.Sprintf("%v", p0), p1.(func(pkg.ResponseWriter, *pkg.Request)))
	out = Ok[any, any](struct{}{})
	return
}

// [pure] Go_Http.handlerFuncServeHTTP → pkg.HandlerFuncServeHTTP
func Go_Http_handlerFuncServeHTTP(p0 any, p1 any, p2 any) (out any) {
	defer SkyFfiRecover(&out)()
	p0.(pkg.HandlerFunc).ServeHTTP(p1.(pkg.ResponseWriter), p2.(*pkg.Request))
	out = Ok[any, any](struct{}{})
	return
}

// [fallible] Go_Http.head → pkg.Head
func Go_Http_head(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	r0, err := pkg.Head(fmt.Sprintf("%v", p0))
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](r0)

	return
}

// [pure] Go_Http.headerAdd → pkg.HeaderAdd
func Go_Http_headerAdd(p0 any, p1 any, p2 any) (out any) {
	defer SkyFfiRecover(&out)()
	p0.(pkg.Header).Add(fmt.Sprintf("%v", p1), fmt.Sprintf("%v", p2))
	out = Ok[any, any](struct{}{})
	return
}

// [pure] Go_Http.headerSet → pkg.HeaderSet
func Go_Http_headerSet(p0 any, p1 any, p2 any) (out any) {
	defer SkyFfiRecover(&out)()
	p0.(pkg.Header).Set(fmt.Sprintf("%v", p1), fmt.Sprintf("%v", p2))
	out = Ok[any, any](struct{}{})
	return
}

// [pure] Go_Http.headerGet → pkg.HeaderGet
func Go_Http_headerGet(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(pkg.Header).Get(fmt.Sprintf("%v", p1)))
	return
}

// [pure] Go_Http.headerValues → pkg.HeaderValues
func Go_Http_headerValues(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(pkg.Header).Values(fmt.Sprintf("%v", p1)))
	return
}

// [pure] Go_Http.headerDel → pkg.HeaderDel
func Go_Http_headerDel(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	p0.(pkg.Header).Del(fmt.Sprintf("%v", p1))
	out = Ok[any, any](struct{}{})
	return
}

// [fallible] Go_Http.headerWrite → pkg.HeaderWrite
func Go_Http_headerWrite(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	err := p0.(pkg.Header).Write(p1.(io.Writer))
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](struct{}{})

	return
}

// [pure] Go_Http.headerClone → pkg.HeaderClone
func Go_Http_headerClone(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(pkg.Header).Clone())
	return
}

// [fallible] Go_Http.headerWriteSubset → pkg.HeaderWriteSubset
func Go_Http_headerWriteSubset(p0 any, p1 any, p2 any) (out any) {
	defer SkyFfiRecover(&out)()
	err := p0.(pkg.Header).WriteSubset(p1.(io.Writer), p2.(map[string]bool))
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](struct{}{})

	return
}

// [fallible] Go_Http.listenAndServe → pkg.ListenAndServe
func Go_Http_listenAndServe(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	err := pkg.ListenAndServe(fmt.Sprintf("%v", p0), p1.(pkg.Handler))
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](struct{}{})

	return
}

// [fallible] Go_Http.listenAndServeTLS → pkg.ListenAndServeTLS
func Go_Http_listenAndServeTLS(p0 any, p1 any, p2 any, p3 any) (out any) {
	defer SkyFfiRecover(&out)()
	err := pkg.ListenAndServeTLS(fmt.Sprintf("%v", p0), fmt.Sprintf("%v", p1), fmt.Sprintf("%v", p2), p3.(pkg.Handler))
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](struct{}{})

	return
}

// [pure] Go_Http.maxBytesErrorError → pkg.MaxBytesErrorError
func Go_Http_maxBytesErrorError(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(*pkg.MaxBytesError).Error())
	return
}

// [pure] Go_Http.maxBytesHandler → pkg.MaxBytesHandler
func Go_Http_maxBytesHandler(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](pkg.MaxBytesHandler(p0.(pkg.Handler), int64(AsInt(p1))))
	return
}

// [pure] Go_Http.maxBytesReader → pkg.MaxBytesReader
func Go_Http_maxBytesReader(p0 any, p1 any, p2 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](pkg.MaxBytesReader(p0.(pkg.ResponseWriter), p1.(io.ReadCloser), int64(AsInt(p2))))
	return
}

// [pure] Go_Http.newCrossOriginProtection → pkg.NewCrossOriginProtection
func Go_Http_newCrossOriginProtection(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	_ = p0
	out = Ok[any, any](pkg.NewCrossOriginProtection())
	return
}

// [pure] Go_Http.newFileTransport → pkg.NewFileTransport
func Go_Http_newFileTransport(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](pkg.NewFileTransport(p0.(pkg.FileSystem)))
	return
}

// [pure] Go_Http.newFileTransportFS → pkg.NewFileTransportFS
func Go_Http_newFileTransportFS(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](pkg.NewFileTransportFS(p0.(fs.FS)))
	return
}

// [fallible] Go_Http.newRequest → pkg.NewRequest
func Go_Http_newRequest(p0 any, p1 any, p2 any) (out any) {
	defer SkyFfiRecover(&out)()
	r0, err := pkg.NewRequest(fmt.Sprintf("%v", p0), fmt.Sprintf("%v", p1), p2.(io.Reader))
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](r0)

	return
}

// [fallible] Go_Http.newRequestWithContext → pkg.NewRequestWithContext
func Go_Http_newRequestWithContext(p0 any, p1 any, p2 any, p3 any) (out any) {
	defer SkyFfiRecover(&out)()
	r0, err := pkg.NewRequestWithContext(p0.(context.Context), fmt.Sprintf("%v", p1), fmt.Sprintf("%v", p2), p3.(io.Reader))
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](r0)

	return
}

// [pure] Go_Http.newResponseController → pkg.NewResponseController
func Go_Http_newResponseController(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](pkg.NewResponseController(p0.(pkg.ResponseWriter)))
	return
}

// [pure] Go_Http.newServeMux → pkg.NewServeMux
func Go_Http_newServeMux(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	_ = p0
	out = Ok[any, any](pkg.NewServeMux())
	return
}

// [pure] Go_Http.notFound → pkg.NotFound
func Go_Http_notFound(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	pkg.NotFound(p0.(pkg.ResponseWriter), p1.(*pkg.Request))
	out = Ok[any, any](struct{}{})
	return
}

// [pure] Go_Http.notFoundHandler → pkg.NotFoundHandler
func Go_Http_notFoundHandler(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	_ = p0
	out = Ok[any, any](pkg.NotFoundHandler())
	return
}

// [fallible] Go_Http.parseCookie → pkg.ParseCookie
func Go_Http_parseCookie(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	r0, err := pkg.ParseCookie(fmt.Sprintf("%v", p0))
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](r0)

	return
}

// [pure] Go_Http.parseHTTPVersion → pkg.ParseHTTPVersion
func Go_Http_parseHTTPVersion(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	r0, r1, r2 := pkg.ParseHTTPVersion(fmt.Sprintf("%v", p0))
	out = Ok[any, any]([]any{r0, r1, r2})

	return
}

// [fallible] Go_Http.parseSetCookie → pkg.ParseSetCookie
func Go_Http_parseSetCookie(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	r0, err := pkg.ParseSetCookie(fmt.Sprintf("%v", p0))
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](r0)

	return
}

// [fallible] Go_Http.parseTime → pkg.ParseTime
func Go_Http_parseTime(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	r0, err := pkg.ParseTime(fmt.Sprintf("%v", p0))
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](r0)

	return
}

// [fallible] Go_Http.post → pkg.Post
func Go_Http_post(p0 any, p1 any, p2 any) (out any) {
	defer SkyFfiRecover(&out)()
	r0, err := pkg.Post(fmt.Sprintf("%v", p0), fmt.Sprintf("%v", p1), p2.(io.Reader))
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](r0)

	return
}

// [fallible] Go_Http.postForm → pkg.PostForm
func Go_Http_postForm(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	r0, err := pkg.PostForm(fmt.Sprintf("%v", p0), p1.(url.Values))
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](r0)

	return
}

// [pure] Go_Http.protocolErrorError → pkg.ProtocolErrorError
func Go_Http_protocolErrorError(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(*pkg.ProtocolError).Error())
	return
}

// [pure] Go_Http.protocolErrorIs → pkg.ProtocolErrorIs
func Go_Http_protocolErrorIs(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(*pkg.ProtocolError).Is(p1.(error)))
	return
}

// [pure] Go_Http.protocolsHTTP1 → pkg.ProtocolsHTTP1
func Go_Http_protocolsHTTP1(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(pkg.Protocols).HTTP1())
	return
}

// [pure] Go_Http.protocolsSetHTTP1 → pkg.ProtocolsSetHTTP1
func Go_Http_protocolsSetHTTP1(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	p0.(*pkg.Protocols).SetHTTP1(AsBool(p1))
	out = Ok[any, any](struct{}{})
	return
}

// [pure] Go_Http.protocolsHTTP2 → pkg.ProtocolsHTTP2
func Go_Http_protocolsHTTP2(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(pkg.Protocols).HTTP2())
	return
}

// [pure] Go_Http.protocolsSetHTTP2 → pkg.ProtocolsSetHTTP2
func Go_Http_protocolsSetHTTP2(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	p0.(*pkg.Protocols).SetHTTP2(AsBool(p1))
	out = Ok[any, any](struct{}{})
	return
}

// [pure] Go_Http.protocolsUnencryptedHTTP2 → pkg.ProtocolsUnencryptedHTTP2
func Go_Http_protocolsUnencryptedHTTP2(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(pkg.Protocols).UnencryptedHTTP2())
	return
}

// [pure] Go_Http.protocolsSetUnencryptedHTTP2 → pkg.ProtocolsSetUnencryptedHTTP2
func Go_Http_protocolsSetUnencryptedHTTP2(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	p0.(*pkg.Protocols).SetUnencryptedHTTP2(AsBool(p1))
	out = Ok[any, any](struct{}{})
	return
}

// [pure] Go_Http.protocolsString → pkg.ProtocolsString
func Go_Http_protocolsString(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(pkg.Protocols).String())
	return
}

// [fallible] Go_Http.proxyFromEnvironment → pkg.ProxyFromEnvironment
func Go_Http_proxyFromEnvironment(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	r0, err := pkg.ProxyFromEnvironment(p0.(*pkg.Request))
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](r0)

	return
}

// [effectful] Go_Http.proxyURL → pkg.ProxyURL
func Go_Http_proxyURL(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](pkg.ProxyURL(p0.(*url.URL)))
	return
}

// [fallible] Go_Http.readRequest → pkg.ReadRequest
func Go_Http_readRequest(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	r0, err := pkg.ReadRequest(p0.(*bufio.Reader))
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](r0)

	return
}

// [fallible] Go_Http.readResponse → pkg.ReadResponse
func Go_Http_readResponse(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	r0, err := pkg.ReadResponse(p0.(*bufio.Reader), p1.(*pkg.Request))
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](r0)

	return
}

// [pure] Go_Http.redirect → pkg.Redirect
func Go_Http_redirect(p0 any, p1 any, p2 any, p3 any) (out any) {
	defer SkyFfiRecover(&out)()
	pkg.Redirect(p0.(pkg.ResponseWriter), p1.(*pkg.Request), fmt.Sprintf("%v", p2), AsInt(p3))
	out = Ok[any, any](struct{}{})
	return
}

// [pure] Go_Http.redirectHandler → pkg.RedirectHandler
func Go_Http_redirectHandler(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](pkg.RedirectHandler(fmt.Sprintf("%v", p0), AsInt(p1)))
	return
}

// [pure] Go_Http.requestContext → pkg.RequestContext
func Go_Http_requestContext(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(*pkg.Request).Context())
	return
}

// [pure] Go_Http.requestWithContext → pkg.RequestWithContext
func Go_Http_requestWithContext(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(*pkg.Request).WithContext(p1.(context.Context)))
	return
}

// [pure] Go_Http.requestClone → pkg.RequestClone
func Go_Http_requestClone(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(*pkg.Request).Clone(p1.(context.Context)))
	return
}

// [pure] Go_Http.requestProtoAtLeast → pkg.RequestProtoAtLeast
func Go_Http_requestProtoAtLeast(p0 any, p1 any, p2 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(*pkg.Request).ProtoAtLeast(AsInt(p1), AsInt(p2)))
	return
}

// [pure] Go_Http.requestUserAgent → pkg.RequestUserAgent
func Go_Http_requestUserAgent(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(*pkg.Request).UserAgent())
	return
}

// [pure] Go_Http.requestCookies → pkg.RequestCookies
func Go_Http_requestCookies(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(*pkg.Request).Cookies())
	return
}

// [pure] Go_Http.requestCookiesNamed → pkg.RequestCookiesNamed
func Go_Http_requestCookiesNamed(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(*pkg.Request).CookiesNamed(fmt.Sprintf("%v", p1)))
	return
}

// [fallible] Go_Http.requestCookie → pkg.RequestCookie
func Go_Http_requestCookie(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	r0, err := p0.(*pkg.Request).Cookie(fmt.Sprintf("%v", p1))
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](r0)

	return
}

// [pure] Go_Http.requestAddCookie → pkg.RequestAddCookie
func Go_Http_requestAddCookie(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	p0.(*pkg.Request).AddCookie(p1.(*pkg.Cookie))
	out = Ok[any, any](struct{}{})
	return
}

// [pure] Go_Http.requestReferer → pkg.RequestReferer
func Go_Http_requestReferer(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(*pkg.Request).Referer())
	return
}

// [fallible] Go_Http.requestMultipartReader → pkg.RequestMultipartReader
func Go_Http_requestMultipartReader(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	r0, err := p0.(*pkg.Request).MultipartReader()
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](r0)

	return
}

// [fallible] Go_Http.requestWrite → pkg.RequestWrite
func Go_Http_requestWrite(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	err := p0.(*pkg.Request).Write(p1.(io.Writer))
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](struct{}{})

	return
}

// [fallible] Go_Http.requestWriteProxy → pkg.RequestWriteProxy
func Go_Http_requestWriteProxy(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	err := p0.(*pkg.Request).WriteProxy(p1.(io.Writer))
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](struct{}{})

	return
}

// [pure] Go_Http.requestBasicAuth → pkg.RequestBasicAuth
func Go_Http_requestBasicAuth(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	r0, r1, r2 := p0.(*pkg.Request).BasicAuth()
	out = Ok[any, any]([]any{r0, r1, r2})

	return
}

// [pure] Go_Http.requestSetBasicAuth → pkg.RequestSetBasicAuth
func Go_Http_requestSetBasicAuth(p0 any, p1 any, p2 any) (out any) {
	defer SkyFfiRecover(&out)()
	p0.(*pkg.Request).SetBasicAuth(fmt.Sprintf("%v", p1), fmt.Sprintf("%v", p2))
	out = Ok[any, any](struct{}{})
	return
}

// [fallible] Go_Http.requestParseForm → pkg.RequestParseForm
func Go_Http_requestParseForm(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	err := p0.(*pkg.Request).ParseForm()
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](struct{}{})

	return
}

// [fallible] Go_Http.requestParseMultipartForm → pkg.RequestParseMultipartForm
func Go_Http_requestParseMultipartForm(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	err := p0.(*pkg.Request).ParseMultipartForm(int64(AsInt(p1)))
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](struct{}{})

	return
}

// [pure] Go_Http.requestFormValue → pkg.RequestFormValue
func Go_Http_requestFormValue(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(*pkg.Request).FormValue(fmt.Sprintf("%v", p1)))
	return
}

// [pure] Go_Http.requestPostFormValue → pkg.RequestPostFormValue
func Go_Http_requestPostFormValue(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(*pkg.Request).PostFormValue(fmt.Sprintf("%v", p1)))
	return
}

// [fallible] Go_Http.requestFormFile → pkg.RequestFormFile
func Go_Http_requestFormFile(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	r0, r1, err := p0.(*pkg.Request).FormFile(fmt.Sprintf("%v", p1))
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any]([]any{r0, r1})

	return
}

// [pure] Go_Http.requestPathValue → pkg.RequestPathValue
func Go_Http_requestPathValue(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(*pkg.Request).PathValue(fmt.Sprintf("%v", p1)))
	return
}

// [pure] Go_Http.requestSetPathValue → pkg.RequestSetPathValue
func Go_Http_requestSetPathValue(p0 any, p1 any, p2 any) (out any) {
	defer SkyFfiRecover(&out)()
	p0.(*pkg.Request).SetPathValue(fmt.Sprintf("%v", p1), fmt.Sprintf("%v", p2))
	out = Ok[any, any](struct{}{})
	return
}

// [pure] Go_Http.responseCookies → pkg.ResponseCookies
func Go_Http_responseCookies(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(*pkg.Response).Cookies())
	return
}

// [fallible] Go_Http.responseLocation → pkg.ResponseLocation
func Go_Http_responseLocation(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	r0, err := p0.(*pkg.Response).Location()
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](r0)

	return
}

// [pure] Go_Http.responseProtoAtLeast → pkg.ResponseProtoAtLeast
func Go_Http_responseProtoAtLeast(p0 any, p1 any, p2 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(*pkg.Response).ProtoAtLeast(AsInt(p1), AsInt(p2)))
	return
}

// [fallible] Go_Http.responseWrite → pkg.ResponseWrite
func Go_Http_responseWrite(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	err := p0.(*pkg.Response).Write(p1.(io.Writer))
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](struct{}{})

	return
}

// [fallible] Go_Http.responseControllerFlush → pkg.ResponseControllerFlush
func Go_Http_responseControllerFlush(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	err := p0.(*pkg.ResponseController).Flush()
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](struct{}{})

	return
}

// [fallible] Go_Http.responseControllerHijack → pkg.ResponseControllerHijack
func Go_Http_responseControllerHijack(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	r0, r1, err := p0.(*pkg.ResponseController).Hijack()
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any]([]any{r0, r1})

	return
}

// [fallible] Go_Http.responseControllerSetReadDeadline → pkg.ResponseControllerSetReadDeadline
func Go_Http_responseControllerSetReadDeadline(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	err := p0.(*pkg.ResponseController).SetReadDeadline(p1.(time.Time))
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](struct{}{})

	return
}

// [fallible] Go_Http.responseControllerSetWriteDeadline → pkg.ResponseControllerSetWriteDeadline
func Go_Http_responseControllerSetWriteDeadline(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	err := p0.(*pkg.ResponseController).SetWriteDeadline(p1.(time.Time))
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](struct{}{})

	return
}

// [fallible] Go_Http.responseControllerEnableFullDuplex → pkg.ResponseControllerEnableFullDuplex
func Go_Http_responseControllerEnableFullDuplex(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	err := p0.(*pkg.ResponseController).EnableFullDuplex()
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](struct{}{})

	return
}

// [fallible] Go_Http.serve → pkg.Serve
func Go_Http_serve(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	err := pkg.Serve(p0.(net.Listener), p1.(pkg.Handler))
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](struct{}{})

	return
}

// [pure] Go_Http.serveContent → pkg.ServeContent
func Go_Http_serveContent(p0 any, p1 any, p2 any, p3 any, p4 any) (out any) {
	defer SkyFfiRecover(&out)()
	pkg.ServeContent(p0.(pkg.ResponseWriter), p1.(*pkg.Request), fmt.Sprintf("%v", p2), p3.(time.Time), p4.(io.ReadSeeker))
	out = Ok[any, any](struct{}{})
	return
}

// [pure] Go_Http.serveFile → pkg.ServeFile
func Go_Http_serveFile(p0 any, p1 any, p2 any) (out any) {
	defer SkyFfiRecover(&out)()
	pkg.ServeFile(p0.(pkg.ResponseWriter), p1.(*pkg.Request), fmt.Sprintf("%v", p2))
	out = Ok[any, any](struct{}{})
	return
}

// [pure] Go_Http.serveFileFS → pkg.ServeFileFS
func Go_Http_serveFileFS(p0 any, p1 any, p2 any, p3 any) (out any) {
	defer SkyFfiRecover(&out)()
	pkg.ServeFileFS(p0.(pkg.ResponseWriter), p1.(*pkg.Request), p2.(fs.FS), fmt.Sprintf("%v", p3))
	out = Ok[any, any](struct{}{})
	return
}

// [pure] Go_Http.serveMuxHandler → pkg.ServeMuxHandler
func Go_Http_serveMuxHandler(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	r0, r1 := p0.(*pkg.ServeMux).Handler(p1.(*pkg.Request))
	out = Ok[any, any]([]any{r0, r1})

	return
}

// [pure] Go_Http.serveMuxServeHTTP → pkg.ServeMuxServeHTTP
func Go_Http_serveMuxServeHTTP(p0 any, p1 any, p2 any) (out any) {
	defer SkyFfiRecover(&out)()
	p0.(*pkg.ServeMux).ServeHTTP(p1.(pkg.ResponseWriter), p2.(*pkg.Request))
	out = Ok[any, any](struct{}{})
	return
}

// [pure] Go_Http.serveMuxHandle → pkg.ServeMuxHandle
func Go_Http_serveMuxHandle(p0 any, p1 any, p2 any) (out any) {
	defer SkyFfiRecover(&out)()
	p0.(*pkg.ServeMux).Handle(fmt.Sprintf("%v", p1), p2.(pkg.Handler))
	out = Ok[any, any](struct{}{})
	return
}

// [pure] Go_Http.serveMuxHandleFunc → pkg.ServeMuxHandleFunc
func Go_Http_serveMuxHandleFunc(p0 any, p1 any, p2 any) (out any) {
	defer SkyFfiRecover(&out)()
	p0.(*pkg.ServeMux).HandleFunc(fmt.Sprintf("%v", p1), p2.(func(pkg.ResponseWriter, *pkg.Request)))
	out = Ok[any, any](struct{}{})
	return
}

// [fallible] Go_Http.serveTLS → pkg.ServeTLS
func Go_Http_serveTLS(p0 any, p1 any, p2 any, p3 any) (out any) {
	defer SkyFfiRecover(&out)()
	err := pkg.ServeTLS(p0.(net.Listener), p1.(pkg.Handler), fmt.Sprintf("%v", p2), fmt.Sprintf("%v", p3))
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](struct{}{})

	return
}

// [fallible] Go_Http.serverClose → pkg.ServerClose
func Go_Http_serverClose(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	err := p0.(*pkg.Server).Close()
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](struct{}{})

	return
}

// [fallible] Go_Http.serverShutdown → pkg.ServerShutdown
func Go_Http_serverShutdown(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	err := p0.(*pkg.Server).Shutdown(p1.(context.Context))
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](struct{}{})

	return
}

// [pure] Go_Http.serverRegisterOnShutdown → pkg.ServerRegisterOnShutdown
func Go_Http_serverRegisterOnShutdown(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	p0.(*pkg.Server).RegisterOnShutdown(p1.(func()))
	out = Ok[any, any](struct{}{})
	return
}

// [fallible] Go_Http.serverListenAndServe → pkg.ServerListenAndServe
func Go_Http_serverListenAndServe(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	err := p0.(*pkg.Server).ListenAndServe()
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](struct{}{})

	return
}

// [fallible] Go_Http.serverServe → pkg.ServerServe
func Go_Http_serverServe(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	err := p0.(*pkg.Server).Serve(p1.(net.Listener))
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](struct{}{})

	return
}

// [fallible] Go_Http.serverServeTLS → pkg.ServerServeTLS
func Go_Http_serverServeTLS(p0 any, p1 any, p2 any, p3 any) (out any) {
	defer SkyFfiRecover(&out)()
	err := p0.(*pkg.Server).ServeTLS(p1.(net.Listener), fmt.Sprintf("%v", p2), fmt.Sprintf("%v", p3))
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](struct{}{})

	return
}

// [pure] Go_Http.serverSetKeepAlivesEnabled → pkg.ServerSetKeepAlivesEnabled
func Go_Http_serverSetKeepAlivesEnabled(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	p0.(*pkg.Server).SetKeepAlivesEnabled(AsBool(p1))
	out = Ok[any, any](struct{}{})
	return
}

// [fallible] Go_Http.serverListenAndServeTLS → pkg.ServerListenAndServeTLS
func Go_Http_serverListenAndServeTLS(p0 any, p1 any, p2 any) (out any) {
	defer SkyFfiRecover(&out)()
	err := p0.(*pkg.Server).ListenAndServeTLS(fmt.Sprintf("%v", p1), fmt.Sprintf("%v", p2))
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](struct{}{})

	return
}

// [pure] Go_Http.setCookie → pkg.SetCookie
func Go_Http_setCookie(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	pkg.SetCookie(p0.(pkg.ResponseWriter), p1.(*pkg.Cookie))
	out = Ok[any, any](struct{}{})
	return
}

// [pure] Go_Http.statusText → pkg.StatusText
func Go_Http_statusText(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](pkg.StatusText(AsInt(p0)))
	return
}

// [pure] Go_Http.stripPrefix → pkg.StripPrefix
func Go_Http_stripPrefix(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](pkg.StripPrefix(fmt.Sprintf("%v", p0), p1.(pkg.Handler)))
	return
}

// [pure] Go_Http.timeoutHandler → pkg.TimeoutHandler
func Go_Http_timeoutHandler(p0 any, p1 any, p2 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](pkg.TimeoutHandler(p0.(pkg.Handler), p1.(time.Duration), fmt.Sprintf("%v", p2)))
	return
}

// [fallible] Go_Http.transportNewClientConn → pkg.TransportNewClientConn
func Go_Http_transportNewClientConn(p0 any, p1 any, p2 any, p3 any) (out any) {
	defer SkyFfiRecover(&out)()
	r0, err := p0.(*pkg.Transport).NewClientConn(p1.(context.Context), fmt.Sprintf("%v", p2), fmt.Sprintf("%v", p3))
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](r0)

	return
}

// [fallible] Go_Http.transportRoundTrip → pkg.TransportRoundTrip
func Go_Http_transportRoundTrip(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	r0, err := p0.(*pkg.Transport).RoundTrip(p1.(*pkg.Request))
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](r0)

	return
}

// [pure] Go_Http.transportClone → pkg.TransportClone
func Go_Http_transportClone(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(*pkg.Transport).Clone())
	return
}

// [pure] Go_Http.transportRegisterProtocol → pkg.TransportRegisterProtocol
func Go_Http_transportRegisterProtocol(p0 any, p1 any, p2 any) (out any) {
	defer SkyFfiRecover(&out)()
	p0.(*pkg.Transport).RegisterProtocol(fmt.Sprintf("%v", p1), p2.(pkg.RoundTripper))
	out = Ok[any, any](struct{}{})
	return
}

// [pure] Go_Http.transportCloseIdleConnections → pkg.TransportCloseIdleConnections
func Go_Http_transportCloseIdleConnections(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	p0.(*pkg.Transport).CloseIdleConnections()
	out = Ok[any, any](struct{}{})
	return
}

// [pure] Go_Http.transportCancelRequest → pkg.TransportCancelRequest
func Go_Http_transportCancelRequest(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	p0.(*pkg.Transport).CancelRequest(p1.(*pkg.Request))
	out = Ok[any, any](struct{}{})
	return
}


// Pin fmt against "imported and not used" across partial files.
var _ = fmt.Sprintf
