// Code generated by sky-ffi-inspect from github.com/gorilla/mux. DO NOT EDIT.
// Re-run `sky add github.com/gorilla/mux` to regenerate.
//
// Wrapper functions are in `package rt` with names <Kernel>_<lowerFn>.
// Sky source resolves `import Github.Com.Gorilla.Mux as X` and calls `X.<lowerFn>` — the canonicaliser routes it via
// the FFI registry to these typed Go functions. Every wrapper wraps
// panics in Err[any, any] via SkyFfiRecover.

package rt

import (
	pkg "github.com/gorilla/mux"
	"fmt"
	http "net/http"
	_ "net/url"  // aliased url; unused in emitted wrappers
	"reflect"
)

// [pure] Go_Mux.cORSMethodMiddleware → pkg.CORSMethodMiddleware
func Go_Mux_cORSMethodMiddleware(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](pkg.CORSMethodMiddleware(p0.(*pkg.Router)))
	return
}
// [pure] typed wrapper for Go_Mux_cORSMethodMiddleware (P7 adaptor target)
func Go_Mux_cORSMethodMiddlewareT(p0 *pkg.Router) (out SkyResult[string, pkg.MiddlewareFunc]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[string, pkg.MiddlewareFunc](pkg.CORSMethodMiddleware(p0))
	return
}

// [pure] Go_Mux.currentRoute → pkg.CurrentRoute
func Go_Mux_currentRoute(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](pkg.CurrentRoute(p0.(*http.Request)))
	return
}
// [pure] typed wrapper for Go_Mux_currentRoute (P7 adaptor target)
func Go_Mux_currentRouteT(p0 *http.Request) (out SkyResult[string, *pkg.Route]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[string, *pkg.Route](pkg.CurrentRoute(p0))
	return
}

func Go_Mux_errMethodMismatch(_ any) any { return pkg.ErrMethodMismatch }

func Go_Mux_setErrMethodMismatch(value any) any { reflect.ValueOf(&pkg.ErrMethodMismatch).Elem().Set(reflect.ValueOf(value).Convert(reflect.TypeOf(pkg.ErrMethodMismatch))); return struct{}{} }

func Go_Mux_errNotFound(_ any) any { return pkg.ErrNotFound }

func Go_Mux_setErrNotFound(value any) any { reflect.ValueOf(&pkg.ErrNotFound).Elem().Set(reflect.ValueOf(value).Convert(reflect.TypeOf(pkg.ErrNotFound))); return struct{}{} }

// [pure] Go_Mux.matcherFuncMatch → pkg.MatcherFuncMatch
func Go_Mux_matcherFuncMatch(p0 any, p1 any, p2 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(pkg.MatcherFunc).Match(p1.(*http.Request), p2.(*pkg.RouteMatch)))
	return
}

// [pure] Go_Mux.middlewareFuncMiddleware → pkg.MiddlewareFuncMiddleware
func Go_Mux_middlewareFuncMiddleware(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(pkg.MiddlewareFunc).Middleware(p1.(http.Handler)))
	return
}

// [pure] Go_Mux.newRouter → pkg.NewRouter
func Go_Mux_newRouter(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	_ = p0
	out = Ok[any, any](pkg.NewRouter())
	return
}
// [pure] typed wrapper for Go_Mux_newRouter (P7 adaptor target)
func Go_Mux_newRouterT() (out SkyResult[string, *pkg.Router]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[string, *pkg.Router](pkg.NewRouter())
	return
}

// [pure] Go_Mux.routeSkipClean → pkg.RouteSkipClean
func Go_Mux_routeSkipClean(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(*pkg.Route).SkipClean())
	return
}

// [pure] Go_Mux.routeMatch → pkg.RouteMatch
func Go_Mux_routeMatch(p0 any, p1 any, p2 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(*pkg.Route).Match(p1.(*http.Request), p2.(*pkg.RouteMatch)))
	return
}

// [fallible] Go_Mux.routeGetError → pkg.RouteGetError
func Go_Mux_routeGetError(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	err := p0.(*pkg.Route).GetError()
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](struct{}{})

	return
}

// [pure] Go_Mux.routeBuildOnly → pkg.RouteBuildOnly
func Go_Mux_routeBuildOnly(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(*pkg.Route).BuildOnly())
	return
}

// [pure] Go_Mux.routeHandler → pkg.RouteHandler
func Go_Mux_routeHandler(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(*pkg.Route).Handler(p1.(http.Handler)))
	return
}

// [pure] Go_Mux.routeHandlerFunc → pkg.RouteHandlerFunc
func Go_Mux_routeHandlerFunc(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(*pkg.Route).HandlerFunc(p1.(func(http.ResponseWriter, *http.Request))))
	return
}

// [pure] Go_Mux.routeGetHandler → pkg.RouteGetHandler
func Go_Mux_routeGetHandler(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(*pkg.Route).GetHandler())
	return
}

// [pure] Go_Mux.routeName → pkg.RouteName
func Go_Mux_routeName(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(*pkg.Route).Name(fmt.Sprintf("%v", p1)))
	return
}

// [pure] Go_Mux.routeGetName → pkg.RouteGetName
func Go_Mux_routeGetName(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(*pkg.Route).GetName())
	return
}

// [pure] Go_Mux.routeHeaders → pkg.RouteHeaders
func Go_Mux_routeHeaders(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(*pkg.Route).Headers(p1.([]string)...))
	return
}

// [pure] Go_Mux.routeHeadersRegexp → pkg.RouteHeadersRegexp
func Go_Mux_routeHeadersRegexp(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(*pkg.Route).HeadersRegexp(p1.([]string)...))
	return
}

// [pure] Go_Mux.routeHost → pkg.RouteHost
func Go_Mux_routeHost(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(*pkg.Route).Host(fmt.Sprintf("%v", p1)))
	return
}

// [pure] Go_Mux.routeMatcherFunc → pkg.RouteMatcherFunc
func Go_Mux_routeMatcherFunc(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(*pkg.Route).MatcherFunc(p1.(pkg.MatcherFunc)))
	return
}

// [pure] Go_Mux.routeMethods → pkg.RouteMethods
func Go_Mux_routeMethods(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(*pkg.Route).Methods(p1.([]string)...))
	return
}

// [pure] Go_Mux.routePath → pkg.RoutePath
func Go_Mux_routePath(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(*pkg.Route).Path(fmt.Sprintf("%v", p1)))
	return
}

// [pure] Go_Mux.routePathPrefix → pkg.RoutePathPrefix
func Go_Mux_routePathPrefix(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(*pkg.Route).PathPrefix(fmt.Sprintf("%v", p1)))
	return
}

// [pure] Go_Mux.routeQueries → pkg.RouteQueries
func Go_Mux_routeQueries(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(*pkg.Route).Queries(p1.([]string)...))
	return
}

// [pure] Go_Mux.routeSchemes → pkg.RouteSchemes
func Go_Mux_routeSchemes(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(*pkg.Route).Schemes(p1.([]string)...))
	return
}

// [pure] Go_Mux.routeBuildVarsFunc → pkg.RouteBuildVarsFunc
func Go_Mux_routeBuildVarsFunc(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(*pkg.Route).BuildVarsFunc(p1.(pkg.BuildVarsFunc)))
	return
}

// [pure] Go_Mux.routeSubrouter → pkg.RouteSubrouter
func Go_Mux_routeSubrouter(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(*pkg.Route).Subrouter())
	return
}

// [fallible] Go_Mux.routeURL → pkg.RouteURL
func Go_Mux_routeURL(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	r0, err := p0.(*pkg.Route).URL(p1.([]string)...)
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](r0)

	return
}

// [fallible] Go_Mux.routeURLHost → pkg.RouteURLHost
func Go_Mux_routeURLHost(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	r0, err := p0.(*pkg.Route).URLHost(p1.([]string)...)
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](r0)

	return
}

// [fallible] Go_Mux.routeURLPath → pkg.RouteURLPath
func Go_Mux_routeURLPath(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	r0, err := p0.(*pkg.Route).URLPath(p1.([]string)...)
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](r0)

	return
}

// [fallible] Go_Mux.routeGetPathTemplate → pkg.RouteGetPathTemplate
func Go_Mux_routeGetPathTemplate(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	r0, err := p0.(*pkg.Route).GetPathTemplate()
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](r0)

	return
}

// [fallible] Go_Mux.routeGetPathRegexp → pkg.RouteGetPathRegexp
func Go_Mux_routeGetPathRegexp(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	r0, err := p0.(*pkg.Route).GetPathRegexp()
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](r0)

	return
}

// [fallible] Go_Mux.routeGetQueriesRegexp → pkg.RouteGetQueriesRegexp
func Go_Mux_routeGetQueriesRegexp(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	r0, err := p0.(*pkg.Route).GetQueriesRegexp()
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](r0)

	return
}

// [fallible] Go_Mux.routeGetQueriesTemplates → pkg.RouteGetQueriesTemplates
func Go_Mux_routeGetQueriesTemplates(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	r0, err := p0.(*pkg.Route).GetQueriesTemplates()
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](r0)

	return
}

// [fallible] Go_Mux.routeGetMethods → pkg.RouteGetMethods
func Go_Mux_routeGetMethods(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	r0, err := p0.(*pkg.Route).GetMethods()
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](r0)

	return
}

// [fallible] Go_Mux.routeGetHostTemplate → pkg.RouteGetHostTemplate
func Go_Mux_routeGetHostTemplate(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	r0, err := p0.(*pkg.Route).GetHostTemplate()
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](r0)

	return
}

// [fallible] Go_Mux.routeGetVarNames → pkg.RouteGetVarNames
func Go_Mux_routeGetVarNames(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	r0, err := p0.(*pkg.Route).GetVarNames()
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](r0)

	return
}

func Go_Mux_newRoute(_ any) any { return new(pkg.Route) }

func Go_Mux_routeMatchRoute(p0 any) any { return SkyFfiFieldGet(p0, "Route") }

func Go_Mux_routeMatchSetRoute(value any, recv any) any { return SkyFfiFieldSet(value, recv, "Route") }

func Go_Mux_routeMatchHandler(p0 any) any { return SkyFfiFieldGet(p0, "Handler") }

func Go_Mux_routeMatchSetHandler(value any, recv any) any { return SkyFfiFieldSet(value, recv, "Handler") }

func Go_Mux_routeMatchVars(p0 any) any { return SkyFfiFieldGet(p0, "Vars") }

func Go_Mux_routeMatchSetVars(value any, recv any) any { return SkyFfiFieldSet(value, recv, "Vars") }

func Go_Mux_routeMatchMatchErr(p0 any) any { return SkyFfiFieldGet(p0, "MatchErr") }

func Go_Mux_routeMatchSetMatchErr(value any, recv any) any { return SkyFfiFieldSet(value, recv, "MatchErr") }

func Go_Mux_newRouteMatch(_ any) any { return new(pkg.RouteMatch) }

// [pure] Go_Mux.routerUse → pkg.RouterUse
func Go_Mux_routerUse(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	p0.(*pkg.Router).Use(p1.([]pkg.MiddlewareFunc)...)
	out = Ok[any, any](struct{}{})
	return
}

// [pure] Go_Mux.routerMatch → pkg.RouterMatch
func Go_Mux_routerMatch(p0 any, p1 any, p2 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(*pkg.Router).Match(p1.(*http.Request), p2.(*pkg.RouteMatch)))
	return
}

// [pure] Go_Mux.routerServeHTTP → pkg.RouterServeHTTP
func Go_Mux_routerServeHTTP(p0 any, p1 any, p2 any) (out any) {
	defer SkyFfiRecover(&out)()
	p0.(*pkg.Router).ServeHTTP(p1.(http.ResponseWriter), p2.(*http.Request))
	out = Ok[any, any](struct{}{})
	return
}

// [pure] Go_Mux.routerGet → pkg.RouterGet
func Go_Mux_routerGet(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(*pkg.Router).Get(fmt.Sprintf("%v", p1)))
	return
}

// [pure] Go_Mux.routerGetRoute → pkg.RouterGetRoute
func Go_Mux_routerGetRoute(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(*pkg.Router).GetRoute(fmt.Sprintf("%v", p1)))
	return
}

// [pure] Go_Mux.routerStrictSlash → pkg.RouterStrictSlash
func Go_Mux_routerStrictSlash(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(*pkg.Router).StrictSlash(AsBool(p1)))
	return
}

// [pure] Go_Mux.routerSkipClean → pkg.RouterSkipClean
func Go_Mux_routerSkipClean(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(*pkg.Router).SkipClean(AsBool(p1)))
	return
}

// [pure] Go_Mux.routerUseEncodedPath → pkg.RouterUseEncodedPath
func Go_Mux_routerUseEncodedPath(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(*pkg.Router).UseEncodedPath())
	return
}

// [pure] Go_Mux.routerNewRoute → pkg.RouterNewRoute
func Go_Mux_routerNewRoute(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(*pkg.Router).NewRoute())
	return
}

// [pure] Go_Mux.routerName → pkg.RouterName
func Go_Mux_routerName(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(*pkg.Router).Name(fmt.Sprintf("%v", p1)))
	return
}

// [pure] Go_Mux.routerHandle → pkg.RouterHandle
func Go_Mux_routerHandle(p0 any, p1 any, p2 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(*pkg.Router).Handle(fmt.Sprintf("%v", p1), p2.(http.Handler)))
	return
}

// [pure] Go_Mux.routerHandleFunc → pkg.RouterHandleFunc
func Go_Mux_routerHandleFunc(p0 any, p1 any, p2 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(*pkg.Router).HandleFunc(fmt.Sprintf("%v", p1), p2.(func(http.ResponseWriter, *http.Request))))
	return
}

// [pure] Go_Mux.routerHeaders → pkg.RouterHeaders
func Go_Mux_routerHeaders(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(*pkg.Router).Headers(p1.([]string)...))
	return
}

// [pure] Go_Mux.routerHost → pkg.RouterHost
func Go_Mux_routerHost(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(*pkg.Router).Host(fmt.Sprintf("%v", p1)))
	return
}

// [pure] Go_Mux.routerMatcherFunc → pkg.RouterMatcherFunc
func Go_Mux_routerMatcherFunc(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(*pkg.Router).MatcherFunc(p1.(pkg.MatcherFunc)))
	return
}

// [pure] Go_Mux.routerMethods → pkg.RouterMethods
func Go_Mux_routerMethods(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(*pkg.Router).Methods(p1.([]string)...))
	return
}

// [pure] Go_Mux.routerPath → pkg.RouterPath
func Go_Mux_routerPath(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(*pkg.Router).Path(fmt.Sprintf("%v", p1)))
	return
}

// [pure] Go_Mux.routerPathPrefix → pkg.RouterPathPrefix
func Go_Mux_routerPathPrefix(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(*pkg.Router).PathPrefix(fmt.Sprintf("%v", p1)))
	return
}

// [pure] Go_Mux.routerQueries → pkg.RouterQueries
func Go_Mux_routerQueries(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(*pkg.Router).Queries(p1.([]string)...))
	return
}

// [pure] Go_Mux.routerSchemes → pkg.RouterSchemes
func Go_Mux_routerSchemes(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(*pkg.Router).Schemes(p1.([]string)...))
	return
}

// [pure] Go_Mux.routerBuildVarsFunc → pkg.RouterBuildVarsFunc
func Go_Mux_routerBuildVarsFunc(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(*pkg.Router).BuildVarsFunc(p1.(pkg.BuildVarsFunc)))
	return
}

// [fallible] Go_Mux.routerWalk → pkg.RouterWalk
func Go_Mux_routerWalk(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	err := p0.(*pkg.Router).Walk(p1.(pkg.WalkFunc))
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](struct{}{})

	return
}

func Go_Mux_routerNotFoundHandler(p0 any) any { return SkyFfiFieldGet(p0, "NotFoundHandler") }

func Go_Mux_routerSetNotFoundHandler(value any, recv any) any { return SkyFfiFieldSet(value, recv, "NotFoundHandler") }

func Go_Mux_routerMethodNotAllowedHandler(p0 any) any { return SkyFfiFieldGet(p0, "MethodNotAllowedHandler") }

func Go_Mux_routerSetMethodNotAllowedHandler(value any, recv any) any { return SkyFfiFieldSet(value, recv, "MethodNotAllowedHandler") }

func Go_Mux_routerKeepContext(p0 any) any { return SkyFfiFieldGet(p0, "KeepContext") }

func Go_Mux_routerSetKeepContext(value any, recv any) any { return SkyFfiFieldSet(value, recv, "KeepContext") }

// [pure] Go_Mux.setURLVars → pkg.SetURLVars
func Go_Mux_setURLVars(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](pkg.SetURLVars(p0.(*http.Request), p1.(map[string]string)))
	return
}

func Go_Mux_skipRouter(_ any) any { return pkg.SkipRouter }

func Go_Mux_setSkipRouter(value any) any { reflect.ValueOf(&pkg.SkipRouter).Elem().Set(reflect.ValueOf(value).Convert(reflect.TypeOf(pkg.SkipRouter))); return struct{}{} }

// [pure] Go_Mux.vars → pkg.Vars
func Go_Mux_vars(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](pkg.Vars(p0.(*http.Request)))
	return
}


// Pin fmt against "imported and not used" across partial files.
var _ = fmt.Sprintf
