-- | Core type representation for Sky's type inference.
-- Adapted from Elm's Type.Type with Sky module names and no Elm.Package.
--
-- Uses Union-Find variables for efficient unification.
-- Two levels: Variable (mutable, for inference) and Type (immutable, canonical).
module Sky.Type.Type where

import qualified Data.Map.Strict as Map
import qualified Sky.Type.UnionFind as UF
import qualified Sky.Sky.ModuleName as ModuleName


-- ═══════════════════════════════════════════════════════════
-- SOLVER-LEVEL TYPES (mutable, during inference)
-- ═══════════════════════════════════════════════════════════

-- | A type variable backed by Union-Find
type Variable = UF.Point Descriptor


-- | Descriptor for a type variable
data Descriptor = Descriptor
    { _content :: !Content
    , _rank    :: {-# UNPACK #-} !Int
    , _mark    :: {-# UNPACK #-} !Int
    , _copy    :: !(Maybe Variable)
    }


-- | What a type variable resolves to
data Content
    = FlexVar !(Maybe String)                     -- unconstrained inferred variable
    | FlexSuper !SuperType !(Maybe String)        -- constrained inferred variable
    | RigidVar !String                            -- from user annotation (cannot unify with concrete)
    | RigidSuper !SuperType !String               -- constrained rigid
    | Structure !FlatType                         -- resolved concrete type
    | Alias !ModuleName.Canonical !String [(String, Variable)] !Variable  -- type alias
    | Error                                       -- error recovery


-- | Constraint categories for special types
data SuperType
    = Number        -- Int or Float
    | Comparable    -- types that support ==, <, >
    | Appendable    -- String or List a
    | CompAppend    -- String or List a where a is Comparable
    deriving (Eq, Show)


-- | Concrete type structures (flattened for efficiency)
data FlatType
    = App1 !ModuleName.Canonical !String [Variable]     -- type constructor application
    | Fun1 !Variable !Variable                          -- function type a -> b
    | EmptyRecord1                                      -- empty record {}
    | Record1 !(Map.Map String Variable) !Variable      -- record with extension var
    | Unit1                                             -- unit type ()
    | Tuple1 !Variable !Variable !(Maybe Variable)      -- 2 or 3 element tuple


instance Show FlatType where
    show _ = "<FlatType>"


-- ═══════════════════════════════════════════════════════════
-- CANONICAL-LEVEL TYPES (immutable, in interfaces)
-- ═══════════════════════════════════════════════════════════

-- | A canonical type (used in annotations, interfaces)
data Type
    = TLambda !Type !Type                                   -- a -> b
    | TVar !String                                          -- type variable
    | TType !ModuleName.Canonical !String [Type]            -- type constructor
    | TRecord !(Map.Map String FieldType) !(Maybe String)   -- record (fields + extension)
    | TUnit                                                 -- ()
    | TTuple !Type !Type !(Maybe Type)                      -- 2 or 3 tuple
    | TAlias !ModuleName.Canonical !String [(String, Type)] !AliasType
    deriving (Eq, Ord, Show)


-- | Record field with source position info
data FieldType = FieldType
    { _fieldIndex :: {-# UNPACK #-} !Int   -- field position in source
    , _fieldType  :: !Type
    }
    deriving (Eq, Ord, Show)


-- | Whether a type alias is filled (resolved) or hollow (just a reference)
data AliasType
    = Hoisted !Type    -- fully resolved
    | Filled !Type     -- from another module's interface
    deriving (Eq, Ord, Show)


-- ═══════════════════════════════════════════════════════════
-- CONSTRAINTS (generated by Constrain, solved by Solve)
-- ═══════════════════════════════════════════════════════════

-- | Type constraints for the solver
data Constraint
    = CTrue                                             -- always satisfied
    | CSaveTheEnvironment                               -- sentinel: capture env
    | CEqual !Region !Category !Type !(Expected Type)   -- two types must unify
    | CLocal !Region !String !(Expected Type)            -- local variable usage
    | CForeign !Region !String !Annotation !(Expected Type) -- imported value
    | CPattern !Region !PCategory !Type !(PExpected Type)   -- pattern constraint
    | CAnd [Constraint]                                  -- conjunction
    | CLet                                               -- let binding
        { _rigidVars  :: [Variable]
        , _flexVars   :: [Variable]
        , _header     :: Map.Map String (Located Type)
        , _headerCon  :: Constraint
        , _bodyCon    :: Constraint
        }


-- | What was expected (for error messages)
data Expected a
    = NoExpectation a
    | FromContext !Region !Context a
    | FromAnnotation !String !Int !SubContext a
    deriving (Show)


-- | Pattern expectation
data PExpected a
    = PNoExpectation a
    | PFromContext !Region !PContext a
    deriving (Show)


-- | Context for error reporting
data Context
    = ListEntry !Int
    | Negate
    | OpLeft !String
    | OpRight !String
    | IfCondition
    | IfBranch !Int
    | CaseBranch !Int
    | CallArity !Int !Int
    | CallArg !String !Int
    | RecordAccess !String !String
    | RecordUpdate !String !String
    | Destructure
    deriving (Show)


data SubContext
    = TypedIfBranch !Int
    | TypedCaseBranch !Int
    | TypedBody
    deriving (Show)


data PContext
    = PTypedArg !String !Int
    | PCaseMatch
    | PCtorArg !String !Int
    | PListEntry !Int
    | PTail
    deriving (Show)


-- | Error category
data Category
    = CList
    | CNumber
    | CFloat
    | CString
    | CChar
    | CIf
    | CCase
    | CRecord
    | CAccess !String
    | CLambda
    | CApp
    | CCustom !String
    deriving (Show)


data PCategory
    = PCRecord
    | PCUnit
    | PCTuple
    | PCList
    | PCCtor !String
    | PCInt
    | PCFloat
    | PCChar
    | PCString
    | PCBool
    deriving (Show)


-- | An annotated type scheme
data Annotation = Forall [String] Type
    deriving (Eq, Show)


-- Simplified region/located types (bridge to Annotation)
type Region = (Int, Int)
type Located a = (Region, a)
