package sky_wrappers

import (
	_ffi_fmt "fmt"
	_ffi_reflect "reflect"

	v84 "github.com/stripe/stripe-go/v84"
	customer "github.com/stripe/stripe-go/v84/customer"
)

var _ = _ffi_fmt.Sprintf

// Auto-generated by Sky compiler

func Sky_github_com_stripe_stripe_go_v84_customer_CreateFundingInstructions(arg0 any, arg1 any) any {
	_arg0 := sky_asString(arg0)
	_arg1 := arg1.(*v84.CustomerCreateFundingInstructionsParams)
	return func() any {
		defer func() { recover() }()
		result, err := customer.CreateFundingInstructions(_arg0, _arg1)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_github_com_stripe_stripe_go_v84_customer_Del(arg0 any, arg1 any) any {
	_arg0 := sky_asString(arg0)
	_arg1 := arg1.(*v84.CustomerParams)
	return func() any {
		defer func() { recover() }()
		result, err := customer.Del(_arg0, _arg1)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_github_com_stripe_stripe_go_v84_customer_DeleteDiscount(arg0 any, arg1 any) any {
	_arg0 := sky_asString(arg0)
	_arg1 := arg1.(*v84.CustomerDeleteDiscountParams)
	return func() any {
		defer func() { recover() }()
		result, err := customer.DeleteDiscount(_arg0, _arg1)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_github_com_stripe_stripe_go_v84_customer_Get(arg0 any, arg1 any) any {
	_arg0 := sky_asString(arg0)
	_arg1 := arg1.(*v84.CustomerParams)
	return func() any {
		defer func() { recover() }()
		result, err := customer.Get(_arg0, _arg1)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_github_com_stripe_stripe_go_v84_customer_List(arg0 any) any {
	_arg0 := arg0.(*v84.CustomerListParams)
	return customer.List(_arg0)
}

func Sky_github_com_stripe_stripe_go_v84_customer_ListPaymentMethods(arg0 any) any {
	_arg0 := arg0.(*v84.CustomerListPaymentMethodsParams)
	return customer.ListPaymentMethods(_arg0)
}

func Sky_github_com_stripe_stripe_go_v84_customer_New(arg0 any) any {
	_arg0 := arg0.(*v84.CustomerParams)
	return func() any {
		defer func() { recover() }()
		result, err := customer.New(_arg0)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_github_com_stripe_stripe_go_v84_customer_RetrievePaymentMethod(arg0 any, arg1 any) any {
	_arg0 := sky_asString(arg0)
	_arg1 := arg1.(*v84.CustomerRetrievePaymentMethodParams)
	return func() any {
		defer func() { recover() }()
		result, err := customer.RetrievePaymentMethod(_arg0, _arg1)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_github_com_stripe_stripe_go_v84_customer_Search(arg0 any) any {
	_arg0 := arg0.(*v84.CustomerSearchParams)
	return customer.Search(_arg0)
}

func Sky_github_com_stripe_stripe_go_v84_customer_Update(arg0 any, arg1 any) any {
	_arg0 := sky_asString(arg0)
	_arg1 := arg1.(*v84.CustomerParams)
	return func() any {
		defer func() { recover() }()
		result, err := customer.Update(_arg0, _arg1)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_github_com_stripe_stripe_go_v84_customer_ClientCreateFundingInstructions(receiver any, arg0 any, arg1 any) any {
	_receiver := receiver.(*customer.Client)
	_arg0 := sky_asString(arg0)
	_arg1 := arg1.(*v84.CustomerCreateFundingInstructionsParams)
	return func() any {
		defer func() { recover() }()
		result, err := _receiver.CreateFundingInstructions(_arg0, _arg1)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_github_com_stripe_stripe_go_v84_customer_ClientDel(receiver any, arg0 any, arg1 any) any {
	_receiver := receiver.(*customer.Client)
	_arg0 := sky_asString(arg0)
	_arg1 := arg1.(*v84.CustomerParams)
	return func() any {
		defer func() { recover() }()
		result, err := _receiver.Del(_arg0, _arg1)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_github_com_stripe_stripe_go_v84_customer_ClientDeleteDiscount(receiver any, arg0 any, arg1 any) any {
	_receiver := receiver.(*customer.Client)
	_arg0 := sky_asString(arg0)
	_arg1 := arg1.(*v84.CustomerDeleteDiscountParams)
	return func() any {
		defer func() { recover() }()
		result, err := _receiver.DeleteDiscount(_arg0, _arg1)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_github_com_stripe_stripe_go_v84_customer_ClientGet(receiver any, arg0 any, arg1 any) any {
	_receiver := receiver.(*customer.Client)
	_arg0 := sky_asString(arg0)
	_arg1 := arg1.(*v84.CustomerParams)
	return func() any {
		defer func() { recover() }()
		result, err := _receiver.Get(_arg0, _arg1)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_github_com_stripe_stripe_go_v84_customer_ClientList(receiver any, arg0 any) any {
	_receiver := receiver.(*customer.Client)
	_arg0 := arg0.(*v84.CustomerListParams)
	return _receiver.List(_arg0)
}

func Sky_github_com_stripe_stripe_go_v84_customer_ClientListPaymentMethods(receiver any, arg0 any) any {
	_receiver := receiver.(*customer.Client)
	_arg0 := arg0.(*v84.CustomerListPaymentMethodsParams)
	return _receiver.ListPaymentMethods(_arg0)
}

func Sky_github_com_stripe_stripe_go_v84_customer_ClientNew(receiver any, arg0 any) any {
	_receiver := receiver.(*customer.Client)
	_arg0 := arg0.(*v84.CustomerParams)
	return func() any {
		defer func() { recover() }()
		result, err := _receiver.New(_arg0)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_github_com_stripe_stripe_go_v84_customer_ClientRetrievePaymentMethod(receiver any, arg0 any, arg1 any) any {
	_receiver := receiver.(*customer.Client)
	_arg0 := sky_asString(arg0)
	_arg1 := arg1.(*v84.CustomerRetrievePaymentMethodParams)
	return func() any {
		defer func() { recover() }()
		result, err := _receiver.RetrievePaymentMethod(_arg0, _arg1)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_github_com_stripe_stripe_go_v84_customer_ClientSearch(receiver any, arg0 any) any {
	_receiver := receiver.(*customer.Client)
	_arg0 := arg0.(*v84.CustomerSearchParams)
	return _receiver.Search(_arg0)
}

func Sky_github_com_stripe_stripe_go_v84_customer_ClientUpdate(receiver any, arg0 any, arg1 any) any {
	_receiver := receiver.(*customer.Client)
	_arg0 := sky_asString(arg0)
	_arg1 := arg1.(*v84.CustomerParams)
	return func() any {
		defer func() { recover() }()
		result, err := _receiver.Update(_arg0, _arg1)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_github_com_stripe_stripe_go_v84_customer_IterCurrent(receiver any) any {
	_receiver := receiver.(*customer.Iter)
	return _receiver.Current()
}

func Sky_github_com_stripe_stripe_go_v84_customer_IterCustomer(receiver any) any {
	_receiver := receiver.(*customer.Iter)
	return _receiver.Customer()
}

func Sky_github_com_stripe_stripe_go_v84_customer_IterCustomerList(receiver any) any {
	_receiver := receiver.(*customer.Iter)
	return _receiver.CustomerList()
}

func Sky_github_com_stripe_stripe_go_v84_customer_IterErr(receiver any) any {
	_receiver := receiver.(*customer.Iter)
	return func() any {
		defer func() { recover() }()
		err := _receiver.Err()
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(struct{}{})
	}()
}

func Sky_github_com_stripe_stripe_go_v84_customer_IterList(receiver any) any {
	_receiver := receiver.(*customer.Iter)
	return _receiver.List()
}

func Sky_github_com_stripe_stripe_go_v84_customer_IterMeta(receiver any) any {
	_receiver := receiver.(*customer.Iter)
	return _receiver.Meta()
}

func Sky_github_com_stripe_stripe_go_v84_customer_IterNext(receiver any) any {
	_receiver := receiver.(*customer.Iter)
	return _receiver.Next()
}

func Sky_github_com_stripe_stripe_go_v84_customer_PaymentMethodIterCurrent(receiver any) any {
	_receiver := receiver.(*customer.PaymentMethodIter)
	return _receiver.Current()
}

func Sky_github_com_stripe_stripe_go_v84_customer_PaymentMethodIterErr(receiver any) any {
	_receiver := receiver.(*customer.PaymentMethodIter)
	return func() any {
		defer func() { recover() }()
		err := _receiver.Err()
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(struct{}{})
	}()
}

func Sky_github_com_stripe_stripe_go_v84_customer_PaymentMethodIterList(receiver any) any {
	_receiver := receiver.(*customer.PaymentMethodIter)
	return _receiver.List()
}

func Sky_github_com_stripe_stripe_go_v84_customer_PaymentMethodIterMeta(receiver any) any {
	_receiver := receiver.(*customer.PaymentMethodIter)
	return _receiver.Meta()
}

func Sky_github_com_stripe_stripe_go_v84_customer_PaymentMethodIterNext(receiver any) any {
	_receiver := receiver.(*customer.PaymentMethodIter)
	return _receiver.Next()
}

func Sky_github_com_stripe_stripe_go_v84_customer_PaymentMethodIterPaymentMethod(receiver any) any {
	_receiver := receiver.(*customer.PaymentMethodIter)
	return _receiver.PaymentMethod()
}

func Sky_github_com_stripe_stripe_go_v84_customer_PaymentMethodIterPaymentMethodList(receiver any) any {
	_receiver := receiver.(*customer.PaymentMethodIter)
	return _receiver.PaymentMethodList()
}

func Sky_github_com_stripe_stripe_go_v84_customer_SearchIterCurrent(receiver any) any {
	_receiver := receiver.(*customer.SearchIter)
	return _receiver.Current()
}

func Sky_github_com_stripe_stripe_go_v84_customer_SearchIterCustomer(receiver any) any {
	_receiver := receiver.(*customer.SearchIter)
	return _receiver.Customer()
}

func Sky_github_com_stripe_stripe_go_v84_customer_SearchIterCustomerSearchResult(receiver any) any {
	_receiver := receiver.(*customer.SearchIter)
	return _receiver.CustomerSearchResult()
}

func Sky_github_com_stripe_stripe_go_v84_customer_SearchIterErr(receiver any) any {
	_receiver := receiver.(*customer.SearchIter)
	return func() any {
		defer func() { recover() }()
		err := _receiver.Err()
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(struct{}{})
	}()
}

func Sky_github_com_stripe_stripe_go_v84_customer_SearchIterMeta(receiver any) any {
	_receiver := receiver.(*customer.SearchIter)
	return _receiver.Meta()
}

func Sky_github_com_stripe_stripe_go_v84_customer_SearchIterNext(receiver any) any {
	_receiver := receiver.(*customer.SearchIter)
	return _receiver.Next()
}

func Sky_github_com_stripe_stripe_go_v84_customer_SearchIterSearchResult(receiver any) any {
	_receiver := receiver.(*customer.SearchIter)
	return _receiver.SearchResult()
}

func Sky_github_com_stripe_stripe_go_v84_customer_FIELD_Client_B(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr {
		v = v.Elem()
	}
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("B")
		if f.IsValid() {
			return f.Interface()
		}
	}
	return nil
}

func Sky_github_com_stripe_stripe_go_v84_customer_FIELD_Client_Key(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr {
		v = v.Elem()
	}
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("Key")
		if f.IsValid() {
			return f.Interface()
		}
	}
	return nil
}

func Sky_github_com_stripe_stripe_go_v84_customer_FIELD_Iter_Iter(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr {
		v = v.Elem()
	}
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("Iter")
		if f.IsValid() {
			return f.Interface()
		}
	}
	return nil
}

func Sky_github_com_stripe_stripe_go_v84_customer_FIELD_PaymentMethodIter_Iter(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr {
		v = v.Elem()
	}
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("Iter")
		if f.IsValid() {
			return f.Interface()
		}
	}
	return nil
}

func Sky_github_com_stripe_stripe_go_v84_customer_FIELD_SearchIter_SearchIter(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr {
		v = v.Elem()
	}
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("SearchIter")
		if f.IsValid() {
			return f.Interface()
		}
	}
	return nil
}
