//! Kernel dispatch (doc 09 A.3). The `(pseudo-module, func) → rt.<symbol>` table
//! is a mechanical port of `Generate/Go/Kernel.hs` (529 entries). Every runtime
//! kernel is `any`-based (takes `any`, returns `any`), so the lowerer applies one
//! uniform rule: widen args to `any`, coerce the `any` return to the call's typed
//! slot (the FFI-return coercion, doc 07 §6).

use std::collections::HashMap;
use std::sync::OnceLock;

/// The Go runtime symbol for a `(pseudo-module, func)` kernel. `None` when the
/// pair is not a known kernel (the caller falls back to `rt.<Mod>_<fn>`).
pub fn kernel_go_name_opt(module: &str, func: &str) -> Option<&'static str> {
    table().get(&(module, func)).copied()
}

/// The Go runtime symbol for a kernel reference, defaulting to `rt.<Mod>_<fn>`.
pub fn kernel_go_name(module: &str, func: &str) -> String {
    kernel_go_name_opt(module, func)
        .map(|s| s.to_string())
        .unwrap_or_else(|| format!("rt.{module}_{func}"))
}

/// Resolve a kernel-alias raw suffix (`"Task_succeed"`) to its runtime symbol by
/// splitting at the first `_` into `(module, func)` and consulting the table
/// (`Task_succeed` → `rt.AnyTaskSucceed`, not `rt.Task_succeed`).
pub fn alias_go_name(raw: &str) -> String {
    if let Some((m, f)) = raw.split_once('_') {
        if let Some(sym) = kernel_go_name_opt(m, f) {
            return sym.to_string();
        }
    }
    format!("rt.{raw}")
}

/// Is `(module, func)` a NULLARY kernel *value* — a Sky binding declared with no
/// parameters (`Dict.empty : Dict k v`, `Cmd.none : Cmd msg`, `Math.pi : Float`,
/// `JsonDec.string : Decoder String`) whose runtime symbol is a zero-arg Go func
/// (`func Dict_empty() any`)? Such a symbol referenced in a *value* slot must be
/// CALLED (`rt.Dict_empty()`) — a bare `rt.Dict_empty` is a `func() any`, not the
/// value, and a typed slot (`map[string]string`) `rt.Coerce`s the func and panics
/// (Limitation #7 value-slot class, kernel branch — the oracle always calls these).
/// A kernel of arity ≥ 1 (`String.toUpper`, `JsonDec.field`) is a genuine function
/// value (HOF callback) and stays bare, so it is NOT in this set. The set mirrors
/// the runtime's zero-parameter kernel funcs exactly.
pub fn is_nullary_kernel_value(module: &str, func: &str) -> bool {
    matches!(
        (module, func),
        ("Dict", "empty")
            | ("Set", "empty")
            | ("Cmd", "none")
            | ("Sub", "none")
            | ("Uuid", "v4")
            | ("Uuid", "v7")
            | ("JsonEnc", "null")
            | ("JsonDec", "string" | "int" | "float" | "bool")
            | ("Config", "string" | "int" | "float" | "bool")
            | ("Math", "pi" | "e" | "phi" | "sqrt2" | "inf" | "nan")
    )
}

/// Type-parameter arity for a GENERIC runtime kernel symbol referenced as a
/// first-class VALUE (passed as an argument, stored in a slot, coerced to `any`).
/// Go rejects a generic function used as a value without instantiation —
/// `any(rt.Basics_identity)` → "cannot use generic function … without
/// instantiation" — so such a reference must be emitted instantiated:
/// `rt.Basics_identity[any]`, `rt.Basics_always[any, any]`. Returns the number of
/// `any` type args to append, or `None` for the non-generic majority (emitted
/// bare, unchanged). These are the only two mapped kernels whose runtime symbol
/// is generic: `func Basics_identity[A any]` and `func Basics_always[A any, B any]`
/// (rt.go). A directly-CALLED kernel (`identity x`) never reaches this path — Go
/// infers the type args at the call site; only a bare value reference (e.g.
/// `JsonEnc.list identity args`) needs the explicit `[any, …]`. Sky's polymorphism
/// erases to `any` at this boundary, so `any` is always the correct instantiation.
pub fn generic_kernel_value_tyargs(runtime_sym: &str) -> Option<usize> {
    match runtime_sym {
        "rt.Basics_identity" => Some(1),
        "rt.Basics_always" => Some(2),
        _ => None,
    }
}

// determinism (L4): lookup-only kernel dispatch table. Built once from the
// ordered `KERNEL_TABLE` slice and consulted purely via `.get()` — its iteration
// order is never observed, so a `HashMap` is sound here.
fn table() -> &'static HashMap<(&'static str, &'static str), &'static str> {
    static T: OnceLock<HashMap<(&'static str, &'static str), &'static str>> = OnceLock::new();
    T.get_or_init(|| {
        let mut m = HashMap::with_capacity(KERNEL_TABLE.len());
        for (module, func, go) in KERNEL_TABLE {
            m.insert((*module, *func), *go);
        }
        m
    })
}

/// The kernel table — `(pseudo-module, func, runtime-symbol)` (Kernel.hs port).
#[rustfmt::skip]
static KERNEL_TABLE: &[(&str, &str, &str)] = &[
    ("Basics", "add", "rt.Basics_add"),
    ("Basics", "sub", "rt.Basics_sub"),
    ("Basics", "mul", "rt.Basics_mul"),
    ("Basics", "fdiv", "rt.Basics_fdiv"),
    ("Basics", "idiv", "rt.Basics_idiv"),
    ("Basics", "modBy", "rt.Basics_modBy"),
    ("Basics", "negate", "rt.Negate"),
    ("Basics", "abs", "rt.Math_abs"),
    ("Basics", "sqrt", "rt.Math_sqrt"),
    // Prelude/Basics `min`/`max` reuse the Math kernels — the HIR kernel table
    // registers them as valid names, but they had no codegen mapping, so a
    // well-typed `min 3 5` passed `sky check` then failed `go build` (E4005).
    ("Basics", "min", "rt.Math_min"),
    ("Basics", "max", "rt.Math_max"),
    ("Basics", "not", "rt.Basics_not"),
    ("Basics", "identity", "rt.Basics_identity"),
    ("Basics", "always", "rt.Basics_always"),
    ("Basics", "compare", "rt.Basics_compare"),
    ("Basics", "append", "rt.Basics_append"),
    ("Basics", "toString", "rt.Debug_toString"),
    ("String", "length", "rt.String_length"),
    ("String", "reverse", "rt.String_reverse"),
    ("String", "append", "rt.String_append"),
    ("String", "split", "rt.String_split"),
    ("String", "join", "rt.String_join"),
    ("String", "contains", "rt.String_contains"),
    ("String", "startsWith", "rt.String_startsWith"),
    ("String", "endsWith", "rt.String_endsWith"),
    ("String", "toInt", "rt.String_toInt"),
    ("String", "fromInt", "rt.String_fromInt"),
    ("String", "toFloat", "rt.String_toFloat"),
    ("String", "fromFloat", "rt.String_fromFloat"),
    ("String", "toUpper", "rt.String_toUpper"),
    ("String", "toLower", "rt.String_toLower"),
    ("String", "trim", "rt.String_trim"),
    ("String", "isEmpty", "rt.String_isEmpty"),
    ("String", "replace", "rt.String_replace"),
    ("String", "slice", "rt.String_slice"),
    ("String", "left", "rt.String_left"),
    ("String", "right", "rt.String_right"),
    ("String", "dropLeft", "rt.String_dropLeft"),
    ("String", "dropRight", "rt.String_dropRight"),
    ("String", "padLeft", "rt.String_padLeft"),
    ("String", "padRight", "rt.String_padRight"),
    ("String", "repeat", "rt.String_repeat"),
    ("String", "lines", "rt.String_lines"),
    ("String", "words", "rt.String_words"),
    ("String", "isValid", "rt.String_isValid"),
    ("String", "normalize", "rt.String_normalize"),
    ("String", "normalizeNFD", "rt.String_normalizeNFD"),
    ("String", "casefold", "rt.String_casefold"),
    ("String", "equalFold", "rt.String_equalFold"),
    ("String", "graphemes", "rt.String_graphemes"),
    ("String", "trimStart", "rt.String_trimStart"),
    ("String", "trimEnd", "rt.String_trimEnd"),
    ("String", "isEmail", "rt.String_isEmail"),
    ("String", "isUrl", "rt.String_isUrl"),
    ("String", "slugify", "rt.String_slugify"),
    ("String", "htmlEscape", "rt.String_htmlEscape"),
    ("String", "truncate", "rt.String_truncate"),
    ("String", "ellipsize", "rt.String_ellipsize"),
    ("String", "toList", "rt.String_toList"),
    ("String", "fromList", "rt.String_fromList"),
    ("String", "concat", "rt.String_concat"),
    ("Uuid", "v4", "rt.Uuid_v4"),
    ("Uuid", "v7", "rt.Uuid_v7"),
    ("Uuid", "parse", "rt.Uuid_parse"),
    ("RateLimit", "allow", "rt.RateLimit_allow"),
    ("Env", "get", "rt.Env_get"),
    ("Env", "getOrDefault", "rt.Env_getOrDefault"),
    ("Env", "require", "rt.Env_require"),
    ("Env", "getInt", "rt.Env_getInt"),
    ("Env", "getBool", "rt.Env_getBool"),
    ("Middleware", "withCors", "rt.Middleware_withCors"),
    ("Middleware", "withLogging", "rt.Middleware_withLogging"),
    ("Middleware", "withBasicAuth", "rt.Middleware_withBasicAuth"),
    ("Middleware", "withRateLimit", "rt.Middleware_withRateLimit"),
    ("Middleware", "rateLimit", "rt.Middleware_rateLimit"),
    ("Middleware", "withCsrf", "rt.Middleware_withCsrf"),
    ("Ffi", "call", "rt.Ffi_call"),
    ("Ffi", "callPure", "rt.Ffi_callPure"),
    ("Ffi", "callTask", "rt.Ffi_callTask"),
    ("Ffi", "has", "rt.Ffi_has"),
    ("Ffi", "isPure", "rt.Ffi_isPure"),
    ("Ffi", "kernel", "rt.Ffi_kernel"),
    ("Doc", "loadCatalog", "rt.Doc_loadCatalog"),
    ("Doc", "searchCatalog", "rt.Doc_searchCatalog"),
    ("Trace", "span", "rt.Trace_span"),
    ("Trace", "event", "rt.Trace_event"),
    ("Trace", "attr", "rt.Trace_attr"),
    ("List", "map", "rt.List_mapAny"),
    ("List", "filter", "rt.List_filterAny"),
    ("List", "foldl", "rt.List_foldl"),
    ("List", "foldr", "rt.List_foldr"),
    ("List", "length", "rt.List_length"),
    ("List", "head", "rt.List_headAny"),
    ("List", "tail", "rt.List_tail"),
    ("List", "indexedMap", "rt.List_indexedMap"),
    ("List", "find", "rt.List_find"),
    ("List", "take", "rt.List_take"),
    ("List", "drop", "rt.List_drop"),
    ("List", "append", "rt.List_append"),
    ("List", "concat", "rt.List_concat"),
    ("List", "concatMap", "rt.List_concatMap"),
    ("List", "reverse", "rt.List_reverseAny"),
    ("List", "sort", "rt.List_sort"),
    ("List", "sortBy", "rt.List_sortBy"),
    ("List", "sortWith", "rt.List_sortWith"),
    ("List", "member", "rt.List_member"),
    ("List", "any", "rt.List_any"),
    ("List", "all", "rt.List_all"),
    ("List", "range", "rt.List_range"),
    ("List", "zip", "rt.List_zip"),
    ("List", "filterMap", "rt.List_filterMap"),
    ("Dict", "empty", "rt.Dict_empty"),
    ("Dict", "insert", "rt.Dict_insert"),
    ("Dict", "get", "rt.Dict_get"),
    ("Dict", "remove", "rt.Dict_remove"),
    ("Dict", "member", "rt.Dict_member"),
    ("Dict", "keys", "rt.Dict_keys"),
    ("Dict", "values", "rt.Dict_values"),
    ("Dict", "toList", "rt.Dict_toList"),
    ("Dict", "fromList", "rt.Dict_fromList"),
    ("Dict", "map", "rt.Dict_map"),
    ("Dict", "foldl", "rt.Dict_foldl"),
    ("Dict", "union", "rt.Dict_union"),
    ("Dict", "size", "rt.Dict_size"),
    ("Dict", "isEmpty", "rt.Dict_isEmpty"),
    ("Maybe", "withDefault", "rt.Maybe_withDefault"),
    ("Maybe", "map", "rt.Maybe_map"),
    ("Maybe", "andThen", "rt.Maybe_andThen"),
    ("Maybe", "map2", "rt.Maybe_map2"),
    ("Maybe", "map3", "rt.Maybe_map3"),
    ("Maybe", "map4", "rt.Maybe_map4"),
    ("Maybe", "map5", "rt.Maybe_map5"),
    ("Maybe", "andMap", "rt.Maybe_andMap"),
    ("Maybe", "combine", "rt.Maybe_combine"),
    ("Maybe", "traverse", "rt.Maybe_traverse"),
    ("Result", "withDefault", "rt.Result_withDefault"),
    ("Result", "map", "rt.Result_map"),
    ("Result", "andThen", "rt.Result_andThen"),
    ("Result", "mapError", "rt.Result_mapError"),
    ("Result", "map2", "rt.Result_map2"),
    ("Result", "map3", "rt.Result_map3"),
    ("Result", "map4", "rt.Result_map4"),
    ("Result", "map5", "rt.Result_map5"),
    ("Result", "andMap", "rt.Result_andMap"),
    ("Result", "combine", "rt.Result_combine"),
    ("Result", "traverse", "rt.Result_traverse"),
    ("Result", "andThenTask", "rt.Result_andThenTask"),
    ("Task", "succeed", "rt.AnyTaskSucceed"),
    ("Task", "fail", "rt.AnyTaskFail"),
    ("Task", "map", "rt.Task_map"),
    ("Task", "andThen", "rt.AnyTaskAndThen"),
    ("Task", "perform", "rt.AnyTaskRun"),
    ("Task", "sequence", "rt.Task_sequence"),
    ("Task", "parallel", "rt.Task_parallel"),
    ("Task", "lazy", "rt.Task_lazy"),
    ("Task", "run", "rt.AnyTaskRun"),
    ("Task", "fromResult", "rt.Task_fromResult"),
    ("Task", "andThenResult", "rt.Task_andThenResult"),
    ("Task", "mapError", "rt.Task_mapError"),
    ("Task", "onError", "rt.Task_onError"),
    ("Task", "retryWith", "rt.Task_retryWith"),
    ("Cmd", "none", "rt.Cmd_none"),
    ("Cmd", "batch", "rt.Cmd_batch"),
    ("Cmd", "perform", "rt.Cmd_perform"),
    ("Cmd", "publish", "rt.Cmd_publish"),
    ("Cmd", "publishNoEcho", "rt.Cmd_publishNoEcho"),
    ("Webview", "app", "rt.Webview_app"),
    ("Time", "now", "rt.Time_now"),
    ("Time", "sleep", "rt.Time_sleep"),
    ("Time", "every", "rt.Time_every"),
    ("Time", "unixMillis", "rt.Time_unixMillis"),
    ("Time", "formatISO8601", "rt.Time_formatISO8601"),
    ("Time", "formatRFC3339", "rt.Time_formatRFC3339"),
    ("Time", "formatHTTP", "rt.Time_formatHTTP"),
    ("Time", "format", "rt.Time_format"),
    ("Time", "parseISO8601", "rt.Time_parseISO8601"),
    ("Time", "parse", "rt.Time_parse"),
    ("Time", "addMillis", "rt.Time_addMillis"),
    ("Time", "diffMillis", "rt.Time_diffMillis"),
    ("Random", "int", "rt.Random_int"),
    ("Random", "float", "rt.Random_float"),
    ("Random", "choice", "rt.Random_choice"),
    ("Random", "choiceMaybe", "rt.Random_choiceMaybe"),
    ("Random", "shuffle", "rt.Random_shuffle"),
    ("Random", "weighted", "rt.Random_weighted"),
    ("Random", "seededInt", "rt.Random_seededInt"),
    ("Random", "seededFloat", "rt.Random_seededFloat"),
    ("Random", "seededChoice", "rt.Random_seededChoice"),
    ("Process", "run", "rt.Process_run"),
    ("File", "readFile", "rt.File_readFile"),
    ("File", "readFileLimit", "rt.File_readFileLimit"),
    ("File", "readFileBytes", "rt.File_readFileBytes"),
    ("File", "writeFile", "rt.File_writeFile"),
    ("File", "append", "rt.File_append"),
    ("File", "exists", "rt.File_exists"),
    ("File", "remove", "rt.File_remove"),
    ("File", "mkdirAll", "rt.File_mkdirAll"),
    ("File", "readDir", "rt.File_readDir"),
    ("File", "isDir", "rt.File_isDir"),
    ("File", "tempFile", "rt.File_tempFile"),
    ("File", "tempDir", "rt.File_tempDir"),
    ("File", "copy", "rt.File_copy"),
    ("File", "rename", "rt.File_rename"),
    ("Io", "readLine", "rt.Io_readLine"),
    ("Io", "writeStdout", "rt.Io_writeStdout"),
    ("Io", "writeStderr", "rt.Io_writeStderr"),
    ("Crypto", "sha256", "rt.Crypto_sha256"),
    ("Crypto", "sha512", "rt.Crypto_sha512"),
    ("Crypto", "md5", "rt.Crypto_md5"),
    ("Crypto", "hmacSha256", "rt.Crypto_hmacSha256"),
    ("Crypto", "hmacSha512", "rt.Crypto_hmacSha512"),
    ("Crypto", "sha1", "rt.Crypto_sha1"),
    ("Crypto", "rsaSha256Sign", "rt.Crypto_rsaSha256Sign"),
    ("Crypto", "rsaSha256Verify", "rt.Crypto_rsaSha256Verify"),
    ("Crypto", "constantTimeEqual", "rt.Crypto_constantTimeEqual"),
    ("Crypto", "randomBytes", "rt.Crypto_randomBytes"),
    ("Crypto", "randomToken", "rt.Crypto_randomToken"),
    ("Crypto", "aesGcmEncrypt", "rt.Crypto_aesGcmEncrypt"),
    ("Crypto", "aesGcmDecrypt", "rt.Crypto_aesGcmDecrypt"),
    ("Crypto", "chacha20Encrypt", "rt.Crypto_chacha20Encrypt"),
    ("Crypto", "chacha20Decrypt", "rt.Crypto_chacha20Decrypt"),
    ("Crypto", "aesKeyFromPassword", "rt.Crypto_aesKeyFromPassword"),
    ("Crypto", "chachaKeyFromPassword", "rt.Crypto_chachaKeyFromPassword"),
    ("Bytes", "toString", "rt.Bytes_toString"),
    ("Bytes", "fromHex", "rt.Bytes_fromHex"),
    ("Bytes", "toHex", "rt.Bytes_toHex"),
    ("Bytes", "fromBase64", "rt.Bytes_fromBase64"),
    ("Bytes", "toBase64", "rt.Bytes_toBase64"),
    ("Encoding", "base64Encode", "rt.Encoding_base64Encode"),
    ("Encoding", "base64Decode", "rt.Encoding_base64Decode"),
    ("Encoding", "urlEncode", "rt.Encoding_urlEncode"),
    ("Encoding", "urlDecode", "rt.Encoding_urlDecode"),
    ("Encoding", "hexEncode", "rt.Encoding_hexEncode"),
    ("Encoding", "hexDecode", "rt.Encoding_hexDecode"),
    ("Regex", "match", "rt.Regex_match"),
    ("Regex", "find", "rt.Regex_find"),
    ("Regex", "findAll", "rt.Regex_findAll"),
    ("Regex", "replace", "rt.Regex_replace"),
    ("Regex", "split", "rt.Regex_split"),
    ("Char", "isUpper", "rt.Char_isUpper"),
    ("Char", "isLower", "rt.Char_isLower"),
    ("Char", "isDigit", "rt.Char_isDigit"),
    ("Char", "isAlpha", "rt.Char_isAlpha"),
    ("Char", "toUpper", "rt.Char_toUpper"),
    ("Char", "toLower", "rt.Char_toLower"),
    ("Char", "toCode", "rt.Char_toCode"),
    ("Char", "fromCode", "rt.Char_fromCode"),
    ("Math", "sqrt", "rt.Math_sqrt"),
    ("Math", "pow", "rt.Math_pow"),
    ("Math", "floor", "rt.Math_floor"),
    ("Math", "ceil", "rt.Math_ceil"),
    ("Math", "round", "rt.Math_round"),
    ("Math", "sin", "rt.Math_sin"),
    ("Math", "cos", "rt.Math_cos"),
    ("Math", "tan", "rt.Math_tan"),
    ("Math", "pi", "rt.Math_piT"),
    ("Math", "e", "rt.Math_eT"),
    ("Math", "log", "rt.Math_log"),
    ("Math", "abs", "rt.Math_abs"),
    ("Math", "min", "rt.Math_min"),
    ("Math", "max", "rt.Math_max"),
    ("Math", "asin", "rt.Math_asin"),
    ("Math", "acos", "rt.Math_acos"),
    ("Math", "atan", "rt.Math_atan"),
    ("Math", "atan2", "rt.Math_atan2"),
    ("Math", "sinh", "rt.Math_sinh"),
    ("Math", "cosh", "rt.Math_cosh"),
    ("Math", "tanh", "rt.Math_tanh"),
    ("Math", "asinh", "rt.Math_asinh"),
    ("Math", "acosh", "rt.Math_acosh"),
    ("Math", "atanh", "rt.Math_atanh"),
    ("Math", "exp", "rt.Math_exp"),
    ("Math", "exp2", "rt.Math_exp2"),
    ("Math", "log2", "rt.Math_log2"),
    ("Math", "log10", "rt.Math_log10"),
    ("Math", "cbrt", "rt.Math_cbrt"),
    ("Math", "hypot", "rt.Math_hypot"),
    ("Math", "trunc", "rt.Math_trunc"),
    ("Math", "mod", "rt.Math_mod"),
    ("Math", "remainder", "rt.Math_remainder"),
    ("Math", "phi", "rt.Math_phiT"),
    ("Math", "sqrt2", "rt.Math_sqrt2T"),
    ("Math", "inf", "rt.Math_infT"),
    ("Math", "nan", "rt.Math_nanT"),
    ("Math", "isNaN", "rt.Math_isNaN"),
    ("Server", "listen", "rt.Server_listen"),
    ("Server", "get", "rt.Server_get"),
    ("Server", "post", "rt.Server_post"),
    ("Server", "put", "rt.Server_put"),
    ("Server", "delete", "rt.Server_delete"),
    ("Server", "text", "rt.Server_text"),
    ("Server", "json", "rt.Server_json"),
    ("Server", "html", "rt.Server_html"),
    ("Server", "withStatus", "rt.Server_withStatus"),
    ("Server", "redirect", "rt.Server_redirect"),
    ("Server", "param", "rt.Server_param"),
    ("Server", "queryParam", "rt.Server_queryParam"),
    ("Server", "header", "rt.Server_header"),
    ("Server", "static", "rt.Server_static"),
    ("Server", "getCookie", "rt.Server_getCookie"),
    ("Server", "cookie", "rt.Server_cookie"),
    ("Server", "withCookie", "rt.Server_withCookie"),
    ("Server", "withHeader", "rt.Server_withHeader"),
    ("Server", "any", "rt.Server_any"),
    ("Server", "csrfIssue", "rt.Server_csrfIssue"),
    ("Server", "csrfVerify", "rt.Server_csrfVerify"),
    ("Server", "api", "rt.Server_api"),
    ("List", "isEmpty", "rt.List_isEmpty"),
    ("Io", "writeString", "rt.Io_writeString"),
    ("Http", "get", "rt.Http_get"),
    ("Http", "post", "rt.Http_post"),
    ("Http", "request", "rt.Http_request"),
    ("Http", "parseQuery", "rt.Http_parseQuery"),
    ("Path", "join", "rt.Path_join"),
    ("Path", "dir", "rt.Path_dir"),
    ("Path", "base", "rt.Path_base"),
    ("Path", "ext", "rt.Path_ext"),
    ("Path", "isAbsolute", "rt.Path_isAbsolute"),
    ("Path", "safeJoin", "rt.Path_safeJoin"),
    ("Debug", "log", "rt.Debug_log"),
    ("Debug", "toString", "rt.Debug_toString"),
    ("Log", "println", "rt.Log_println"),
    ("Log", "debug", "rt.Log_debug"),
    ("Log", "info", "rt.Log_info"),
    ("Log", "warn", "rt.Log_warn"),
    ("Log", "error", "rt.Log_error"),
    ("Log", "debugWith", "rt.Log_debugWith"),
    ("Log", "infoWith", "rt.Log_infoWith"),
    ("Log", "warnWith", "rt.Log_warnWith"),
    ("Log", "errorWith", "rt.Log_errorWith"),
    ("Log", "with", "rt.Log_with"),
    ("Context", "background", "rt.Context_background"),
    ("Context", "todo", "rt.Context_todo"),
    ("Context", "withValue", "rt.Context_withValue"),
    ("Context", "withCancel", "rt.Context_withCancel"),
    ("Fmt", "sprint", "rt.Fmt_sprint"),
    ("Fmt", "sprintf", "rt.Fmt_sprintf"),
    ("Fmt", "sprintln", "rt.Fmt_sprintln"),
    ("Fmt", "errorf", "rt.Fmt_errorf"),
    ("Basics", "errorToString", "rt.Basics_errorToString"),
    ("Basics", "js", "rt.Basics_js"),
    ("System", "args", "rt.System_args"),
    ("System", "getArg", "rt.System_getArg"),
    ("System", "getenv", "rt.System_getenv"),
    ("System", "getenvOr", "rt.System_getenvOr"),
    ("System", "getenvInt", "rt.System_getenvInt"),
    ("System", "getenvBool", "rt.System_getenvBool"),
    ("System", "cwd", "rt.System_cwd"),
    ("System", "getcwd", "rt.System_getcwd"),
    ("System", "exit", "rt.System_exit"),
    ("System", "loadEnv", "rt.System_loadEnv"),
    ("System", "setenv", "rt.System_setenv"),
    ("System", "unsetenv", "rt.System_unsetenv"),
    ("Time", "timeString", "rt.Time_timeString"),
    ("String", "toBytes", "rt.String_toBytes"),
    ("String", "fromBytes", "rt.String_fromBytes"),
    ("String", "fromChar", "rt.String_fromChar"),
    ("String", "toChar", "rt.String_toChar"),
    ("Basics", "modBy", "rt.Basics_modBy"),
    ("Basics", "fst", "rt.Basics_fst"),
    ("Basics", "snd", "rt.Basics_snd"),
    ("List", "cons", "rt.List_cons"),
    ("Sub", "none", "rt.Sub_none"),
    ("Sub", "every", "rt.Sub_every"),
    ("Sub", "batch", "rt.Sub_batch"),
    ("Sub", "subscribeTopic", "rt.Sub_subscribeTopic"),
    ("Sub", "subscribeStream", "rt.Sub_subscribeStream"),
    ("HttpStream", "open", "rt.HttpStream_open"),
    ("HttpStream", "close", "rt.HttpStream_close"),
    ("HttpStream", "forEachChunk", "rt.HttpStream_forEachChunk"),
    ("ServerStream", "stream", "rt.ServerStream_stream"),
    ("ServerStream", "emit", "rt.ServerStream_emit"),
    ("ServerStream", "finish", "rt.ServerStream_finish"),
    ("ServerStream", "withContentType", "rt.ServerStream_withContentType"),
    ("WebSocket", "connect", "rt.WebSocket_connect"),
    ("WebSocket", "connectWith", "rt.WebSocket_connectWith"),
    ("WebSocket", "send", "rt.WebSocket_send"),
    ("WebSocket", "sendBinary", "rt.WebSocket_sendBinary"),
    ("WebSocket", "close", "rt.WebSocket_close"),
    ("WebSocket", "closeWithCode", "rt.WebSocket_closeWithCode"),
    ("Sub", "subscribeWebSocket", "rt.Sub_subscribeWebSocket"),
    ("ServerWebSocket", "upgrade", "rt.ServerWebSocket_upgrade"),
    ("ServerWebSocket", "sendToClient", "rt.ServerWebSocket_sendToClient"),
    ("ServerWebSocket", "sendBinaryToClient", "rt.ServerWebSocket_sendBinaryToClient"),
    ("ServerWebSocket", "broadcast", "rt.ServerWebSocket_broadcast"),
    ("ServerWebSocket", "closeClient", "rt.ServerWebSocket_closeClient"),
    ("PubSub", "publish", "rt.PubSub_publish"),
    ("PubSub", "publishNoEcho", "rt.PubSub_publishNoEcho"),
    ("Set", "empty", "rt.Set_empty"),
    ("Set", "fromList", "rt.Set_fromList"),
    ("Set", "insert", "rt.Set_insert"),
    ("Set", "remove", "rt.Set_remove"),
    ("Set", "member", "rt.Set_member"),
    ("Set", "toList", "rt.Set_toList"),
    ("Set", "size", "rt.Set_size"),
    ("Set", "union", "rt.Set_union"),
    ("Set", "intersect", "rt.Set_intersect"),
    ("Set", "diff", "rt.Set_diff"),
    ("JsonEnc", "string", "rt.JsonEnc_string"),
    ("JsonEnc", "int", "rt.JsonEnc_int"),
    ("JsonEnc", "float", "rt.JsonEnc_float"),
    ("JsonEnc", "bool", "rt.JsonEnc_bool"),
    ("JsonEnc", "null", "rt.JsonEnc_null"),
    ("JsonEnc", "list", "rt.JsonEnc_list"),
    ("JsonEnc", "object", "rt.JsonEnc_object"),
    ("JsonEnc", "encode", "rt.JsonEnc_encode"),
    ("JsonDec", "decodeString", "rt.JsonDec_decodeString"),
    ("JsonDec", "string", "rt.JsonDec_string"),
    ("JsonDec", "int", "rt.JsonDec_int"),
    ("JsonDec", "float", "rt.JsonDec_float"),
    ("JsonDec", "bool", "rt.JsonDec_bool"),
    ("JsonDec", "field", "rt.JsonDec_field"),
    ("JsonDec", "index", "rt.JsonDec_index"),
    ("JsonDec", "list", "rt.JsonDec_list"),
    ("JsonDec", "map", "rt.JsonDec_map"),
    ("JsonDec", "andThen", "rt.JsonDec_andThen"),
    ("JsonDec", "succeed", "rt.JsonDec_succeed"),
    ("JsonDec", "fail", "rt.JsonDec_fail"),
    ("JsonDec", "oneOf", "rt.JsonDec_oneOf"),
    ("JsonDec", "at", "rt.JsonDec_at"),
    ("JsonDec", "map2", "rt.JsonDec_map2"),
    ("JsonDec", "map3", "rt.JsonDec_map3"),
    ("JsonDec", "map4", "rt.JsonDec_map4"),
    ("JsonDec", "map5", "rt.JsonDec_map5"),
    ("Db", "connect", "rt.Db_connect"),
    ("Db", "open", "rt.Db_open"),
    ("Db", "close", "rt.Db_close"),
    ("Db", "exec", "rt.Db_exec"),
    ("Db", "migrateApply", "rt.Db_migrateApply"),
    ("Db", "execRaw", "rt.Db_execRaw"),
    ("Db", "updateFields", "rt.Db_updateFields"),
    ("Db", "insertFields", "rt.Db_insertFields"),
    ("Db", "insertFieldsReturning", "rt.Db_insertFieldsReturning"),
    ("Db", "getField", "rt.Db_getField"),
    ("Db", "getFieldOr", "rt.Db_getFieldOr"),
    ("Db", "getString", "rt.Db_getString"),
    ("Db", "getInt", "rt.Db_getInt"),
    ("Db", "getBool", "rt.Db_getBool"),
    ("Db", "query", "rt.Db_query"),
    ("Db", "queryDecode", "rt.Db_queryDecode"),
    ("Db", "getByIdDecode", "rt.Db_getByIdDecode"),
    ("Db", "insertRow", "rt.Db_insertRow"),
    ("Db", "getById", "rt.Db_getById"),
    ("Db", "updateById", "rt.Db_updateById"),
    ("Db", "deleteById", "rt.Db_deleteById"),
    ("Db", "findWhere", "rt.Db_findWhere"),
    ("Db", "findOneByField", "rt.Db_findOneByField"),
    ("Db", "findManyByField", "rt.Db_findManyByField"),
    ("Db", "findByConditions", "rt.Db_findByConditions"),
    ("Db", "unsafeFindWhere", "rt.Db_unsafeFindWhere"),
    ("Db", "withTransaction", "rt.Db_withTransaction"),
    ("Auth", "hashPassword", "rt.Auth_hashPassword"),
    ("Auth", "verifyPassword", "rt.Auth_verifyPassword"),
    ("Auth", "signToken", "rt.Auth_signToken"),
    ("Auth", "verifyToken", "rt.Auth_verifyToken"),
    ("Auth", "register", "rt.Auth_register"),
    ("Auth", "login", "rt.Auth_login"),
    ("Auth", "setRole", "rt.Auth_setRole"),
    ("Auth", "hashPasswordCost", "rt.Auth_hashPasswordCost"),
    ("Auth", "passwordStrength", "rt.Auth_passwordStrength"),
    ("JsonDecP", "required", "rt.JsonDecP_required"),
    ("JsonDecP", "optional", "rt.JsonDecP_optional"),
    ("JsonDecP", "custom", "rt.JsonDecP_custom"),
    ("JsonDecP", "requiredAt", "rt.JsonDecP_requiredAt"),
    ("DbDec", "string", "rt.DbDec_string"),
    ("DbDec", "int", "rt.DbDec_int"),
    ("DbDec", "float", "rt.DbDec_float"),
    ("DbDec", "bool", "rt.DbDec_bool"),
    ("DbDec", "money", "rt.DbDec_money"),
    ("DbDec", "nullable", "rt.DbDec_nullable"),
    ("DbDec", "succeed", "rt.DbDec_succeed"),
    ("DbDec", "fail", "rt.DbDec_fail"),
    ("DbDec", "map", "rt.DbDec_map"),
    ("DbDec", "andThen", "rt.DbDec_andThen"),
    ("DbDec", "andMap", "rt.DbDec_andMap"),
    ("DbDec", "map2", "rt.DbDec_map2"),
    ("DbDec", "map3", "rt.DbDec_map3"),
    ("DbDec", "map4", "rt.DbDec_map4"),
    ("DbDec", "map5", "rt.DbDec_map5"),
    ("DbDec", "required", "rt.DbDec_required"),
    ("DbDec", "optional", "rt.DbDec_optional"),
    ("Lazy", "lazy", "rt.Std_Ui_Lazy_lazy"),
    ("Lazy", "lazy2", "rt.Std_Ui_Lazy_lazy2"),
    ("Lazy", "lazy3", "rt.Std_Ui_Lazy_lazy3"),
    ("Lazy", "lazy4", "rt.Std_Ui_Lazy_lazy4"),
    ("Lazy", "lazy5", "rt.Std_Ui_Lazy_lazy5"),
    ("Compression", "gzip", "rt.Compression_gzip"),
    ("Compression", "gunzip", "rt.Compression_gunzip"),
    ("Compression", "zstdCompress", "rt.Compression_zstdCompress"),
    ("Compression", "zstdDecompress", "rt.Compression_zstdDecompress"),
    ("Csv", "parse", "rt.Csv_parse"),
    ("Csv", "parseWithDelimiter", "rt.Csv_parseWithDelimiter"),
    ("Csv", "encode", "rt.Csv_encode"),
    ("Csv", "encodeWithDelimiter", "rt.Csv_encodeWithDelimiter"),
    ("Csv", "parseStreamFromFile", "rt.Csv_parseStreamFromFile"),
    ("Cache", "newRaw", "rt.Cache_new"),
    ("Cache", "get", "rt.Cache_get"),
    ("Cache", "put", "rt.Cache_put"),
    ("Cache", "remove", "rt.Cache_remove"),
    ("Cache", "clear", "rt.Cache_clear"),
    ("Cache", "size", "rt.Cache_size"),
    ("Cache", "stats", "rt.Cache_stats"),
    ("Email", "send", "rt.Email_send"),
    ("Config", "string", "rt.Config_string"),
    ("Config", "int", "rt.Config_int"),
    ("Config", "float", "rt.Config_float"),
    ("Config", "bool", "rt.Config_bool"),
    ("Config", "nullable", "rt.Config_nullable"),
    ("Config", "field", "rt.Config_field"),
    ("Config", "at", "rt.Config_at"),
    ("Config", "list", "rt.Config_list"),
    ("Config", "succeed", "rt.Config_succeed"),
    ("Config", "fail", "rt.Config_fail"),
    ("Config", "map", "rt.Config_map"),
    ("Config", "andThen", "rt.Config_andThen"),
    ("Config", "decodeToml", "rt.Config_decodeToml"),
    ("Config", "decodeYaml", "rt.Config_decodeYaml"),
    ("Config", "decodeJson", "rt.Config_decodeJson"),
    ("Config", "loadFromFile", "rt.Config_loadFromFile"),
    ("Hub", "readOverview", "rt.Hub_readOverview"),
    ("Hub", "readLogs", "rt.Hub_readLogs"),
    ("Hub", "readMetrics", "rt.Hub_readMetrics"),
    ("Hub", "readTraces", "rt.Hub_readTraces"),
    ("Hub", "readErrors", "rt.Hub_readErrors"),
    ("Hub", "listServices", "rt.Hub_listServices"),
    ("Hub", "readServiceStats", "rt.Hub_readServiceStats"),
    ("Hub", "readFilteredLogs", "rt.Hub_readFilteredLogs"),
    ("Hub", "readFilteredMetrics", "rt.Hub_readFilteredMetrics"),
    ("Hub", "readFilteredTraces", "rt.Hub_readFilteredTraces"),
    ("Hub", "readFilteredErrors", "rt.Hub_readFilteredErrors"),
    ("Hub", "currentIdentity", "rt.Hub_currentIdentity"),
];
