// Code generated by sky-ffi-inspect from github.com/stripe/stripe-go/v84/customer. DO NOT EDIT.
// Re-run `sky add github.com/stripe/stripe-go/v84/customer` to regenerate.
//
// Wrapper functions are in `package rt` with names <Kernel>_<lowerFn>.
// Sky source resolves `import Github.Com.Stripe.StripeGo.V84.Customer as X` and calls `X.<lowerFn>` — the canonicaliser routes it via
// the FFI registry to these typed Go functions. Every wrapper wraps
// panics in Err[any, any] via SkyFfiRecover.

package rt

import (
	pkg "github.com/stripe/stripe-go/v84/customer"
	"fmt"
	stripe_go "github.com/stripe/stripe-go/v84"
)

// [fallible] Go_Customer.clientNew → pkg.ClientNew
func Go_Customer_clientNew(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	r0, err := p0.(pkg.Client).New(p1.(*stripe_go.CustomerParams))
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](r0)

	return
}
type FfiT_Go_Customer_clientNew_P0 = pkg.Client
type FfiT_Go_Customer_clientNew_P1 = *stripe_go.CustomerParams
type FfiT_Go_Customer_clientNew_R = *stripe_go.Customer
// [fallible] typed wrapper for Go_Customer_clientNew (P7 adaptor target)
func Go_Customer_clientNewT(p0 pkg.Client, p1 *stripe_go.CustomerParams) (out SkyResult[string, *stripe_go.Customer]) {
	defer SkyFfiRecoverT(&out)()
	r0, err := p0.New(p1)
	if err != nil { out = Err[string, *stripe_go.Customer](err.Error()); return }
	out = Ok[string, *stripe_go.Customer](r0)
	return
}

// [fallible] Go_Customer.clientGet → pkg.ClientGet
func Go_Customer_clientGet(p0 any, p1 any, p2 any) (out any) {
	defer SkyFfiRecover(&out)()
	r0, err := p0.(pkg.Client).Get(fmt.Sprintf("%v", p1), p2.(*stripe_go.CustomerParams))
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](r0)

	return
}
type FfiT_Go_Customer_clientGet_P0 = pkg.Client
type FfiT_Go_Customer_clientGet_P2 = *stripe_go.CustomerParams
type FfiT_Go_Customer_clientGet_R = *stripe_go.Customer
// [fallible] typed wrapper for Go_Customer_clientGet (P7 adaptor target)
func Go_Customer_clientGetT(p0 pkg.Client, p1 string, p2 *stripe_go.CustomerParams) (out SkyResult[string, *stripe_go.Customer]) {
	defer SkyFfiRecoverT(&out)()
	r0, err := p0.Get(p1, p2)
	if err != nil { out = Err[string, *stripe_go.Customer](err.Error()); return }
	out = Ok[string, *stripe_go.Customer](r0)
	return
}

// [fallible] Go_Customer.clientUpdate → pkg.ClientUpdate
func Go_Customer_clientUpdate(p0 any, p1 any, p2 any) (out any) {
	defer SkyFfiRecover(&out)()
	r0, err := p0.(pkg.Client).Update(fmt.Sprintf("%v", p1), p2.(*stripe_go.CustomerParams))
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](r0)

	return
}
type FfiT_Go_Customer_clientUpdate_P0 = pkg.Client
type FfiT_Go_Customer_clientUpdate_P2 = *stripe_go.CustomerParams
type FfiT_Go_Customer_clientUpdate_R = *stripe_go.Customer
// [fallible] typed wrapper for Go_Customer_clientUpdate (P7 adaptor target)
func Go_Customer_clientUpdateT(p0 pkg.Client, p1 string, p2 *stripe_go.CustomerParams) (out SkyResult[string, *stripe_go.Customer]) {
	defer SkyFfiRecoverT(&out)()
	r0, err := p0.Update(p1, p2)
	if err != nil { out = Err[string, *stripe_go.Customer](err.Error()); return }
	out = Ok[string, *stripe_go.Customer](r0)
	return
}

// [fallible] Go_Customer.clientDel → pkg.ClientDel
func Go_Customer_clientDel(p0 any, p1 any, p2 any) (out any) {
	defer SkyFfiRecover(&out)()
	r0, err := p0.(pkg.Client).Del(fmt.Sprintf("%v", p1), p2.(*stripe_go.CustomerParams))
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](r0)

	return
}
type FfiT_Go_Customer_clientDel_P0 = pkg.Client
type FfiT_Go_Customer_clientDel_P2 = *stripe_go.CustomerParams
type FfiT_Go_Customer_clientDel_R = *stripe_go.Customer
// [fallible] typed wrapper for Go_Customer_clientDel (P7 adaptor target)
func Go_Customer_clientDelT(p0 pkg.Client, p1 string, p2 *stripe_go.CustomerParams) (out SkyResult[string, *stripe_go.Customer]) {
	defer SkyFfiRecoverT(&out)()
	r0, err := p0.Del(p1, p2)
	if err != nil { out = Err[string, *stripe_go.Customer](err.Error()); return }
	out = Ok[string, *stripe_go.Customer](r0)
	return
}

// [fallible] Go_Customer.clientCreateFundingInstructions → pkg.ClientCreateFundingInstructions
func Go_Customer_clientCreateFundingInstructions(p0 any, p1 any, p2 any) (out any) {
	defer SkyFfiRecover(&out)()
	r0, err := p0.(pkg.Client).CreateFundingInstructions(fmt.Sprintf("%v", p1), p2.(*stripe_go.CustomerCreateFundingInstructionsParams))
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](r0)

	return
}
type FfiT_Go_Customer_clientCreateFundingInstructions_P0 = pkg.Client
type FfiT_Go_Customer_clientCreateFundingInstructions_P2 = *stripe_go.CustomerCreateFundingInstructionsParams
type FfiT_Go_Customer_clientCreateFundingInstructions_R = *stripe_go.FundingInstructions
// [fallible] typed wrapper for Go_Customer_clientCreateFundingInstructions (P7 adaptor target)
func Go_Customer_clientCreateFundingInstructionsT(p0 pkg.Client, p1 string, p2 *stripe_go.CustomerCreateFundingInstructionsParams) (out SkyResult[string, *stripe_go.FundingInstructions]) {
	defer SkyFfiRecoverT(&out)()
	r0, err := p0.CreateFundingInstructions(p1, p2)
	if err != nil { out = Err[string, *stripe_go.FundingInstructions](err.Error()); return }
	out = Ok[string, *stripe_go.FundingInstructions](r0)
	return
}

// [fallible] Go_Customer.clientDeleteDiscount → pkg.ClientDeleteDiscount
func Go_Customer_clientDeleteDiscount(p0 any, p1 any, p2 any) (out any) {
	defer SkyFfiRecover(&out)()
	r0, err := p0.(pkg.Client).DeleteDiscount(fmt.Sprintf("%v", p1), p2.(*stripe_go.CustomerDeleteDiscountParams))
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](r0)

	return
}
type FfiT_Go_Customer_clientDeleteDiscount_P0 = pkg.Client
type FfiT_Go_Customer_clientDeleteDiscount_P2 = *stripe_go.CustomerDeleteDiscountParams
type FfiT_Go_Customer_clientDeleteDiscount_R = *stripe_go.Customer
// [fallible] typed wrapper for Go_Customer_clientDeleteDiscount (P7 adaptor target)
func Go_Customer_clientDeleteDiscountT(p0 pkg.Client, p1 string, p2 *stripe_go.CustomerDeleteDiscountParams) (out SkyResult[string, *stripe_go.Customer]) {
	defer SkyFfiRecoverT(&out)()
	r0, err := p0.DeleteDiscount(p1, p2)
	if err != nil { out = Err[string, *stripe_go.Customer](err.Error()); return }
	out = Ok[string, *stripe_go.Customer](r0)
	return
}

// [fallible] Go_Customer.clientRetrievePaymentMethod → pkg.ClientRetrievePaymentMethod
func Go_Customer_clientRetrievePaymentMethod(p0 any, p1 any, p2 any) (out any) {
	defer SkyFfiRecover(&out)()
	r0, err := p0.(pkg.Client).RetrievePaymentMethod(fmt.Sprintf("%v", p1), p2.(*stripe_go.CustomerRetrievePaymentMethodParams))
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](r0)

	return
}
type FfiT_Go_Customer_clientRetrievePaymentMethod_P0 = pkg.Client
type FfiT_Go_Customer_clientRetrievePaymentMethod_P2 = *stripe_go.CustomerRetrievePaymentMethodParams
type FfiT_Go_Customer_clientRetrievePaymentMethod_R = *stripe_go.PaymentMethod
// [fallible] typed wrapper for Go_Customer_clientRetrievePaymentMethod (P7 adaptor target)
func Go_Customer_clientRetrievePaymentMethodT(p0 pkg.Client, p1 string, p2 *stripe_go.CustomerRetrievePaymentMethodParams) (out SkyResult[string, *stripe_go.PaymentMethod]) {
	defer SkyFfiRecoverT(&out)()
	r0, err := p0.RetrievePaymentMethod(p1, p2)
	if err != nil { out = Err[string, *stripe_go.PaymentMethod](err.Error()); return }
	out = Ok[string, *stripe_go.PaymentMethod](r0)
	return
}

// [pure] Go_Customer.clientList → pkg.ClientList
func Go_Customer_clientList(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(pkg.Client).List(p1.(*stripe_go.CustomerListParams)))
	return
}
type FfiT_Go_Customer_clientList_P0 = pkg.Client
type FfiT_Go_Customer_clientList_P1 = *stripe_go.CustomerListParams
type FfiT_Go_Customer_clientList_R = *pkg.Iter
// [pure] typed wrapper for Go_Customer_clientList (P7 adaptor target)
func Go_Customer_clientListT(p0 pkg.Client, p1 *stripe_go.CustomerListParams) (out SkyResult[string, *pkg.Iter]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[string, *pkg.Iter](p0.List(p1))
	return
}

// [pure] Go_Customer.clientListPaymentMethods → pkg.ClientListPaymentMethods
func Go_Customer_clientListPaymentMethods(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(pkg.Client).ListPaymentMethods(p1.(*stripe_go.CustomerListPaymentMethodsParams)))
	return
}
type FfiT_Go_Customer_clientListPaymentMethods_P0 = pkg.Client
type FfiT_Go_Customer_clientListPaymentMethods_P1 = *stripe_go.CustomerListPaymentMethodsParams
type FfiT_Go_Customer_clientListPaymentMethods_R = *pkg.PaymentMethodIter
// [pure] typed wrapper for Go_Customer_clientListPaymentMethods (P7 adaptor target)
func Go_Customer_clientListPaymentMethodsT(p0 pkg.Client, p1 *stripe_go.CustomerListPaymentMethodsParams) (out SkyResult[string, *pkg.PaymentMethodIter]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[string, *pkg.PaymentMethodIter](p0.ListPaymentMethods(p1))
	return
}

// [pure] Go_Customer.clientSearch → pkg.ClientSearch
func Go_Customer_clientSearch(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(pkg.Client).Search(p1.(*stripe_go.CustomerSearchParams)))
	return
}
type FfiT_Go_Customer_clientSearch_P0 = pkg.Client
type FfiT_Go_Customer_clientSearch_P1 = *stripe_go.CustomerSearchParams
type FfiT_Go_Customer_clientSearch_R = *pkg.SearchIter
// [pure] typed wrapper for Go_Customer_clientSearch (P7 adaptor target)
func Go_Customer_clientSearchT(p0 pkg.Client, p1 *stripe_go.CustomerSearchParams) (out SkyResult[string, *pkg.SearchIter]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[string, *pkg.SearchIter](p0.Search(p1))
	return
}

func Go_Customer_clientB(p0 any) any { return SkyFfiFieldGet(p0, "B") }

func Go_Customer_clientSetB(value any, recv any) any { return SkyFfiFieldSet(value, recv, "B") }

func Go_Customer_clientKey(p0 any) any { return SkyFfiFieldGet(p0, "Key") }

func Go_Customer_clientSetKey(value any, recv any) any { return SkyFfiFieldSet(value, recv, "Key") }

func Go_Customer_newClient(_ any) any { return new(pkg.Client) }

// [fallible] Go_Customer.createFundingInstructions → pkg.CreateFundingInstructions
func Go_Customer_createFundingInstructions(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	r0, err := pkg.CreateFundingInstructions(fmt.Sprintf("%v", p0), p1.(*stripe_go.CustomerCreateFundingInstructionsParams))
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](r0)

	return
}
type FfiT_Go_Customer_createFundingInstructions_P1 = *stripe_go.CustomerCreateFundingInstructionsParams
type FfiT_Go_Customer_createFundingInstructions_R = *stripe_go.FundingInstructions
// [fallible] typed wrapper for Go_Customer_createFundingInstructions (P7 adaptor target)
func Go_Customer_createFundingInstructionsT(p0 string, p1 *stripe_go.CustomerCreateFundingInstructionsParams) (out SkyResult[string, *stripe_go.FundingInstructions]) {
	defer SkyFfiRecoverT(&out)()
	r0, err := pkg.CreateFundingInstructions(p0, p1)
	if err != nil { out = Err[string, *stripe_go.FundingInstructions](err.Error()); return }
	out = Ok[string, *stripe_go.FundingInstructions](r0)
	return
}

// [fallible] Go_Customer.del → pkg.Del
func Go_Customer_del(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	r0, err := pkg.Del(fmt.Sprintf("%v", p0), p1.(*stripe_go.CustomerParams))
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](r0)

	return
}
type FfiT_Go_Customer_del_P1 = *stripe_go.CustomerParams
type FfiT_Go_Customer_del_R = *stripe_go.Customer
// [fallible] typed wrapper for Go_Customer_del (P7 adaptor target)
func Go_Customer_delT(p0 string, p1 *stripe_go.CustomerParams) (out SkyResult[string, *stripe_go.Customer]) {
	defer SkyFfiRecoverT(&out)()
	r0, err := pkg.Del(p0, p1)
	if err != nil { out = Err[string, *stripe_go.Customer](err.Error()); return }
	out = Ok[string, *stripe_go.Customer](r0)
	return
}

// [fallible] Go_Customer.deleteDiscount → pkg.DeleteDiscount
func Go_Customer_deleteDiscount(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	r0, err := pkg.DeleteDiscount(fmt.Sprintf("%v", p0), p1.(*stripe_go.CustomerDeleteDiscountParams))
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](r0)

	return
}
type FfiT_Go_Customer_deleteDiscount_P1 = *stripe_go.CustomerDeleteDiscountParams
type FfiT_Go_Customer_deleteDiscount_R = *stripe_go.Customer
// [fallible] typed wrapper for Go_Customer_deleteDiscount (P7 adaptor target)
func Go_Customer_deleteDiscountT(p0 string, p1 *stripe_go.CustomerDeleteDiscountParams) (out SkyResult[string, *stripe_go.Customer]) {
	defer SkyFfiRecoverT(&out)()
	r0, err := pkg.DeleteDiscount(p0, p1)
	if err != nil { out = Err[string, *stripe_go.Customer](err.Error()); return }
	out = Ok[string, *stripe_go.Customer](r0)
	return
}

// [fallible] Go_Customer.get → pkg.Get
func Go_Customer_get(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	r0, err := pkg.Get(fmt.Sprintf("%v", p0), p1.(*stripe_go.CustomerParams))
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](r0)

	return
}
type FfiT_Go_Customer_get_P1 = *stripe_go.CustomerParams
type FfiT_Go_Customer_get_R = *stripe_go.Customer
// [fallible] typed wrapper for Go_Customer_get (P7 adaptor target)
func Go_Customer_getT(p0 string, p1 *stripe_go.CustomerParams) (out SkyResult[string, *stripe_go.Customer]) {
	defer SkyFfiRecoverT(&out)()
	r0, err := pkg.Get(p0, p1)
	if err != nil { out = Err[string, *stripe_go.Customer](err.Error()); return }
	out = Ok[string, *stripe_go.Customer](r0)
	return
}

// [pure] Go_Customer.iterCustomer → pkg.IterCustomer
func Go_Customer_iterCustomer(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(*pkg.Iter).Customer())
	return
}
type FfiT_Go_Customer_iterCustomer_P0 = *pkg.Iter
type FfiT_Go_Customer_iterCustomer_R = *stripe_go.Customer
// [pure] typed wrapper for Go_Customer_iterCustomer (P7 adaptor target)
func Go_Customer_iterCustomerT(p0 *pkg.Iter) (out SkyResult[string, *stripe_go.Customer]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[string, *stripe_go.Customer](p0.Customer())
	return
}

// [pure] Go_Customer.iterCustomerList → pkg.IterCustomerList
func Go_Customer_iterCustomerList(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(*pkg.Iter).CustomerList())
	return
}
type FfiT_Go_Customer_iterCustomerList_P0 = *pkg.Iter
type FfiT_Go_Customer_iterCustomerList_R = *stripe_go.CustomerList
// [pure] typed wrapper for Go_Customer_iterCustomerList (P7 adaptor target)
func Go_Customer_iterCustomerListT(p0 *pkg.Iter) (out SkyResult[string, *stripe_go.CustomerList]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[string, *stripe_go.CustomerList](p0.CustomerList())
	return
}

// [pure] Go_Customer.iterCurrent → pkg.IterCurrent
func Go_Customer_iterCurrent(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(*pkg.Iter).Current())
	return
}

// [fallible] Go_Customer.iterErr → pkg.IterErr
func Go_Customer_iterErr(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	err := p0.(*pkg.Iter).Err()
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](struct{}{})

	return
}
type FfiT_Go_Customer_iterErr_P0 = *pkg.Iter
// [fallible] typed wrapper for Go_Customer_iterErr (P7 adaptor target)
func Go_Customer_iterErrT(p0 *pkg.Iter) (out SkyResult[string, struct{}]) {
	defer SkyFfiRecoverT(&out)()
	err := p0.Err()
	if err != nil { out = Err[string, struct{}](err.Error()); return }
	out = Ok[string, struct{}](struct{}{})
	return
}

// [pure] Go_Customer.iterList → pkg.IterList
func Go_Customer_iterList(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(*pkg.Iter).List())
	return
}
type FfiT_Go_Customer_iterList_P0 = *pkg.Iter
type FfiT_Go_Customer_iterList_R = stripe_go.ListContainer
// [pure] typed wrapper for Go_Customer_iterList (P7 adaptor target)
func Go_Customer_iterListT(p0 *pkg.Iter) (out SkyResult[string, stripe_go.ListContainer]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[string, stripe_go.ListContainer](p0.List())
	return
}

// [pure] Go_Customer.iterMeta → pkg.IterMeta
func Go_Customer_iterMeta(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(*pkg.Iter).Meta())
	return
}
type FfiT_Go_Customer_iterMeta_P0 = *pkg.Iter
type FfiT_Go_Customer_iterMeta_R = *stripe_go.ListMeta
// [pure] typed wrapper for Go_Customer_iterMeta (P7 adaptor target)
func Go_Customer_iterMetaT(p0 *pkg.Iter) (out SkyResult[string, *stripe_go.ListMeta]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[string, *stripe_go.ListMeta](p0.Meta())
	return
}

// [pure] Go_Customer.iterNext → pkg.IterNext
func Go_Customer_iterNext(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(*pkg.Iter).Next())
	return
}
type FfiT_Go_Customer_iterNext_P0 = *pkg.Iter
// [pure] typed wrapper for Go_Customer_iterNext (P7 adaptor target)
func Go_Customer_iterNextT(p0 *pkg.Iter) (out SkyResult[string, bool]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[string, bool](p0.Next())
	return
}

func Go_Customer_iterIter(p0 any) any { return SkyFfiFieldGet(p0, "Iter") }

func Go_Customer_iterSetIter(value any, recv any) any { return SkyFfiFieldSet(value, recv, "Iter") }

func Go_Customer_newIter(_ any) any { return new(pkg.Iter) }

// [pure] Go_Customer.list → pkg.List
func Go_Customer_list(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](pkg.List(p0.(*stripe_go.CustomerListParams)))
	return
}
type FfiT_Go_Customer_list_P0 = *stripe_go.CustomerListParams
type FfiT_Go_Customer_list_R = *pkg.Iter
// [pure] typed wrapper for Go_Customer_list (P7 adaptor target)
func Go_Customer_listT(p0 *stripe_go.CustomerListParams) (out SkyResult[string, *pkg.Iter]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[string, *pkg.Iter](pkg.List(p0))
	return
}

// [pure] Go_Customer.listPaymentMethods → pkg.ListPaymentMethods
func Go_Customer_listPaymentMethods(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](pkg.ListPaymentMethods(p0.(*stripe_go.CustomerListPaymentMethodsParams)))
	return
}
type FfiT_Go_Customer_listPaymentMethods_P0 = *stripe_go.CustomerListPaymentMethodsParams
type FfiT_Go_Customer_listPaymentMethods_R = *pkg.PaymentMethodIter
// [pure] typed wrapper for Go_Customer_listPaymentMethods (P7 adaptor target)
func Go_Customer_listPaymentMethodsT(p0 *stripe_go.CustomerListPaymentMethodsParams) (out SkyResult[string, *pkg.PaymentMethodIter]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[string, *pkg.PaymentMethodIter](pkg.ListPaymentMethods(p0))
	return
}

// [fallible] Go_Customer.new → pkg.New
func Go_Customer_new(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	r0, err := pkg.New(p0.(*stripe_go.CustomerParams))
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](r0)

	return
}
type FfiT_Go_Customer_new_P0 = *stripe_go.CustomerParams
type FfiT_Go_Customer_new_R = *stripe_go.Customer
// [fallible] typed wrapper for Go_Customer_new (P7 adaptor target)
func Go_Customer_newT(p0 *stripe_go.CustomerParams) (out SkyResult[string, *stripe_go.Customer]) {
	defer SkyFfiRecoverT(&out)()
	r0, err := pkg.New(p0)
	if err != nil { out = Err[string, *stripe_go.Customer](err.Error()); return }
	out = Ok[string, *stripe_go.Customer](r0)
	return
}

// [pure] Go_Customer.paymentMethodIterPaymentMethod → pkg.PaymentMethodIterPaymentMethod
func Go_Customer_paymentMethodIterPaymentMethod(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(*pkg.PaymentMethodIter).PaymentMethod())
	return
}
type FfiT_Go_Customer_paymentMethodIterPaymentMethod_P0 = *pkg.PaymentMethodIter
type FfiT_Go_Customer_paymentMethodIterPaymentMethod_R = *stripe_go.PaymentMethod
// [pure] typed wrapper for Go_Customer_paymentMethodIterPaymentMethod (P7 adaptor target)
func Go_Customer_paymentMethodIterPaymentMethodT(p0 *pkg.PaymentMethodIter) (out SkyResult[string, *stripe_go.PaymentMethod]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[string, *stripe_go.PaymentMethod](p0.PaymentMethod())
	return
}

// [pure] Go_Customer.paymentMethodIterPaymentMethodList → pkg.PaymentMethodIterPaymentMethodList
func Go_Customer_paymentMethodIterPaymentMethodList(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(*pkg.PaymentMethodIter).PaymentMethodList())
	return
}
type FfiT_Go_Customer_paymentMethodIterPaymentMethodList_P0 = *pkg.PaymentMethodIter
type FfiT_Go_Customer_paymentMethodIterPaymentMethodList_R = *stripe_go.PaymentMethodList
// [pure] typed wrapper for Go_Customer_paymentMethodIterPaymentMethodList (P7 adaptor target)
func Go_Customer_paymentMethodIterPaymentMethodListT(p0 *pkg.PaymentMethodIter) (out SkyResult[string, *stripe_go.PaymentMethodList]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[string, *stripe_go.PaymentMethodList](p0.PaymentMethodList())
	return
}

// [pure] Go_Customer.paymentMethodIterCurrent → pkg.PaymentMethodIterCurrent
func Go_Customer_paymentMethodIterCurrent(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(*pkg.PaymentMethodIter).Current())
	return
}

// [fallible] Go_Customer.paymentMethodIterErr → pkg.PaymentMethodIterErr
func Go_Customer_paymentMethodIterErr(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	err := p0.(*pkg.PaymentMethodIter).Err()
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](struct{}{})

	return
}
type FfiT_Go_Customer_paymentMethodIterErr_P0 = *pkg.PaymentMethodIter
// [fallible] typed wrapper for Go_Customer_paymentMethodIterErr (P7 adaptor target)
func Go_Customer_paymentMethodIterErrT(p0 *pkg.PaymentMethodIter) (out SkyResult[string, struct{}]) {
	defer SkyFfiRecoverT(&out)()
	err := p0.Err()
	if err != nil { out = Err[string, struct{}](err.Error()); return }
	out = Ok[string, struct{}](struct{}{})
	return
}

// [pure] Go_Customer.paymentMethodIterList → pkg.PaymentMethodIterList
func Go_Customer_paymentMethodIterList(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(*pkg.PaymentMethodIter).List())
	return
}
type FfiT_Go_Customer_paymentMethodIterList_P0 = *pkg.PaymentMethodIter
type FfiT_Go_Customer_paymentMethodIterList_R = stripe_go.ListContainer
// [pure] typed wrapper for Go_Customer_paymentMethodIterList (P7 adaptor target)
func Go_Customer_paymentMethodIterListT(p0 *pkg.PaymentMethodIter) (out SkyResult[string, stripe_go.ListContainer]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[string, stripe_go.ListContainer](p0.List())
	return
}

// [pure] Go_Customer.paymentMethodIterMeta → pkg.PaymentMethodIterMeta
func Go_Customer_paymentMethodIterMeta(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(*pkg.PaymentMethodIter).Meta())
	return
}
type FfiT_Go_Customer_paymentMethodIterMeta_P0 = *pkg.PaymentMethodIter
type FfiT_Go_Customer_paymentMethodIterMeta_R = *stripe_go.ListMeta
// [pure] typed wrapper for Go_Customer_paymentMethodIterMeta (P7 adaptor target)
func Go_Customer_paymentMethodIterMetaT(p0 *pkg.PaymentMethodIter) (out SkyResult[string, *stripe_go.ListMeta]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[string, *stripe_go.ListMeta](p0.Meta())
	return
}

// [pure] Go_Customer.paymentMethodIterNext → pkg.PaymentMethodIterNext
func Go_Customer_paymentMethodIterNext(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(*pkg.PaymentMethodIter).Next())
	return
}
type FfiT_Go_Customer_paymentMethodIterNext_P0 = *pkg.PaymentMethodIter
// [pure] typed wrapper for Go_Customer_paymentMethodIterNext (P7 adaptor target)
func Go_Customer_paymentMethodIterNextT(p0 *pkg.PaymentMethodIter) (out SkyResult[string, bool]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[string, bool](p0.Next())
	return
}

func Go_Customer_paymentMethodIterIter(p0 any) any { return SkyFfiFieldGet(p0, "Iter") }

func Go_Customer_paymentMethodIterSetIter(value any, recv any) any { return SkyFfiFieldSet(value, recv, "Iter") }

func Go_Customer_newPaymentMethodIter(_ any) any { return new(pkg.PaymentMethodIter) }

// [fallible] Go_Customer.retrievePaymentMethod → pkg.RetrievePaymentMethod
func Go_Customer_retrievePaymentMethod(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	r0, err := pkg.RetrievePaymentMethod(fmt.Sprintf("%v", p0), p1.(*stripe_go.CustomerRetrievePaymentMethodParams))
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](r0)

	return
}
type FfiT_Go_Customer_retrievePaymentMethod_P1 = *stripe_go.CustomerRetrievePaymentMethodParams
type FfiT_Go_Customer_retrievePaymentMethod_R = *stripe_go.PaymentMethod
// [fallible] typed wrapper for Go_Customer_retrievePaymentMethod (P7 adaptor target)
func Go_Customer_retrievePaymentMethodT(p0 string, p1 *stripe_go.CustomerRetrievePaymentMethodParams) (out SkyResult[string, *stripe_go.PaymentMethod]) {
	defer SkyFfiRecoverT(&out)()
	r0, err := pkg.RetrievePaymentMethod(p0, p1)
	if err != nil { out = Err[string, *stripe_go.PaymentMethod](err.Error()); return }
	out = Ok[string, *stripe_go.PaymentMethod](r0)
	return
}

// [pure] Go_Customer.search → pkg.Search
func Go_Customer_search(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](pkg.Search(p0.(*stripe_go.CustomerSearchParams)))
	return
}
type FfiT_Go_Customer_search_P0 = *stripe_go.CustomerSearchParams
type FfiT_Go_Customer_search_R = *pkg.SearchIter
// [pure] typed wrapper for Go_Customer_search (P7 adaptor target)
func Go_Customer_searchT(p0 *stripe_go.CustomerSearchParams) (out SkyResult[string, *pkg.SearchIter]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[string, *pkg.SearchIter](pkg.Search(p0))
	return
}

// [pure] Go_Customer.searchIterCustomer → pkg.SearchIterCustomer
func Go_Customer_searchIterCustomer(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(*pkg.SearchIter).Customer())
	return
}
type FfiT_Go_Customer_searchIterCustomer_P0 = *pkg.SearchIter
type FfiT_Go_Customer_searchIterCustomer_R = *stripe_go.Customer
// [pure] typed wrapper for Go_Customer_searchIterCustomer (P7 adaptor target)
func Go_Customer_searchIterCustomerT(p0 *pkg.SearchIter) (out SkyResult[string, *stripe_go.Customer]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[string, *stripe_go.Customer](p0.Customer())
	return
}

// [pure] Go_Customer.searchIterCustomerSearchResult → pkg.SearchIterCustomerSearchResult
func Go_Customer_searchIterCustomerSearchResult(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(*pkg.SearchIter).CustomerSearchResult())
	return
}
type FfiT_Go_Customer_searchIterCustomerSearchResult_P0 = *pkg.SearchIter
type FfiT_Go_Customer_searchIterCustomerSearchResult_R = *stripe_go.CustomerSearchResult
// [pure] typed wrapper for Go_Customer_searchIterCustomerSearchResult (P7 adaptor target)
func Go_Customer_searchIterCustomerSearchResultT(p0 *pkg.SearchIter) (out SkyResult[string, *stripe_go.CustomerSearchResult]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[string, *stripe_go.CustomerSearchResult](p0.CustomerSearchResult())
	return
}

// [pure] Go_Customer.searchIterCurrent → pkg.SearchIterCurrent
func Go_Customer_searchIterCurrent(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(*pkg.SearchIter).Current())
	return
}

// [fallible] Go_Customer.searchIterErr → pkg.SearchIterErr
func Go_Customer_searchIterErr(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	err := p0.(*pkg.SearchIter).Err()
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](struct{}{})

	return
}
type FfiT_Go_Customer_searchIterErr_P0 = *pkg.SearchIter
// [fallible] typed wrapper for Go_Customer_searchIterErr (P7 adaptor target)
func Go_Customer_searchIterErrT(p0 *pkg.SearchIter) (out SkyResult[string, struct{}]) {
	defer SkyFfiRecoverT(&out)()
	err := p0.Err()
	if err != nil { out = Err[string, struct{}](err.Error()); return }
	out = Ok[string, struct{}](struct{}{})
	return
}

// [pure] Go_Customer.searchIterMeta → pkg.SearchIterMeta
func Go_Customer_searchIterMeta(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(*pkg.SearchIter).Meta())
	return
}
type FfiT_Go_Customer_searchIterMeta_P0 = *pkg.SearchIter
type FfiT_Go_Customer_searchIterMeta_R = *stripe_go.SearchMeta
// [pure] typed wrapper for Go_Customer_searchIterMeta (P7 adaptor target)
func Go_Customer_searchIterMetaT(p0 *pkg.SearchIter) (out SkyResult[string, *stripe_go.SearchMeta]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[string, *stripe_go.SearchMeta](p0.Meta())
	return
}

// [pure] Go_Customer.searchIterNext → pkg.SearchIterNext
func Go_Customer_searchIterNext(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(*pkg.SearchIter).Next())
	return
}
type FfiT_Go_Customer_searchIterNext_P0 = *pkg.SearchIter
// [pure] typed wrapper for Go_Customer_searchIterNext (P7 adaptor target)
func Go_Customer_searchIterNextT(p0 *pkg.SearchIter) (out SkyResult[string, bool]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[string, bool](p0.Next())
	return
}

// [pure] Go_Customer.searchIterSearchResult → pkg.SearchIterSearchResult
func Go_Customer_searchIterSearchResult(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(*pkg.SearchIter).SearchResult())
	return
}
type FfiT_Go_Customer_searchIterSearchResult_P0 = *pkg.SearchIter
type FfiT_Go_Customer_searchIterSearchResult_R = stripe_go.SearchContainer
// [pure] typed wrapper for Go_Customer_searchIterSearchResult (P7 adaptor target)
func Go_Customer_searchIterSearchResultT(p0 *pkg.SearchIter) (out SkyResult[string, stripe_go.SearchContainer]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[string, stripe_go.SearchContainer](p0.SearchResult())
	return
}

func Go_Customer_searchIterSearchIter(p0 any) any { return SkyFfiFieldGet(p0, "SearchIter") }

func Go_Customer_searchIterSetSearchIter(value any, recv any) any { return SkyFfiFieldSet(value, recv, "SearchIter") }

func Go_Customer_newSearchIter(_ any) any { return new(pkg.SearchIter) }

// [fallible] Go_Customer.update → pkg.Update
func Go_Customer_update(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	r0, err := pkg.Update(fmt.Sprintf("%v", p0), p1.(*stripe_go.CustomerParams))
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](r0)

	return
}
type FfiT_Go_Customer_update_P1 = *stripe_go.CustomerParams
type FfiT_Go_Customer_update_R = *stripe_go.Customer
// [fallible] typed wrapper for Go_Customer_update (P7 adaptor target)
func Go_Customer_updateT(p0 string, p1 *stripe_go.CustomerParams) (out SkyResult[string, *stripe_go.Customer]) {
	defer SkyFfiRecoverT(&out)()
	r0, err := pkg.Update(p0, p1)
	if err != nil { out = Err[string, *stripe_go.Customer](err.Error()); return }
	out = Ok[string, *stripe_go.Customer](r0)
	return
}


// Pin fmt against "imported and not used" across partial files.
var _ = fmt.Sprintf
