// Code generated by sky-ffi-inspect from google.golang.org/api/option. DO NOT EDIT.
// Re-run `sky add google.golang.org/api/option` to regenerate.
//
// Wrapper functions are in `package rt` with names <Kernel>_<lowerFn>.
// Sky source resolves `import Google.Golang.Org.Api.Option as X` and calls `X.<lowerFn>` — the canonicaliser routes it via
// the FFI registry to these typed Go functions. Every wrapper wraps
// panics in Err[any, any] via SkyFfiRecover.

package rt

import (
	pkg "google.golang.org/api/option"
	"fmt"
	auth "cloud.google.com/go/auth"
	oauth2 "golang.org/x/oauth2"
	google "golang.org/x/oauth2/google"
	internal "google.golang.org/api/internal"
	grpc "google.golang.org/grpc"
	slog "log/slog"
	http "net/http"
)

// [pure] Go_Option.clientOptionApply → pkg.ClientOptionApply
func Go_Option_clientOptionApply(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	p0.(pkg.ClientOption).Apply(p1.(*internal.DialSettings))
	out = Ok[any, any](struct{}{})
	return
}

// [pure] Go_Option.impersonateCredentials → pkg.ImpersonateCredentials
func Go_Option_impersonateCredentials(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](pkg.ImpersonateCredentials(fmt.Sprintf("%v", p0), p1.([]string)...))
	return
}

// [pure] Go_Option.withAPIKey → pkg.WithAPIKey
func Go_Option_withAPIKey(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](pkg.WithAPIKey(fmt.Sprintf("%v", p0)))
	return
}

// [pure] Go_Option.withAudiences → pkg.WithAudiences
func Go_Option_withAudiences(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](pkg.WithAudiences(p0.([]string)...))
	return
}

// [pure] Go_Option.withAuthCredentials → pkg.WithAuthCredentials
func Go_Option_withAuthCredentials(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](pkg.WithAuthCredentials(p0.(*auth.Credentials)))
	return
}

// [pure] Go_Option.withAuthCredentialsFile → pkg.WithAuthCredentialsFile
func Go_Option_withAuthCredentialsFile(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](pkg.WithAuthCredentialsFile(p0.(pkg.CredentialsType), fmt.Sprintf("%v", p1)))
	return
}

// [pure] Go_Option.withAuthCredentialsJSON → pkg.WithAuthCredentialsJSON
func Go_Option_withAuthCredentialsJSON(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](pkg.WithAuthCredentialsJSON(p0.(pkg.CredentialsType), SkyFfiArg_bytes(p1)))
	return
}

// [pure] Go_Option.withClientCertSource → pkg.WithClientCertSource
func Go_Option_withClientCertSource(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](pkg.WithClientCertSource(p0.(pkg.ClientCertSource)))
	return
}

// [pure] Go_Option.withCredentials → pkg.WithCredentials
func Go_Option_withCredentials(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](pkg.WithCredentials(p0.(*google.Credentials)))
	return
}

// [pure] Go_Option.withCredentialsFile → pkg.WithCredentialsFile
func Go_Option_withCredentialsFile(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](pkg.WithCredentialsFile(fmt.Sprintf("%v", p0)))
	return
}

// [pure] Go_Option.withCredentialsJSON → pkg.WithCredentialsJSON
func Go_Option_withCredentialsJSON(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](pkg.WithCredentialsJSON(SkyFfiArg_bytes(p0)))
	return
}

// [pure] Go_Option.withEndpoint → pkg.WithEndpoint
func Go_Option_withEndpoint(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](pkg.WithEndpoint(fmt.Sprintf("%v", p0)))
	return
}

// [pure] Go_Option.withGRPCConn → pkg.WithGRPCConn
func Go_Option_withGRPCConn(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](pkg.WithGRPCConn(p0.(*grpc.ClientConn)))
	return
}

// [pure] Go_Option.withGRPCConnectionPool → pkg.WithGRPCConnectionPool
func Go_Option_withGRPCConnectionPool(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](pkg.WithGRPCConnectionPool(AsInt(p0)))
	return
}

// [pure] Go_Option.withGRPCDialOption → pkg.WithGRPCDialOption
func Go_Option_withGRPCDialOption(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](pkg.WithGRPCDialOption(p0.(grpc.DialOption)))
	return
}

// [pure] Go_Option.withHTTPClient → pkg.WithHTTPClient
func Go_Option_withHTTPClient(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](pkg.WithHTTPClient(p0.(*http.Client)))
	return
}

// [pure] Go_Option.withLogger → pkg.WithLogger
func Go_Option_withLogger(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](pkg.WithLogger(p0.(*slog.Logger)))
	return
}

// [pure] Go_Option.withQuotaProject → pkg.WithQuotaProject
func Go_Option_withQuotaProject(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](pkg.WithQuotaProject(fmt.Sprintf("%v", p0)))
	return
}

// [pure] Go_Option.withRequestReason → pkg.WithRequestReason
func Go_Option_withRequestReason(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](pkg.WithRequestReason(fmt.Sprintf("%v", p0)))
	return
}

// [pure] Go_Option.withScopes → pkg.WithScopes
func Go_Option_withScopes(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](pkg.WithScopes(p0.([]string)...))
	return
}

// [pure] Go_Option.withServiceAccountFile → pkg.WithServiceAccountFile
func Go_Option_withServiceAccountFile(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](pkg.WithServiceAccountFile(fmt.Sprintf("%v", p0)))
	return
}

// [pure] Go_Option.withTelemetryDisabled → pkg.WithTelemetryDisabled
func Go_Option_withTelemetryDisabled(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	_ = p0
	out = Ok[any, any](pkg.WithTelemetryDisabled())
	return
}

// [pure] Go_Option.withTokenSource → pkg.WithTokenSource
func Go_Option_withTokenSource(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](pkg.WithTokenSource(p0.(oauth2.TokenSource)))
	return
}

// [pure] Go_Option.withUniverseDomain → pkg.WithUniverseDomain
func Go_Option_withUniverseDomain(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](pkg.WithUniverseDomain(fmt.Sprintf("%v", p0)))
	return
}

// [pure] Go_Option.withUserAgent → pkg.WithUserAgent
func Go_Option_withUserAgent(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](pkg.WithUserAgent(fmt.Sprintf("%v", p0)))
	return
}

// [pure] Go_Option.withoutAuthentication → pkg.WithoutAuthentication
func Go_Option_withoutAuthentication(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	_ = p0
	out = Ok[any, any](pkg.WithoutAuthentication())
	return
}


// Pin fmt against "imported and not used" across partial files.
var _ = fmt.Sprintf
