// Code generated by sky-ffi-inspect from strings. DO NOT EDIT.
// Re-run `sky add strings` to regenerate.
//
// Wrapper functions are in `package rt` with names <Kernel>_<lowerFn>.
// Sky source resolves `import Strings as X` and calls `X.<lowerFn>` — the canonicaliser routes it via
// the FFI registry to these typed Go functions. Every wrapper wraps
// panics in Err[any, any] via SkyFfiRecover.

package rt

import (
	pkg "strings"
	"fmt"
	io "io"
	unicode "unicode"
)

type FfiT_Go_Strings_builderString_P0 = *pkg.Builder
// [pure] typed wrapper for Go_Strings_builderString (P7 adaptor target)
func Go_Strings_builderStringT(arg0 *pkg.Builder) (out SkyResult[any, string]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[any,string](arg0.String())
	return
}

type FfiT_Go_Strings_builderLen_P0 = *pkg.Builder
// [pure] typed wrapper for Go_Strings_builderLen (P7 adaptor target)
func Go_Strings_builderLenT(arg0 *pkg.Builder) (out SkyResult[any, int]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[any,int](arg0.Len())
	return
}

type FfiT_Go_Strings_builderCap_P0 = *pkg.Builder
// [pure] typed wrapper for Go_Strings_builderCap (P7 adaptor target)
func Go_Strings_builderCapT(arg0 *pkg.Builder) (out SkyResult[any, int]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[any,int](arg0.Cap())
	return
}

type FfiT_Go_Strings_builderReset_P0 = *pkg.Builder
// [pure] typed wrapper for Go_Strings_builderReset (P7 adaptor target)
func Go_Strings_builderResetT(arg0 *pkg.Builder) (out SkyResult[any, struct{}]) {
	defer SkyFfiRecoverT(&out)()
	arg0.Reset()
	out = Ok[any,struct{}](struct{}{})
	return
}

type FfiT_Go_Strings_builderGrow_P0 = *pkg.Builder
// [pure] typed wrapper for Go_Strings_builderGrow (P7 adaptor target)
func Go_Strings_builderGrowT(arg0 *pkg.Builder, arg1 int) (out SkyResult[any, struct{}]) {
	defer SkyFfiRecoverT(&out)()
	arg0.Grow(arg1)
	out = Ok[any,struct{}](struct{}{})
	return
}

type FfiT_Go_Strings_builderWrite_P0 = *pkg.Builder
// [fallible] typed wrapper for Go_Strings_builderWrite (P7 adaptor target)
func Go_Strings_builderWriteT(arg0 *pkg.Builder, arg1 []byte) (out SkyResult[any, int]) {
	defer SkyFfiRecoverT(&out)()
	r0, err := arg0.Write(arg1)
	if err != nil { out = Err[any,int](ErrFfi(err.Error())); return }
	out = Ok[any,int](r0)
	return
}

type FfiT_Go_Strings_builderWriteByte_P0 = *pkg.Builder
// [fallible] typed wrapper for Go_Strings_builderWriteByte (P7 adaptor target)
func Go_Strings_builderWriteByteT(arg0 *pkg.Builder, arg1 byte) (out SkyResult[any, struct{}]) {
	defer SkyFfiRecoverT(&out)()
	err := arg0.WriteByte(arg1)
	if err != nil { out = Err[any,struct{}](ErrFfi(err.Error())); return }
	out = Ok[any,struct{}](struct{}{})
	return
}

type FfiT_Go_Strings_builderWriteRune_P0 = *pkg.Builder
// [fallible] typed wrapper for Go_Strings_builderWriteRune (P7 adaptor target)
func Go_Strings_builderWriteRuneT(arg0 *pkg.Builder, arg1 rune) (out SkyResult[any, int]) {
	defer SkyFfiRecoverT(&out)()
	r0, err := arg0.WriteRune(arg1)
	if err != nil { out = Err[any,int](ErrFfi(err.Error())); return }
	out = Ok[any,int](r0)
	return
}

type FfiT_Go_Strings_builderWriteString_P0 = *pkg.Builder
// [fallible] typed wrapper for Go_Strings_builderWriteString (P7 adaptor target)
func Go_Strings_builderWriteStringT(arg0 *pkg.Builder, arg1 string) (out SkyResult[any, int]) {
	defer SkyFfiRecoverT(&out)()
	r0, err := arg0.WriteString(arg1)
	if err != nil { out = Err[any,int](ErrFfi(err.Error())); return }
	out = Ok[any,int](r0)
	return
}

func Go_Strings_newBuilder(_ any) any { return new(pkg.Builder) }

// [pure] typed wrapper for Go_Strings_clone (P7 adaptor target)
func Go_Strings_cloneT(arg0 string) (out SkyResult[any, string]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[any,string](pkg.Clone(arg0))
	return
}

// [pure] typed wrapper for Go_Strings_compare (P7 adaptor target)
func Go_Strings_compareT(arg0 string, arg1 string) (out SkyResult[any, int]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[any,int](pkg.Compare(arg0, arg1))
	return
}

// [pure] typed wrapper for Go_Strings_contains (P7 adaptor target)
func Go_Strings_containsT(arg0 string, arg1 string) (out SkyResult[any, bool]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[any,bool](pkg.Contains(arg0, arg1))
	return
}

// [pure] typed wrapper for Go_Strings_containsAny (P7 adaptor target)
func Go_Strings_containsAnyT(arg0 string, arg1 string) (out SkyResult[any, bool]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[any,bool](pkg.ContainsAny(arg0, arg1))
	return
}

// [pure] typed wrapper for Go_Strings_containsFunc (P7 adaptor target)
func Go_Strings_containsFuncT(arg0 string, arg1 func(rune) bool) (out SkyResult[any, bool]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[any,bool](pkg.ContainsFunc(arg0, arg1))
	return
}

// [pure] typed wrapper for Go_Strings_containsRune (P7 adaptor target)
func Go_Strings_containsRuneT(arg0 string, arg1 rune) (out SkyResult[any, bool]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[any,bool](pkg.ContainsRune(arg0, arg1))
	return
}

// [pure] typed wrapper for Go_Strings_count (P7 adaptor target)
func Go_Strings_countT(arg0 string, arg1 string) (out SkyResult[any, int]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[any,int](pkg.Count(arg0, arg1))
	return
}

// [pure] typed wrapper for Go_Strings_cut (P7 adaptor target)
func Go_Strings_cutT(arg0 string, arg1 string) (out SkyResult[any, SkyTuple3]) {
	defer SkyFfiRecoverT(&out)()
	r0, r1, r2 := pkg.Cut(arg0, arg1)
	out = Ok[any,SkyTuple3](SkyTuple3{V0: any(r0), V1: any(r1), V2: any(r2)})
	return
}

// [pure] typed wrapper for Go_Strings_cutPrefix (P7 adaptor target)
func Go_Strings_cutPrefixT(arg0 string, arg1 string) (out SkyResult[any, SkyTuple2]) {
	defer SkyFfiRecoverT(&out)()
	r0, r1 := pkg.CutPrefix(arg0, arg1)
	out = Ok[any,SkyTuple2](SkyTuple2{V0: any(r0), V1: any(r1)})
	return
}

// [pure] typed wrapper for Go_Strings_cutSuffix (P7 adaptor target)
func Go_Strings_cutSuffixT(arg0 string, arg1 string) (out SkyResult[any, SkyTuple2]) {
	defer SkyFfiRecoverT(&out)()
	r0, r1 := pkg.CutSuffix(arg0, arg1)
	out = Ok[any,SkyTuple2](SkyTuple2{V0: any(r0), V1: any(r1)})
	return
}

// [pure] typed wrapper for Go_Strings_equalFold (P7 adaptor target)
func Go_Strings_equalFoldT(arg0 string, arg1 string) (out SkyResult[any, bool]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[any,bool](pkg.EqualFold(arg0, arg1))
	return
}

// [pure] typed wrapper for Go_Strings_fields (P7 adaptor target)
func Go_Strings_fieldsT(arg0 string) (out SkyResult[any, []string]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[any,[]string](pkg.Fields(arg0))
	return
}

// [pure] typed wrapper for Go_Strings_fieldsFunc (P7 adaptor target)
func Go_Strings_fieldsFuncT(arg0 string, arg1 func(rune) bool) (out SkyResult[any, []string]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[any,[]string](pkg.FieldsFunc(arg0, arg1))
	return
}

// [pure] Go_Strings.fieldsFuncSeq → pkg.FieldsFuncSeq
func Go_Strings_fieldsFuncSeq(arg0 any, arg1 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](pkg.FieldsFuncSeq(fmt.Sprintf("%v", arg0), arg1.(func(rune) bool)))
	return
}

// [pure] Go_Strings.fieldsSeq → pkg.FieldsSeq
func Go_Strings_fieldsSeq(arg0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](pkg.FieldsSeq(fmt.Sprintf("%v", arg0)))
	return
}

// [pure] typed wrapper for Go_Strings_hasPrefix (P7 adaptor target)
func Go_Strings_hasPrefixT(arg0 string, arg1 string) (out SkyResult[any, bool]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[any,bool](pkg.HasPrefix(arg0, arg1))
	return
}

// [pure] typed wrapper for Go_Strings_hasSuffix (P7 adaptor target)
func Go_Strings_hasSuffixT(arg0 string, arg1 string) (out SkyResult[any, bool]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[any,bool](pkg.HasSuffix(arg0, arg1))
	return
}

// [pure] typed wrapper for Go_Strings_index (P7 adaptor target)
func Go_Strings_indexT(arg0 string, arg1 string) (out SkyResult[any, int]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[any,int](pkg.Index(arg0, arg1))
	return
}

// [pure] typed wrapper for Go_Strings_indexAny (P7 adaptor target)
func Go_Strings_indexAnyT(arg0 string, arg1 string) (out SkyResult[any, int]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[any,int](pkg.IndexAny(arg0, arg1))
	return
}

// [pure] typed wrapper for Go_Strings_indexByte (P7 adaptor target)
func Go_Strings_indexByteT(arg0 string, arg1 byte) (out SkyResult[any, int]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[any,int](pkg.IndexByte(arg0, arg1))
	return
}

// [pure] typed wrapper for Go_Strings_indexFunc (P7 adaptor target)
func Go_Strings_indexFuncT(arg0 string, arg1 func(rune) bool) (out SkyResult[any, int]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[any,int](pkg.IndexFunc(arg0, arg1))
	return
}

// [pure] typed wrapper for Go_Strings_indexRune (P7 adaptor target)
func Go_Strings_indexRuneT(arg0 string, arg1 rune) (out SkyResult[any, int]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[any,int](pkg.IndexRune(arg0, arg1))
	return
}

// [pure] typed wrapper for Go_Strings_join (P7 adaptor target)
func Go_Strings_joinT(arg0 []string, arg1 string) (out SkyResult[any, string]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[any,string](pkg.Join(arg0, arg1))
	return
}

// [pure] typed wrapper for Go_Strings_lastIndex (P7 adaptor target)
func Go_Strings_lastIndexT(arg0 string, arg1 string) (out SkyResult[any, int]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[any,int](pkg.LastIndex(arg0, arg1))
	return
}

// [pure] typed wrapper for Go_Strings_lastIndexAny (P7 adaptor target)
func Go_Strings_lastIndexAnyT(arg0 string, arg1 string) (out SkyResult[any, int]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[any,int](pkg.LastIndexAny(arg0, arg1))
	return
}

// [pure] typed wrapper for Go_Strings_lastIndexByte (P7 adaptor target)
func Go_Strings_lastIndexByteT(arg0 string, arg1 byte) (out SkyResult[any, int]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[any,int](pkg.LastIndexByte(arg0, arg1))
	return
}

// [pure] typed wrapper for Go_Strings_lastIndexFunc (P7 adaptor target)
func Go_Strings_lastIndexFuncT(arg0 string, arg1 func(rune) bool) (out SkyResult[any, int]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[any,int](pkg.LastIndexFunc(arg0, arg1))
	return
}

// [pure] Go_Strings.lines → pkg.Lines
func Go_Strings_lines(arg0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](pkg.Lines(fmt.Sprintf("%v", arg0)))
	return
}

// [pure] typed wrapper for Go_Strings_map (P7 adaptor target)
func Go_Strings_mapT(arg0 func(rune) rune, arg1 string) (out SkyResult[any, string]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[any,string](pkg.Map(arg0, arg1))
	return
}

type FfiT_Go_Strings_newReader_R = *pkg.Reader
// [pure] typed wrapper for Go_Strings_newReader (P7 adaptor target)
func Go_Strings_newReaderT(arg0 string) (out SkyResult[any, *pkg.Reader]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[any,*pkg.Reader](pkg.NewReader(arg0))
	return
}

type FfiT_Go_Strings_newReplacer_R = *pkg.Replacer
// [pure] typed wrapper for Go_Strings_newReplacer (P7 adaptor target)
func Go_Strings_newReplacerT(arg0 []string) (out SkyResult[any, *pkg.Replacer]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[any,*pkg.Replacer](pkg.NewReplacer(arg0...))
	return
}

type FfiT_Go_Strings_readerLen_P0 = *pkg.Reader
// [pure] typed wrapper for Go_Strings_readerLen (P7 adaptor target)
func Go_Strings_readerLenT(arg0 *pkg.Reader) (out SkyResult[any, int]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[any,int](arg0.Len())
	return
}

type FfiT_Go_Strings_readerSize_P0 = *pkg.Reader
// [pure] typed wrapper for Go_Strings_readerSize (P7 adaptor target)
func Go_Strings_readerSizeT(arg0 *pkg.Reader) (out SkyResult[any, int64]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[any,int64](arg0.Size())
	return
}

type FfiT_Go_Strings_readerRead_P0 = *pkg.Reader
// [fallible] typed wrapper for Go_Strings_readerRead (P7 adaptor target)
func Go_Strings_readerReadT(arg0 *pkg.Reader, arg1 []byte) (out SkyResult[any, int]) {
	defer SkyFfiRecoverT(&out)()
	r0, err := arg0.Read(arg1)
	if err != nil { out = Err[any,int](ErrFfi(err.Error())); return }
	out = Ok[any,int](r0)
	return
}

type FfiT_Go_Strings_readerReadAt_P0 = *pkg.Reader
// [fallible] typed wrapper for Go_Strings_readerReadAt (P7 adaptor target)
func Go_Strings_readerReadAtT(arg0 *pkg.Reader, arg1 []byte, arg2 int64) (out SkyResult[any, int]) {
	defer SkyFfiRecoverT(&out)()
	r0, err := arg0.ReadAt(arg1, arg2)
	if err != nil { out = Err[any,int](ErrFfi(err.Error())); return }
	out = Ok[any,int](r0)
	return
}

type FfiT_Go_Strings_readerReadByte_P0 = *pkg.Reader
// [fallible] typed wrapper for Go_Strings_readerReadByte (P7 adaptor target)
func Go_Strings_readerReadByteT(arg0 *pkg.Reader) (out SkyResult[any, byte]) {
	defer SkyFfiRecoverT(&out)()
	r0, err := arg0.ReadByte()
	if err != nil { out = Err[any,byte](ErrFfi(err.Error())); return }
	out = Ok[any,byte](r0)
	return
}

type FfiT_Go_Strings_readerUnreadByte_P0 = *pkg.Reader
// [fallible] typed wrapper for Go_Strings_readerUnreadByte (P7 adaptor target)
func Go_Strings_readerUnreadByteT(arg0 *pkg.Reader) (out SkyResult[any, struct{}]) {
	defer SkyFfiRecoverT(&out)()
	err := arg0.UnreadByte()
	if err != nil { out = Err[any,struct{}](ErrFfi(err.Error())); return }
	out = Ok[any,struct{}](struct{}{})
	return
}

type FfiT_Go_Strings_readerReadRune_P0 = *pkg.Reader
// [fallible] typed wrapper for Go_Strings_readerReadRune (P7 adaptor target)
func Go_Strings_readerReadRuneT(arg0 *pkg.Reader) (out SkyResult[any, SkyTuple2]) {
	defer SkyFfiRecoverT(&out)()
	r0, r1, err := arg0.ReadRune()
	if err != nil { out = Err[any,SkyTuple2](ErrFfi(err.Error())); return }
	out = Ok[any,SkyTuple2](SkyTuple2{V0: any(r0), V1: any(r1)})
	return
}

type FfiT_Go_Strings_readerUnreadRune_P0 = *pkg.Reader
// [fallible] typed wrapper for Go_Strings_readerUnreadRune (P7 adaptor target)
func Go_Strings_readerUnreadRuneT(arg0 *pkg.Reader) (out SkyResult[any, struct{}]) {
	defer SkyFfiRecoverT(&out)()
	err := arg0.UnreadRune()
	if err != nil { out = Err[any,struct{}](ErrFfi(err.Error())); return }
	out = Ok[any,struct{}](struct{}{})
	return
}

type FfiT_Go_Strings_readerSeek_P0 = *pkg.Reader
// [fallible] typed wrapper for Go_Strings_readerSeek (P7 adaptor target)
func Go_Strings_readerSeekT(arg0 *pkg.Reader, arg1 int64, arg2 int) (out SkyResult[any, int64]) {
	defer SkyFfiRecoverT(&out)()
	r0, err := arg0.Seek(arg1, arg2)
	if err != nil { out = Err[any,int64](ErrFfi(err.Error())); return }
	out = Ok[any,int64](r0)
	return
}

type FfiT_Go_Strings_readerWriteTo_P0 = *pkg.Reader
type FfiT_Go_Strings_readerWriteTo_P1 = io.Writer
// [fallible] typed wrapper for Go_Strings_readerWriteTo (P7 adaptor target)
func Go_Strings_readerWriteToT(arg0 *pkg.Reader, arg1 io.Writer) (out SkyResult[any, int64]) {
	defer SkyFfiRecoverT(&out)()
	r0, err := arg0.WriteTo(arg1)
	if err != nil { out = Err[any,int64](ErrFfi(err.Error())); return }
	out = Ok[any,int64](r0)
	return
}

type FfiT_Go_Strings_readerReset_P0 = *pkg.Reader
// [pure] typed wrapper for Go_Strings_readerReset (P7 adaptor target)
func Go_Strings_readerResetT(arg0 *pkg.Reader, arg1 string) (out SkyResult[any, struct{}]) {
	defer SkyFfiRecoverT(&out)()
	arg0.Reset(arg1)
	out = Ok[any,struct{}](struct{}{})
	return
}

// [pure] typed wrapper for Go_Strings_repeat (P7 adaptor target)
func Go_Strings_repeatT(arg0 string, arg1 int) (out SkyResult[any, string]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[any,string](pkg.Repeat(arg0, arg1))
	return
}

// [pure] typed wrapper for Go_Strings_replace (P7 adaptor target)
func Go_Strings_replaceT(arg0 string, arg1 string, arg2 string, arg3 int) (out SkyResult[any, string]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[any,string](pkg.Replace(arg0, arg1, arg2, arg3))
	return
}

// [pure] typed wrapper for Go_Strings_replaceAll (P7 adaptor target)
func Go_Strings_replaceAllT(arg0 string, arg1 string, arg2 string) (out SkyResult[any, string]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[any,string](pkg.ReplaceAll(arg0, arg1, arg2))
	return
}

type FfiT_Go_Strings_replacerReplace_P0 = *pkg.Replacer
// [pure] typed wrapper for Go_Strings_replacerReplace (P7 adaptor target)
func Go_Strings_replacerReplaceT(arg0 *pkg.Replacer, arg1 string) (out SkyResult[any, string]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[any,string](arg0.Replace(arg1))
	return
}

type FfiT_Go_Strings_replacerWriteString_P0 = *pkg.Replacer
type FfiT_Go_Strings_replacerWriteString_P1 = io.Writer
// [fallible] typed wrapper for Go_Strings_replacerWriteString (P7 adaptor target)
func Go_Strings_replacerWriteStringT(arg0 *pkg.Replacer, arg1 io.Writer, arg2 string) (out SkyResult[any, int]) {
	defer SkyFfiRecoverT(&out)()
	r0, err := arg0.WriteString(arg1, arg2)
	if err != nil { out = Err[any,int](ErrFfi(err.Error())); return }
	out = Ok[any,int](r0)
	return
}

// [pure] typed wrapper for Go_Strings_split (P7 adaptor target)
func Go_Strings_splitT(arg0 string, arg1 string) (out SkyResult[any, []string]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[any,[]string](pkg.Split(arg0, arg1))
	return
}

// [pure] typed wrapper for Go_Strings_splitAfter (P7 adaptor target)
func Go_Strings_splitAfterT(arg0 string, arg1 string) (out SkyResult[any, []string]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[any,[]string](pkg.SplitAfter(arg0, arg1))
	return
}

// [pure] typed wrapper for Go_Strings_splitAfterN (P7 adaptor target)
func Go_Strings_splitAfterNT(arg0 string, arg1 string, arg2 int) (out SkyResult[any, []string]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[any,[]string](pkg.SplitAfterN(arg0, arg1, arg2))
	return
}

// [pure] Go_Strings.splitAfterSeq → pkg.SplitAfterSeq
func Go_Strings_splitAfterSeq(arg0 any, arg1 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](pkg.SplitAfterSeq(fmt.Sprintf("%v", arg0), fmt.Sprintf("%v", arg1)))
	return
}

// [pure] typed wrapper for Go_Strings_splitN (P7 adaptor target)
func Go_Strings_splitNT(arg0 string, arg1 string, arg2 int) (out SkyResult[any, []string]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[any,[]string](pkg.SplitN(arg0, arg1, arg2))
	return
}

// [pure] Go_Strings.splitSeq → pkg.SplitSeq
func Go_Strings_splitSeq(arg0 any, arg1 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](pkg.SplitSeq(fmt.Sprintf("%v", arg0), fmt.Sprintf("%v", arg1)))
	return
}

// [pure] typed wrapper for Go_Strings_title (P7 adaptor target)
func Go_Strings_titleT(arg0 string) (out SkyResult[any, string]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[any,string](pkg.Title(arg0))
	return
}

// [pure] typed wrapper for Go_Strings_toLower (P7 adaptor target)
func Go_Strings_toLowerT(arg0 string) (out SkyResult[any, string]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[any,string](pkg.ToLower(arg0))
	return
}

type FfiT_Go_Strings_toLowerSpecial_P0 = unicode.SpecialCase
// [pure] typed wrapper for Go_Strings_toLowerSpecial (P7 adaptor target)
func Go_Strings_toLowerSpecialT(arg0 unicode.SpecialCase, arg1 string) (out SkyResult[any, string]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[any,string](pkg.ToLowerSpecial(arg0, arg1))
	return
}

// [pure] typed wrapper for Go_Strings_toTitle (P7 adaptor target)
func Go_Strings_toTitleT(arg0 string) (out SkyResult[any, string]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[any,string](pkg.ToTitle(arg0))
	return
}

type FfiT_Go_Strings_toTitleSpecial_P0 = unicode.SpecialCase
// [pure] typed wrapper for Go_Strings_toTitleSpecial (P7 adaptor target)
func Go_Strings_toTitleSpecialT(arg0 unicode.SpecialCase, arg1 string) (out SkyResult[any, string]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[any,string](pkg.ToTitleSpecial(arg0, arg1))
	return
}

// [pure] typed wrapper for Go_Strings_toUpper (P7 adaptor target)
func Go_Strings_toUpperT(arg0 string) (out SkyResult[any, string]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[any,string](pkg.ToUpper(arg0))
	return
}

type FfiT_Go_Strings_toUpperSpecial_P0 = unicode.SpecialCase
// [pure] typed wrapper for Go_Strings_toUpperSpecial (P7 adaptor target)
func Go_Strings_toUpperSpecialT(arg0 unicode.SpecialCase, arg1 string) (out SkyResult[any, string]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[any,string](pkg.ToUpperSpecial(arg0, arg1))
	return
}

// [pure] typed wrapper for Go_Strings_toValidUTF8 (P7 adaptor target)
func Go_Strings_toValidUTF8T(arg0 string, arg1 string) (out SkyResult[any, string]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[any,string](pkg.ToValidUTF8(arg0, arg1))
	return
}

// [pure] typed wrapper for Go_Strings_trim (P7 adaptor target)
func Go_Strings_trimT(arg0 string, arg1 string) (out SkyResult[any, string]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[any,string](pkg.Trim(arg0, arg1))
	return
}

// [pure] typed wrapper for Go_Strings_trimFunc (P7 adaptor target)
func Go_Strings_trimFuncT(arg0 string, arg1 func(rune) bool) (out SkyResult[any, string]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[any,string](pkg.TrimFunc(arg0, arg1))
	return
}

// [pure] typed wrapper for Go_Strings_trimLeft (P7 adaptor target)
func Go_Strings_trimLeftT(arg0 string, arg1 string) (out SkyResult[any, string]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[any,string](pkg.TrimLeft(arg0, arg1))
	return
}

// [pure] typed wrapper for Go_Strings_trimLeftFunc (P7 adaptor target)
func Go_Strings_trimLeftFuncT(arg0 string, arg1 func(rune) bool) (out SkyResult[any, string]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[any,string](pkg.TrimLeftFunc(arg0, arg1))
	return
}

// [pure] typed wrapper for Go_Strings_trimPrefix (P7 adaptor target)
func Go_Strings_trimPrefixT(arg0 string, arg1 string) (out SkyResult[any, string]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[any,string](pkg.TrimPrefix(arg0, arg1))
	return
}

// [pure] typed wrapper for Go_Strings_trimRight (P7 adaptor target)
func Go_Strings_trimRightT(arg0 string, arg1 string) (out SkyResult[any, string]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[any,string](pkg.TrimRight(arg0, arg1))
	return
}

// [pure] typed wrapper for Go_Strings_trimRightFunc (P7 adaptor target)
func Go_Strings_trimRightFuncT(arg0 string, arg1 func(rune) bool) (out SkyResult[any, string]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[any,string](pkg.TrimRightFunc(arg0, arg1))
	return
}

// [pure] typed wrapper for Go_Strings_trimSpace (P7 adaptor target)
func Go_Strings_trimSpaceT(arg0 string) (out SkyResult[any, string]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[any,string](pkg.TrimSpace(arg0))
	return
}

// [pure] typed wrapper for Go_Strings_trimSuffix (P7 adaptor target)
func Go_Strings_trimSuffixT(arg0 string, arg1 string) (out SkyResult[any, string]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[any,string](pkg.TrimSuffix(arg0, arg1))
	return
}


// Pin fmt against "imported and not used" across partial files.
var _ = fmt.Sprintf
