// Code generated by sky-ffi-inspect from github.com/google/uuid. DO NOT EDIT.
// Re-run `sky add github.com/google/uuid` to regenerate.
//
// Wrapper functions are in `package rt` with names <Kernel>_<lowerFn>.
// Sky source resolves `import Github.Com.Google.Uuid as X` and calls `X.<lowerFn>` — the canonicaliser routes it via
// the FFI registry to these typed Go functions. Every wrapper wraps
// panics in Err[any, any] via SkyFfiRecover.

package rt

import (
	pkg "github.com/google/uuid"
	"fmt"
	_ "database/sql/driver"  // aliased driver; unused in emitted wrappers
	hash "hash"
	io "io"
)

// [pure] Go_Uuid.clockSequence → pkg.ClockSequence
func Go_Uuid_clockSequence(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	_ = p0
	out = Ok[any, any](pkg.ClockSequence())
	return
}

// [pure] Go_Uuid.disableRandPool → pkg.DisableRandPool
func Go_Uuid_disableRandPool(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	_ = p0
	pkg.DisableRandPool()
	out = Ok[any, any](struct{}{})
	return
}

// [pure] Go_Uuid.domainString → pkg.DomainString
func Go_Uuid_domainString(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(pkg.Domain).String())
	return
}

// [pure] Go_Uuid.enableRandPool → pkg.EnableRandPool
func Go_Uuid_enableRandPool(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	_ = p0
	pkg.EnableRandPool()
	out = Ok[any, any](struct{}{})
	return
}

// [fallible] Go_Uuid.fromBytes → pkg.FromBytes
func Go_Uuid_fromBytes(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	r0, err := pkg.FromBytes(SkyFfiArg_bytes(p0))
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](r0)

	return
}

// [fallible] Go_Uuid.getTime → pkg.GetTime
func Go_Uuid_getTime(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	_ = p0
	r0, r1, err := pkg.GetTime()
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any]([]any{r0, r1})

	return
}

// [pure] Go_Uuid.isInvalidLengthError → pkg.IsInvalidLengthError
func Go_Uuid_isInvalidLengthError(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](pkg.IsInvalidLengthError(p0.(error)))
	return
}

// [pure] Go_Uuid.must → pkg.Must
func Go_Uuid_must(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](pkg.Must(p0.(pkg.UUID), p1.(error)))
	return
}

// [pure] Go_Uuid.mustParse → pkg.MustParse
func Go_Uuid_mustParse(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](pkg.MustParse(fmt.Sprintf("%v", p0)))
	return
}

// [pure] Go_Uuid.new → pkg.New
func Go_Uuid_new(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	_ = p0
	out = Ok[any, any](pkg.New())
	return
}

// [fallible] Go_Uuid.newDCEGroup → pkg.NewDCEGroup
func Go_Uuid_newDCEGroup(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	_ = p0
	r0, err := pkg.NewDCEGroup()
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](r0)

	return
}

// [fallible] Go_Uuid.newDCEPerson → pkg.NewDCEPerson
func Go_Uuid_newDCEPerson(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	_ = p0
	r0, err := pkg.NewDCEPerson()
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](r0)

	return
}

// [fallible] Go_Uuid.newDCESecurity → pkg.NewDCESecurity
func Go_Uuid_newDCESecurity(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	r0, err := pkg.NewDCESecurity(p0.(pkg.Domain), uint32(AsInt(p1)))
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](r0)

	return
}

// [pure] Go_Uuid.newHash → pkg.NewHash
func Go_Uuid_newHash(p0 any, p1 any, p2 any, p3 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](pkg.NewHash(p0.(hash.Hash), p1.(pkg.UUID), SkyFfiArg_bytes(p2), AsInt(p3)))
	return
}

// [pure] Go_Uuid.newMD5 → pkg.NewMD5
func Go_Uuid_newMD5(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](pkg.NewMD5(p0.(pkg.UUID), SkyFfiArg_bytes(p1)))
	return
}

// [fallible] Go_Uuid.newRandom → pkg.NewRandom
func Go_Uuid_newRandom(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	_ = p0
	r0, err := pkg.NewRandom()
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](r0)

	return
}

// [fallible] Go_Uuid.newRandomFromReader → pkg.NewRandomFromReader
func Go_Uuid_newRandomFromReader(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	r0, err := pkg.NewRandomFromReader(p0.(io.Reader))
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](r0)

	return
}

// [pure] Go_Uuid.newSHA1 → pkg.NewSHA1
func Go_Uuid_newSHA1(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](pkg.NewSHA1(p0.(pkg.UUID), SkyFfiArg_bytes(p1)))
	return
}

// [pure] Go_Uuid.newString → pkg.NewString
func Go_Uuid_newString(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	_ = p0
	out = Ok[any, any](pkg.NewString())
	return
}

// [fallible] Go_Uuid.newUUID → pkg.NewUUID
func Go_Uuid_newUUID(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	_ = p0
	r0, err := pkg.NewUUID()
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](r0)

	return
}

// [fallible] Go_Uuid.newV6 → pkg.NewV6
func Go_Uuid_newV6(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	_ = p0
	r0, err := pkg.NewV6()
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](r0)

	return
}

// [fallible] Go_Uuid.newV7 → pkg.NewV7
func Go_Uuid_newV7(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	_ = p0
	r0, err := pkg.NewV7()
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](r0)

	return
}

// [fallible] Go_Uuid.newV7FromReader → pkg.NewV7FromReader
func Go_Uuid_newV7FromReader(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	r0, err := pkg.NewV7FromReader(p0.(io.Reader))
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](r0)

	return
}

// [pure] Go_Uuid.nodeID → pkg.NodeID
func Go_Uuid_nodeID(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	_ = p0
	out = Ok[any, any](pkg.NodeID())
	return
}

// [pure] Go_Uuid.nodeInterface → pkg.NodeInterface
func Go_Uuid_nodeInterface(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	_ = p0
	out = Ok[any, any](pkg.NodeInterface())
	return
}

// [fallible] Go_Uuid.nullUUIDScan → pkg.NullUUIDScan
func Go_Uuid_nullUUIDScan(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	err := p0.(*pkg.NullUUID).Scan(p1.(interface{}))
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](struct{}{})

	return
}

// [fallible] Go_Uuid.nullUUIDValue → pkg.NullUUIDValue
func Go_Uuid_nullUUIDValue(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	r0, err := p0.(pkg.NullUUID).Value()
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](r0)

	return
}

// [fallible] Go_Uuid.nullUUIDMarshalBinary → pkg.NullUUIDMarshalBinary
func Go_Uuid_nullUUIDMarshalBinary(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	r0, err := p0.(pkg.NullUUID).MarshalBinary()
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](r0)

	return
}

// [fallible] Go_Uuid.nullUUIDUnmarshalBinary → pkg.NullUUIDUnmarshalBinary
func Go_Uuid_nullUUIDUnmarshalBinary(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	err := p0.(*pkg.NullUUID).UnmarshalBinary(SkyFfiArg_bytes(p1))
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](struct{}{})

	return
}

// [fallible] Go_Uuid.nullUUIDMarshalText → pkg.NullUUIDMarshalText
func Go_Uuid_nullUUIDMarshalText(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	r0, err := p0.(pkg.NullUUID).MarshalText()
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](r0)

	return
}

// [fallible] Go_Uuid.nullUUIDUnmarshalText → pkg.NullUUIDUnmarshalText
func Go_Uuid_nullUUIDUnmarshalText(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	err := p0.(*pkg.NullUUID).UnmarshalText(SkyFfiArg_bytes(p1))
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](struct{}{})

	return
}

// [fallible] Go_Uuid.nullUUIDMarshalJSON → pkg.NullUUIDMarshalJSON
func Go_Uuid_nullUUIDMarshalJSON(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	r0, err := p0.(pkg.NullUUID).MarshalJSON()
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](r0)

	return
}

// [fallible] Go_Uuid.nullUUIDUnmarshalJSON → pkg.NullUUIDUnmarshalJSON
func Go_Uuid_nullUUIDUnmarshalJSON(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	err := p0.(*pkg.NullUUID).UnmarshalJSON(SkyFfiArg_bytes(p1))
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](struct{}{})

	return
}

// [fallible] Go_Uuid.parse → pkg.Parse
func Go_Uuid_parse(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	r0, err := pkg.Parse(fmt.Sprintf("%v", p0))
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](r0)

	return
}

// [fallible] Go_Uuid.parseBytes → pkg.ParseBytes
func Go_Uuid_parseBytes(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	r0, err := pkg.ParseBytes(SkyFfiArg_bytes(p0))
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](r0)

	return
}

// [pure] Go_Uuid.setClockSequence → pkg.SetClockSequence
func Go_Uuid_setClockSequence(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	pkg.SetClockSequence(AsInt(p0))
	out = Ok[any, any](struct{}{})
	return
}

// [pure] Go_Uuid.setNodeID → pkg.SetNodeID
func Go_Uuid_setNodeID(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](pkg.SetNodeID(SkyFfiArg_bytes(p0)))
	return
}

// [pure] Go_Uuid.setNodeInterface → pkg.SetNodeInterface
func Go_Uuid_setNodeInterface(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](pkg.SetNodeInterface(fmt.Sprintf("%v", p0)))
	return
}

// [pure] Go_Uuid.setRand → pkg.SetRand
func Go_Uuid_setRand(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	pkg.SetRand(p0.(io.Reader))
	out = Ok[any, any](struct{}{})
	return
}

// [pure] Go_Uuid.timeUnixTime → pkg.TimeUnixTime
func Go_Uuid_timeUnixTime(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	r0, r1 := p0.(pkg.Time).UnixTime()
	out = Ok[any, any]([]any{r0, r1})

	return
}

// [pure] Go_Uuid.uUIDDomain → pkg.UUIDDomain
func Go_Uuid_uUIDDomain(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(pkg.UUID).Domain())
	return
}

// [pure] Go_Uuid.uUIDID → pkg.UUIDID
func Go_Uuid_uUIDID(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(pkg.UUID).ID())
	return
}

// [fallible] Go_Uuid.uUIDMarshalText → pkg.UUIDMarshalText
func Go_Uuid_uUIDMarshalText(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	r0, err := p0.(pkg.UUID).MarshalText()
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](r0)

	return
}

// [fallible] Go_Uuid.uUIDUnmarshalText → pkg.UUIDUnmarshalText
func Go_Uuid_uUIDUnmarshalText(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	err := p0.(*pkg.UUID).UnmarshalText(SkyFfiArg_bytes(p1))
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](struct{}{})

	return
}

// [fallible] Go_Uuid.uUIDMarshalBinary → pkg.UUIDMarshalBinary
func Go_Uuid_uUIDMarshalBinary(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	r0, err := p0.(pkg.UUID).MarshalBinary()
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](r0)

	return
}

// [fallible] Go_Uuid.uUIDUnmarshalBinary → pkg.UUIDUnmarshalBinary
func Go_Uuid_uUIDUnmarshalBinary(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	err := p0.(*pkg.UUID).UnmarshalBinary(SkyFfiArg_bytes(p1))
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](struct{}{})

	return
}

// [pure] Go_Uuid.uUIDNodeID → pkg.UUIDNodeID
func Go_Uuid_uUIDNodeID(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(pkg.UUID).NodeID())
	return
}

// [fallible] Go_Uuid.uUIDScan → pkg.UUIDScan
func Go_Uuid_uUIDScan(p0 any, p1 any) (out any) {
	defer SkyFfiRecover(&out)()
	err := p0.(*pkg.UUID).Scan(p1.(interface{}))
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](struct{}{})

	return
}

// [fallible] Go_Uuid.uUIDValue → pkg.UUIDValue
func Go_Uuid_uUIDValue(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	r0, err := p0.(pkg.UUID).Value()
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](r0)

	return
}

// [pure] Go_Uuid.uUIDTime → pkg.UUIDTime
func Go_Uuid_uUIDTime(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(pkg.UUID).Time())
	return
}

// [pure] Go_Uuid.uUIDClockSequence → pkg.UUIDClockSequence
func Go_Uuid_uUIDClockSequence(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(pkg.UUID).ClockSequence())
	return
}

// [pure] Go_Uuid.uUIDString → pkg.UUIDString
func Go_Uuid_uUIDString(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(pkg.UUID).String())
	return
}

// [pure] Go_Uuid.uUIDURN → pkg.UUIDURN
func Go_Uuid_uUIDURN(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(pkg.UUID).URN())
	return
}

// [pure] Go_Uuid.uUIDVariant → pkg.UUIDVariant
func Go_Uuid_uUIDVariant(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(pkg.UUID).Variant())
	return
}

// [pure] Go_Uuid.uUIDVersion → pkg.UUIDVersion
func Go_Uuid_uUIDVersion(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(pkg.UUID).Version())
	return
}

// [pure] Go_Uuid.uUIDsStrings → pkg.UUIDsStrings
func Go_Uuid_uUIDsStrings(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(pkg.UUIDs).Strings())
	return
}

// [fallible] Go_Uuid.validate → pkg.Validate
func Go_Uuid_validate(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	err := pkg.Validate(fmt.Sprintf("%v", p0))
	if err != nil { out = Err[any, any](err.Error()); return }
	out = Ok[any, any](struct{}{})

	return
}

// [pure] Go_Uuid.variantString → pkg.VariantString
func Go_Uuid_variantString(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(pkg.Variant).String())
	return
}

// [pure] Go_Uuid.versionString → pkg.VersionString
func Go_Uuid_versionString(p0 any) (out any) {
	defer SkyFfiRecover(&out)()
	out = Ok[any, any](p0.(pkg.Version).String())
	return
}


// Pin fmt against "imported and not used" across partial files.
var _ = fmt.Sprintf
