package sky_wrappers

import (
	context "context"
	_ffi_fmt "fmt"
)

var _ = _ffi_fmt.Sprintf

// Auto-generated by Sky compiler

func Sky_context_Background(_ any) any {

	return func() any {
		defer func() { recover() }()
		result := context.Background()
		return SkyOk(result)
	}()
}

func Sky_context_Cause(arg0 any) any {
	_arg0 := sky_asContext(arg0)
	return func() any {
		defer func() { recover() }()
		err := context.Cause(_arg0)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(struct{}{})
	}()
}

func Sky_context_TODO(_ any) any {

	return func() any {
		defer func() { recover() }()
		result := context.TODO()
		return SkyOk(result)
	}()
}

func Sky_context_WithCancel(arg0 any) any {
	_arg0 := sky_asContext(arg0)
	return func() any {
		defer func() { recover() }()
		_r0, _r1 := context.WithCancel(_arg0)
		return SkyOk(SkyTuple2{_r0, _r1})
	}()
}

func Sky_context_WithCancelCause(arg0 any) any {
	_arg0 := sky_asContext(arg0)
	return func() any {
		defer func() { recover() }()
		_r0, _r1 := context.WithCancelCause(_arg0)
		return SkyOk(SkyTuple2{_r0, _r1})
	}()
}

func Sky_context_WithValue(arg0 any, arg1 any, arg2 any) any {
	_arg0 := sky_asContext(arg0)
	_arg1 := arg1
	_arg2 := arg2
	return func() any {
		defer func() { recover() }()
		result := context.WithValue(_arg0, _arg1, _arg2)
		return SkyOk(result)
	}()
}

func Sky_context_WithoutCancel(arg0 any) any {
	_arg0 := sky_asContext(arg0)
	return func() any {
		defer func() { recover() }()
		result := context.WithoutCancel(_arg0)
		return SkyOk(result)
	}()
}

func Sky_context_ContextErr(receiver any) any {
	_receiver := receiver.(context.Context)
	return func() any {
		defer func() { recover() }()
		err := _receiver.Err()
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(struct{}{})
	}()
}

func Sky_context_ContextValue(receiver any, arg0 any) any {
	_receiver := receiver.(context.Context)
	_arg0 := arg0
	return func() any {
		defer func() { recover() }()
		result := _receiver.Value(_arg0)
		return SkyOk(result)
	}()
}
