package skylive_rt

import (
	"bufio"
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"os"
	"strconv"
	"strings"
	"time"
)

// LiveConfig holds the server configuration from sky.toml [live] section.
type LiveConfig struct {
	Port         int           // Server port (default: 4000)
	TTL          time.Duration // Session TTL (default: 30m)
	StoreType    string        // Session store backend: "memory" | "sqlite" | "redis" | "postgresql"
	StorePath    string        // Connection string/path for stores
	InputMode    string        // "debounce" (default) or "blur" — when onInput sends to server
	PollInterval int           // Polling fallback interval in ms (0 = SSE only, default: 0)
	StaticDir    string        // Path to static assets (empty = no static serving)
}

// PageDef defines a route mapping: URL pattern → Page constructor value.
type PageDef struct {
	Pattern string // URL pattern (e.g., "/", "/todos", "/users/:id")
	Page    any    // The Page value for this route
}

// LiveApp defines the application interface that the generated code implements.
type LiveApp struct {
	// Init creates the initial model from a request. The page parameter
	// is the matched Page value from the route table.
	Init func(req map[string]any, page any) (model any, cmds []any)

	// Update processes a Msg and returns the new model + commands.
	Update func(msg any, model any) (newModel any, cmds []any)

	// View renders the model to a VNode tree.
	View func(model any) *VNode

	// DecodeMsg deserializes a wire message into a Msg value.
	DecodeMsg func(name string, args []json.RawMessage) (any, error)

	// URLForPage returns the URL path for a Page value (reverse routing).
	URLForPage func(page any) string

	// TitleForPage returns the page title for a Page value.
	TitleForPage func(page any) string

	// Routes is the ordered list of route definitions.
	Routes []PageDef

	// NotFound is the Page value for 404s.
	NotFound any

	// StaticDir is the path to static assets (empty = no static serving).
	StaticDir string

	// BuildNavigateMsg creates a Navigate Msg for a given page value.
	// Generated by the compiler based on the Msg type definition.
	BuildNavigateMsg func(page any) any

	// Subscriptions evaluates the subscriptions function with the current model.
	// Returns a Sub ADT value the runtime walks to extract SubDefs.
	Subscriptions func(model any) any

	// MsgTagToName maps a Msg tag index to its constructor name.
	MsgTagToName func(tag int) string

	// config is set internally by StartServer
	config LiveConfig
}

// MsgEnvelope is the JSON structure sent by the JS client.
type MsgEnvelope struct {
	Msg  string            `json:"msg"`
	Args []json.RawMessage `json:"args"`
	SID  string            `json:"sid"`
}

// EventResponse is returned to the JS client after processing an event.
type EventResponse struct {
	Patches []Patch `json:"patches"`
	URL     string  `json:"url,omitempty"`   // Set when Navigate changes the page
	Title   string  `json:"title,omitempty"` // Set when page title changes
}

// loadDotEnv reads a .env file and sets environment variables.
// Only sets vars that are not already set in the environment,
// so real env vars take precedence over .env values.
// After loading, env var overrides are applied to the config.
func loadDotEnv() {
	f, err := os.Open(".env")
	if err != nil {
		return // no .env file, that's fine
	}
	defer f.Close()

	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		key, val, ok := strings.Cut(line, "=")
		if !ok {
			continue
		}
		key = strings.TrimSpace(key)
		val = strings.TrimSpace(val)
		// Remove surrounding quotes
		if len(val) >= 2 && ((val[0] == '"' && val[len(val)-1] == '"') || (val[0] == '\'' && val[len(val)-1] == '\'')) {
			val = val[1 : len(val)-1]
		}
		// .env values override everything (set unconditionally)
		os.Setenv(key, val)
	}
}

// applyEnvOverrides reads SKY_LIVE_* environment variables and overrides
// the compiled-in config values. Env var names mirror sky.toml structure.
// Priority: compiled defaults < sky.toml < env vars < .env
func applyEnvOverrides(config *LiveConfig) {
	if v := os.Getenv("SKY_LIVE_PORT"); v != "" {
		if port, err := strconv.Atoi(v); err == nil {
			config.Port = port
		}
	}
	if v := os.Getenv("SKY_LIVE_INPUT"); v != "" {
		config.InputMode = v
	}
	if v := os.Getenv("SKY_LIVE_POLL_INTERVAL"); v != "" {
		if interval, err := strconv.Atoi(v); err == nil {
			config.PollInterval = interval
		}
	}
	if v := os.Getenv("SKY_LIVE_SESSION_STORE"); v != "" {
		config.StoreType = v
	}
	if v := os.Getenv("SKY_LIVE_SESSION_PATH"); v != "" {
		config.StorePath = v
	}
	if v := os.Getenv("SKY_LIVE_SESSION_URL"); v != "" {
		config.StorePath = v
	}
	if v := os.Getenv("SKY_LIVE_STATIC_DIR"); v != "" {
		config.StaticDir = v
	}
	if v := os.Getenv("SKY_LIVE_TTL"); v != "" {
		if d, err := time.ParseDuration(v); err == nil {
			config.TTL = d
		}
	}
}


// StartServer creates and starts the Sky.Live HTTP server.
func StartServer(config LiveConfig, app LiveApp) {
	// Load .env file first (sets env vars), then apply env overrides to config.
	// Priority: compiled defaults < sky.toml (compile time) < env vars < .env file
	loadDotEnv()
	applyEnvOverrides(&config)
	app.config = config

	// Per-session mutex to prevent race conditions between event handling
	// and SSE subscription ticks on the same session.
	sessLock := NewSessionLocker()
	var store SessionStore
	switch config.StoreType {
	case "sqlite":
		dbPath := config.StorePath
		if dbPath == "" {
			dbPath = "sessions.db"
		}
		var err error
		store, err = NewSQLiteStore(dbPath, config.TTL)
		if err != nil {
			log.Fatalf("Failed to open SQLite session store at %s: %v", dbPath, err)
		}
		log.Printf("Using SQLite session store: %s", dbPath)
	case "redis":
		url := config.StorePath
		if url == "" {
			url = "localhost:6379"
		}
		var err error
		store, err = NewRedisStore(url, config.TTL)
		if err != nil {
			log.Fatalf("Failed to connect to Redis at %s: %v", url, err)
		}
		log.Printf("Using Redis session store: %s", url)
	case "postgresql", "postgres":
		url := config.StorePath
		if url == "" {
			url = "postgres://localhost:5432/sky_sessions?sslmode=disable"
		}
		var err error
		store, err = NewPostgresStore(url, config.TTL)
		if err != nil {
			log.Fatalf("Failed to connect to PostgreSQL at %s: %v", url, err)
		}
		log.Printf("Using PostgreSQL session store")
	case "firestore":
		credPath := config.StorePath // service account JSON, "project:ID", or "" for ADC
		var err error
		store, err = NewFirestoreStore(credPath, config.TTL)
		if err != nil {
			log.Fatalf("Failed to connect to Firestore: %v", err)
		}
		log.Printf("Using Firestore session store")
	default:
		store = NewMemoryStore(config.TTL)
	}
	mux := http.NewServeMux()

	// Serve the JS client
	mux.HandleFunc("GET /_sky/live.js", func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/javascript")
		w.Header().Set("Cache-Control", "public, max-age=3600")
		w.Write([]byte(LiveJS))
	})

	// Serve static assets (config overrides app default)
	staticDir := app.StaticDir
	if config.StaticDir != "" {
		staticDir = config.StaticDir
	}
	if staticDir != "" {
		mux.Handle("GET /static/", http.StripPrefix("/static/", http.FileServer(http.Dir(staticDir))))
	}

	// Event handler — processes Msg from the JS client
	mux.HandleFunc("POST /_sky/event", func(w http.ResponseWriter, r *http.Request) {
		handleEvent(w, r, store, &app, sessLock)
	})

	// URL resolver — maps a URL path back to a Navigate Msg (for browser back/forward)
	mux.HandleFunc("GET /_sky/resolve", func(w http.ResponseWriter, r *http.Request) {
		handleResolve(w, r, &app)
	})

	// Polling endpoint — fallback for serverless (Lambda, etc.) where SSE isn't available
	mux.HandleFunc("GET /_sky/poll", func(w http.ResponseWriter, r *http.Request) {
		handlePoll(w, r, store, &app, sessLock)
	})

	// Client config endpoint — passes LiveConfig to JS client
	mux.HandleFunc("GET /_sky/config", func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		inputMode := app.config.InputMode
		if inputMode == "" {
			inputMode = "debounce"
		}
		pollInterval := app.config.PollInterval
		fmt.Fprintf(w, `{"inputMode":%q,"pollInterval":%d}`, inputMode, pollInterval)
	})

	// SSE subscriptions
	sseManager := NewSSEManager(&app, store, sessLock)
	mux.HandleFunc("GET /_sky/stream", sseManager.HandleSSE)

	// Start subscription timers if app defines subscriptions
	if app.Subscriptions != nil {
		initModel, _ := app.Init(map[string]any{}, nil)
		subValue := app.Subscriptions(initModel)
		subDefs := WalkSubValue(subValue, app.MsgTagToName)
		if len(subDefs) > 0 {
			sseManager.RunSubscriptions(subDefs)
			log.Printf("Started %d subscription(s)", len(subDefs))
		}
	}

	// Page routes — initial GET requests
	mux.HandleFunc("GET /", func(w http.ResponseWriter, r *http.Request) {
		// Skip non-page requests (favicon, robots.txt, etc.)
		p := r.URL.Path
		if strings.Contains(p, ".") && p != "/" {
			http.NotFound(w, r)
			return
		}
		handlePageRequest(w, r, store, &app)
	})

	addr := fmt.Sprintf(":%d", config.Port)
	log.Printf("Sky.Live server running on http://localhost%s", addr)
	log.Fatal(http.ListenAndServe(addr, mux))
}

func handlePageRequest(w http.ResponseWriter, r *http.Request, store SessionStore, app *LiveApp) {
	// Match route
	page, params := matchRoute(r.URL.Path, app.Routes, app.NotFound)

	// Check for existing session via cookie (survives page refresh)
	var sid string
	var model any
	if cookie, err := r.Cookie("sky_sid"); err == nil && cookie.Value != "" {
		if sess, ok := store.Get(cookie.Value); ok {
			// Restore existing session — page refresh survival
			sid = cookie.Value
			model = sess.Model

			// If navigating to a different route on refresh, send Navigate msg
			currentPage := getPageFromModel(model)
			if !pagesEqual(currentPage, page) {
				// Build a Navigate msg for this page
				if app.BuildNavigateMsg != nil {
					navigateMsg := app.BuildNavigateMsg(page)
					if navigateMsg != nil {
						newModel, _ := app.Update(navigateMsg, model)
						model = newModel
					}
				}
			}
		}
	}

	// No existing session — create fresh
	if sid == "" {
		req := buildRequest(r, params)
		var cmds []any
		model, cmds = app.Init(req, page)
		_ = cmds
		sid = store.NewID()
	}

	// Render view
	viewTree := app.View(model)
	AssignSkyIDs(viewTree)

	// Save session
	store.Set(sid, &Session{
		Model:    model,
		PrevView: viewTree,
		Created:  time.Now(),
	})

	// Set session cookie (HttpOnly, SameSite=Lax, path=/)
	http.SetCookie(w, &http.Cookie{
		Name:     "sky_sid",
		Value:    sid,
		Path:     "/",
		HttpOnly: true,
		SameSite: http.SameSiteLaxMode,
		MaxAge:   int(app.config.TTL.Seconds()),
	})

	// Render full page
	title := app.TitleForPage(page)
	html := RenderFullPage(viewTree, title, sid)

	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	w.Write([]byte(html))
}

func handleEvent(w http.ResponseWriter, r *http.Request, store SessionStore, app *LiveApp, sessLock *SessionLocker) {
	var env MsgEnvelope
	if err := json.NewDecoder(r.Body).Decode(&env); err != nil {
		http.Error(w, "bad request", 400)
		return
	}

	// Lock this session to prevent race with SSE subscription ticks (single-instance)
	sessLock.Lock(env.SID)
	defer sessLock.Unlock(env.SID)

	// Decode the message (done once, outside retry loop)
	msg, err := app.DecodeMsg(env.Msg, env.Args)
	if err != nil {
		http.Error(w, "unknown message: "+env.Msg, 400)
		return
	}

	// Optimistic concurrency retry loop (handles multi-instance races via store versioning)
	var patches []Patch
	var resp EventResponse
	const maxRetries = 3
	for attempt := 0; attempt < maxRetries; attempt++ {
		sess, ok := store.Get(env.SID)
		if !ok {
			http.Error(w, "session expired", 410)
			return
		}

		oldPage := getPageFromModel(sess.Model)

		newModel, cmds := app.Update(msg, sess.Model)
		_ = cmds

		newView := app.View(newModel)
		AssignSkyIDs(newView)

		patches = Diff(sess.PrevView, newView)

		sess.Model = newModel
		sess.PrevView = newView
		sess.MsgLog = append(sess.MsgLog, msg)
		if store.Set(env.SID, sess) {
			resp = EventResponse{Patches: patches}
			newPage := getPageFromModel(newModel)
			if !pagesEqual(oldPage, newPage) {
				resp.URL = app.URLForPage(newPage)
				resp.Title = app.TitleForPage(newPage)
			}
			break // success
		}
		// Version conflict — retry with fresh session
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(resp)
}

func handleResolve(w http.ResponseWriter, r *http.Request, app *LiveApp) {
	urlPath := r.URL.Query().Get("path")
	if urlPath == "" {
		urlPath = "/"
	}

	page, _ := matchRoute(urlPath, app.Routes, app.NotFound)
	pageJSON, _ := json.Marshal(page)

	w.Header().Set("Content-Type", "application/json")
	fmt.Fprintf(w, `{"msg":"Navigate","args":[%s]}`, string(pageJSON))
}

func matchRoute(urlPath string, routes []PageDef, notFound any) (page any, params map[string]string) {
	params = make(map[string]string)

	for _, route := range routes {
		if matched, p := matchPattern(route.Pattern, urlPath); matched {
			return route.Page, p
		}
	}

	return notFound, params
}

func matchPattern(pattern, urlPath string) (bool, map[string]string) {
	params := make(map[string]string)

	// Exact match
	if pattern == urlPath {
		return true, params
	}

	// Pattern matching with :param placeholders
	patternParts := strings.Split(strings.Trim(pattern, "/"), "/")
	pathParts := strings.Split(strings.Trim(urlPath, "/"), "/")

	if len(patternParts) != len(pathParts) {
		return false, nil
	}

	for i, pp := range patternParts {
		if strings.HasPrefix(pp, ":") {
			params[pp[1:]] = pathParts[i]
		} else if pp != pathParts[i] {
			return false, nil
		}
	}

	return true, params
}

func buildRequest(r *http.Request, params map[string]string) map[string]any {
	query := make(map[string]any)
	for k, v := range r.URL.Query() {
		if len(v) > 0 {
			query[k] = v[0]
		}
	}

	headers := make(map[string]any)
	for k, v := range r.Header {
		if len(v) > 0 {
			headers[k] = v[0]
		}
	}

	cookies := make(map[string]any)
	for _, c := range r.Cookies() {
		cookies[c.Name] = c.Value
	}

	paramsAny := make(map[string]any)
	for k, v := range params {
		paramsAny[k] = v
	}

	return map[string]any{
		"method":  r.Method,
		"path":    r.URL.Path,
		"params":  paramsAny,
		"query":   query,
		"headers": headers,
		"cookies": cookies,
	}
}

// getPageFromModel extracts the "page" field from a model map.
// Sky models are map[string]any; the "page" field holds the current Page value.
func getPageFromModel(model any) any {
	if m, ok := model.(map[string]any); ok {
		return m["page"]
	}
	return nil
}

// pagesEqual checks if two page values are equal.
// Handles comparison between structs and map representations.
func pagesEqual(a, b any) bool {
	if a == nil && b == nil {
		return true
	}
	if a == nil || b == nil {
		return false
	}
	// Try to extract Tag from both values for comparison
	tagA := extractTag(a)
	tagB := extractTag(b)
	if tagA >= 0 && tagB >= 0 {
		return tagA == tagB
	}
	return fmt.Sprintf("%v", a) == fmt.Sprintf("%v", b)
}

// extractTag tries to get the Tag int from various representations
func extractTag(v any) int {
	// map[string]any with "Tag" key (from JSON deserialization)
	if m, ok := v.(map[string]any); ok {
		if tag, ok := m["Tag"]; ok {
			switch t := tag.(type) {
			case int:
				return t
			case float64:
				return int(t)
			}
		}
	}
	// Use reflection-free approach: try fmt.Sprintf and parse
	s := fmt.Sprintf("%v", v)
	// Struct like Page{Tag:0} → "{0}" or similar
	if len(s) > 2 && s[0] == '{' {
		for i := 1; i < len(s); i++ {
			if s[i] >= '0' && s[i] <= '9' {
				n := 0
				for i < len(s) && s[i] >= '0' && s[i] <= '9' {
					n = n*10 + int(s[i]-'0')
					i++
				}
				return n
			}
			if s[i] != ' ' {
				break
			}
		}
	}
	return -1
}

// handlePoll is a polling fallback for environments where SSE isn't available
// (e.g., Lambda). The client periodically calls GET /_sky/poll?sid=X and the
// server re-renders the view, diffs against PrevView, and returns patches.
func handlePoll(w http.ResponseWriter, r *http.Request, store SessionStore, app *LiveApp, sessLock *SessionLocker) {
	sid := r.URL.Query().Get("sid")
	if sid == "" {
		if cookie, err := r.Cookie("sky_sid"); err == nil {
			sid = cookie.Value
		}
	}
	if sid == "" {
		http.Error(w, "missing sid", 400)
		return
	}

	sessLock.Lock(sid)
	defer sessLock.Unlock(sid)

	var resp EventResponse
	const maxRetries = 3
	for attempt := 0; attempt < maxRetries; attempt++ {
		sess, ok := store.Get(sid)
		if !ok {
			http.Error(w, "session expired", 410)
			return
		}

		newView := app.View(sess.Model)
		AssignSkyIDs(newView)
		patches := Diff(sess.PrevView, newView)

		if len(patches) > 0 {
			sess.PrevView = newView
			if !store.Set(sid, sess) {
				continue // version conflict — retry
			}
		}
		resp = EventResponse{Patches: patches}
		break
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(resp)
}
